### ISSUE TITLE
Run jsHint for Windows 7 using command prompt

### ISSUE THREAD

**Issue by ashishalw** [jshint/jshint#1012]
Hi,
1. ```
     We are using Windows 7. Can I run this on windows using command line to check errors in all of my JS file inside a folder. I was unable to find such option in help documents. 
   ```
2. ```
     Is there any export option where I can generate excel report of all my jsHint warnings?
   ```

Thanks,
Ashish

**Comment by Raghavendraj** [comment]
Hi All,

I have installed Node in for ex : C:\Program files and in d:\JSHint i run "npm install jshint -g" in command line. But it is failing. Please resolve asap. Plzzzzz.

Node version is : v0.12.2
npm version  is : 2.7.4

Thanks,
Raghav
