### ISSUE TITLE
Devel option is broken

### ISSUE THREAD

**Issue by maksimr** [jshint/jshint#1027]
Hi! I try to catch error about using `console.log`, but jshint doesn't throw error
when is set `devel:false`.

Passed to `JSHINT` function arguments:

``` javascript
{ '0': '/* jshint unused:false, browser:true, strict:true, devel:false */\n\nvar foo = "foo";\n\nconsole.log("foo");\n',
  '1': {},
  '2': undefined }
```

jshint -v -> jshint v1.1.0

P.S.
I can not find unit test on this option in file `tests/stable/unit/options.js`.

**Comment by christianhaller** [comment]
@Skalman Thx :)
