### ISSUE TITLE
"jshint . | less" shows no results when actual results are too numerous

### ISSUE THREAD

**Issue by mcandre** [jshint/jshint#1045]
On one of my projects, `jshint .` shows about 1000 results. When I pipe this to less (`jshint . | less`), it shows no results. When I repeat `jshint . | less` for a different project with fewer results, they correctly display in less.

System:

    $ specs jshint node git os
    Specs:

    specs 0.4
    https://github.com/mcandre/specs#readme

    jshint --version
    jshint v1.1.0

    npm --version
    1.2.17

    node --version
    v0.10.3

    git --version
    git version 1.8.0.msysgit.0

    systeminfo | findstr /B /C:"OS Name" /C:"OS Version"
    OS Name:                   Microsoft Windows XP Professional
    OS Version:                5.1.2600 Service Pack 3 Build 2600

**Comment by lukeapage** [comment]
tested with 1600 errors on windows 7 and I couldn't reproduce. This could be an issue with your system or a fixed bug in jshint. Please let us know if this is still happening.
