### ISSUE TITLE
How to ignore .min.js and -min.js files in all subdirectories?

### ISSUE THREAD

**Issue by mcandre** [jshint/jshint#1046]
I can eliminate a specific folder's minified JS from jshint results by putting `<folder>/*[.-]min.js` in my project's `.jshintignore`. How can I eliminate all minified JS from jshint results, no matter which subfolder or how deeply nested? I tried `*[.-]min.js`, `*/*[.-]min.js`, and `**[.-]min.js`, all without success.

**Comment by michael-freidgeim-webjet** [comment]
similar question https://stackoverflow.com/questions/25987084/git-ignoring-all-minified-suffixed-files
