### ISSUE TITLE
Unify scope handling

### ISSUE THREAD

**Issue by usrbincc** [jshint/jshint#1061]
This continues a discussion that began in #1054.

Currently, jshint (as of dea5f5963213e9609b1f1da966ee31e288fc7cfd) relies on two different scope systems, one for function scope, and one for block scope.

Three possible solutions were presented:
1. continue with two systems, and fix corner cases.
2. convert everything to use the current block scope system.
3. convert everything to use the current function scope system.

Continuing with the first solution is going to make it harder to properly fix a lot of outstanding scope bugs, so the main question is really whether to do strategy 2 or 3. Though there is the insanity of strategy 4 &mdash; convert everything to use an entirely new scope system.

**Comment by lukeapage** [comment]
I am working on this, going for (2) by moving function scoping into the block scope manager
