### ISSUE TITLE
Separate function hoisting from latedef

### ISSUE THREAD

**Issue by OrangeDog** [jshint/jshint#1073]
`latedef` should only cover declarations with `var`.
Listing function definitions after code that calls them can be a great help to readability - as the code layout is closer to the logical execution order.

i.e. this code should not raise a `latedef` warning

``` javascript
if (a) {
    doLast();
}
else {
    doSometimes();
    doLast();
}

function doSometimes() { a = true; };

function doLast() {};
```

However, if the declaration were `var doLast = function() {};`, then `latedef` warning should be raised.

**Comment by ExplodingCabbage** [comment]
I agree with @OrangeDog on this; it's not a particularly widespread practice, but when I have a lengthy function that defines some massive subprocedures, I often find it useful for readability to give the high-level implementation at the top followed by the function definitions after my `return` statement. Using a variable before it's been declared with `var`, though, is something I can't imagine a legitimate use for.

If I were able to set `latedef` to "var_only" or something to enable its functionality only for variables, not function declarations, I would do so. Currently I have to choose between dropping some warnings I'd like or changing my coding style.
