### ISSUE TITLE
JSHint with asi: true still thinks that "use strict" should use a semicolon

### ISSUE THREAD

**Issue by mcandre** [jshint/jshint#1075]
I've set `"asi": true` in my `.jshintrc`, but JSHint still complains:

```
$ jshint .
index.js: line 1, col 1, Missing semicolon.

$ less index.js
'use strict'
...
```

**Comment by dav-** [comment]
This is still an issue for me

**Comment by caitp** [comment]
@dav- you will still need a semicolon depending on what comes after the "use strict" directive, regardless of your ASI settings. The reason for this is, for instance the following:

```js
"use strict"
(function() {
})()
```

This ends up being:

{String} {Call}{Call} --- in other words, the string is not processed as a directive, it's processed as a plain old string expression, which is the LHS of a call expression, and the result of that first call is itself called.

So this confuses people, but yeah I think we're right to warn about things like that. There are other productions where you'll get similar results, too. However, if you think the statement following should be allowed, please open a new issue with a reproduction
