### ISSUE TITLE
Strict violation (W040) reports wrong character

### ISSUE THREAD

**Issue by Krinkle** [jshint/jshint#1119]
```js
( function () {
'use strict';
var x = {};
x.once = function ( event, listener ) {
	function wrapper() {
		listener.apply( this, Array.prototype.slice.call( arguments, 0 ) );
	}
	x.something( event, wrapper );
};
}() );
```

```
[L6:C25] W040: Possible strict violation.
    listener.apply( this, Array.prototype.slice.call( arguments, 0 ) );
                          ^
```

Fixed by using `/*jshint validthis:true */` since it is a valid use in my case, however reporting the character position as bug.

**Comment by lukeapage** [comment]
I can only reproduce with tabs.. jshint assumes a tab of 4 characters. if the tab is instead counted as 1 character, you get a mismatch of 3, explaining why with 2 tabs, the character is 6 more than is expected.

**Comment by lukeapage** [comment]
this can be "fixed" by setting `indent: 1`
