### ISSUE TITLE
A generator function shall contain a yield statement.

### ISSUE THREAD

**Issue by Raynos** [jshint/jshint#1123]
a generator that only contains a return statement is probably a valid generator

``` js
/*jshint forin:true, noarg:true, noempty:true, eqeqeq:true, bitwise:true, undef:true, unused:true, curly:true, browser:true, devel:true, esnext:true, indent:4, maxerr:50 */
var of, run;

run(function *() {
    return of(5);
});
```

The above currently errors complaining about lack of yields

**Comment by monolithed** [comment]
```js
'use strict';

export default {
	/**
	 * entries
	 *
	 * @param {Object} object
	 * @return {Generator}
	 */
	 * entries (object) {
		for (let key of Object.keys(object)) {
			yield [key, object[key]];
		}
	}
};
```

```
   tools/functional.js
     37 |    },
             ^ A generator function shall contain a yield statement.
     65 |    }
             ^ A generator function shall contain a yield statement.
```

`"grunt-contrib-jshint": "^0.11.2",`

**Comment by artin-phares** [comment]
Receiving 'A generator function shall contain a yield statement' in jshint@2.8.0 
Regression?

**Comment by kilianc** [comment]
`v2.0.8` here still getting the warning

**Comment by kilianc** [comment]
found: https://github.com/jshint/jshint/commit/37757f0195e9ee4eb4bd8aeb5162c2a3c1565832#diff-91ba5f4df12e1b6b0629662164b3f14eR17

we need to use `noyeld` option, not sure why but at least I can turn it off.

**Comment by artin-phares** [comment]
yep, I'm using <code>"noyield": true</code> to get rid of this warning too
no idea why generator function with no yields treat as a problem again...
