### ISSUE TITLE
Change EcmaScript levels to a single flag "ecma"

### ISSUE THREAD

**Issue by nschonni** [jshint/jshint#1148]
Separating out the discussion from https://github.com/jshint/jshint/issues/1137#issuecomment-19694125 although I've changed 'eslevel' to 'ecma'

This would allow the current flags to be folded into one:
- es3 -> ecma: 3
- es5 -> ecma: 5
- esnext -> ecma: 6? or 'next'
- moz -> ecma: 'moz'

**Comment by lukeapage** [comment]
merging to #2124
