### ISSUE TITLE
Parser gets confused by colon instead of semi-colon

### ISSUE THREAD

**Issue by Krinkle** [jshint/jshint#1150]
Given the (simplified) scenario:

``` js
/*global ve */
/*jshint strict:false */
ve.dm.MWReferenceListNode.static.toDomElements = function ( dataElement, doc ) {
    var el,
        elements = dataElement.attributes.domElements;

    if ( elements ) {
        return ve.copyDomElements( elements, doc ):
    }

    el = doc.createElement( 'div' );

    return [ el ];
};
```

I get the following errors:

```
line 4: 'el' is defined but never used
line 8: Missing semicolon; Expected '{' to match '{' from line 7
line 9: Missing semicolon
line 11: 'el' is not defined; 'doc' is not defined
line 13: 'el' is not defined
line 14: Expected '(end)' and instead saw '}'
```

Although I eventually figured that the colon on line 8 needs to be a semicolon, the other errors were quite confusing.

I don't think jshint is to blame here, but if it is feasible to improve its tolerant behaviour (where it accounts for certain errors to avoid false positives later on) it'd be nice if it could account for this too and recover from it.

**Comment by lukeapage** [comment]
Its really difficult to guess the kind of errors and try and recover - jshint does do that, but if it picks the wrong assumption, it fails. Its pretty unlikely this would ever be fixed.

**Comment by nicolo-ribaudo** [comment]
I think this wouldn't be a too hard improvement: a statement can't start with `:` so if JSHint encounters a colon while looking for a semicolon, it is quite probably a typing error.
