### ISSUE TITLE
Initilization of a var to 'undefined' in a loop gives wrong error

### ISSUE THREAD

**Issue by jontra** [jshint/jshint#1191]
```javascript
for (var i=0; i<10; i++)
{
    var a = undefined;
    if (i%2)
        a = 1;
    if (a===undefined)
        console.log("error");
}
```

test.js: line 3, col 9, It's not necessary to initialize 'a' to 'undefined'.

It is necessary, since 'a' is *not* in the 'for' block scope.

**Comment by stevage** [comment]
Whee, this is an old issue. Just came here to chime in about #1142. I ran into a bug in my code where the right answer was to change `var foo;` to `var foo=undefined;`, so it's pretty irritating to then have JSHint tell me that it's "not necessary".

**Comment by lukeapage** [comment]
@stevage there you go, I made a PR to fix it.

I can also confirm that disabling W080 e.g. `// jshint -W080` does work on master

**Comment by stevage** [comment]
Whoa, thank you! :)

**Comment by qfox** [comment]
:+1:
