### ISSUE TITLE
Option to prohibit the use of a variable outside of its defining block

### ISSUE THREAD

**Issue by AnAppAMonth** [jshint/jshint#1235]
Now, JavaScript doesn't have block scoping, which is the source of much debate around the "onevar" check. But why can't we "simulate" block scoping with JSHint, by only allowing a variable that's defined in a block to be used inside that block (and its child blocks)?

When a developer defines a variable inside a block, his intention is probably to only use the variable inside this block, and so is the impression any reader of the code would get. If the variable is also used outside of the block, either before or after, it's likely because the developer (or another one) mistakenly reused the same name (and forgot to define it). Additionally, even if the use is conscious, it still hampers readability of the code because it violates the expectation of readers.

This check is in the same vein of `latedef`. JavaScript's variable scoping and hoisting violate reader expectations in two important ways:

1. A variable is hoisted to the top of the function even if it's defined later in the function.
2. A variable is function scoped even if it's defined inside a block.

The `latedef` check addresses the first one, the proposed check would address the second in the same way:

1. If the variable is defined here, the expectation is that it will only be used after this point, it shouldn't be used before this point.
2. If the variable is defined in this block, the expectation is that it will only be used inside this block, it shouldn't be used outside of it.

**Comment by lukeapage** [comment]
The only case this doesn't work as of master is #2409. fixes will be in the release after 2.8.0
