### ISSUE TITLE
False negative for unused:true in some circumstances

### ISSUE THREAD

**Issue by Boldewyn** [jshint/jshint#1246]
If you evaluate the following code with `unused:true` set,

```js
var
    /* globally do something */
    not_unused;

not_unused = 1;
```

you get the false negative error message:

```
bug.js: line 2, col 32, 'ly do something' is defined but never used.

1 error
```

It seems, that `/* global` is consumed by the config detector first, leaving the remaining `ly do something` which is then wrongly detected in the test as variable token.

**Comment by lukeapage** [comment]
This is no longer a bug in 2.7.0 and probably long before.
@rwaldron you could close this..

**Comment by Boldewyn** [comment]
Yes, I just tested with v2.5.7. The problem is gone. Thanks!
