### ISSUE TITLE
Document 'onecase' option

### ISSUE THREAD

**Issue by gregjacobs** [jshint/jshint#1249]
The 'onecase' option is missing from http://jshint.com/docs/options/

Also, I noticed a comment in the code that listed the 'onecase' option as "Obsolete." This should not be the case:
1. https://github.com/jshint/jshint/issues/198, and
2. For a switch statement that might have some case(s) commented out (either temporarily, or otherwise), we should have the ability to turn off warnings for that without rewriting into an `if` statement.

**Comment by rugk** [comment]
BTW: if this option has gone I think you can also remove it from your own [`.jshintrc` file](https://github.com/jshint/jshint/blob/master/.jshintrc#L9). :smile:
