### ISSUE TITLE
Support undefined variable with eqeqeq and eqnull.

### ISSUE THREAD

**Issue by FarSeeing** [jshint/jshint#1275]
Caching `undefined` to variable and using both `eqeqeq:true` and `eqnull:true` options  will result in an error. Consider the code:

``` javascript
(function(undefined){
  return foo == undefined;
})()
```

**Comment by Yaffle** [comment]
@valueof , because of `eqnull:true`

**Comment by Yaffle** [comment]
Could you please change this?

https://github.com/Yaffle/jshint/commit/1b311620d699c1510bcb56449a2ba6c635ba89a7

**Comment by Yaffle** [comment]
@valueof is it possible to add `equndefined` ?

**Comment by valueof** [comment]
I haven't been working on JSHint in about two years. There's a new team now.

**Comment by valueof** [comment]
I'm curious, though, why would you cache `undefined`?

**Comment by Yaffle** [comment]
I am not caching it... I do not know why the author of this issue does this, but in fact jshint will report an error without caching too. I want to use undefined everywhere, So I think `eqnull` could allow both `x == null` and `x == undefined`.

**Comment by FarSeeing** [comment]
@valueof 
> I'm curious, though, why would you cache undefined?

Just for minification reasons. I've opened this issue with the following code:
```javascript
(function(undefined){
  return foo == undefined;
})()
```
And it could be minified to
```javascript
!function(n){return foo==n}()
```

But the problem was with `eqnull` rule not allowing you to do so.
