### ISSUE TITLE
css and ternary operator

### ISSUE THREAD

**Issue by watereddown** [jshint/jshint#1278]
seems to have a problem with using the ternary operator to assign a value to css, eg,
confused by (from Jquery Cookbook, 13.1)
$tt.css({
'top': $ev_y + $tt_y > $bd_y ? $ev_y − $tt_y : $ev_y,
'left': $ev_x + $tt_x + 20 > $bd_x ? $ev_x − $tt_x − 10 : $ev_x + 15
});

**Comment by lukeapage** [comment]
You are using the wrong `-`.

`−` !== `-`
