### ISSUE TITLE
Do not enforce loopfunc when the increment value is a let binding

### ISSUE THREAD

**Issue by rwaldron** [jshint/jshint#1301]
Unlike `var` bindings, `let` does what you expect:

```js
var a = [];

for (let i = 0; i < 5; i++) {
  a.push(function() { return i; });
}
a.forEach(fn => console.log(fn()));

// 0
// 1
// 2
// 3
// 4
```

http://gul.ly/dhi (turn on "let": options -> show all options -> blockbinding)

**Comment by lukeapage** [comment]
this has been fixed at some point in the last year and a half.
