### ISSUE TITLE
Treat try and catch blocks as different pseudo-scopes

### ISSUE THREAD

**Issue by valueof** [jshint/jshint#1302]
To be consistent with other out-of-scope warnings we need to treat `catch` blocks as separate pseudo-scopes:

```javascript

if (false) {
  var a = function () { /* ... */ };
}

a(); // JSHint warns about 'a' being used out of scope.

try {
  var b = function () { /* ... */ };
  throw;
} catch (err) {
  b(); // JSHint doesn't warn about 'b' being used out of scope but _should_.
}
```

**Comment by lukeapage** [comment]
Fixed by #2468 - catch is now treated like any other block, not as if it is a function. Will be released in the release after 2.8.0.

warning message change request put into #2484
