### ISSUE TITLE
Option to disable === warnings for typeof comparisons with string literals

### ISSUE THREAD

**Issue by pimterry** [jshint/jshint#1310]
Any typeof comparison with a string literal (`typeof X == 'object'`) is guaranteed to be equivalent to the triple-equals version, as the types of both arguments are guaranteed to be strings. It'd be useful to be able to explicitly allow this, without having to disable triple-equals checking (eqeqeq) across the board as now. I'd actually argue for this to be the default behaviour for eqeqeq, but I'd be happy with a relaxing option at least.

Notably the article the JSHint references about equality comparison in the eqeqeq docs (http://javascriptweblog.wordpress.com/2011/02/07/truth-equality-and-javascript/) actually explicitly describes triple-equals here as an example of 'equality overkill'.

**I'd be happy to have a go at implementing this**, as long as there's general agreement that it's something JSHint would accept. Thoughts?

**Comment by liquidise** [comment]
> "There is irrefutably no benefit to abstract equality comparisons and therefore no reason to ever use them."

The sheer overstatement here is astounding. It is eclipsed only by the irony of the reality: to disable `eqeqeq`, setting it to `false` is actually inadequate and fails to update the setting. Instead, you must say 
```
"eqeqeq": true  // enables setting
"eqeqeq": false  // enables setting
"eqeqeq": null  // disables setting
```
If only someone had used an abstract comparator here.
