### ISSUE TITLE
inline maxlen configuration failing in anonymous function closures.

### ISSUE THREAD

**Issue by petebacondarwin** [jshint/jshint#1313]
In the following code, the first "very long line" is still reported as a warning, even though there is an inline directive disabling the feature.  This only happens for the anonymous function and not the named function:

```javascript
/* jshint maxlen: 50 */

(function() {
  /* jshint maxlen: false */
  ///////////// VERY LONG LINE ////////////////////
})();

(function test() {
  /* jshint maxlen: false */
  ///////////// VERY LONG LINE ////////////////////
})();
```

This seems to be that the line length checking happens before the jshint directives for that function block have been read. (Same happens if you explicitly disable the W101 warning.)

**Comment by lukeapage** [comment]
Fixed in v2.4.4
