### ISSUE TITLE
Unwanted W044 Error Message for RegExp Construction

### ISSUE THREAD

**Issue by adambom** [jshint/jshint#1317]
I'm trying to validate the following code with jshint and it keeps failing with the error, W044: Bad or unnecessary escaping.

I'm trying to construct a RegExp from a collection of strings, but it's complaining about escaping the '.' character. In this case, that character must be escaped in order for the test to function properly, since I'm trying to detect '.' characters.

```javascript
var VALID_CHARS = /[A-z0-9\-~:\/\?#\[\]@\!\$\&\'\(\)\*\+,;=%]/.source;
var TEST = new RegExp('(?:https?:\/\/)?(?:www\.)?' + VALID_CHARS + '*\.[a-z]+\/' + VALID_CHARS + '*\.(png|jpeg|jpg|tiff|tif|gif|svg)(\?;' + VALID_CHARS + '*)?', 'g');
```

Looking at the docs, I could not find a relaxing rule for this test. Is there a rule I can turn off? Should this be addressed in the jshint source?

**Comment by nicolo-ribaudo** [comment]
@rusekr It *is* an unnecessary escaping: you could just write `\\?`

**Comment by lukeapage** [comment]
Is there a bug here?

**Comment by nicolo-ribaudo** [comment]
No, because both the warning in the first code first and the one in the last were correct (It isn't necessary to escape `.` and `?` in strings)
