### ISSUE TITLE
Function declaration incorrectly reported as unused when global variable exists

### ISSUE THREAD

**Issue by Rob--W** [jshint/jshint#1320]
```javascript
/*1*/ /* jshint unused:true */
/*2*/ /* globals y */
/*3*/ (function() { 
/*4*/     'use strict';
/*5*/     y(); // Call local function
/*6*/     function y() { 
/*7*/     } 
/*8*/ })();
/*9*/ y(); // Call global function
```
Errors:
```
y.js: line 6, col 15, 'y' is already defined.
y.js: line 6, col 15, 'y' is defined but never used.
```
I expected no errors. Swapping the local function declaration and call results in no errors.

```javascript
/*1*/ /* jshint unused:true */
/*2*/ /* globals y */
/*3*/ (function() { 
/*4*/     'use strict';
/*5*/     function y() {
/*6*/     }
/*7*/     y(); // Call local function
/*8*/ })();
/*9*/ y(); // Call global function
```

When another y is not declared globally, i.e. line 2 is removed, then the error also goes away (but a new error is rightfully raised about the use of an undefined y, at line 9).

### Temporary work-around
In my real case, the variables were implicitly defined in `.jshintrc` using `devel:true`. In a node script, I declared a function called `prompt`, and called it a few lines back. This caused the error. A temporary work-around is to either rename the functions, or to insert
```
/* globals -alert */
```

at the top of the file.

**Comment by lukeapage** [comment]
Fixed by #2468 will be released in the next release (after 2.8.0)
