### ISSUE TITLE
Inconsistent warning: Bad operand (W017)

### ISSUE THREAD

**Issue by fi5er** [jshint/jshint#1329]
Either both or none of these should raise a warning:

    /* global numPending, notify */
    if (!--numPending) { notify("idle"); }
    if (!numPending++) { notify("busy"); }

The second condition raises a "Bad operand" warning, the first one doesn't.

**Comment by YellowSM** [comment]
Bump. It is annoying me too

**Comment by rwaldron** [comment]
Are you using the "[plusplus](http://jshint.com/docs/options/#plusplus)" option? If you are, I suggest removing it. It originates in the overly opinionated JSLint. It cannot be removed or changed without likely breaking substantial amounts of existing code.
