### ISSUE TITLE
Support external file as input

### ISSUE THREAD

**Issue by afeld** [jshint/jshint#1353]
I teach [a JS class](https://github.com/afeld/advanced_js) and [ask](https://github.com/afeld/advanced_js#requirements) that my student run all their code through JSHint before submitting.  For those that don't and leave blatant mistakes, it would be great to be able to send them a permalink like

http://jshint.com/?src=https%3A%2F%2Fraw.github.com%2Fafeld%2Fadvanced_js%2Fmaster%2Fbuild.js

that loads and runs their file.  [The W3C Validator](http://validator.w3.org/) supports this (input by URI with a permalink) for HTML.

**Comment by jugglinmike** [comment]
This is a nice idea, but fetching files from the web requires a level of architectural complexity that we're not able to take on at this time. Anyone wishing to implement this feature should feel free to start a discussion on [jshint.com's dedicated source code repository](https://github.com/jshint/jshint.github.io).
