### ISSUE TITLE
Add jshint option to disable "Missing '()' invoking a constructor. (W058)"

### ISSUE THREAD

**Issue by dantman** [jshint/jshint#1357]
I'd like so see a jslint option to turn off:
`Missing '()' invoking a constructor. (W058)`

I'm not interested in hearing warnings when `new Foo` is used in my code.
- It's perfectly valid ECMAScript.
- The `()` is redundant when `new` is already present.
- No one is going to try turning that into `new Foo bar` like the issue with `if ( foo ) bar();` being incorrectly turned into `if ( foo ) bar(); baz();`.
- Worrying about someone forgetting `new` and writing `Foo` is pointless since `Foo()` is also a bug in the code so requiring `()` won't help anyways.
- `new Foo` is not bad coding style in this local project. In fact the code in this project quite consistently omits `()` on constructors with no args so jshint only omits warnings for code that doesn't follow the local coding style.

I shouldn't have to write `/* jshint -W058 */` at the start of every file when I have a perfectly good .jshintrc file that I could put a named jshint option into.

**Comment by GSchutz** [comment]
Just to point that in the code below, I'm getting this error too, when it shouldn't (right?).
```
new (Function.prototype.bind.apply(Neomap, [Neomap].concat(_.toArray(arguments))));
```

**Comment by trusktr** [comment]
+1 for an option. I also like less punctuation when not needed.

```js
if (makeNode) node = new Node
```

vs

```js
if (makeNode) {
  node = new Node();
}
```

I really don't think the first example is harder to read or error prone, and is perfectly clear.

**Comment by trusktr** [comment]
@GSchutz Your example *should* have that error, because you're using `new` without the parens. We can modify your example to make it more evident why you get the error by taking everything out of the outer-most parens, so your code is equivalent to:

```js
let something = Function.prototype.bind.apply(Neomap, [Neomap].concat(_.toArray(arguments)));
new (something)
```

which simplifies to

```js
let something = Function.prototype.bind.apply(Neomap, [Neomap].concat(_.toArray(arguments)));
new something // no parens here, so you get the error.
```

where `something` is obviously a function.
