### ISSUE TITLE
Regarding removing 'white' and 'onevar'

### ISSUE THREAD

**Issue by jdwissler** [jshint/jshint#1358]
Is there a particular reason these need to be removed (onevar and white)?

I don't know how many people use them, but I like them because they bring consistency to my code formatting. I'm not particularly stuck on using Crockfords style, but being able to specify some consistency to my code is nice. 

However, I also know how the code looks has nothing to do with functionality, so maybe it doesn't belong in JSHint. Is there another tool I should be using for this feature?

Thanks.

**Comment by dcrockwell** [comment]
I hate to sound unappreciative, yet I am disappointed that these features were removed.

**Comment by mightyiam** [comment]
I'm now using [![js-standard-style](https://cdn.rawgit.com/feross/standard/master/badge.svg)](https://github.com/feross/standard) in all the things.

**Comment by doberkofler** [comment]
Use http://eslint.org. It's now basically a superset of jshint and jscs but also allows custom rules.

**Comment by rocky1138** [comment]
+1 on putting style rules back in. It's a pain to run two things when the first one worked great.

**Comment by doberkofler** [comment]
@rocky1138 just use eslint. One linter does it all and you can create your own custom rules.
