### ISSUE TITLE
Option for trailing commas?

### ISSUE THREAD

**Issue by Nilre** [jshint/jshint#136]
Is there a way to detect trailing commas with JSHint?

**Comment by yellenseram** [comment]
Is there an easy way to detect ONLY the trailing commas?

**Comment by arianf** [comment]
+1

**Comment by waynebloss** [comment]
@scottgonzalez or anyone really I guess - Is there any extension for this yet?

**Comment by waynebloss** [comment]
@scottgonzalez and anyone reading this - I see here [the note](http://jshint.com/docs/options/#laxcomma) about how Jshint doesn't want to be a style enforcer and to just use JSCS. So, that's what I shall do!

**Comment by gurdiga** [comment]
+1

**Comment by chramer** [comment]
+1

**Comment by arschmitz** [comment]
This feature was removed and is not coming back if you want style enforcement use jscs, or esformatter but +1 comments are not going to do much good at this point this is a 4 year old issue

**Comment by mcandre** [comment]
@arschmitz

-1

**Comment by EddieOne** [comment]
+2
