### ISSUE TITLE
Add option to suppress "Use '===' to compare with '0'" error

### ISSUE THREAD

**Issue by timdown** [jshint/jshint#1366]
Using `==` to compare to zero simply isn't an error or dangerous when comparing a value that is guaranteed to be a Number. For example:

```
var arr = ["foo"];
var arrIsEmpty = (arr.length == 0);
```

I tend to use `==` in these situations and it is a purely stylistic decision. I would like JSHint to respect my well-informed wishes.

**Comment by privman** [comment]
For others who may have a hard time to make use of valueof's answer, setting `"-W041": false` seems to do the trick.

**Comment by ldong** [comment]
Thanks @privman 

FYI, I also found more details [here](https://github.com/jshint/jshint/blob/bfcc86d6e51f53ae1e05cfdd33618e9bc0a9a957/tests/regression/thirdparty.js)

**Comment by redoPop** [comment]
Is there a motivation for keeping `W041` warnings in effect when `"eqeqeq": false`?

They effectively prohibit use of `==` and `!=` in affected situations.
