### ISSUE TITLE
// jshint ignore:line not working

### ISSUE THREAD

**Issue by jdewit** [jshint/jshint#1389]
Just tried this in the demo on the home page as well and it seems to have no effect. 

ignore:start / ignore:end does work

**Comment by UltCombo** [comment]
I'm having this issue with jshint@2.9.2 and the `unused` rule.

```js
for ( var x of this.gen ) { // jshint ignore:line
}
```

```plain
       	Unused Variables:
       		x(175),
```

**Comment by UltCombo** [comment]
Oh, never mind my previous comment, it was just the `--show-non-errors` that displays unused variables even when ignoring the `unused` rule violation.
