### ISSUE TITLE
Allow to run in parallel

### ISSUE THREAD

**Issue by rik** [jshint/jshint#1407]
On a large codebase, running in parallel can highly reduce the time it takes to run the whole linting.

**Comment by wjordan** [comment]
It looks like JSHint 3 work was abandoned in May 2014 (ed36a5ba60cdfc16a05f809e185d584139b70b96) - should this issue be reopened?

As a currently-available workaround, jgable/grunt-jshint2#6 implements multi-threaded jshinting as a Grunt plugin.
