### ISSUE TITLE
No warnings for trailing commas

### ISSUE THREAD

**Issue by mafigit** [jshint/jshint#1416]
It seems like jshint doesn't warn you about trailling commas inside hashes.
Like the following:

```
position: {
  my: 'bottom center',
  at: 'top center',
  viewport: true,
  adjust: { method: 'flip' }, //<----- Like this one here
} 
```

This breaks in IE10 and IE11, so it would be a good thing to check these things.

**Comment by waynebloss** [comment]
@valueof I just don't want trailing commas in my personal code, so it doesn't really matter to me personally, if ES5 allows them or not. That's why a lot of people have been asking for this feature I guess in other issues here.

**Comment by waynebloss** [comment]
@valueof Oh - I see here [the note](http://jshint.com/docs/options/#laxcomma) about how Jshint doesn't want to be a style enforcer and to just use JSCS. So, that's what I shall do!
