### ISSUE TITLE
option to capture only "console"?

### ISSUE THREAD

**Issue by balabesimple** [jshint/jshint#1437]
Is there any options to capture only "console" api usage?

devel: false,

By adding above statement , "console"  usage is warned but following keyword usage also showing as warning.

alert,confirm, console, Debug, opera, prompt

**Comment by lukeapage** [comment]
you can blacklist globals after putting devel to true, e.g.

```
/* jshint undef: true, devel: true */
/* globals -console */

console.log("hi");
alert("hi");
```

The same will be possible in the jshintrc using the predef option and the leading `-`
