### ISSUE TITLE
ignore doesn't work in some cases

### ISSUE THREAD

**Issue by clee704** [jshint/jshint#1465]
The following code gives you a warning.

    (function () {
      function foo() {
        /* jshint ignore:start */
        @@workload
        /* jshint ignore:end */
      }
      foo();
    })();

Strangely, the warning disappears when there are odd number of newlines between the top level function and function `foo`. So for example, with the following code:

    (function () {

      function foo() {
        /* jshint ignore:start */
        @@workload
        /* jshint ignore:end */
      }
      foo();
    })();

You see no errors.

This is confirmed with v2.4.1.

**Comment by lukeapage** [comment]
re-tested with master after latest improvements (https://github.com/jshint/jshint/commit/09716080b4e49c6ab6b96c29351a9f816c3e6419) to ignore and it is still an issue - though some of these cases might be fixed.

**Comment by jugglinmike** [comment]
This was a tricky one! The test cases provided in the comments on this issue were resolved via gh-2427 as @lukeapage mentioned, but it wasn't until we landed gh-2512 that the originally-reported example was fixed.

Anyway, we're all better now! Expect the fix in the next release of JSHint (whatever follows 2.8.0). Thanks for the help, everyone!
