### ISSUE TITLE
Reserved name '__proto__', Unable to continue (0%)

### ISSUE THREAD

**Issue by oryband** [jshint/jshint#148]
See this line:

```
var x = typeof "test".__proto__ === "object" ;
```

JSHint returns with the following 2 errors:

```
1. Reserved name '__proto__'.
2. Stopping, unable to continue. (0% Scanned)
```

I searched the web and [found out using `.__proto__` is outdated](http://www.techques.com/question/1-5277196/jslint-complains-about-__proto__-being-a-reserved-word).

However, trying `test['__proto__']` instead causes another problem:

```
['__proto__'] is better written in dot notation..
```

Which brings us back to square one.

Two problems arise:
1. What is the correct method of testing `.__proto__` ?
2. Even if JSHint is correct, why does it stop linting the page afterwards?

**Comment by rambo-panda** [comment]
one :  /* jshint: proto : true */
two : var like_proto = "__proto__"; Object[like_proto];   

l like the first
