### ISSUE TITLE
It *is* necessary to initialize 'x' to 'undefined'.

### ISSUE THREAD

**Issue by axkibe** [jshint/jshint#1484]
See following simplified test
```
for( var i = 0; i < 10; i++ )
{
	var x = undefined;

	if( i % 2 === 0 )
	{
		x = null;
	}

	if( x === undefined )
	{
		console.log( i );
	}
}
```

the output is as one can easily guess:
```
1
3
5
7
9
```

jshint complains that:
test.js: line 3, col 9, It's not necessary to initialize 'x' to 'undefined'.

However,
```
for( var i = 0; i < 10; i++ )
{
	var x;

	if( i % 2 === 0 )
	{
		x = null;
	}

	if( x === undefined )
	{
		console.log( i );
	}
}
```

will produce on V8 (chrome and node)
only
```
1
```

As x will not be reset to undefined on every loop interation.

( jshint v2.4.2 )

**Comment by gaearon** [comment]
It's a strange rule.

**Comment by qsona** [comment]
+1

**Comment by Kariiboo** [comment]
Explicit initialize to undefined is useless since this is the default javascript behavior.
The problem here is that javascript do not have block scope. 
`x` have to be initialize to `undefined` at each iteration.
The following code behave like expected and jshint do not complain:
```javascript
var x;
for( var i = 0; i < 10; i++ )
{
    x = undefined;

    if( i % 2 === 0 )
    {
        x = null;
    }

    if( x === undefined )
    {
        console.log( i );
    }
}
```

**Comment by axkibe** [comment]
I know, but my first code sample was also good, yet jshint falsely complains.

**Comment by rwaldron** [comment]
> I know, but my first code sample was also good

This is the mistake: JSHint is identifying bad practices so that you can fix them. If you want to ignore JSHint's advice, tell JSHint that: 

```
/* jshint -W080 */
```

**Comment by axkibe** [comment]
My first example is NOT bad practice! Its perfect okay code! The only one at fault here is jshint

**Comment by axkibe** [comment]
And -W080 turns of _all_ setting to undefined errors, outside of loops its a good warning, inside its not.

**Comment by Kariiboo** [comment]
+1 @axkibe

I agree with @axkibe: This is correct javascript code! Doing it or not is just be a mater of taste. 
But fixing the code to be JSHint compliant is not a mechanical replacements.
JSHint do not advice. It is developper task to choose how to fix the code. The fact is that for inside loop code, the first idea breaks the code...
I can understand that it is a bad practice because of the default behaviour of variable declaration. 
But since JS do not have block scope, it leads to write code a unnatural way, hoisting variable declaration just to avoid JSHint to complain.
It would be nice to also be able to use directives like `/* jshint -W080 */` locally to a line and locally to a block of code to silent JSHint on a precise portion of code.

@rwaldron you say "JSHint is identifying bad practices so that you can fix them".
The goal of JSHint is not clear to me. We can read on JSHint web site
 - "This is JSHint, a tool that helps to detect errors and potential problems"
 - "JSHint is a program that flags suspicious usage in programs written in JavaScript"
I find all very interesting. But they should be dissociated : 
 - Errors, 
 - Potential problems, 
 - Bad practices.

**Comment by rwaldron** [comment]
> "JSHint is a program that flags suspicious usage in programs written in JavaScript"

Redeclaring a `var` binding within the for loop body is a "suspicious usage". If a reader was coming from another language, or was new to programming, this pattern would **look** like:

- a new `var` binding for each loop turn
- the `var` binding is scoped to the for loop body

Neither thing is true, which is suspicious. 


> hoisting variable declaration just to avoid JSHint to complain.

What's the point of using a code linting tool if you don't want to follow the guidance it provides?


> It would be nice to also be able to use directives like /* jshint -W080 */ locally to a line and locally to a block of code to silent JSHint on a precise portion of code.

Do you mean like this: 

```js
/* jshint -W080 */
for (var i = 0; i < 10; i++) {
  var x = undefined;

  if (i % 2 === 0) {
    x = null;
  }

  if (x === undefined) {
    console.log(i);
  }
}
/* jshint +W080 */
```

Or more like this?


```js
for (var i = 0; i < 10; i++) {
  /* jshint -W080 */
  var x = undefined;
  /* jshint +W080 */
  if (i % 2 === 0) {
    x = null;
  }

  if (x === undefined) {
    console.log(i);
  }
}
```

**Comment by rwaldron** [comment]
https://github.com/jshint/jshint/issues/1484

**Comment by axkibe** [comment]
Having opened this issue a year ago, in the meantime my javascript coding style has anyway developed so I'm manually hoisting variables today. I did this like above when I was relatively new to it coming with many years experience in C++/Java/Lua etc who all do sane variable shadowing.

Anyway the issue with jshint is, it gives the coder the *wrong* guidance.

It literally says, you do not need to set the variable to undefined here while you have. It would guide you saying like "hey, you know, manually hoisting this would look cleaner"... okay, today I agree, I guess some peopel would argue about it.

But it says "leave that = undefined" away. Which however will break your code. Which back then it did for me, when I wasn't yet aware how variable non-shadowing / hoisting works in Javascript.

**Comment by axkibe** [comment]
BTW: 
```
for (var i = 0; i < 10; i++) {
  var x; x = undefined;

  if (i % 2 === 0) {
    x = null;
  }

  if (x === undefined) {
    console.log(i);
  }
}
```
Is a nicer looking way to get rid of warning 80 when not wanting to manually hoist x. However to repeat my opinion we shouldn't direct people the wrong way.

**Comment by MarcoSulla** [comment]
Sometimes I need, for the sake of explicitness, to write `var a = undefined` to make it clear I want it undefined, and I do not forget to initialize it. 

I think an unnoticeable difference in script load is much less important that code clearness.

**Comment by MarcoSulla** [comment]
Furthermore:

for (var i=0; i<5; i+=1) { 
    var x = undefined; 
    console.log(x); 
    x = 5; 
}

result: 
5x undefined

for (var i=0; i<5; i+=1) { 
    var x; 
    console.log(x); 
    x = 5; 
}

result:
1x undefined
4x 5

Ok, declaring a variable inside a for loop is a bad practice, but it's **NOT** signaled by JSHint...

**Comment by jonnylink** [comment]
I think this needs to be reopened. The guidance here seems bad. V8 will create a new hidden class each time you add a parameter to an object or class. The recommendation I've heard and read many times is to include any parameters you know you'll need from the start. 

supporting example: https://blog.ghaiklor.com/optimizations-tricks-in-v8-d284b6c8b183

**Comment by jugglinmike** [comment]
@jonnylink The issue being discussed here does not concern parameters. Though the reference you cited describes property definition, that is also not relevant to this particular conversation. Perhaps you intended to post your comment elsewhere?

**Comment by manngo** [comment]
My own additional thoughts:

1. The statement `var x = undefined;` is doing _two_ things. The variable declaration, as everybody has already mentioned is virtually hoisted. If you do this manually, then you can focus on the next point.
2. jsHint has no problems with `x = undefined;` so manually hoisting the declaration will also solve the problem.
3. declaring variables on the fly in JavaScript is probably a bad idea, and a hangover from C where it is not so bad. In C, variables have block scope, so it is meaningful to declare a temporary variable as you have done. In JavaScript normal variables do not have block scope, and so their declaration at this point is confusing, and possibly a bit lazy.
4. Modern JavaScript has the `let` variable, which is scoped more like the C style variables, and declaring it later has a point.

Just thinking out loud …
