### ISSUE TITLE
2.4.3 jshint comment parser regression

### ISSUE THREAD

**Issue by Raynos** [jshint/jshint#1496]
The following file

```js
module.exports = {
    A: function () {
        return (!this.a);
    },
    B: function(c) {
        /* jshint camelcase: false */
        return c.a[this.b].some_junk;
    }
};
```

And the following command

`echo '{ "camelcase": true }' > ./jshint.json && jshint --config ./jshint.json test.js`

Will pass & fail in 2.4.2 and 2.4.3 respectively.

I'm not sure what changes landed in 2.4.3 to break the jshint comment parser, nothing obvouis as far as I could see, maybe the spaces to tabs change brings a regression.

We worked around this by downgrading to 2.4.2

**Comment by lukeapage** [comment]
Fixed in jshint 2.4.4
