### ISSUE TITLE
Allow multiple .jshintrc via "import" or "include" functionality

### ISSUE THREAD

**Issue by eternicode** [jshint/jshint#1502]
This may be duplicate-ish of #1401, but I feel that the scope of that issue is beyond the simple one I'll outline below.

My project has a directory structure like this:

```
- javascript/
  | - main_app/
  |   | - main.js
  |   + - supporting_files_etc.js
  | - per_page/
  |   | - payment.js
  |   + - profile.js
  + - common.js
```

We currently have `javascript/.jshintrc`, which contains the general rules for our code as well as globals from `common.js`.  But, what we'd also like to do is have `javascript/main_app/.jshintrc` that defines a number of additional globals available to the files under that directory.

As I understand it (and if I read the source correctly), jshint only allows one .jshintrc, found by walking up the directory tree from the file being linted (and stopping the search once it's found).  So what we're doing currently is putting `/* global */` directives at the top of every js file in that directory to "declare" the variables needed by that file.  Not ideal.

I'd like to propose a new configuration rule like "import" or "include", which would be an array of paths to JSON files (relative to the config file they're in) with rules to include in the current config.

For example, `javascript/main_app/.jshintrc` might look like:

```
{
  "include": ["../.jshintrc"],
  "globals": {
    "extra_global": false,
    "etc": false
  }
}
```

The merging would be like "stacking" configs: for `include: [a, b]`, the rules for `a` would be the base config, those would be overridden by the config in `b`, and _that_ would be overridden by the config in the current config file.

I can also imagine this being extended to the CLI to allow multiple instances of the `--config` option (`jshint -c a.json -c b.json` would stack `b.json` on `a.json`).

Does this seem reasonable?

**Comment by macgyver** [comment]
There still does not seem to be any documentation for this feature but based on the PR where it was added it looks like a shallow extend: https://github.com/jshint/jshint/pull/1314/files

**Comment by jugglinmike** [comment]
Docs on this option were introduced in this commit: https://github.com/jshint/jshint.github.io/commit/88c019d6aeec1f0151716a8d5b62de388dd166b9. You can find them on this page: http://jshint.com/docs/cli/
