### ISSUE TITLE
Running jshint in a folder containing a file named "node.js" executes the "node.js" file.

### ISSUE THREAD

**Issue by alumb** [jshint/jshint#1515]
System: windows 7, powershell, jshint v2.4.1, nodejs v0.10.24

preconditions: add a default program to .js files, in my case I have a text editor set as the default so that if a .js file is executed, it loads it in a text editor. 

steps to reproduce:
1. locate a folder containing two javascript flies, one named node.js
2. run jshint on the second javascript file.

expected behaviour:
- jshint error are returned from the second javascript file

actual behaviour:
- node.js file is executed, opening it in the text editor in my case.

**Comment by lukeapage** [comment]
Thanks!
