### ISSUE TITLE
Column reported wrong for W004, already defined.

### ISSUE THREAD

**Issue by mokkabonna** [jshint/jshint#1519]
With this code

    function test() {
      'use strict';
      var foo;
      var foo            = 'yo';
    }

And the standard options I get this errors:

    filePath.js: line 4, col 22, 'foo' is already defined. (W004)

No matter how much whitespace I have between between the second `foo` and the `=` it reports the error at the `=`.

Same behaviour with `var foo            ;`

IMO it should be at 10. (right after `foo`)

**Comment by lukeapage** [comment]
Fixed in master, probably by my scope refactorings. Will be released in the next release (after 2.8.0)
