### ISSUE TITLE
Command line JSHint without Node.js

### ISSUE THREAD

**Issue by dvorapa** [jshint/jshint#1521]
Is there any other option, how to get JSHint into Windows command line without using Node.js? Is it possible to get jshint.bat and jshint command line environment with all dependencies in simple zip archive or by using git clone? I know, Node.js is needed to compile the JavaScript. But is it needed to run JSHint in command line? Or could I install and compile it somehow with Node.js and then use it without Node.js? I actually work on a plugin for one text editor and the plugins for that are based on command line (like compilers). But I don't want users to install Node.js to use my plugin. I'm beginner in Node.js.

**Comment by meson10** [comment]
@dvorapa +1

**Comment by jmichae3** [comment]
I would request the same thing. need a console-mode binary for windows, preferably 32-bit.

**Comment by jmichae3** [comment]
oh, and 1521 was a feature request, not a request for support. please read before blasting away at bug reports. if you are able to provide a binary by compiling for windows using mingw-w64 (sf.net) then it would be most helpful. one possibility is windows script host (wscript.exe). you can probably specify the language in the script tags, but it might be an ie-flavored version of jscript or VBA you get.

Q: is this the way jslint was intended to run under? or something else? I suspect the DOM is going to be different for JScript commandline.

**Comment by jmichae3** [comment]
that is, if it's enabled...
