### ISSUE TITLE
forin warning cannot be suppressed

### ISSUE THREAD

**Issue by Marshallx** [jshint/jshint#1537]
Whether setting forin:false in .jshintrc or setting /* jshint forin:false */ in code

The forin warning about not wrapping in an if statement still appears.

**Comment by lukeapage** [comment]
cannot reproduce going back to 2.4.3 and forwards..

**Comment by lukeapage** [comment]
used
```
/* jshint forin: true */
function test() {
  /* jshint forin: false */
	var a = [];
	for(var b in a) {
  	console.log(b);
	}
}
```

If you provide a test case that reproduces the problem I'll re-open
