### ISSUE TITLE
Option to disallow "var" keyword with esnext: true

### ISSUE THREAD

**Issue by fluidsonic** [jshint/jshint#1549]
`esnext: true` adds support for `let` and `const` which make `var` obsolete in most cases, esp. in node.js environments. It would be great to have an option to warn about variables declared with `var` since its usage is most likely a mistake in ES6 files.

**Comment by callumlocke** [comment]
relevant discussion:
[Is there any reason to use the “var” keyword in ES6?](http://programmers.stackexchange.com/questions/274342/is-there-any-reason-to-use-the-var-keyword-in-es6)

**Comment by rwaldron** [comment]
@caitp @jugglinmike are either of you interested in this one?

**Comment by caitp** [comment]
I guess if it's a linting rule people want, why not?

**Comment by callumlocke** [comment]
thanks for this @caitp :+1:
