### ISSUE TITLE
esnext and object initializer shorthand

### ISSUE THREAD

**Issue by mvolkmann** [jshint/jshint#1555]
jshint complains about this:

let foo = 1;
let obj = {foo};

Shouldn't that be okay and be treated just like this?
let obj = {foo: foo};

**Comment by alFReD-NSH** [comment]
I just checked and this works in master version 2.6.0

**Comment by lukeapage** [comment]
@rwaldron this can be closed

**Comment by rwaldron** [comment]
Thanks!
