### ISSUE TITLE
ES6 Modules and strict option

### ISSUE THREAD

**Issue by DonutEspresso** [jshint/jshint#1636]
ES6 modules are strict by default. Is there a way to trigger strict parsing without actually having to output the 'use strict' statement within ES6 files? It's not clear to me if ESNext triggers that. Using globalstrict: true causes the parser to complain about missing use strict statements. My understanding is that ES6 assumes strict by default, and does not require the 'use strict' identifier. 

(Context: source code does not have 'use strict', but ES6 transpiler adds 'use strict'. I want to avoid having two 'use strict' statements in transpiled code.)

**Comment by wuct** [comment]
+1

**Comment by jugglinmike** [comment]
What are you +1'ing?

**Comment by arcanis** [comment]
JSHint warns about missing strict mode declarations even when the file is an ES6 module. So we +1'ing this :

> This is correct. Detection should be trivial, any file with an export must be treated as a module.

**Comment by kikonen** [comment]
So, has there been in progress on this. I.e. adding extra "use strict" into .es6 files is a bit clumsy workaround.

**Comment by jugglinmike** [comment]
Many people have posted "+1", but there has been no progress that I am aware of. If anyone is interested in helping out, I will update the "Assignee" attribute on this issue to make that more clear

**Comment by caitp** [comment]
so, there's a bit of a problem with this --- we don't know if we need to parse as a script or as a module.

yeah, we could sniff the file and see if it contains any module-specific syntax, but that doesn't help much (that's not how engines will behave, most likely, especially if we end up with the `<script module>` or whatever that has been proposed before. If a file containing no module syntax is still a module, then we'd be dishonest in doing this.

I think what it really needs, is like an extra setting in .jshintrc or something, to list files which are to be parsed as modules --- or to enable "parse as module by default". This would also allow us to report module syntax in scripts as syntax errors, I think. @rwaldron would know better, but otoh that seems right

**Comment by rwaldron** [comment]
> I think what it really needs, is like an extra setting in .jshintrc or something, to list files which are to be parsed as modules --- or to enable "parse as module by default".

That's about the only unambiguous solution I've seen so far. I can support that. @jugglinmike ?

**Comment by kikonen** [comment]
Detecting it by file extension surely sounds rather robust to me (I presume you are meaning that). Such file extension list could even default into something like [".es6'"] (unless something else specified by the .jshintrc). However, I think that "parse as module by default" option could have some trouble with projects containing both es5 and es6 files.

**Comment by caitp** [comment]
doesn't sound very robust to me, especially since there isn't always a file name at all =)

**Comment by rwaldron** [comment]
> Detecting it by file extension surely sounds rather robust to me

Then perhaps we'll include globbing capabilities in @caitp's proposed solution, but there will not be any semantics that specifically look for files with ".es6" (because that's not a thing)

**Comment by impinball** [comment]
Also, ES6 import and export statements aren't valid in script bodies. The `esnext`option would be best to take that into account for non-modules. 

Also, would a `module`option (defaults to `esnext` value) work? A value of a string indicates a globbing pattern, and false means it's not a module? (This also means the built-in `exports` and `require` should be initially undefined for Node)

**Comment by rwaldron** [comment]
@impinball 

> import and export statements aren't valid in script bodies


Yes, it's conceivable that an implementation could infer that a particular file should be treated as implicitly strict if _ImportDeclaration_ or _ExportDeclaration_ are present

**Comment by jugglinmike** [comment]
I'm reluctant to extend any value option with file semantics because this could cause confusion if the option were to be set this way when used in contexts where there are no files, or if it were set as an in-line directive.

As mentioned in gh-2306, it's probably better to separate all file-targeting concerns to the `overrides` option (which is restricted to .jshintrc files).

**Comment by jugglinmike** [comment]
We just landed gh-2306, so you can expect the `module` option in the next version of JSHint (>2.7.0).

As noted in that discussion, there is no foolproof heuristic to inferring whether a given program is module code or not, so you'll need to be explicit in enabling this option for the code you intend to execute as a module.

Regarding enabling by file name: see [my previous comment](https://github.com/jshint/jshint/issues/1636#issuecomment-94497591) for rationale against building that into the option itself. You can again reference gh-2306 for information on using JSHint's `overrides` option to specify rules according to file name (which has the added benefit of working for *all* options).

**Comment by impinball** [comment]
Yay!
