### ISSUE TITLE
validthis option doesn't work in anonymous functions

### ISSUE THREAD

**Issue by mansona** [jshint/jshint#1640]
Bit of a strange one, I'm using Cloud9 IDE which has an inbuilt jshint instance and it's not picking up some of the options I need it to correctly. 

Unfortunatley I can't recreate this on the command line because i don't know how to turn on checking for this particular error, maybe someone could point me in the right direction. 

Anyway, here is the example with annotations as to where the warnings are
```
/* global App */
App.Router.map(function () {
    /* jshint validthis: true */
    this.resource('first', function(){      // :warning: Use of 'this' in callback function
        this.route('sub', {path: '/:sub'}); // :warning: Use of 'this' in callback function
    });
    this.resource('second');                // :warning: Use of 'this' in callback function
});


function mapFunction(){
    /* jshint validthis: true */
    this.resource('first', function(){       //no warning
        /* jshint validthis: true */
        this.route('sub', {path: '/:sub'});  // :warning: Use of 'this' in callback function
    });
    this.resource('second');                  //no warning
}
```

now there should really not be any difference between the anonymous function and the named function really, but clearly it is treating it differently.

**Comment by rw251** [comment]
That would seem to me to be the correct behaviour based on the error message.  In your top example 'this' appears 3 times, each of which is in a callback function hence the 3 warnings.  In the bottom example only 1 instance of 'this' occurs in a callback function hence only one warning.

I suggest this can be closed unless anyone has anything else to add.

**Comment by mansona** [comment]
Agreed, past me couldn't see there difference but I see it now #progress
