### ISSUE TITLE
Option to remove warnings for reserved keywords

### ISSUE THREAD

**Issue by danielb2** [jshint/jshint#1646]
Could be two scenarios really and it would make sense to have options to disable one or both.

At the very lease it should be possible to disable the warnings for the second use-case.

Default is the keyword. Should be able to turn off warning.

``` javascript
var default = {};
```

Delete is the keyword below, but this should be safe usage.

``` javascript
var post = Post.find({author: 'daniel'});
post.delete();
```

**Comment by Krinkle** [comment]
@danielb2 Yes, by enabling `/jshint es5:true */` (the default as of JSHint 2.x). Using reserved words such as `delete` only works in ES5 engines. That isn't a choice by JSHint but by the actual specification and implementation in javascript engines. If you need to support ES3 environments, then using `delete` in dot-position will actually cause an error, and as such JSHint also warns for that.
