### ISSUE TITLE
"undef:false" and "globalstrict:true" bug

### ISSUE THREAD

**Issue by christianbundy** [jshint/jshint#1665]
I'm not sure if anyone reads old closed issues, but #1033 is a bug that still needs to be fixed.

> This works:
> 
> ``` js
> /*jshint globalstrict:true */
> /*jshint undef:false*/
> var fn = function () {
>   'use strict';
>   return someGlobal;
> }
> ```
> 
> Whereas this throws `'someGlobal' is not defined`:
> 
> ``` js
> /*jshint globalstrict:true */
> /*jshint undef:false*/
> 'use strict';
> var fn = function () {
>   return someGlobal;
> }
> ```
> 
> Using a global in strict mode in a function doesn't throw an error (as we can see in the first example), but widening the scope causes problems. Javascript doesn't interpret globals differently depending on where the `'use strict';` is set – why does JSHint?

I'm using this with @Meteor, where all Javascript files are wrapped in a `(function (){ ... )();` closure before they're concatenated, so accessing globals **is** possible while a file scoped `'use strict';` **isn't** allowed to leak to other files. I'd be more than happy to help with this bug in any way that I can. Thanks!

**Comment by lukeapage** [comment]
this doesn't seem a bug any more - both throw ?
@jugglinmike should this be closed?
