### ISSUE TITLE
Add option for requirejs global option

### ISSUE THREAD

**Issue by zafar-saleem** [jshint/jshint#1686]
I am using jshint with my requirejs application. Everytime, I parse my code it gives me error that "require" and "define" are not defined. One way to overcome this is to add "/*global define:false */" at the top of every module which is cumbersome. Therefore, would be great to add an option in jshint so that it could be set to true or false to overcome this error.

**Comment by mjomble** [comment]
Since there are already several library-specific configuration options for JSHint that add predefined variables, how about one for AMD that adds 'define' and 'require'?

**Comment by jugglinmike** [comment]
Technically speaking, an environment option for AMD would only add `define` (`require` being a RequireJS-specific extension). In that case, there isn't really much saved from a dedicated option. There may be slightly more benefit to a "requirejs" environment option, but [we're discouraging library-specific extensions](https://github.com/jshint/jshint/pull/1955#issuecomment-62461476) and really only maintaining the current ones for backwards compatibility.

**Comment by ryanfitzer** [comment]
>  (`require` being a RequireJS-specific extension).

The `require` global variable is part of the [AMD spec](https://github.com/amdjs/amdjs-api/blob/master/AMD.md#global-variables-):

> This specification reserves the global variable "require" for use by module loaders. Module loaders are free to use this global variable as they see fit. They may use the variable and add any properties or functions to it as desired for module loader specific functionality. They can also choose not to use "require" as well.

**Comment by jugglinmike** [comment]
It's certainly mentioned there, but that's about as non-committal as spec language can get. Because a loader might not define `require` globally (as is the case with curl.js, for example), it would be inappropriate for JSHint to insert `require` into the list of pre-defined globals for such cases.

**Comment by ryanfitzer** [comment]
> It's certainly mentioned there, but that's about as non-committal as spec language can get.

This should not be about one's opinion on the commitment of the AMD spec. Your defense of not adding an `amd` option seems to be based on an incorrect understanding of which globals the AMD spec reserves:

> Technically speaking, an environment option for AMD would only add define (require being a RequireJS-specific extension). In that case, there isn't really much saved from a dedicated option.

It would beneficial for JSHint to have a standard that one can consult in order to evaluate future decisions against. For example: "Must reserve more than 2 globals" is a requirement that could be used.
