### ISSUE TITLE
eval as a property name cannot be harmful

### ISSUE THREAD

**Issue by alxgnon** [jshint/jshint#1690]
Tested with v2.5.1.

---

```js
// INPUT:             // OUTPUT:
var a = {};           //
a.eval = 5;           // line 2, col 8, eval can be harmful.
```

```js
// INPUT:             // OUTPUT:
var a = {};           //
a['eval'] = 5;        // line 2, col 2, eval can be harmful.
```

```js
// INPUT:             // OUTPUT:
var a = {eval: 5};    // <no output>
```

```js
// INPUT:             // OUTPUT:
var a = {eval: 5};    //
var b = a.eval;       // line 2, col 15, eval can be harmful.
```

---

None of these cases can be harmful. JSHint forbids us of using `eval` as a property name. That can obviously be problematic when working with an API that defines a property or method `eval`. This isn't something we should have to work around.

At the same time, we don't want to stop detecting any cases where `eval` is used in a harmful way.

### Related Issues
* Eval error when eval method exists in a object #738
* eval is not always evil #1204

**Comment by jugglinmike** [comment]
We have a number of open issues tracking this bug, so I'm going to close this in favor of the original: gh-738.
