### ISSUE TITLE
When node: true is set globally, can't override to false

### ISSUE THREAD

**Issue by qris** [jshint/jshint#1712]
I have a mixture of Node files and client-side javascript modules (loaded with `require.js`) in my application.

The Gruntfile defines a `jshint` task:

    jshint: {
      files: [
        '**/*.js',
        '!node_modules/**/*'
      ],
      options: {
        node: true
      }
    },

I get errors from the client-side use of Require.JS global `require` variable:

    lib/require.config.js
     13 |var require = {
             ^ Redefinition of 'require'.

This is allowed in RequireJS, and I use it to share configuration (module loading paths) between tests and production code, although they have different initial `require()` statements.

> Also, you can define the config object as the global variable require before require.js is loaded, and have the values applied automatically. This example specifies some dependencies to load as soon as require.js defines require():

I think the solution would be to turn `node` mode *off* for the client-side JavaScript files, leaving it on for the server-side files. But I get the above error even if I have the following line in the same file:

    /* jshint node: false */

It appears that I can't turn Node mode off. Any idea why?

Note: I can disable the warning with this code instead:

    /*jshint -W079 */

But of course I don't want to allow polluting the global namespace accidentally.

**Comment by nicolo-ribaudo** [comment]
This is a dupicate of #1535

**Comment by lukeapage** [comment]
yes, I agree
