### ISSUE TITLE
TypeError: Cannot read property '<whatever>' of undefined

### ISSUE THREAD

**Issue by anshou** [jshint/jshint#1730]
When typing a simple logging middleware for an express app I am building, I ended up with this line:

```javascript
console.log("%s %s -> %j". req.method, req.url, req);
```

Which triggered no output when fed into jshint.  The issue is the period/dot character after the closing double-quote.  When this line is compiled, the following error is thrown:

```
TypeError: Cannot read property 'method' of undefined
```

btw jshint is great :)

**Comment by lukeapage** [comment]
jshint no longer does style checking, jscs would have caught this issue if setup correctly.

Another possible rule would be string literal followed by dot is invalid, requiring you to wrap in parenthesis or abstract to a var.

I think the conclusion of this is just to close it?

**Comment by jugglinmike** [comment]
For many developers, method chaining (especially involving promises) involves whitespace between property access, e.g.

```js
return fetch()
  .then(good)
  .then(good2, handleError);
```

To me, this makes the issue much more obviously about style--the code and configuration that would support one kind of whitespace and not the other would involve a lot of nuance in the interpretation of "acceptable" whitespace. So I agree with Luke on this one; I'll close it and recommend using JSCS to enforce this expectation.
