### ISSUE TITLE
JSHint marks "javascript:void(0);" as a JS URL

### ISSUE THREAD

**Issue by strugee** [jshint/jshint#1738]
If I assign an element's `href` to `javascript:void(0);` (as opposed to `#`), like so:

```
$('#foobar').attr("href", "javascript:void(0);");
```

JSHint picks up the `javascript:void(0);` construct as a Script URL:

```
PS C:\Users\hal9000\Development\strugee.github.com> grunt lint
Running "jshint:all" (jshint) task

   js\main.js
     30 |    $('#lightbulb-icon').attr("href", "javascript:void(0);");
                                                                    ^ Script URL.

>> 1 error in 4 files
```

when in fact it isn't doing anything and is semantically valid. There should be an exception for these types of Script URLs.

**Comment by MikeGodin** [comment]
Passes jslint:
`$('#foobar').attr('href','javascript'+String.fromCharCode(58)+'void(0);');`

**Comment by strugee** [comment]
@MikeGodin looks like a separate bug.

**Comment by englishextra** [comment]
@kcampion putting # and return false is not always desirebale
in my case i dont want hash to appear
