### ISSUE TITLE
Allow per-identifier `newcap: false`

### ISSUE THREAD

**Issue by dantman** [jshint/jshint#1742]
Some libraries, for example [Q](https://github.com/kriskowal/q), are used uppercase but do not need `new` (in fact it's not even recommended).

Right now the only options for `newcap` are on and off for everything. So I either get false errors for Q and I have to turn off `newcap` per-function or I miss warnings for real errors where I miss `new` for a different class.

I'd like an option to disable newcap for a single identifier so instead of turning off all newcap for individual blocks I can instead turn off newcap for Q in an entire file when I require it.

**Comment by kofifus** [comment]
+1 need this as well
