### ISSUE TITLE
redefinition of Promise (W079)

### ISSUE THREAD

**Issue by helmus** [jshint/jshint#1747]
I just switched from 2.4.4 to 2.5.1
But now all my requires are messed up because:

`var Promise = require('bluebird')`
Will warn about:
`Redefinition of Promise (W079)`

Is there anyway I can fix this ? I'm using bluebird all over the place.

**Comment by fluidsonic** [comment]
I wonder why the warning is also thrown for block scoping:

```js
const Promise = require('bluebird');  // same for `let`
```

The global variable will be untouched in this case.

If you can use ES6 features (node 0.11+) and #2090 is fixed then renaming the variable should not be necessary anymore.

**Comment by rwaldron** [comment]
> The global variable will be untouched in this case.

True, and that should be filed as a different issue—which you did, thanks!

But...

> If you can use ES6 features (node 0.11+) and #2090 is fixed then renaming the variable should not be necessary anymore.

`let` and `const` in v8 (as seen in node 0.11.x) are a prototype implementation that is not longer correct (as in, several years out of date) and therefore _not_ an ES6 feature, so you _really_ shouldn't be using them, because they don't adhere to the specification semantics.

**Comment by caitp** [comment]
> so you really shouldn't be using them, because they don't adhere to the specification semantics.

In fact, please, please do not use these (in either v8 or in web applications) --- otherwise we might never be able to ship "correct" behaviour ;_; and that would be sad. If you see legacy let/const behaviour in the wild, please tell the appropriate people to remove it

**Comment by rwaldron** [comment]
@caitp +9001

**Comment by fluidsonic** [comment]
Can anyone reference info on what changed about `const` and `let`?
I wasn't able to find any info on that and I see no reason for not using it in Node.

**Comment by rwaldron** [comment]
@fluidsonic it looks like the version of v8 running in node 0.10.35 has [TDZ semantics](https://gist.github.com/rwaldron/f0807a758aa03bcdd58a), but let and const are still intentionally (and incorrectly) limited to strict mode code.

**Comment by jugglinmike** [comment]
Hey everybody,

JSHint 2.8.1 ([released today](https://github.com/jshint/jshint/releases/tag/2.6.1)) includes [a new option named `futurehostile`](http://jshint.com/docs/options/#futurehostile) which we designed to be a more understandable alternative to `predef: ['-Promise']`. Hope that helps!

**Comment by JackCA** [comment]
^ *2.6.1*

**Comment by aexmachina** [comment]
I don't know how that's more understandable, but anyway... ;)​

**Comment by sam-github** [comment]
Even with Promise in v8/io.js, its deathly slow, and ***unlike*** `Array`, Promise was explicitly designed to allow alternative and interoperable implementations.

```
Promise = require('bluebird');
```

should be a warning

```
var Promise = require('bluebird');
```

should not be, IMO. I've gone the globals route, ATM.

**Comment by aldendaniels** [comment]
@domenic - would love your input here. Is overriding `window.Promise` on the web or `global.Promise` on node/iojs within a local scope future proof?

Example:
```javascript
var Promise = require('bluebird');
```

**Comment by rwaldron** [comment]
> Is overriding window.Promise on the web or global.Promise on node/iojs within a local scope future-proof?

This is self contradictory.

**Comment by domenic** [comment]
No, it is future hostile.

**Comment by aldendaniels** [comment]
@domenic - Thanks!

@rwaldron - 
> This is self contradictory.

Sorry for the confusion. I've updated my question for clarity. I meant, "is redefining the `Promise` builtin within a local scope future-proof".

The examples provided by @petkaantonov in [bluebird](https://github.com/petkaantonov/bluebird) redefine the `Promise` builtin, which led me to wonder if (in the case of Promises particularly - per @sam-github's comment) this was actually accepted practice. 

Sounds like the answer is "no".

**Comment by sam-github** [comment]
https://github.com/jshint/jshint/issues/1747#issuecomment-94024023

@domenic why future hostile? Promises were explicitly designed by spec to support alternate co-existing implementations... why not call the promise implementation being used in a particular node module `Promise`, rather than, say, `Bluebird`, or `MyPromise`?

Is this going to somehow confuse the v8 optimizer? I wouldn't think so.

Or is it because you hope that all other promise implementations are going to die and only the one shipping in the js runtime will remain?

**Comment by domenic** [comment]
For the same reason it is future hostile to overwrite `Object`, `Map`, or `window`.

**Comment by sam-github** [comment]
I dunno. `var Promise = Promise || require('bluebird')` seems future proof, not future hostile. Object has always existed, Promise barely exists.

**Comment by caitp** [comment]
treating them as interchangeable is a good way to break the web, please don't do that u_u use one or the other, explicitly

**Comment by rwaldron** [comment]
> For the same reason it is future hostile to overwrite Object, Map, or window.

Yep, [exactly as I've said before.](https://github.com/jshint/jshint/issues/1747#issuecomment-50287120)

**Comment by sam-github** [comment]
Ah, well, this is just going in circles, but any serious attempt to convince the world that all existing code that has `var Promise` in it suddenly became wrong sometime recently (even in environments that *have no Promise* implementation, like pretty much all node code in production), is going to take a bit more work.

Drawing analogies between Promise and js builtin types that have existed for decades needs a bit more backup than simply asserting they are analogous.

**Comment by rwaldron** [comment]
> (even in environments that have no Promise implementation, like pretty much all node code in production)

There is no way for JSHint to know what runtime the code it's analyzing will run in. JSHint isn't going to break anyone's production code. If you want to pave over the Identifer bindings of built-in objects, just do it, and [tell JSHint to shut up](https://github.com/jshint/jshint/issues/1747#issuecomment-52574352)

**Comment by caitp** [comment]
> just do it, and tell JSHint to shut up

This is perfectly fine --- but try not to treat native implementations and third party implementations as interchangeable, unless you have good reason to be sure that the third party implementation is as spec-compliant as possible, or is at least trying to be, so that there's a bit more room for the spec to grow if it needs to without breaking applications

**Comment by helmus** [comment]
`var Promise = Promise || require('bluebird')`

That is horrible, don't do that ever

**Comment by PavelPolyakov** [comment]
How this issue should be fixed at the end?

I've tried the
```
futurehostile : true,
```

But still have this warning:
![image](https://cloud.githubusercontent.com/assets/839290/8016558/276f20b2-0be5-11e5-840b-3579f4008aa7.png)

From the other point:
```
predef   : ['angular','-Promise']
```

works, but as I understand I should stick to the first solution.

Any thoughts?

**Comment by andrew-luhring** [comment]
I've got a similar issue:
I have a file that I use both in the browser and in node; 
When in the browser, I rely on the function being a global function (it's an object that contains a bunch of custom matchers for jasmine), but when it's in node, I export it via module.exports.

```js
"use strict";
var module = module || {
    exports : {}
};

function Matchers(){ 
    // code...
}
// code...

module.exports = Matchers;
```

Jshint throws the error:

```
  line 3  col 5  Redefinition of 'module'.
```
two questions:

1.  If what I'm doing is ok, is this a bug with jshint?
1.  If I shouldn't do this, what should I do?

**Comment by WebReflection** [comment]
@andrew-luhring beside the empty block within the constructor, this would pass:

```js
"use strict";
var module;
if (!module) {
    module = {
        exports: {}
    };
}

function Matchers() {
    // put something here
}

module.exports = Matchers;
```

what's the difference?  actually there's no concrete difference with what you wrote, it's just a more prolix and maybe clear way to do the same.

Cheers

**Comment by joegoldbeck** [comment]
I'm probably missing something, but is there a way to suppress this error? I am using `esnext: true`, and have tried such varied options as
```
  "globals": {
    "Promise": false
  },
  "-Promise": false,
  "predef": [ "-Promise" ]
```
but none of them seem to override the error

**Comment by jugglinmike** [comment]
Hi @joegoldbeck. While I'm glad you found a workaround that solved your
problem, that is not a formally supported usage of the `globals` configuration.
Since we don't document it or test it, it may not work in a future release of
JSHint. I just verified that the following configuration suppresses the warning
you reported for both `let` and `const` bindings:

    {
      "esversion": 6,
      "predef": ["-Promise"]
    }

This is a safer approach, so please consider using it instead.

**Comment by joegoldbeck** [comment]
Hi @jugglinmike thanks for the response! The configuration you suggest isn't working for me for some reason. I've stripped my .jshintrc so that it only contains those lines and I still get the W079 warning. I am using JSHint v2.9.4 on WebStorm.

**Comment by rsp** [comment]
I'd like to point out that to this day, as of April 2017, the Bluebird docs still recommend this usage in Node:

    var Promise = require("bluebird");

and every single piece of documentation uses names like [`Promise.promisifyAll`](http://bluebirdjs.com/docs/api/promise.promisifyall.html) (not `Bluebird.promisifyAll`) to describe methods that are available in Bluebird but not in native Promise.

That is why I would expect everyone to follow the usage recommended in the Bluebird documentation unless it it changed to reflect the recommendation expressed here.

See: http://bluebirdjs.com/docs/getting-started.html
