### ISSUE TITLE
Nicer brace checking

### ISSUE THREAD

**Issue by appsforartists** [jshint/jshint#1749]
I absolutely agree that this should be linted:

    if (thing)
        intentional();
        accident();

but having braces around a single line adds visual clutter that distracts from code readability:

    if (thing)
        intentional();
        
    // is better than
    
    if (thing) {
        intentional();
    }

@valueof, how do you feel about a laxing option that suppresses warnings about missing `{`s on single-line `if`s, but errors if an `if` is followed by multiple indented lines?

**Comment by mikesherov** [comment]
I'm going to close this, because it would require JSHint to maintain it's indentation checking code, which it will be removing soon. @jugglinmike feel free to reopen if you disagree.
