### ISSUE TITLE
ignore unused if prefixed with underscore

### ISSUE THREAD

**Issue by seanmonstar** [jshint/jshint#1762]
It'd be cool if I could add an underscore to some parameters that I don't want to delete, but leave as a reminder that I can use them later. Such as:

``` js
function foo(bar, _baz) {
  return bar * 2;
}
```

Similarly done in Rust and Haskell.

**Comment by Kagami** [comment]
Another use case is ECMAScript 2015 oneline arrow functions. Consider this example:

`return fn().then(_ => true).catch(_ => false)`

In my opinion it's rather ugly to write it like this:

`return fn().then(() => true).catch(() => false)`

Single underscore looks perfectly fine as a single throw-away argument.

**Comment by sandstrom** [comment]
I second this. Having support for this would be great!

Another case is destructuring:

```js
let [_first, second, rest] = myFunction();
// I know this can be written as let [, second, rest] = myFunction(); 
// but it's useful to name the unused variable, to make the code easier to understand.
```

FWIW ESLint has support for this: http://eslint.org/docs/rules/no-unused-vars#varsignorepattern

**Comment by perlun** [comment]
Other languages than Rust and Haskell also does the same (Rubocop for Ruby ignores unused parameters if they are `_`-prefixed).

Just saying "Javascript is neither Rust nor Haskell" is not such a constructive statement imho. _Of course_ it isn't, but that doesn't mean we cannot learn anything from the other language communities. There is a lot of wisdom in the programming world out there.

**Comment by sandstrom** [comment]
@perlun Glad påsk! 🐣

We moved to ESLint, it's a worthy successor to JShint.

**Comment by perlun** [comment]
> @perlun Glad påsk! 🐣

Detsamma! 😄 

> We moved to ESLint, it's a worthy successor to JShint.

OK, cool. Do you have some guide on how to configure `ember-cli` for ESLint instead of JSHint?

**Comment by sandstrom** [comment]
@perlun We just based it off the airbnb-styleguide (add `"extends": "airbnb-base"` to your .eslintrc).

I don't have the files on this computer, but I don't think we've done any configuration in particular, maybe a few minor things but nothing big.

**Comment by perlun** [comment]
> I don't have the files on this computer, but I don't think we've done any configuration in particular, maybe a few minor things but nothing big.

OK, thanks. I installed it now with the default settings and it is working, but it doesn't accept `_foo` parameters anyway. 😄 Anyway, we can move this conversation to email instead...
