### ISSUE TITLE
Rest parameters and default parameters

### ISSUE THREAD

**Issue by MartinKolarik** [jshint/jshint#1779]
JSHint reports `Regular parameters cannot come after default parameters` if you use both default parameter and rest parameter, but I think this is a valid use case:
```js
function f (x = 0, ...y) {}
```

**Comment by UltCombo** [comment]
Should the "Regular parameters cannot come after default parameters" error even exist at all?

AFAIK this is valid:

```js
function f(a = 1, b) {
    console.log(a, b); // 1, 2
}
f(undefined, 2);
```

Yet JSHint throws the aforementioned error.

**Comment by caitp** [comment]
you're right, it doesn't make much sense :< (https://people.mozilla.org/%7Ejorendorff/es6-draft.html#sec-destructuring-binding-patterns-runtime-semantics-iteratorbindinginitialization)

**Comment by UltCombo** [comment]
It could be downgraded to a warning/config option IMO (e.g. useful for people that consider it a bad practice).
But it is not much of a choice when you're passing callbacks to 3rd-party APIs.

**Comment by UltCombo** [comment]
If downgrading to a warning/config is preferred, I guess a new issue should be opened to track the progress on it.

If the error is removed altogether, then it fixes both OP's and my issue.

**Comment by caitp** [comment]
ever since at least draft rev 20 (from 10/2013), the workings have been "initializers can go anywhere, and just replace undefined values". I don't have any older drafts, so maybe this was different at some point. Anyways, we should probably just delete the warning, it's kinda bogus

**Comment by caitp** [comment]
@rwaldron wdyt?

**Comment by rwaldron** [comment]
There are two things here: 

1. Formal rest parameters are restricted to last position. 
2. There is no restriction on defaults

**Comment by lukeapage** [comment]
Any preference on whether to convert to a warning or remove outright ?

Not sure what you mean by `There is no restriction on defaults` but if its that `function(a = b,b){}` fails, that is covered in other issues (and fixed in a PR)
