### ISSUE TITLE
Support for ES6++/Traceur types and annotations

### ISSUE THREAD

**Issue by OliverJAsh** [jshint/jshint#1789]
[Traceur has built in support for `types` and `annotations`](https://github.com/vojtajina/es6-playground#and-what-the-hell-is-the-). **These are not part of the ES6 standard**, however some projects are beginning to use them nonetheless (because Traceur enables you). I think there _might_ be some discussion about adding them to ES7, which could be why they appear in Traceur.

I don't believe support for this belongs in JSHint, but is there any other way one can extend JSHint so that the linter doesn't complain when it sees syntax such as below?

``` js
// Annotations
@Inject(Foo)
function bar(foo) {}
```

``` js
// Types
function bar(name: String) {
}
```

**Comment by hannahhoward** [comment]
++ on this one as well, or at least a fork specifically for AtScript

**Comment by glan** [comment]
:+1:
