### ISSUE TITLE
jshint config directive "ignore" not recognized in ant task

### ISSUE THREAD

**Issue by Lapeth** [jshint/jshint#1794]
When using the dedicated ant task (version 0.3.6) to parse source code, the inline configuration directives
`// jshint ignore:line,
/* jshint ignore:start */ and
/* jshint ignore:end */`
are not recognized, failing with the message "Bad option: 'ignore'"

**Comment by lukeapage** [comment]
> When using the dedicated ant task (version 0.3.6)

Maybe that is using an old version of jshint. Can you provide a test case where jshint fails (using www.jshint.com for instance). Otherwise please raise this issue with the author of the ant task.
