### ISSUE TITLE
Spurious trailing arguments in jshint.js

### ISSUE THREAD

**Issue by xiemaisi** [jshint/jshint#1800]
The following invocations of function `statement` pass a Boolean argument, although `statement` does not take any arguments at all:

  - https://github.com/jshint/jshint/blob/master/src/jshint.js#L1748

    Note that this is the only use of parameter `startLine` of function `statements`, so this parameter is effectively ignored as well.

  - https://github.com/jshint/jshint/blob/master/src/jshint.js#L3672

The following invocations of `bitwiseassignop` pass two extra arguments that are ignored:

  - https://github.com/jshint/jshint/blob/master/src/jshint.js#L2205
  - https://github.com/jshint/jshint/blob/master/src/jshint.js#L2206
  - https://github.com/jshint/jshint/blob/master/src/jshint.js#L2207
  - https://github.com/jshint/jshint/blob/master/src/jshint.js#L2208
  - https://github.com/jshint/jshint/blob/master/src/jshint.js#L2209
  - https://github.com/jshint/jshint/blob/master/src/jshint.js#L2210

Similarly, these two calls to `suffix` pass an extra argument that is ignored:

  - https://github.com/jshint/jshint/blob/master/src/jshint.js#L2361
  - https://github.com/jshint/jshint/blob/master/src/jshint.js#L2365

This call to `prefix` passes a precedence as its third argument, which is ignored. Interestingly, it passes a precedence value of 160, while `prefix` uses precedence 150:

  - https://github.com/jshint/jshint/blob/master/src/jshint.js#L2717

And finally, this call to `lookupBlockType` passes an argument `true`, which `lookupBlockType` ignores:

  - https://github.com/jshint/jshint/blob/master/src/jshint.js#L2718

**Comment by jugglinmike** [comment]
Thanks for following up with gh-1801! Closing this as it's no longer relevant.
