### ISSUE TITLE
Update .jshintrc document in the examples

### ISSUE THREAD

**Issue by dualcyclone** [jshint/jshint#1804]
Following on from the (now closed) request: https://github.com/jshint/jshint/issues/1799

The .jshintrc file in the examples doesn't fully explain the full configurable options available to the end user.

For instance, "unused" can be configured to; true, false, "vars", or "strict"; but this isn't explained anywhere that I can find.

**Comment by jugglinmike** [comment]
We're now documenting options in the source code itself--see [`src/options.js`](https://github.com/jshint/jshint/blob/2444a0463e1a99d46e4afa50ed934c317265529d/src/options.js). (That includes a description of the accepted values for the `unused` option.) The in-line documentation is used to automatically generate content on jshint.com, making it easier for users to discover.
