### ISSUE TITLE
new weird yield* syntax error?

### ISSUE THREAD

**Issue by jonathanong** [jshint/jshint#1839]
![screen shot 2014-09-08 at 12 48 33 am](https://cloud.githubusercontent.com/assets/643505/4182337/a9f28062-372c-11e4-9e29-32abcf39f568.png)

**Comment by jugglinmike** [comment]
This issue was resolved in gh-1948 and [released in version 2.5.9](https://github.com/jshint/jshint/releases/tag/2.5.9) in November of last year. Thanks for the report!
