### ISSUE TITLE
ES6: arrow function + default parameters

### ISSUE THREAD

**Issue by mhelvens** [jshint/jshint#1849]
The ES6 standard allows for arrow functions to have default parameters, but jshint does not parse those correctly:

    var fn = (options = {}) => { console.log(options); }

This may be related to #1657.

I see how this is a tricky one to parse, because you don't know whether `(options = {})` is an expression or a formal parameter list until you reach `=>`. I am [given to understand](http://tc39wiki.calculist.org/es6/arrow-functions/) that LR(1) parsers should solve this by parsing the formal parameter list as a general expression, and then checking its structure in a separate stage of compilation.

**Comment by jugglinmike** [comment]
Good news! We fixed this in gh-1989. That the fix landed at dc48781adfd9626be9453a88f209ee1fad23acf4 and was included in [the `2.6.0` release of JSHint](https://github.com/jshint/jshint/releases/tag/2.6.0).

    $ git checkout 2.6.0
    $ echo "/* jshint esnext: true, unused: false */'use strict';var fn = (options = {}) => { console.log(options); };" > tmp.js
    $ ./bin/jshint tmp.js
    $ echo $?
    0
    $ echo "/* jshint esnext: true */'use strict';var \$window;return (value = '') => { return \$window.String(value); };" > tmp.js
    $ ./bin/jshint tmp.js
    $ echo $?
    0

Thanks for the report!

**Comment by Wildhoney** [comment]
Lovely! :beers:
