### ISSUE TITLE
New Release Notes Format: Feedback

### ISSUE THREAD

**Issue by bdkjones** [jshint/jshint#1864]
@rwaldron - you asked for feedback on the new release notes format. I like it a lot; great improvement! However, when a new option is added, it would be really helpful if the release notes gave a brief explanation of what it does. Additionally, the docs on the website need to be updated. The comment next to `ignoreDelimiters` in the JSHint source is... not really clear. A slightly more elaborate explanation in the release notes would really help.

**Comment by jugglinmike** [comment]
We're [now](https://github.com/jshint/jshint/commit/93af5c1b092d674655df0d9382465af0433e3635) using [conventional-changelog](https://www.npmjs.com/package/conventional-changelog) to generate [a formal `CHANGELOG.md` file](https://github.com/jshint/jshint/blob/925a706af6dd1db31d1a70cd6a00f3961d72b083/CHANGELOG.md), which is [consumed by the jshint.com build process to generate blog posts](https://github.com/jshint/jshint.github.io/commit/b90df5f7b37dd98395ca3d75dc86450ec92a6842). Thanks to @caitp for leading the charge on machine-readable commit message annotations!
