### ISSUE TITLE
Inline directives ignored when function is declared in an array.

### ISSUE THREAD

**Issue by wtfribley** [jshint/jshint#1895]
Given the following with `maxlen` set to 80:

```js
function foo() {
  var a = "this line is toooooooooooooooooooooooooooooo loooooooooooooooooooooooooooooooong!";

/* jshint maxlen: false */
  var b = "so is is this oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooone!";
}

var arr = [function bar() {
  var a = "this line is toooooooooooooooooooooooooooooo loooooooooooooooooooooooooooooooong!";

/* jshint maxlen: false */
  var b = "so is is this oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooone!";
}];
```
I would expect to see two warnings:

`line 2, col 94, Line is too long.`
`line 9, col 94, Line is too long.`

Instead, I see three warnings:

`line 2, col 94, Line is too long.`
`line 9, col 94, Line is too long.`
`line 12, col 90, Line is too long.`

When the inline directive is inside a function declared in an array, it is ignored. This usage is common in AngularJS, necessitated by its dependency injection system.

**Comment by mikesherov** [comment]
@wtfribley thanks again. Going to close this now as jscs is the way to go here.
