### ISSUE TITLE
ES6 Enhanced Object Literals not supported

### ISSUE THREAD

**Issue by jamespamplin** [jshint/jshint#1896]
JSHint with `esnext = true` doesn't support a dynamic property name in a object literal.

```js
var obj = {
    // __proto__
    __proto__: theProtoObj,
    // Shorthand for ‘handler: handler’
    handler,
    // Methods
    toString() {
     // Super calls
     return "d " + super.toString();
    },
    // Computed (dynamic) property names
    [ 'prop_' + (() => 42)() ]: 42
};
```

Example from: https://github.com/lukehoban/es6features#enhanced-object-literals

**Comment by lukeapage** [comment]
@rwaldron this can be closed now can't it? the example works on the website..

**Comment by rwaldron** [comment]
Yes, thanks @lukeapage for the triage
