### ISSUE TITLE
missing documentation for "extends" config option

### ISSUE THREAD

**Issue by c32hedge** [jshint/jshint#1902]
super useful option, but it isn't in the [config options documentation](http://jshint.com/docs/options/)--just happened to run across it in the [release notes](https://github.com/jshint/jshint/releases/tag/2.5.1)

**Comment by tilmanpotthof** [comment]
+1

**Comment by jugglinmike** [comment]
Patches welcome!

**Comment by jugglinmike** [comment]
Resolved via https://github.com/jshint/jshint.github.io/pull/24
