### ISSUE TITLE
CLI filepath pattern/glob failing in Windows

### ISSUE THREAD

**Issue by UltCombo** [jshint/jshint#1904]
See https://github.com/es6rocks/harmonic/issues/52

Basically, `jshint **/*.js` fails in my Windows 7 machine while it works fine on Ubuntu.

I didn't find any docs regarding patterns/globs support in the CLI, so does this work as a side-effect of running the JSHint CLI on a Linux machine or am I doing something wrong?

Running JSHint 2.5.6 on Node 0.11.14, Windows 7 x64 Ultimate.

**Comment by cachaito** [comment]
Confirming - this way helps in Windows
