### ISSUE TITLE
Docs bug: globals and predef are both missing at http://www.jshint.com/docs/options/

### ISSUE THREAD

**Issue by paulvi** [jshint/jshint#1914]
`globals` and `predef` keywords are both missing at http://www.jshint.com/docs/options/ .

While http://www.jshint.com/docs/ shows `predef` in example.

see also http://stackoverflow.com/questions/22551402/difference-between-globals-and-predef-in-jshintrc

**Comment by jugglinmike** [comment]
These variables have since been included in http://www.jshint.com/docs/options/ . Thanks for the report (and sorry about the delay)!
