### ISSUE TITLE
Suggestion: add an option 'maxlines' to control the number of lines by file

### ISSUE THREAD

**Issue by bastienmoulia** [jshint/jshint#1915]
By exemple:
/*jshint maxlines:2000 */
Generates a warning for files of more than 2000 lines.

This can be useful for Metrics.

**Comment by avnersorek** [comment]
+1

**Comment by jugglinmike** [comment]
JSHint has deprecated all options relating to code style. [JSCS](http://jscs.info/) is a great tool for enforcing code style, including this very issue--see [the `maximumNumberOfLines` option](http://jscs.info/rule/maximumNumberOfLines.html)
