### ISSUE TITLE
Add option to warn when typeof is used with parentheses

### ISSUE THREAD

**Issue by samdutton** [jshint/jshint#1918]
`typeof` is an operator, not a function, and style guides such as [Google's](https://google-styleguide.googlecode.com/svn/trunk/javascriptguide.xml?showone=Parentheses#Parentheses) advise against using parentheses with unary operators (and after keywords such as `throw`).

**Comment by jugglinmike** [comment]
The proposed `singleGroups` option was implemented in gh-1919 and [released in version 2.5.9](https://github.com/jshint/jshint/releases/tag/2.5.9) in November of 2014. It can be used to disallow forms like the one reported. Thanks for the suggestion!
