### ISSUE TITLE
Doesn't detect infinite recursion 

### ISSUE THREAD

**Issue by Newlifer** [jshint/jshint#1921]
Just example:

```
function foo() {
	return foo();
}

function main() {
  foo();
  return 'Hello, World!';
}

main();
```

**Comment by jugglinmike** [comment]
I don't think a static analysis tool can address the class of problem reported in any meaningful way. We could special-case some potentially dangerous patterns, though, but we'd want to be fairly confidence that any such problem was both generic enough to be helpful, but dangerous enough to merit a warning. Clearly, this will require a smaller scope than this issue suggests, so if anyone is interested in this kind of check, please open an issue dedicated to the pattern you have in mind!
