### ISSUE TITLE
Suppress "confusing plusses"

### ISSUE THREAD

**Issue by jmm** [jshint/jshint#1922]
How do you suppress detection of "confusing plusses" and / or related syntax? I don't see it [documented](http://jshint.com/docs/options/).

**Comment by jmm** [comment]
@lukeapage Can you please explain the status of this issue? What do the labels mean and how do they jibe with it being closed?

You can reproduce it with this script:

```js
var a, b = 0, c = 0;
a = b + ++c;
console.log(a);
```

```
script.js: line 2, col 9, Confusing plusses.

1 error
```

**Comment by lukeapage** [comment]
There were a number of issues all mentioning the ability to suppress warnings in the config. I meant to close this, create a new issue to cover that and link, but I didn't, sorry!
I've created it now:
https://github.com/jshint/jshint/issues/2551

**Comment by lukeapage** [comment]
@jmm @impinball as I commented here https://github.com/jshint/jshint/issues/2551#issuecomment-121148888
it is possible to suppress individual warnings in the config using the format
```
    "-W007": true
```

**Comment by jmm** [comment]
@lukeapage Ok, no problem, thank you!
