### ISSUE TITLE
ES6 Spread operator at beginning of array

### ISSUE THREAD

**Issue by ceane** [jshint/jshint#1925]
This is firing an error that says "Spread must be the final element of an element list"

```
 var xy = [0, 0];
 var wh = [100, 100];
 var dims = [...xy, ..wh];
```

This seems incorrect behavior, as spreads can be anywhere in a list. (Tested FF, Safari 8)

**Comment by lencioni** [comment]
This looks like the relevant bug over there: https://github.com/facebook/jstransform/issues/52

**Comment by thelrner** [comment]
Can we reopen this issue?

The following is perfectly valid, but raises the "Spread must be the final element of an element list" warning.

```Javascript
let small = [2, 3, 4];
let bigger = [1, ...small, 5];      // Warning flag here
console.log(bigger);                // [1, 2, 3, 4, 5]
```

**Comment by caitp** [comment]
See the earlier comment I posted years ago. jshint has unit tests guarding that this does not cause an error, and the error you mention is not in src/messages.js.

Could be a very old version, maybe, or not jshint at all?

**Comment by thelrner** [comment]
Doh, yup problem wasn't with jshint after all. Thanks!

**Comment by derwaldgeist** [comment]
I'm getting this with the jshint version currently used in Atom's jshint plugin.

Here's my code:
```js
import {addLocaleData} from 'react-intl';
import en from 'react-intl/locale-data/en';
import de from 'react-intl/locale-data/de';

addLocaleData([
  ...en, // <-- here jshint complains "spread must be the final element of an element l..."
  ...de
]);
```
This sample code is taken from https://github.com/yahoo/react-intl/wiki#locale-data-in-browsers

**Comment by jugglinmike** [comment]
@derwaldgeist As Cait has mentioned a few times, this has not been an issue in JSHint for many years. Please ensure that the version of JSHint in use by your plugin is up-to-date (2.9.4 at the time of this writing)

**Comment by derwaldgeist** [comment]
@jugglinmike The plugin uses jshint 2.4.4 and jshint-jsx 0.4.0. Is this too old?

**Comment by jugglinmike** [comment]
I can't comment on the version/behavior of jshint-jsx, but 2.4.4 is certainly outdated.

**Comment by derwaldgeist** [comment]
Ok, thanks for the info.
