### ISSUE TITLE
Default values in deconstructed function parameter list

### ISSUE THREAD

**Issue by bobmyers** [jshint/jshint#1941]
The following is valid ES6:

    function x({delay = 10} = {}) {...

This means, default the parameter to an empty object, then pull the delay property from it, but if it doesn't exist use 10 instead.

JSHint gives the message:

    Expected an identifier and instead saw '10'.

**Comment by jeroencranendonk-wf** [comment]
+1

**Comment by rauchg** [comment]
+1

**Comment by ricardohbin** [comment]
+1

**Comment by getify** [comment]
lazy curious (haven't tried/verified myself)... would that be the same as something like:

```js
function x( {delay} = {delay:10}  ) { .. }
```

**Comment by ricardohbin** [comment]
yep, it is. And this way works in jshint ;)

**Comment by getify** [comment]
Could anyone explain why the OP version would be desired? IMO, seems inferior in every way except number of characters.

**Comment by domenic** [comment]
The difference is most pronounced with more than one option.

```js
function x1({ y = 10, z = 20 } = {}) { console.log(y, z); }
function x2({ y, z } = { y: 10, z: 20 }) { console.log(y, z); }

x1({ y: 1 }); // 1, 20
x2({ y: 1 }); // 1, undefined
```

with one option there's still a smaller difference

```js
function x1({ delay = 10 } = {}) { console.log(delay); }
function x2({ delay } = { delay: 10 }) { console.log(delay); }

x1({}); // 10
x2({}); // undefined
```

**Comment by getify** [comment]
@domenic yep was just writing a comment to mention that i'd noticed the difference, which is about whether the `= 10` defaulting happens before or after the `= { }` defaulting. Your second snippet perfectly illustrates that. Thanks.

**Comment by OverZealous** [comment]
:+1: Yeah, this one just got me.  I was so excited to have cleaner methods, too.  :-)

**Comment by bndw** [comment]
+1

**Comment by sloria** [comment]
+1

**Comment by jugglinmike** [comment]
Patches welcome, folks!

**Comment by rtm** [comment]
This fails, presumably for the same reason:

    var {x = 1} = obj;

**Comment by vatula** [comment]
function fn([options = {eventtype: null, compId: null, eventId: null, marketId: null}]) {
    let empty = !Object.keys(options).map(key => options[key]).filter(Boolean).length;
  }

Is properly compiled with traceur, but jshint (2.7.x) throws all sorts of exceptions here

**Comment by jlowcs** [comment]
+1

**Comment by bucaran** [comment]
This still fails

```js
let {a = 1, b = 2} = ab
```

Why is this issue closed?

**Comment by caitp** [comment]
It's not

**Comment by bucaran** [comment]
@caitp Indeed, it isn't! :smile:

**Comment by dehau** [comment]
+1

**Comment by rwaldron** [comment]
@dehau what are you "+1'ing"?

**Comment by dehau** [comment]
@rwaldron I have got the same issue (not sure if it is the correct way of reporting it). The following example fails on 2.7 ` ({ url, method = 'GET', body, headers = {} } = {}) =>  ...`. It compiles correctly using `Babel`

**Comment by KyleLH** [comment]
+1

This syntax still raises problems

**Comment by nicolo-ribaudo** [comment]
Please wait until #2391 has been merged.

**Comment by gausie** [comment]
Still getting a W116 and W024 when I use

`constructor ({ interval, recurrence, strict = true } = {}) {`

in a class constructor.

**Comment by nicolo-ribaudo** [comment]
The fix will be released in the next JSHint version.

**Comment by Neurostep** [comment]
@nicolo-ribaudo Awesome! Don't you know the new release ETA?

**Comment by lukeapage** [comment]
Its on @jugglinmike todo list,  there is a couple more important things to get in,  but it should be soon.

**Comment by Neurostep** [comment]
@lukeapage Sounds great! Thanks

**Comment by jisaacks** [comment]
@getify 

> would that be the same as something like:

```javascript
function x( {delay} = {delay:10}  ) { .. }
```


Consider these 2 functions:

```javascript
function a({foo=1} = {}) {
  console.log(foo); 
}
function b({foo} = {foo:1}) {
  console.log(foo); 
}

a({bar:2}); // 1
b({bar:2}); // undefined
```

This is because the former always defaults `foo` to `1` if the __key__ not set. The latter only defaults `foo` to `1` if the entire parameter is omitted.

**Comment by jisaacks** [comment]
Actually @getify it looks like @domenic already pointed that out, so I apologize.
