### ISSUE TITLE
Browserify 5+ dependency breaks JavaScriptCore starting in 2.5.6

### ISSUE THREAD

**Issue by bdkjones** [jshint/jshint#1963]
I use JavaScriptCore (the low-level C library that powers JavaScript in WebKit) to run JSHint. I have used this for 2+ years without issue, until I tried to update to JSHint 2.5.10. After 8+ hours of debugging and testing, here is what I've found:

### The 2.5.6 pre-built version works
If I download the zipped release for 2.5.6, the `jshint.js` file that was built on September 21st (and is part of the zipped download) WORKS. 

### Rebuilding 2.5.6 fails
If, however, I re-build 2.5.6 by running the following commands, the newly-built `jshint.js` file FAILS to run correctly in JavaScriptCore:

```
cd [path to unzipped 2.5.6 folder]
npm cache clean
npm install
./bin/build
```

I clear my npm cache just to be sure I'm pulling down the latest packages specified in `package.json` The newly-built `jshint.js` file will fail. Specifically, JSC throws an exception when it tries to evaluate the `JSHINT` function. It returns the stunningly-useless message: `"TypeError: undefined is not an object on line (null) of (null)"` This sort of exception usually occurs when JavaScript is malformed.

Since the pre-built version of JSHint (from 21 September) works just fine, I believe the problem lies with one of the dependencies specified in `package.json`. Many of those dependencies have released new versions since those that were available on 21 September and one of those newer versions is breaking the JSHint build. 

Note: Browserify has updated their API since the version that was available on 21 September, so I had to edit `bin/build` line 19 in order to run the build script. The original line was: 

    bundle.bundle({}, function (err, src) {

And the modification was:

    bundle.bundle(function (err, src) {

### 2.5.5 Works In All Cases

If I download the zipped 2.5.5 release and follow the same procedure to build that version, the built `jshint.js` file works flawlessly. 

### Changing 2.5.6's Dependencies Works

To test my theory, I downloaded a fresh copy of the 2.5.6 release, opened `package.json` and changed the `browserify` devDependency from `5.x` to `4.x`. The latter value is what was in the `package.json` file for JSHint 2.5.5, which built correctly. 

After doing this, I cleared my npm cache, ran `npm install` and then the build script. The resulting `jshint.js` file worked flawlessly. 

### This fix works for 2.5.10 too

I downloaded the 2.5.10 zipped release. The pre-built file in `dist` failed. However, I edited `package.json` to change browserify back to `4.x` and then edited line 19 of `bin/build` to use the old Browserify API: 

    bundle.bundle({}, function (err, src) {

When I built this, the resulting `jshint.js` file worked flawlessly again.

### Bottom Line: Browserify 5+ is broken

After all of the above, I tried changing the browserify devDependency in `package.json` to `5.10.1` and then ran `npm install` after cleaning my cache and deleting the existing `node_modules`. This had no effect: the built versions of `jshint.js` still failed. 

There is something wrong with Browserify 5 (or one of its MANY depdendencies) that WENT wrong after 21 September and is now breaking JSHint's build in a very, very subtle way. 

I also put the `jshint.js` file built with the latest browserify and the one built with browserify `4.x` into a file-diff tool and there are MASSIVE structural differences. Huge sections are in different spots, etc. 

I'm not sure what's broken, but something is. 

### Proposal: Shrinkwrap

I propose that from now on, for each release, npm's `shrinkwrap` command should be used to generate a shrinkwrap json file that specifies the EXACT versions of the dependencies that were used to build each release. 

This way, it's possible to always grab an older version of JSHint and build it *exactly* as it was built when the release took place. Right now, that is NOT possible because the `package.json` file will pull down the latest version of each dependency that meets compatibility specifications. There is no way to go back and build the release exactly as it was built on the date it came out. 

Note: I do not propose that the `shrinkwrap` file replace the standard `package.json` file; simply that it be created at the time of each release so that it's available if needed. That way, if a dependency breaks the build, it's possible to go back and use the shrinkwrapped json file to install the exact dependencies that were used for the release and then update them one at a time to track down the one that's breaking. 

I've opened a separate issue for this request.

**Comment by bdkjones** [comment]
Update: Just grabbed JSHint 2.6.0 and built it without issue. Whatever the problem was that caused this, it seems to have been fixed in Browserify 6. Closing. Self-fixing bugs are the best kind.

**Comment by bdkjones** [comment]
For the record, though, I still think adding `shrinkwrap` to the build process would be a good idea!

**Comment by rwaldron** [comment]
@bdkjones Thanks for the follow up, very much appreciated :)
