### ISSUE TITLE
ES6 Rest parameters in arrow functions

### ISSUE THREAD

**Issue by elierotenberg** [jshint/jshint#1981]
Hello again, I'm back with another ES6-related issue, using `esnext: true`.

The following code:
```js
((...args) => args)();
((...args) => args)();
```
yields:
```
'args' is not defined.
'args' is not defined.
```
while the following:
```js
(function(...args) { return args; })();
```
doesn't yield any error.

I do believe arrow funcs can have rest parameters, as it is semantically desugared to a lexically-bound function.

**Comment by jugglinmike** [comment]
Good news! I implemented a fix for this in gh-1989. That the fix landed at dc48781adfd9626be9453a88f209ee1fad23acf4 and was included in [the `2.6.0` release of JSHint](https://github.com/jshint/jshint/releases/tag/2.6.0).

    $ git checkout 2.6.0
    $ echo "/* jshint esnext: true */'use strict';((...args) => args)();" > tmp.js
    $ ./bin/jshint tmp.js
    $ echo $?
    0

Thanks for the report!
