### ISSUE TITLE
Feature request: maxlen-option only for code

### ISSUE THREAD

**Issue by flash1293** [jshint/jshint#1985]
Hi,

would anybody (beside me) like the option to define a maximum line-length only for code and not for comment-sections?

I think the readability of a continuous text doesn't suffer from long lines (a lot of people use soft-wrap in the editor so it doesn't really makes a difference).

Is this worth a PR?

**Comment by jugglinmike** [comment]
I think your reasoning is sound, but the maxlen option is deprecated, so we aren't considering extensions like these.
