### ISSUE TITLE
E030 and E033 related to typeof definedness check

### ISSUE THREAD

**Issue by gagern** [jshint/jshint#1988]
I've seen the following idiom in minified code (minifier unknown):

    "undefined"==typeof a&&(a=1);

This raises a surprising number of warnings and errors:

    line 1, col 12, Missing semicolon. (W033)
    line 1, col 12, Expected an identifier and instead saw '=='. (E030)
    line 1, col 14, Expected an operator and instead saw 'typeof'. (E033)
    line 1, col 14, Expected an assignment or function call and instead saw an expression. (W030)
    line 1, col 20, Missing semicolon. (W033)
    line 1, col 28, Expected an assignment or function call and instead saw an expression. (W030)

    6 errors

Even the fully parenthesized version

    ("undefined"==(typeof a))&&(a=1);

still yields one warning:

    line 1, col 32, Expected an assignment or function call and instead saw an expression. (W030)

but that is probably acceptable, and even more importantly, can be suppressed using suitable comments. The errors however can not be suppressed.

And at least to me they indicate that the parser got something fundamentally wrong about the semantics of this expression. The `typeof` from `UnaryExpression` binds stronger than the `==` from `EqualityExpression` which in turn binds stronger than the `&&` from `LogicalANDExpression`. At least at first glance, it seems as if the Pratt parser in JSHint *should* reproduce this, since it apparently has priority 150 for `prefix`, 100 for `==` and 50 for `&&`. But apparently things don't work that way despite these priorities.

Trying to understand the problem, I tried other partially parenthesized forms.

    ("undefined"==typeof a)&&(a=1);

is back to the single warning, so apparently that gets parsed correctly. However,

    "undefined"==(typeof a)&&(a=1);

gave even more problems:

    line 1, col 12, Missing semicolon. (W033)
    line 1, col 12, Expected an identifier and instead saw '=='. (E030)
    line 1, col 14, Expected an operator and instead saw '('. (E033)
    line 1, col 15, Expected an operator and instead saw 'typeof'. (E033)
    line 1, col 15, Expected an assignment or function call and instead saw an expression. (W030)
    line 1, col 21, Missing semicolon. (W033)
    line 1, col 22, Expected an assignment or function call and instead saw an expression. (W030)
    line 1, col 23, Missing semicolon. (W033)
    line 1, col 23, Expected an identifier and instead saw ')'. (E030)
    line 1, col 24, Expected an operator and instead saw '&&'. (E033)
    line 1, col 26, Expected an operator and instead saw '('. (E033)
    line 1, col 26, Expected an assignment or function call and instead saw an expression. (W030)
    line 1, col 27, Missing semicolon. (W033)
    line 1, col 30, Missing semicolon. (W033)
    line 1, col 30, Expected an identifier and instead saw ')'. (E030)
    line 1, col 30, Expected an assignment or function call and instead saw an expression. (W030)

    16 errors

**Comment by ryneeverett** [comment]
I was experiencing the same annoyances until I found [the expr option](http://jshint.com/docs/options/#expr).

**Comment by jugglinmike** [comment]
I just stumbled across this report--sorry we've let it sit for so long. I can
reproduce it reliably on the `master` branch with the following input:

    // jshint expr: true
    "" === typeof 0;

Output:

    gh-1988.js: line 2, col 4, Missing semicolon.
    gh-1988.js: line 2, col 4, Expected an identifier and instead saw '==='.
    gh-1988.js: line 2, col 8, Expected an operator and instead saw 'typeof'.
    gh-1988.js: line 2, col 14, Missing semicolon.

Strangely, the left-hand side of the equality operator must be a string
literal--numeric literals, RegExp literals, identifiers, `null` all parse
correctly.

**Comment by nicolo-ribaudo** [comment]
The string is parsed as a statement: this code is linted correctly
```js
0;
"" === typeof 0;
```

A simpler repro case is `"" === "";`

**Comment by nicolo-ribaudo** [comment]
This might be fixed by #2716 (I haven't tested it)

**Comment by jugglinmike** [comment]
This was indeed fixed by gh-2716 and subsequently [released in JSHint version
2.9.3](https://github.com/jshint/jshint/releases/tag/2.9.3). Thanks for reporting!
