### ISSUE TITLE
ES6 globals are activated even though esnext=false

### ISSUE THREAD

**Issue by hacker112** [jshint/jshint#1995]
Promise etc. are added to global predefined list even though "esnext" option is not true. Which just now hide the error that Promise that I used was undefined. (and that I should add var Promise = require('bluebird'); )

I think it was this change is the reason for why the Promise etc. are not seemed as undefined: 
https://github.com/jshint/jshint/commit/54c29007f26a719e3c100f4088d92d190dd0192a

**Comment by coolaj86** [comment]
I just ran into this too.

Is there a way to explicitly ignore globals? That's the option I was actually looking for - like `{ "globals": { "Promise": null } }` or something (rather than true is rw and false is ro)

**Comment by rwaldron** [comment]
I'm going to roll this change back.

**Comment by jugglinmike** [comment]
Hey everybody,

JSHint 2.8.1 ([released today](https://github.com/jshint/jshint/releases/tag/2.6.1)) includes [a new option named `futurehostile`](http://jshint.com/docs/options/#futurehostile) which we designed to be a more understandable way to resolve issues like these.

**Comment by lukeapage** [comment]
@jugglinmike can this be closed now?

**Comment by jugglinmike** [comment]
@lukeapage yup! Thanks
