### ISSUE TITLE
Tagged Template Strings are not linting correctly

### ISSUE THREAD

**Issue by KevinGrandon** [jshint/jshint#2000]
I'm getting a ```Missing semicolon.``` error when using a tagged template string. If I have time I'll try to submit a test case for this soon.

My code looks roughly like:
```
function tag() {}

var testStr = 'bar';
function foo() {
  return tag `some
    ${testStr} here`;
}
foo();

```

**Comment by XeCycle** [comment]
I checked out the earliest commit related to template strings --- b4be350f6720b1a824f76fc60e383a6c426da69c to be exact, and it still complains on tagged templates.  Does not look like regression to me.

**Comment by msegado** [comment]
The same issue occurs without the tag:
```javascript
var testStr = 'bar';
function foo() {
  return `some
    ${testStr} here`;
}
/* "Missing semicolon" and "Expected an assignment or function call
and instead saw an expression" */
```

Also, a different error occurs when using a generator function as follows:
```javascript
function* foo() {
  yield `some
    string here`;
}
/* "Bad line breaking before 'some    string here'" */
```

**Comment by caitp** [comment]
this bug was fixed iirc... are you still able to reproduce on newer versions? let me dig up the commit.

**Comment by caitp** [comment]
https://github.com/jshint/jshint/commit/5c9c7fd199aa0f6c748ea84dc62943288eaa7e9a --- I guess we never released this one (@rwaldron is anything blocking another patch release? there are a lot of commits since the last one)

**Comment by ruimarinho** [comment]
I tried it on 2.6.0 and noticed that tagged template strings throw out the missing semicolon error.

**Comment by caitp** [comment]
yeah, it's fixed just not released yet, i guess it's been a while since the last patch update =)

**Comment by ruimarinho** [comment]
Ah, nice, I had to temporarily disable jshint on pre commit :disappointed_relieved: was considering giving it a try, but happy to test with master :)

**Comment by msegado** [comment]
@caitp Yup, I'm using 2.6.0. Thanks for the update!

**Comment by ruimarinho** [comment]
@caitp master is still not working with tagged template strings.

**Comment by caitp** [comment]
okay, could you file another bug about that? I'll take a look tonight

**Comment by ruimarinho** [comment]
Hm, I believe this issue already tracks the error with tagged template strings. The example posted by @KevinGrandon still throws an error when using master. Do you still want me to open a new issue?

```
function tag() {}

tag`foo`;
```

Output: 

```
test.js: line 3, col 4, Missing semicolon.
test.js: line 3, col 4, Expected an assignment or function call and instead saw an expression.
```

**Comment by XeCycle** [comment]
```javascript
function TAG() {}
var str = (TAG`foo${bar}baz`);
```
This is not passing, in current master (as of 278ad75d5550365fbfcb03c1fc4fb271b870d9e8).
