### ISSUE TITLE
eval as table key is not harmful.

### ISSUE THREAD

**Issue by axkibe** [jshint/jshint#2013]
```
var x = { };
x.eval = 'bar';
```
Output: test.js: line 2, col 8, eval can be harmful.

Seriously no, eval as table key is a perfect name as any other.

**Comment by alFReD-NSH** [comment]
This could be kinda hard, because you have to make sure the object is not equal to the window object...

**Comment by axkibe** [comment]
Why? Just warn on window.eval and thats it.

Yes, if someone really wants to circumvent it, like
```
var x = window;
x.eval('console.log( 7 )');
```

This will be possible. But there is no problem.

Since the other way around is already also possible and missed by jshint
```
var x = 'eval';
window[x]('console.log( 7 )');
```

jshint is a hinting tool for developers, not a sandboxing tool that can catch each and every evil plan.

**Comment by jugglinmike** [comment]
We have a number of open issues tracking this bug, so I'm going to close this in favor of the original: gh-738.
