### ISSUE TITLE
ES6 classes with export default flagged as 'not defined'

### ISSUE THREAD

**Issue by bvalosek** [jshint/jshint#2019]
When a class is exported via `export default`, the class is incorrectly being marked as `not defined` inside (and out) of the class definition

Example code:

```javascript
export default class T
{
  static method1()
  {

  }

  method2()
  {
    T.method1();
  }
}
```

An even simpler example:

```javascript
export default class T
{

}

var t = new T();
```

Both examples result in `T is not defined`

**Comment by wycats** [comment]
I just hit this today. :cry:

**Comment by rwaldron** [comment]
@jugglinmike do you have time to take a look at this?

**Comment by wycats** [comment]
@rwaldron similarly, it seems that `import Foo, { bar } from "baz"` is not properly supproted.

**Comment by jugglinmike** [comment]
@rwaldron I should be able to look into this later in the week. I'll self-assign when I start

**Comment by pkarl** [comment]
Same here. C'mon Mike!

**Comment by rwaldron** [comment]
This should be fixed in a release today, which will include: https://github.com/jshint/jshint/pull/2198

**Comment by rwaldron** [comment]
Confirmed. This was resolved with https://github.com/jshint/jshint/commit/ff7228ed6624f3186ef338c01c228f7fb0d8da63 and released in https://github.com/jshint/jshint/releases/tag/2.6.1
