### ISSUE TITLE
Please update dependency version for hmtlparser2

### ISSUE THREAD

**Issue by phun-ky** [jshint/jshint#2029]
It got known vulnerabilities below `v3.8.3`: https://github.com/fb55/htmlparser2/issues/105

NOTE: new version of htmlparser2 is not out yet, so treat this issue as a reminder.

**Comment by lukeapage** [comment]
That issue was closed as part of a sub dependency and htmlparser2 is not out of date at the moment. If you think we should di something, comment and i will reopen.
