### ISSUE TITLE
Enabling eqnull option throws and exception on lint

### ISSUE THREAD

**Issue by faferreyra** [jshint/jshint#2031]
Trying to lint a piece of code like this:

    if (x ==

will throw an exception if the "eqnull" option is enabled.

It also throws the exception when code ends with "!=".

The exception thrown has the following message:

    Uncaught TypeError: Cannot read property 'value' of undefined 

Tried with the current master build, and the error still occurs.

I created a basic jsFiddle which reproduces the error.

http://jsfiddle.net/cp0x2hor/

**Comment by jugglinmike** [comment]
Thanks for the report! This class of bugs has been addressed by the recently-merged gh-2338. Expect the fix in the next release of JSHint (version > 2.7.0).
