### ISSUE TITLE
Warning: Cannot set property 'type' of undefined Use --force to continue.

### ISSUE THREAD

**Issue by cowwoc** [jshint/jshint#2033]
JSHint 2.5.10

1. Extract the contents of http://search.maven.org/remotecontent?filepath=org/webjars/prefixfree/b44a065-1/prefixfree-b44a065-1.jar into some directory.
2. Run JSHint with the default configuration on the extracted files. Notice that it reports violations but does not crash.
3. Re-run the same test, but this time use the following configuration:

    ```
eqeqeq: true,
forin: true,
strict: true
```
4. Notice that JSHint crashes with `Warning: Cannot set property 'type' of undefined Use --force to continue.`
5. You will need all 3 configuration options. Disabling any of them will cause the problem to go away.

This error message makes it very difficult to figure out what is going on. Is it a JSHint bug (I think so)? If it's a violation in user code, what file/line is it in?

**Comment by lukeapage** [comment]
@cowwoc can you confirm if this was fixed?
