### ISSUE TITLE
documentation tool request

### ISSUE THREAD

**Issue by ajoslin103** [jshint/jshint#2034]
There should be a tool into which you can enter the jshint message and it will return the directive(s) to use to control that message 

I always end up googling to find someone who mentions the directive I need, I can't find a definitive list

And ending up with // jshint ignore:line seems unsatisfying

thanks
al;

**Comment by ajoslin103** [comment]
today I needed it this way:

the code was: var vm = this;

jshint said: Possible strict violation

I looked at the strict option, but it's only for turning strict on, not off (according to the docs)

I found that I could surround the call with warning control options

/*jshint -W040 */
var vm = this;
/*jshint +W040 */

but the eventual thing I chose was: 

var vm = this; // jshint ignore: line

In this case I had to go google to find out how to turn on verbose from within a gruntfile in order to find out the number of the warning

I'd like to be able go to the docs and enter the error/warning & be presented with relevant options

**Comment by nicolo-ribaudo** [comment]
You can use https://jslinterrors.com/?linter=jshint, even if it doesn't document every  error.

**Comment by ajoslin103** [comment]
sweet!  thanks!

I'll call this one done !
