### ISSUE TITLE
Support ES6 `export { a as b }` syntax  

### ISSUE THREAD

**Issue by bobmyers** [jshint/jshint#2036]
This code

    var a = [ 1 ];
    export {a as b};

which to the best of my knowledge is valid under currently proposed specs and works fine with Traceur, generates

    export.js: line 3, col 11, Unexpected 'as'.

and a bunch of follow-on errors.

**Comment by rauchg** [comment]
+1. `as` support would be great!

**Comment by lukeapage** [comment]
@rwaldron I cannot reproduce this in the latest jshint, do you want to close?

**Comment by caitp** [comment]
Thanks

**Comment by lrsjng** [comment]
as this works great with `var` declarations it gives me a `a is not defined` in case of `let` or `const` declarations:

```js
// jshint esnext: true

const a = 1;
export {a as b};
//      ^ a is not defined
```

can anyone confirm this? should I open a new issue for this?

**Comment by lukeapage** [comment]
open a new issue and we can check it - this bug is fixed and closed.  it is very likely fixed on master.

**Comment by lrsjng** [comment]
okay, opened #2681
