### ISSUE TITLE
JSHint CLI infinite loop with un-closed ES6 class

### ISSUE THREAD

**Issue by saschagehlich** [jshint/jshint#2038]
Hey,

I'm currently porting some ES5 code to ES6, and sometimes it happens that I have some code like this:

```js
class Foo {

export default Foo;
```

It seems that JSHint runs into an infinite loop when it sees a ES6 class with a missing closing brace, followed by some random statement.

My JSHint version is 2.510, node.js version 0.10.28.

**Comment by jugglinmike** [comment]
This class of bugs has been addressed by the recently-merged gh-2338. Expect the fix in the next release of JSHint (version > 2.7.0).
