### ISSUE TITLE
Option to support implied strict (ES6 modules)?

### ISSUE THREAD

**Issue by impinball** [jshint/jshint#2053]
ES6 modules are specified to always be in strict mode, regardless of if there is a `"use strict"` directive. Every transpiler I've come across, from 6to5 to ES6 Module Transpiler to Traceur all add that statement, without any option to omit it. Something like a boolean `impliedstrict` could be useful here, as a relaxing option.

The "strict by default" for modules has been in the spec for quite some time, probably a lot longer than the import/export syntax itself.

**Comment by jugglinmike** [comment]
We just landed gh-2306, so you can expect the `module` option in the next version of JSHint (>2.7.0).

Thanks for the report!
