### ISSUE TITLE
default after case label is not a mistake

### ISSUE THREAD

**Issue by fasttime** [jshint/jshint#2058]
A switch block where a `default` label follows another label triggers **Expected a 'break' statement before 'default'**:

```js
    switch (value)
    {
    case 'A':
        console.log('A');
        break;
    case 'B':
        console.log('B');
        break;
    case 'C':
    default:
        console.log('C');
        break;
    }
```

If the line with `default` is moved before the line with `case`, there is no warning.

```js
    ...
    default:
    case 'C':
    ...
```

Weird, since many people expect `default` to be the last label in a switch block.

**Comment by hpshelton** [comment]
See the documentation on [Switch statements](http://jshint.com/docs/) which indicates the missing 'break' is expected. Javascript does not have a restriction on where the default case must appear in a switch statement (per [MSDN](http://msdn.microsoft.com/en-us/library/ie/hzc6t81t(v=vs.94).aspx)). I suppose an enforcing option could be added to ensure that the default case is the last case in a switch statement.

**Comment by rwaldron** [comment]
The point is that you're misusing a fall-through. If the case C and default are the same thing, then there is no point in having case C—it's "lint".

**Comment by fasttime** [comment]
@hpshelton Thanks! The documentation is rather vague. If there are no statements in between, omitting the break between two case labels is ok to JSHint, just as it is (see my second code snippet) between a default and a case label - but not between a case label and default.
