### ISSUE TITLE
"singleGroups" option gives spurious warnings for negative instanceof condition

### ISSUE THREAD

**Issue by Qantas94Heavy** [jshint/jshint#2064]
Using JSHint v2.5.11, when I try the following code:

```js
// jshint singleGroups:true
if (!(a instanceof b)) alert(1);
```

It will give out a spurious warning that "Grouping operator is unnecessary for lone expressions". It is in fact necessary, because the unary negation operator has a higher precedence than the `instanceof` operator.

**Comment by Krinkle** [comment]
Should we exclude `!!` (boolean cast) as well?

```js
      4 |return !!( window.JSON && JSON.stringify && JSON.parse );
                                                                 ^ Grouping operator is unnecessary for lone expressions.
```

**Comment by rwaldron** [comment]
> Grouping operator is unnecessary for lone expressions

In the example you gave, this error just seems wrong.

**Comment by jugglinmike** [comment]
@Krinkle Definitely. @rwaldron is right, that is another bug. It's covered by my patch in gh-2065, but [I've added another regression test to be safe](https://github.com/jshint/jshint/commit/62cdf5bcdedd4efc1d67dfb3bffaae54c4bebcdd). Thanks!

**Comment by gagle** [comment]
Same issue here:

```javascript
//Warning
path.resolve(alias.dir, alias.path) + (obj.trail ? '/' + obj.trail : '');

//No warning & invalid
path.resolve(alias.dir, alias.path) + obj.trail ? '/' + obj.trail : '';
```

**Comment by dsl101** [comment]
Another example?

    var a = 2;
    var b = 3;
    var resultStr;

    // Correct answer (5), but jshint gives warning:
    resultStr = 'Total: ' + (a + b) + '.';
                                    ^ Grouping operator is unnecessary for lone expressions.

    // Incorrect answer (23), but jshint gives no warning:
    resultStr = 'Total: ' + a + b + '.';

**Comment by Qantas94Heavy** [comment]
Also, should this trigger the warning or not?

```js
// jshint singleGroups:true
if ( (foo = 1) ) alert(1);
```

This is usually used to indicate that the assignment was deliberate, but currently triggers a warning with the `singleGroups` option enabled even though this silences the "assignment instead of conditional expression" warning.

**Comment by gagle** [comment]
I still receive the warning from my previous post.
