### ISSUE TITLE
Object Literals in String Templates show E020

### ISSUE THREAD

**Issue by despairblue** [jshint/jshint#2082]
```javascript
console.log(`TypeError: expected "${ util.inspect(object, { depth: 0 }) }" to be of type "${typeSchema}"`);
```
shows `Expected '}' to match '{' from line 60 and instead saw '}) }" to be of type "${'. (E020)` although it is correct syntax. `esnext` is enabled.

**Comment by rwaldron** [comment]
Thanks for the report!
