### ISSUE TITLE
Shadowing issue errorneuously reported as redefinition when using block scoping

### ISSUE THREAD

**Issue by fluidsonic** [jshint/jshint#2090]
```js
const Set = require('some-set-package');  // Redefinition of 'Set'
```

Since `let` and `const` are block scoped the global variable will be left untouched. 
This looks like a bug as this is shadowing, not redefinition.

I actually stumbled across this problem when overwriting `Set` (as node's implementation is very limited) and we can expect more such warnings in the future as the number of predefined global symbols increases.

(jshint 2.5.11)

**Comment by lukeapage** [comment]
@jugglinmike this can probably be closed I think, unless @fluidsonic can provide a proper test case which doesn't work on master, but I think it should.

**Comment by jugglinmike** [comment]
This is still an issue on `master`

`gh-2090.js`:

```js
// jshint esnext: true
{
  var Proxy = null; // expected error
  const Set = null;
  let Map = null;
}
(function() {
  var Proxy = null;
  const Set = null;
  let Map = null;
}());
```

    gh-2090.js: line 3, col 7, Redefinition of 'Proxy'.
    gh-2090.js: line 4, col 9, Redefinition of 'Set'.
    gh-2090.js: line 5, col 7, Redefinition of 'Map'.
