### ISSUE TITLE
'forin' will be bypassed when there is a fake if

### ISSUE THREAD

**Issue by hotleave** [jshint/jshint#2095]
```javascript
var obj = {},
    key,
    someLogic;
/* jshint forin: true */
for (s in obj) {
    if (someLogic) {
        // code here
    }
}
```
jshint will happy and complain **nothing** about `hasOwnProperty`

**Comment by rwaldron** [comment]
function noStinkinProtoProps(o, p) {
  return Object.prototype.hasOwnProperty.call(o, p);
};

var obj = {}, key;

for (key in obj) {
  if (noStinkinProtoProps(obj, key)) {
    // code here
  }
}
```

**Comment by hotleave** [comment]
thank you for your response. You are right, but what I mean is the if logic has nothing business about 
`hasOwnProperty`.

That would be very complicate to check this.

I had update to the latest version, and it could work perfect if the logic statement start with `!`.

Thank you for your effort.
