### ISSUE TITLE
Warning for getElementById('#foo')

### ISSUE THREAD

**Issue by samdutton** [jshint/jshint#2097]
This may be too niche or otherwise not appropriate, but...

It's easy to mistakenly add a hash sign to the ID argument when using `document.getElementById()`, particularly when moving from `document.querySelector()`.

A warning from JSHint for invalid ID values would be useful: an ID should never begin with a hash sign.

**Comment by mikesherov** [comment]
@samdutton thanks for contributing! Something like this, as you suspected, is not something that belongs is core JSHint. We have plans to eventually provide a plugin system that would allow you to do this. For this reason, I'm going to close this issue. Thanks!
