### ISSUE TITLE
Warn for event handlers with brackets

### ISSUE THREAD

**Issue by samdutton** [jshint/jshint#2098]
This may (as per my previous issue) be too niche or otherwise not appropriate, but...

It's easy to mistakenly add brackets when registering an event handler function, for example `img.onload = foo();`. This error can be quite hard to spot until runtime.

A warning from JSHint would be useful: registering an event handler should always name a function or object.

**Comment by rwaldron** [comment]
There is no way to unambiguously determine the correct thing to do. Consider the following: 


```js
// module file
export function makeHandler(some, params) {
  return function(event) {
    // do stuff with `some`, `params` and `event`
  };
}
```

```js
// program
import { makeHandler } from "module";

var img = new Image();
img.onload = makeHandler();
```
