### ISSUE TITLE
No errors for "reserved syntax"

### ISSUE THREAD

**Issue by rwaldron** [jshint/jshint#2106]
In ES6 there will be a new ["reserved syntax"](https://github.com/rwaldron/tc39-notes/blob/master/es6/2014-09/sept-25.md#conclusionresolution-2), which was further refined to a [simple restriction](https://github.com/rwaldron/tc39-notes/blob/master/es6/2014-11/nov-19.md#conclusionresolution-2). Once there is a published [specification draft](http://wiki.ecmascript.org/doku.php?id=harmony:specification_drafts) that includes this new "reserved syntax", we should add some kind of support for relaxing syntax errors triggered by forms that fall under "reserved syntax". 

This is related to https://github.com/jshint/jshint/pull/1791

**Comment by snostorm** [comment]
:+1: it is nice to be able to opt in for popular/proposed patterns like this. It doesn't have to be on by default after all (so it will still "correctly" report errors for general users who aren't opting in.)

**Comment by nicolo-ribaudo** [comment]
Where is "reserved syntax" defined in the spec?

**Comment by lukeapage** [comment]
I can't find it in the latest spec either. I think its highly likely the change didn't get in.
The next mention of types was here: https://github.com/rwaldron/tc39-notes/blob/960f83864c9960b640c79aa3dea60649d8cc9acc/es6/2015-01/jan-28.md#experimental-new-directions-for-javascript-at-google

There is no mention in the drafts changes:
http://wiki.ecmascript.org/doku.php?id=harmony:specification_drafts

and I doubt a change will go in now.

Please re-open if we are wrong or something changes.
