### ISSUE TITLE
Nodejs mode doesn't know about `escape` global function.

### ISSUE THREAD

**Issue by mirek** [jshint/jshint#2107]
Create simple coffee file:

    echo "console.log unescape 'a'" > foo.coffee

Runs fine printing "a":

    coffee foo.coffee 
    a

jshint reports unused function:

    $ coffee-jshint -o node foo.coffee 
    --------------------------------
    foo.coffee
    1:13: 'unescape' is not defined.

**Comment by jugglinmike** [comment]
You'll be glad to know that you can opt-in to non-standard globals like `unescape` with [the `nonstandard` option](http://jshint.com/docs/options/#nonstandard).

**Comment by caitp** [comment]
it's kind of weird that nonstandard only gives you escape/unescape, and none of the other details from annex b.
