### ISSUE TITLE
Shrink the npm package by ignoring the `dist` folder

### ISSUE THREAD

**Issue by hawkrives** [jshint/jshint#2110]
Out of curiosity, why does the `files` array in package.json include the `dist` folder? Especially since the `main` key points to `src/jshint.js`.

Would you accept a PR to remove `dist` from the files array, and shrink the distributed package by ~1.3MB?

**Comment by jugglinmike** [comment]
I didn't set this up myself, so I can't say for certain. I do have a guess, though. By publishing the contents of the `dist` directory, JSHint allows consumers who are writing browser code to use JSHint without maintaining their own build step. Make sense?

**Comment by hawkrives** [comment]
I can see the validity of that case. I do wonder, however, how many people that case serves?

**Comment by jugglinmike** [comment]
It's hard to say with any authority how many of [JSHint's dependents](https://www.npmjs.com/browse/depended/jshint) target the browser, so I can only offer anecdotal evidence. Most recently, I saw it in [the Ractive.js tutorials](http://learn.ractivejs.org/), and you can check out [a list of others on the JSHint website](http://jshint.com/install/).

**Comment by jugglinmike** [comment]
Anyway, thanks for the thought!

**Comment by nicknikolov** [comment]
If package is installed by npm, surely the user is expected to have a build step anyway? Otherwise they can use a CDN? Is this a real use case? This adds 2.1mb to everyone's node_modules folder
.
