### ISSUE TITLE
immed wrong failure?

### ISSUE THREAD

**Issue by thiagof** [jshint/jshint#2111]
given the following expression

    (function(d, s, id) {
			var js, fjs = d.getElementsByTagName(s)[0];
			if (d.getElementById(id)) return;
			js = d.createElement(s); js.id = id;
			js.src = "//connect.facebook.net/en_US/sdk.js";
			fjs.parentNode.insertBefore(js, fjs);
		}(document, 'script', 'facebook-jssdk'));

Why jshint still asks to *Wrap an immediate function invocation in parens*

**Comment by caitp** [comment]
because it's more like this:

```js
(function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id;
        js.src = "//connect.facebook.net/en_US/sdk.js";
        fjs.parentNode.insertBefore(js, fjs);
    })(document, 'script', 'facebook-jssdk');
```

(although the first example would have been a syntax error).
