### ISSUE TITLE
loopfunc in examples is failed

### ISSUE THREAD

**Issue by popomore** [jshint/jshint#2112]
I use the code in http://jshint.com/docs/options/#loopfunc, and can't pass jshint.

```
var nums = [];

for (var i = 0; i < 10; i++) {
  (function (i) {
    nums[i] = function (j) {
        return i + j;
    };
  }(i));
}
```

loopfunc: false, jshint@2.5.11

**Comment by prithivirajan** [comment]
loopfunc is relaxing option, the value has to set to true to avoid jshint errors.

**Comment by popomore** [comment]
I know that, but code above is safe, see bad code below.

```
var nums = [];

for (var i = 0; i < 10; i++) {
  nums[i] = function (j) {
    return i + j;
  };
}

nums[0](2); // Prints 12 instead of 2
```

So it shouldn't warn this case.

**Comment by prithivirajan** [comment]
This code is considered as error unless config is set.

Defining function inside loop is error as per JSLint definition. To overcome this error config loopfunc which has to be set to true.

For further reading on this refer, https://jslinterrors.com/dont-make-functions-within-a-loop

**Comment by popomore** [comment]
According to this article, the first is worked but has performance problems. Then jshint will warn any case of function in the loop.

Thx @prithivirajan
