### ISSUE TITLE
Release v2.6.0?

### ISSUE THREAD

**Issue by ljharb** [jshint/jshint#2115]
I'd love to use https://github.com/jshint/jshint/pull/2063 but jshint hasn't been published with this fix yet. Any chance for a release?

**Comment by rwaldron** [comment]
Sorry, I completely dropped the ball on that after we spoke last week. 

@jugglinmike @caitp let's wrap up any open issues and release tomorrow.

**Comment by caitp** [comment]
all 278 of them? =) i'll go through some things tonight

**Comment by ljharb** [comment]
Thanks! :-)

**Comment by rwaldron** [comment]
Naw, just the most recent and relevant ones. 


I wish there was a "burn these issues to the ground" feature...

**Comment by rwaldron** [comment]
https://github.com/jshint/jshint/releases/tag/2.6.0
