### ISSUE TITLE
"Unexpected reserved word" with esnext

### ISSUE THREAD

**Issue by andywillis** [jshint/jshint#2116]
Using the `esnext` option set to true I'm getting an "unexpected reserved word" warning on `export` where I wouldn't expect an warning. See also `import`.

For example:

```javascript
/* jshint esnext: true */

let thing = (value) => value + '';

export default thing;
```

**Comment by prithivirajan** [comment]
esnext option seems working for the same code pasted. 

![image](https://cloud.githubusercontent.com/assets/768544/5855544/656edac8-a25f-11e4-933b-486269061c1f.png)

**Comment by andywillis** [comment]
Seems to be an issue with SublimeLinter...
