### ISSUE TITLE
esnext: System.import -> Expected an identifier

### ISSUE THREAD

**Issue by piuccio** [jshint/jshint#2120]
I'm using jshint 2.5.11 to lint this code

``` js
System.import('app/app').then(function (app) {
    app.start();
});
```

Using

```
    "esnext"   : true,
```

And I get the error

```
^ Expected an identifier and instead saw 'import' (a reserved word).
```

[System JS](https://github.com/systemjs/systemjs)

**Comment by rwaldron** [comment]
Can you share the entire JSHint configuration? JSHint allows ReservedWords as properties by default for ES5+ (ES5 is the default).

**Comment by jugglinmike** [comment]
I can't reproduce that here. The following passes in JSHint 2.5.11

```js
/*jshint esnext: true */
'use strict';
System.import('app/app').then(function (app) {
   app.start();
});
```

I can reproduce that error if I enable `es3` instead:

```js
/*jshint esnext: true */
'use strict';
System.import('app/app').then(function (app) {
   app.start();
});
```

...but that also triggers a warning about the `System` global (as expected) "line 3, col 1, 'System' is not defined.". It doesn't sound like you're seeing that second warning, though. I can think of a few reasons for this:

- `undef: false`
- `globals System: true`
- paradoxically, `es3: true, esnext: true`

**Comment by piuccio** [comment]
This is my .jshintrc

```
{
    // http://www.jshint.com/docs/options/

    // Enforcing options
    "bitwise"  : true,
    "curly"    : true,
    "eqeqeq"   : true,
    "es3"      : true,
    "immed"    : true,
    "latedef"  : true,
    "newcap"   : true,
    "noarg"    : true,
    "noempty"  : true,
    "nonew"    : true,
    "quotmark" : "single",
    "unused"   : true,
    "undef"    : true,
    "trailing" : true,

    // Relaxing options
    "expr"     : true,
    "laxbreak" : true,
    "maxerr"   : 100,
    "esnext"   : true,

    // Environments
    "browser"  : true,
    "jquery"   : false,

    "globals"   : {
        "define": false
    }
}
```

If I remove `esnext` it complains that System is not defined.

**Comment by jugglinmike** [comment]
The problem is that you are using both `esnext` and `es3`. If you are writing code for an ECMAScript 6-supporting environment, then the restrictions of an ES3 environment (in this case: reserve words as property names) do not apply. Remove `"es3"    : true` from your RC file and you should be all set!

**Comment by rwaldron** [comment]
Should JSHint 3 try to fix things like this?

**Comment by jugglinmike** [comment]
@rwaldron I think it's an API design problem that JSHint 3 can avoid altogether: https://github.com/jshint/jshint/issues/2124

**Comment by rwaldron** [comment]
Awesome.
