### ISSUE TITLE
Typo in wiki (Documentation.md)

### ISSUE THREAD

**Issue by lewiscowper** [jshint/jshint#2123]
joshing instead of jshint.

I wouldn't have caught it had I not just typed it on a mac and had it auto-correct myself.

**Comment by jugglinmike** [comment]
Thanks for the report, Lewis!

@rwaldron In its current form, the wiki attempts to cover the same information as the JSHint website. This duplication just makes documentation maintenance difficult. What do you think about disabling the wiki altogether?
