### ISSUE TITLE
Consolidate ECMAScript version options

### ISSUE THREAD

**Issue by jugglinmike** [jshint/jshint#2124]
Replace boolean options `es3`, `es5`, and `esnext` with a single option named `esversion` that may be set to `3`, `5`, or `6`. This:

- precludes invalid configurations like `es3: false, es5: true`
- scales better for future versions of ECMAScript
- eliminates the ambiguity of `esnext` (whose meaning will change when ES6 is finalized)

This is definitely a breaking change and should be implemented for the next major release of JSHint (if at all).

**Comment by nicolo-ribaudo** [comment]
Related / duplicated -> #1148

**Comment by nicolo-ribaudo** [comment]
I'm implementing this option without removing `es3`, `es5` and `esnext`.

I've two questions:
1) What does `es5: false` mean? Is it totally unuseful?
2) Should `esversion: 2015` be a possible value? (synonymous of `esversion: 6`)

**Comment by lukeapage** [comment]
IMO
1) i think so.. depends what you mean, I assume `es5: false, es3: true` => `esversion: 3`, `es5: false, esnext:true` => Invalid option ?
2) yes! good thinking.

**Comment by nicolo-ribaudo** [comment]
> `esversion: 3, es5: false, esnext:true` => Invalid option ?

If JSHint throws an Invalid option warning fot that code, it also should throw it for `esnext: true, es3: true`, but this would be a breaking change. I think JSHint should silently ignore this invalid configuration ad consider only the last option:
- `esnext: true, es3: true` = `esversion: 3`
- `esversion: 3, es5: false, esnext:true` = `esversion: 6`

**Comment by Mouvedia** [comment]
Couldn't `esnext: true` become an alias of `esversion: 6+`?
