### ISSUE TITLE
Error when a class method returns an instance of same class (ES6)

### ISSUE THREAD

**Issue by mohebifar** [jshint/jshint#2129]
Consider this code :

    export default
    class Vector3() {
        clone() {
            return new Vector3();
        }
    }

When running `jshint` giving `esnext: true` it says :

    return new Vector3();
               ^ 'Vector3' is not defined.

**Comment by nicolo-ribaudo** [comment]
Can't reproduce using JSHint 2.8.0. Maybe already fixed?

**Comment by jugglinmike** [comment]
I can't find a release that parses `class X() {}`. Even correcting that, I can't reproduce the reported error for any release. @mohebifar if this is still a problem for you, please let us know.
