### ISSUE TITLE
Browser variables missing the window constructor: Window

### ISSUE THREAD

**Issue by appden** [jshint/jshint#2132]
I use this to access the window prototype (`window.__proto__`).

**Comment by rwaldron** [comment]
Seems like an easy patch to contribute ;)

**Comment by mrjoelkemp** [comment]
Is this a `wont-fix` now?

![image](https://cloud.githubusercontent.com/assets/865203/9077236/c4a53a54-3af9-11e5-91da-93b93769f11b.png)

`npm test` fails since __proto__ is deprecated.

**Comment by jugglinmike** [comment]
Nope. The original report is for the global variable named `Window`; the example in the description is a workaround.
