### ISSUE TITLE
The wiki doc link is broken 

### ISSUE THREAD

**Issue by FuDesign2008** [jshint/jshint#2133]
https://github.com/jshint/jshint/wiki/Documentation

![image](https://cloud.githubusercontent.com/assets/908026/5914301/1284f694-a62e-11e4-906a-3bdf74f5394e.png)

`This page` link pointed to `https://github.com/docs/options/` when I opened it. 
It may be  broken!

**Comment by jugglinmike** [comment]
Thanks for the report, @FuDesign2008!

@rwaldron In its current form, the wiki attempts to cover the same information as the JSHint website. This duplication just makes documentation maintenance difficult. What do you think about disabling the wiki altogether?
