### ISSUE TITLE
Priorities of JSHint violations

### ISSUE THREAD

**Issue by mohanr** [jshint/jshint#2134]
This is about the violations that we have to fix by using JSHint. What are  the JavaScript errors based on coding guidelines that JSHint developers would recommend as the highest priority ? Something like John Papa's guidelines ?

**Comment by mikesherov** [comment]
Hi @mohanr, Thanks for contributing! The public issue tracker is not a good place for this question. It's better suited for something like http://programmers.stackexchange.com/ Thanks again.
