### ISSUE TITLE
JSHint doesn't enforce whitepsace after function()

### ISSUE THREAD

**Issue by liorch88** [jshint/jshint#2136]
For the following code, JSHint will issue no warnings:
```js
function test(){
    alert("test");
}
test();
```
while JSLint will issue `Expected exactly one space between ')' and '{'.` - as expected.

I was sure that JSHint also supported it, but after playing with some settings such as "nonbsp" and "white", I couldn't get it to work.

**Comment by rwaldron** [comment]
Thanks for the report! The future of JSHint is going to focus on valuable code linting features, instead of style-centric warnings. JSCS is an ideal tool for checking code style against a customizable set of rules :)

**Comment by liorch88** [comment]
I understand, thanks for the recommendation!
