### ISSUE TITLE
singleGroups still failing

### ISSUE THREAD

**Issue by gagle** [jshint/jshint#2139]
https://github.com/jshint/jshint/issues/2064

I still receive the warning.

v2.6.0

Warning & valid

```javascript
> 'foo' + ('bar' ? 'baz' : 'qux');
foobaz
```

No warning & invalid

```javascript
> 'foo' + 'bar' ? 'baz' : 'qux';
baz
```

**Comment by fasttime** [comment]
*\<joke\>But you're not supposed to code like that! :-1: \</joke\>* 
Glad to see I'm not the first one who notices this problem. Hope this is going to get fixed soon.
