### ISSUE TITLE
ES6 export from source

### ISSUE THREAD

**Issue by leebyron** [jshint/jshint#2143]
jshint errors when encountering an ES6 export from a source:

```js
export { foo } from "source"
```

https://people.mozilla.org/~jorendorff/es6-draft.html#sec-exports

**Comment by caitp** [comment]
what version?

**Comment by caitp** [comment]
and, what error, for that matter

**Comment by leebyron** [comment]
Latest version and master branch. Error is a silent parse error which surfaces as an undefined identifier.

Hopefully the attached pull helps illustrate.
