### ISSUE TITLE
Feature request: blockscope

### ISSUE THREAD

**Issue by Epaminaidos** [jshint/jshint#2145]
Hi,

is there any chance to have an additional option implemented?
Let's have a look at the following code:

function foo(){
  "use strict";
  var a = [];
  for (var i=0;i<10;i++) {  }
  var a = [];
  for (var i = 0; i<10; i++) {  }
}

Two warnings are coming up:
1.) "a is already defined"
2.) "i is already defined"

Is there any chance to get an option that treats var-declarations with "blockscope", like in Java or C#?

Then there would only be one warning: "a is already defined".

IMO, the duplicate declaration of "i" is perfectly fine and even good coding style. Moving the index-variables to the top of methods would just reduce readability without gaining anything.

I know the details about variable declaration in javascript, but that does not mean that I like them :-)

Any chance, this might get implemented?

Regards
Andreas

**Comment by rwaldron** [comment]
> Is there any chance to get an option that treats var-declarations with "blockscope", like in Java or C#?

No, but JSHint will be getting upgrades to properly understand and support `let` and `const` block scope semantics for ES6.

**Comment by Epaminaidos** [comment]
It's nice to hear that javascript will actually support this in the future - I did not know that yet.
On the other hand: It will take ages before all browsers not supporting "let" will be gone from the web and the average website can actually use "let". And it will probably also take some time until the minifiers are able to replace let with var.
In contrast to these issues: If you will implement a feature for "let" anyway, it should be kind of trivial to add an option that treats every "var" like a "let".
