### ISSUE TITLE
Curly option only warning when multiline

### ISSUE THREAD

**Issue by popomore** [jshint/jshint#2150]
Can you give an option that don't warn when oneline

```
{
  "curly": "oneline"
}
```

Code

```
// Good
if (true) console.log(true);

// Bad
if (true)
  console.log(true);
  console.log(true);
```

**Comment by msimerson** [comment]
:+1:

**Comment by popomore** [comment]
If you accept this idea, I can make a PR.

**Comment by lukeapage** [comment]
Its kind of a style requirement in the case where you want it fail/pass depending on whitespace.
In that case, please consider switching off curly requirement in jshint and investigating jscs.. It may already be possible.

e.g. you want curly's not required and then an enforcement that without curlies, the statement is on the same line with no new line.

**Comment by glepretre** [comment]
@lukeapage Hi, I'm not sure it is an issue yet so I'm asking you here before: Is there a reason the JSHint `curly` option has not been deprecated in favor of JSCS `requireCurlyBraces` rule ?

**Comment by jugglinmike** [comment]
Omitting braces for single-statement conditional block bodies can be misleading depending on the indentation of the surrounding code ([the recent SSL/TLS bug in IOS](https://www.imperialviolet.org/2014/02/22/applebug.html) is a high-profile example of this kind of confusion). For this reason, we do not consider brace usage a stylistic concern.
