### ISSUE TITLE
loopfunc not enforced when using arrow functions

### ISSUE THREAD

**Issue by pornel** [jshint/jshint#2153]
```js
var trouble = [];
for(var i=0; i < 10; i++) {
    trouble.push(() => i);
}
```

It should warn as if it was `trouble.push(function() {return i;});`

**Comment by jasonhansel** [comment]
:+1:

**Comment by rwaldron** [comment]
This is a good one, thanks!

**Comment by jasonhansel** [comment]
Has there been any progress on this issue? I have spent quite a bit of time trying to solve bugs related to putting arrow functions in loops.
