### ISSUE TITLE
option "camelcase" not raising any warnings

### ISSUE THREAD

**Issue by AJ-Tucker** [jshint/jshint#2173]
I am unable to get any warnings raised when using the flag "camelcase" in my .jshintrc. An example of what I would expect to raise a warning is:
```javascript
var BAm = 1;
```
My .jshintrc looks like:

```javascript
{
	"loopfunc" : true,
	"curly": true,
	"camelcase": true
}
```
and the other options seem to be working fine.

**Comment by rwaldron** [comment]
This option is being removed in JSHint 3.0, please update your build systems to use JSCS for style-related source code checks: 

- https://github.com/jshint/jshint/issues/1870
- https://github.com/jscs-dev/node-jscs

**Comment by jugglinmike** [comment]
@rwaldron ahem gh-2122
