### ISSUE TITLE
'readFile' function mistakenly reported as being unused

### ISSUE THREAD

**Issue by nmatpt** [jshint/jshint#2191]
When I run jshint in this code with the `unused` option set to `vars` it reports the following function as being defined but never used:

```
readFile("as");

function readFile(text) {
    console.log(text);
}
```

I noticed that the declaration order and the function name matter. If I define the function first or if I change the function name the error is not reported.

**Comment by neytema** [comment]
Simple pattern to reproduce this behaviour is:

```js
var used; fn;
function fn() {
    used;
    function used() {}
}

// Output: line 4, col 14, 'used' is defined but never used.
```

Problem also occurs if you have declared variable of same name as function in outer scope, `/*globals ... */`or `predef` option included.

Please fix it, this thing is really annoying.
