### ISSUE TITLE
!=== syntax error breaks parser:

### ISSUE THREAD

**Issue by MichaelJCole** [jshint/jshint#2193]
Hi, this code broke the parser:

```
if (process.env.NODE_ENV === 'production' || payload.payment.id !=== 'token') {
```

The extra = in !=== breaks the parser with this output:

```
/home/user/scm/project/src/controllers/register.js
  line 74  col 74  Expected an identifier and instead saw '='.
  line 74  col 76  Unrecoverable syntax error. (41% scanned).
```

Version:
└─┬ gulp-jshint@1.9.2
  └── jshint@2.6.0 

Thanks!

**Comment by Delapouite** [comment]
There's an extraneous equal sign, shoud be : `!==`

**Comment by MichaelJCole** [comment]
Yes, and it breaks the parser.  That's the bug. :-)  Sorry if I didn't make that clear.

**Comment by rwaldron** [comment]
There's no bug here. JSHint is produced these lines to inform you that there is an issue: 

```
line 74  col 74  Expected an identifier and instead saw '='.
line 74  col 76  Unrecoverable syntax error. (41% scanned).
```

**Comment by MichaelJCole** [comment]
Hey, for a syntax error finder that is going to bust my balls over == vs === it would be helpful to actually indicate what the problem is.

**Comment by rwaldron** [comment]
> helpful to actually indicate what the problem is.

Like this? 

```
line 74  col 74  Expected an identifier and instead saw '='.
line 74  col 76  Unrecoverable syntax error. (41% scanned).
```

:P
