### ISSUE TITLE
ES6 (esnext:true), jshint says "Foo is not defined"... but it's defined!

### ISSUE THREAD

**Issue by trusktr** [jshint/jshint#2197]
I have some code that looks like

```js
import _ from 'underscore';
import template from 'header.hbs';
import ViewBase from 'ViewBase';

/**
 * @class Header
 * @extends {ViewBase}
 */
export default
class Header extends ViewBase {

  /*
   * Method documentation.
   */
  someMethod() {
    // ...
  }
}

// Other stuff to document for the Header class, using underscore to extend the prototype.
_(Header.prototype).extend({

  /*
   * @property {Function} template A handlebars template function.
   */
  template: template
});
```

and jshint says

```
/path/to/views/header.js
  line 21  col 3  'Header' is not defined.

  ⚠  1 warning
```

The app works, Header is defined, and the template loads. This seems like a bug with the esnext feature.

**Comment by trusktr** [comment]
I found the problem. jshint fails with

```js
export default class Name extends Other {}
console.log(Name); // error, Name is not defined.
```

but works with

```js
class Name extends Other {}
console.log(Name); // no error
export default Name;
```

**Comment by trusktr** [comment]
Is that a problem with jshint? Or is there something in the ES6 spec that prevents the default export from being used after being exported?

**Comment by jugglinmike** [comment]
When part of an `export` statement, the class becomes a ClassExpression, not a ClassDeclaration. ClassExpressions do not create a new entry in the environment record.

**Comment by rwaldron** [comment]
@jugglinmike This was the case, but changed at some point in the last 6 months (I don't have the bandwidth to search at the moment), but this should suffice: https://people.mozilla.org/~jorendorff/es6-draft.html#sec-exports-runtime-semantics-evaluation
