### ISSUE TITLE
Export in only avaliable in ES(use esnext option)

### ISSUE THREAD

**Issue by diegogarciaa** [jshint/jshint#2211]
I am using JSHint as sublime linter plugin. Any idea how to fix this? 

This is the code:

export.render = function(req, res) {
    res.send('Hello World');
};

Thanks.

**Comment by rwaldron** [comment]
That code will not work in any existing runtime. `export` is a FutureReservedWord since ES1 and a Keyword as of ES6, which means it has never been allowed as an Identifier. Is it possible that you meant `exports` (with an "s")?

**Comment by diegogarciaa** [comment]
I am sorry, my first day with javascript. You are correct. Fixing the export to exports made the error disappear . Thanks for the fast input.

**Comment by rwaldron** [comment]
Awesome! Glad to help :)
