### ISSUE TITLE
Constructor case is not correctly read from inline ES6 class syntax

### ISSUE THREAD

**Issue by pornel** [jshint/jshint#2212]
```js
const singleton = new (class ClassName {});
```

Warns about lowercase constructor name, even though `ClassName` is uppercased.

**Comment by rwaldron** [comment]
Thanks for the report! `newcap` is a deprecated option that JSHint will no longer be maintaining or updating support for. http://jshint.com/docs/options/#newcap

For style related checks, JSHint recommends JSCS, which is a dedicated style-checking tool. https://github.com/jscs-dev/node-jscs

cc @mikesherov
