### ISSUE TITLE
2.6.1 seems backward incompatible with 2.*.*

### ISSUE THREAD

**Issue by aghassemi** [jshint/jshint#2213]
Our lints are now failing with ```Set is not defined```. Looks like ```esnext``` went from defaulting to ```true``` to defaulting to ```false```.

**Comment by BorePlusPlus** [comment]
:+1:

**Comment by catrope** [comment]
We are getting failures with `'JSON' is not defined`, even though `browser: true` is configured. This worked in 2.6.0.

Breaking compatibility in a minor release is seriously not cool. Tools like npm assume that all 2.6.* versions are interchangeable.

**Comment by caitp** [comment]
I think this was an accident, please remain calm while this is fixed =)

**Comment by Krinkle** [comment]
Projects that are strict about dependencies are still affected by this because grunt-contrib-jshint uses a ranging version (`^2.6.0`). As such this is essentially breaking lots of builds worldwide.

**Comment by rwaldron** [comment]
@krinkle @catrope `es3: true`?

**Comment by rwaldron** [comment]
`JSON` identifier was introduced in ES5. The `futurehostile` patch [reorganized the `ecmaIdentifiers`](https://github.com/jshint/jshint/commit/da52aa096a1a5c3c40e731c9bcceb038e410deeb#diff-e1f4db7ff8a0b6404f1b0a110e625830) to mirror reality and by enabling ES5 identifiers when !ES3. If a project had `es3: true` and no explicit global entry for `JSON`, then the project was Doing It Wrong:tm: 

This is with es3 turned on:
![](http://i.gyazo.com/39054ba21e2091ea5922363d95ef8fd3.png)

This is with es3 turned off:
![](http://i.gyazo.com/c872efc56f1eec94d763fe1452a054af.png)


If a project was using appropriate for the the code being operated on, then this is not a breaking change.

**Comment by caitp** [comment]
well, it's a breaking change because the semantics of the options changed --- whether they changed for the better or not is irrelevant, we probably did break peoples apps this way. It might be worth a followup to not break anything by default.

**Comment by catrope** [comment]
It looks like that is indeed what we were doing wrong, our mistake. It's not very nice to introduce new errors in a point release, but you're completely right that our `.jshintrc` was wrong.

The original report by @aghassemi stands, though: the default value for `esnext` appears to have changed in a point release.

**Comment by rwaldron** [comment]
> Looks like esnext went from defaulting to true to defaulting to false.

...
> the default value for esnext appears to have changed in a point release.

Nope, it's still `true` https://github.com/jshint/jshint/blob/02c2628de6401363fad48b3cc7668eef2c2d7c1a/src/options.js#L558



@aghassemi can you paste your jshintrc and any in-comment options you're using?

**Comment by rwaldron** [comment]
~~Nope, it's still true https://github.com/jshint/jshint/blob/02c2628de6401363fad48b3cc7668eef2c2d7c1a/src/options.js#L558~~

Sorry, I have myself turned around ([brain fried](https://github.com/bocoup/test262/commit/6ae706cb2dab7853b946779a52f56d5cc1d1d3a4)).

**Comment by lukeapage** [comment]
I take it that jshint is now staying with esnext false by default.
