### ISSUE TITLE
validthis does not work with ES6 methods (emits W040 Possible strict violation)

### ISSUE THREAD

**Issue by dtinth** [jshint/jshint#2217]
Any usage of `this` outside ES6 method constructor makes JSHint say: "W040 Possible strict violation"

Example test case:

```js
export class GameTimer {
  constructor() {
    this._started = new Date().getTime()
  }
  get time() {
    return (new Date().getTime() - this._started) / 1000 // <-- W040 on this line
  }
}
```

See more examples on [this comment](https://github.com/bemusic/bemuse/pull/107#issuecomment-76518794).

**Comment by pascalduez** [comment]
Same issue here, starting from `v2.6.1`. Actually it's **any** `this` usage, even inside a constructor.

**Comment by jugglinmike** [comment]
Verified. This is a regression introduced in commit d75ef694385ba44ab49b2d2b2cf1f4bed0949ca7 . It's specific to class expressions and can be minimally reproduced as follows:

```js
void class Foo {
  method() {
    return this;
  }
}
```

Thanks for the report! I'm working on a fix now

**Comment by rwaldron** [comment]
@jugglinmike can you take a look at the patch for this?

**Comment by jugglinmike** [comment]
@rwaldron I think your patch is the correct long-term solution, but my patch should probably land also just to correct the behavior of internal methods: gh-2219

**Comment by rwaldron** [comment]
Fixed https://github.com/jshint/jshint/commit/1d04f55e1087a8a8cebc78fa51c85912c6361d0f
