### ISSUE TITLE
"Possible strict violation" when using this in inline exported ES6 classes

### ISSUE THREAD

**Issue by joIivier** [jshint/jshint#2228]
In my ES6 class declared like this:

    export default class Data {
      foo() {
      }
      bar() {
        this.foo();
      }
    }

I have a warning about "Possible strict violation.", which seem incorrect for me as I use correctly this.

Then if I split my class declaration and the export like this:

    class Data {
      foo() {
      }
      bar() {
        this.foo();
      }
    }
    export default Data;

I have no more warning, so I guess there is some issue in detecting class statements when they are into an export statement.
(I am using v2.6.1).

**Comment by jugglinmike** [comment]
Thanks for the report! I believe this is a duplicate of gh-2217 which we resolved in gh-2219 and released in [version 2.6.3](https://github.com/jshint/jshint/releases/tag/2.6.3). Can you try updating your version of JSHint and letting me know if that resolves your problem?

**Comment by joIivier** [comment]
Oh I looked only through the list of open issues, not the recently closed ones, my mistake.
Thanks a lot this is indeed fixed in 2.6.3!
And thanks for your quickness!
