### ISSUE TITLE
Allow non-camelCase names in object properties

### ISSUE THREAD

**Issue by losingkeys** [jshint/jshint#2239]
Sometimes APIs return objects with `snake_case` or `TitleCase` properties. It'd be nice to have [camelcase](http://jshint.com/docs/options/#camelcase) be enforced for variable names, but not object properties that were accessed (e.g. object literals would still complain):
```js
var one = {
  more_snakes: 'something' // warning because this property was defined here
};

var two = somethingIGotFromAjax.snake_case; // no warning, because I'm just accessing it here
```

**Comment by jugglinmike** [comment]
Note that the `camelcase` option is documented as deprecated. This makes it an unlikely candidate for further development, but your feature request sounds like a good idea for [JSCS](https://github.com/jscs-dev/node-jscs)!
