### ISSUE TITLE
Ignore minified files by default

### ISSUE THREAD

**Issue by masi** [jshint/jshint#2240]
jshint processes by default all *.js files. It would be great if it could ignore all *min.js files.

Masi

**Comment by jugglinmike** [comment]
In the context of a JavaScript project, minified files are typically either the result of a build step or third-party library code. In either case, the common practice is to store them in a distinct directory (e.g. `out/` in the former case or `lib/` in the latter case) for organizational reasons that would make your goal easier.

But I don't mean to say, "you're doing it wrong." If your current file organization works for you, you can update your project's scripts to invoke the JSHint executable according to whatever rules you like, though--`find` is a great tool for this, if you're on a *nix platform.

I can appreciate your motivation, but I think this may be a little too opinionated for JSHint to implement. While there's a strong convention to append `.min` to minified files, it is only a convention. I would worry about edge situations where a user wished to lint a file like `math.min.js` and couldn't.

**Comment by masi** [comment]
I don't have set up a full build process (yet), so minified libraries and my own code live in the same directories. That's were the mess comes from. But actually I'm fine with .jshintignore.

You have stated good reasons, not to implement the requested feature. Thank you for considering it.
