### ISSUE TITLE
Some feature requests for the website

### ISSUE THREAD

**Issue by stevemao** [jshint/jshint#2244]
Can we add autocomplete for "Jump to docs"?
Can we add "go back to top" button after each option in the table?
Can we add a changelog page or migration guide? I can't find any deprecated option list on the page. It would be great for reference.

Thanks a lot!

**Comment by jugglinmike** [comment]
These sound like good ideas, but we maintain a separate repository for the JSHint website. Could you open a separate issue for each of these on that project: https://github.com/jshint/jshint.github.io ? Thanks!

**Comment by stevemao** [comment]
Sure
