### ISSUE TITLE
`export VariableStatement` should export all bound names

### ISSUE THREAD

**Issue by caitp** [jshint/jshint#2253]
This seems to have changed in the march draft, how exciting :>

Right now, we only seem to be marking the first variable as exported, when in fact each of them should be exported. (This affects apps, because exported variables are automatically considered "used")

Looking at the code, it looks like the way VariableStatement's "fud" is called may be an error, too.

**Comment by lukeapage** [comment]
@caitp duplicate https://github.com/jshint/jshint/issues/2248
plug I made a PR to fix it just now

**Comment by lukeapage** [comment]
re fud do you mean why
`state.syntax["let"].fud.call(state.syntax["let"].fud);` isn't `state.syntax["let"].fud();` ?

**Comment by caitp** [comment]
yeah, normally these functions are called with the parsed token as their `this`b binding

**Comment by caitp** [comment]
and yeah it's a dupe, clearly not caffinated enough =) I saw this and for some reason thought it was filed on a different repo
