### ISSUE TITLE
singleGroups option detects IIFE as invalid grouping in some cases.

### ISSUE THREAD

**Issue by Nedlinin** [jshint/jshint#2257]
The use case I've got:

In jshintrc I have this as a declaration

        "singleGroups"  : true,     // true: Prohibits unnecessary grouping operators
        "esnext"        : true,

In one of my files I have the following IIFE (stripped way down for simplicities sake):

		const dropDownData = ((type) => {
			console.log(type); // Demo purpose.  Don't let JShint complain about unused variable.
			return [
				{ text: "Meter1", value: "1" },
				{ text: "Meter2", value: "2" },
				{ text: "Meter3", value: "3" }
			];
		})(options.type);

It runs fine if I skip past JSHint and go ahead and build.  However, JSHint reports the following:

    [15:32:53] Starting 'lint'...

    c:\Users\cheath\Documents\dashboard\widgets\metering\pulseMeter\pulseMeter.js
      line 212  col 38  Unnecessary grouping operator.

      ‼  1 warning

    [15:32:54] 'lint' errored after 872 ms

I'm not sure if this problem is specific to esnext property being set to true or not.  However, changing the IIFE from a fat arrow function to a simple function declaration does *not* fix the issue.

**Comment by Nedlinin** [comment]
After a bit more experimentation, if I remove the variable assignment from the IIFE the error goes away.

    ((type) => {
        console.log(type); // Demo purpose.  Don't let JShint complain about unused variable.
        return [
            { text: "Meter1", value: "1" },
            { text: "Meter2", value: "2" },
            { text: "Meter3", value: "3" }
        ];
    })(options.type);

However, in my case the whole point is to get the return value.  I refactored a bit to simply use a switch statement to assign my variable but I think this is a valid use case and should be looked into.

**Comment by sudaraka** [comment]
I'm having the same issue even with esnext flag set to false.

```
(function() {
    'use strict';

    var add_two = (function() {
        var increment = 2;

        return function(value) {
            return value + increment;
        };

    }());

    console.log(add_two(1));

}());
```

```
$ jshint add.js
add.js: line 4, col 19, Unnecessary grouping operator.
 
1 error
```

**Comment by jugglinmike** [comment]
@sudaraka The behavior you have reported is expected. The grouping operator in that code is unnecessary, so you may remove it without effecting your program's functionality.

**Comment by jugglinmike** [comment]
...but then again, if we special-case IIFEs as statements, I guess it's only reasonable to do the same when they appear within expressions.

**Comment by sudaraka** [comment]
@jugglinmike exactly why posted the above example, to indicate that it treats the two function expressions differently. The error is only shown for the IIFE that create the "add_two" function, but not for the outer anonymous IIFE.
