### ISSUE TITLE
let top with browser:true reported as unused

### ISSUE THREAD

**Issue by MayhemYDG** [jshint/jshint#2258]
On `jshint v2.6.3`.

```js
/* jshint esnext: true, browser: true, unused: true */
(function() {
  let top;
  if (true) {
    top++;
  }
})();
```

`test.js: line 3, col 10, 'top' is defined but never used.`

Can't reproduce this error when I use `const` or `var` instead, or if `top` is used in the same block level.

**Comment by jugglinmike** [comment]
Thanks for the report! This issue was resolved via gh-2214 and released in [version 2.7.0](https://github.com/jshint/jshint/releases/tag/2.7.0/).
