### ISSUE TITLE
Multiplication and Division are not associative, grouping IS necessary

### ISSUE THREAD

**Issue by mMerlin** [jshint/jshint#2260]
Environments:
http://jshint.com/ as of 2015/03/15
Windows 7, FireFox 36.0.1
Fedora 21, Google Chrome 41.0.2272.76

```javascript
/* jshint singleGroups: true */
var s1 = 10, s0 = 5, dt = 0.5, a0, a1;
a0 = (s1 - s0) / (dt * dt);
a1 = s1 / (dt * dt);
console.log(a0);
console.log(a1);
a1 = s1 / dt * dt;
a0 = (s1 - s0) / dt * dt;
console.log(a0);
console.log(a1);
```

jslint.com complains about "Unnecessary grouping operator" for lines 3 and 4.  The grouping IS necessary.  Changing to … / dt / dt would work, but as long as multiple is used, the order of operation needs to be controlled to get the correct result.

**Comment by rwaldron** [comment]
Thanks for the report. jslint.com is not this project, but I assume you actually meant jshint.com? Either way, I can repro this issue. 

cc @jugglinmike

**Comment by mMerlin** [comment]
yes, jshint.  I use both, and fingers got on 'autopilot' in the description.  The environment info and code block both show jshint.  jslint does not report anything about the grouping.  IIRC, in some cases, jslint will recommend adding extra brackets for clarity.

**Comment by jugglinmike** [comment]
On it

**Comment by mMerlin** [comment]
Correct results with my simple test case at least, as of v2.7.0
