### ISSUE TITLE
Extra complaints about ES5 option being set per default

### ISSUE THREAD

**Issue by mMerlin** [jshint/jshint#2262]
Environment: http://jshint.com/ as of 2015/03/15

Minimal test case example

```javascript
/* jshint es5: true */
function aLen() {
  /* jshint validthis: true */
  return this.length;
}
function aFirst() {
  /* jshint validthis: true */
  return this[0];
}
console.log(aLen.call([0,1,2]));
console.log(aFirst.call([0,1,2]));
```

Specifying the es5: true flag for jslint generates a message that "ES5 option is now set per default".  Fine.  Valid message.  But, that should be the last of it.  For some reason, that "ES5 option is now set per default" keeps getting repeated for every use of the validthis: true in the function scope.  Get rid of the initial ES5 flag, and the other warnings goes away too.

**Comment by caitp** [comment]
This is a dupe of #2251

**Comment by mMerlin** [comment]
Maybe related cause, but not really dup.  #2251 is about the initial warning.  I figured the initial warning was valid, but the duplicates were bogus.  Hopefully the fix for #2551 also gets this one, when it gets out to jslint.com.

**Comment by lukeapage** [comment]
I can't reproduce this in the latest release. Also see #2518

**Comment by mMerlin** [comment]
The sample code no longer generates any warning messages on jshint.com as of 2015/07/04, which shows jshint version 2.8.0.  Something that made it out to the web site version has fixed the issues(s).
