### ISSUE TITLE
[es6] support `PropertyName : BindingElement` syntax in ObjectBindingPattern

### ISSUE THREAD

**Issue by caitp** [jshint/jshint#2267]
Brought up by ato in #jshint on freenode. This might be a duplicate but it should be easy to implement

**Comment by lukeapage** [comment]
is that just this?
```
let { a: b } = { a: 1 }; // b = 1
```
If so, that passes in 2.8.0.

If not @nicolo-ribaudo has made alot of enhancements in master.

**Comment by nicolo-ribaudo** [comment]
*PropertyName* can only be an *IdentifierName*, a *StringLiteral*, a *NumericLiteral* or a *ComputedPropertyName*. The first one is already supported, the other ones are implemented by #2495.
So this issue can be closed.

**Comment by lukeapage** [comment]
That's merged, so closing. will be in release after 2.8.0
