### ISSUE TITLE
big error of the ASI mode: single line "var a = b return c" doesn't raise any error

### ISSUE THREAD

**Issue by bob-eel** [jshint/jshint#2278]
(new here)
I'm using v2.6.3 with rhino, asi=true, and this kind of code doesn't wake jshint up:
<pre><code>
function a() {
	var b = 3 return 5
}
</code></pre>
in other terms, it looks like every single semicolon warning is being silenced; does jshint treat newlines as if they weren't there at all?

just like the similar fixed (?) bug <a src="https://www.bountysource.com/issues/127785-improve-asi-support">here</a>, my version doesn't always warn me correctly against this type of thing:
<pre><code>
var a = b
[3].foo() ////nothing :(

var c = d
('a'+'b').foo() ////nothing :(

var e = f
+g ////Bad line breaking before '+'. ok

var h = i
-g ////Bad line breaking before '-': ok

var j = k
/qwe/.foo() ////Bad line breaking before '/'.

////yet it goes on ignoring the first / and "throws" an error telling me
////that '.foo' isn't the indentifier it expected;
////it however doesn't have any problem, first '/' excepted, with this type of thing:

var foo = bar
/aze/4

////is it its normal behavior?

</code></pre>
anyhow, quite annoying for someone who uses asi like me; quite absurd too that the two first asi exceptions (by far, more common than the three others) don't raise any warning :/

i checked the same stuff without asi=true, it happens that jshint treats the above expressions like any actual interpreter, ie without raising warnings:
<pre><code>var a = b
[3].foo()
////is treated just like:
var a = b[3].foo()
</code></pre>
thus: it's truly missing some important thing wrt helping those using the asi syntax not to make those very few mistakes we (and in fact, others that would forget one semicolon at the wrong place) could do.

**Comment by bob-eel** [comment]
afterthought, i guess that the warnings for each case where there's "(" or "[" (or the three less probable other cases) would be annoying if one has the habit like i do to write stuff like:
<pre><code>
foo.bar
(
    very_very_very_very_long_stuff,
    yet_another_very_very_very_very_long_stuff
)
</code></pre>

it remains that missing warnings for fully incorrect missing semicolons inside one single line (eg "var a = b return c"), which are (relatively) present with asi=false (raises a missing semicolon; an error would've been more logical i think) are in my opinion definitely constituting a bug.

**Comment by bob-eel** [comment]
nobody for this bug? it's kindof big if jshint doesn't even warn for actual syntax errors.

**Comment by caitp** [comment]
i'll take a look --- on the upside, it's an early error whenever you try to run this in a js engine, so...

**Comment by rwaldron** [comment]
> the fact that warnings for absence of semicolons inside one single line (eg "var a = b return c") are not there when asi=true, is in my opinion definitely a bug.

You're using the the option incorrectly. `asi` is a [relaxing option](http://jshint.com/docs/options/#relaxing-options), so by setting it to `true`, you're _relaxing_ the rules. 


![](http://i.gyazo.com/c8035b86ed907fcd10b8a9cdc701f1b3.png)

**Comment by bob-eel** [comment]
i beg you pardon, but the ASI of JS doesn't append any semicolon in the middle of a sentence, this jshint option is utterly absurd, doesn't correspond to anything
there's a difference between becoming more "relaxed" and altogether becoming pointless because not even warning for mere syntax errors that won't even be accepted by the parser.

i think you don't know enough about ASI to say that it's quite normal that the "relaxing" option called "asi" doesn't warn for missed semicolons *inside* lines: it's got nothing to do with js's ASI, it's just syntax error.

**Comment by bob-eel** [comment]
*on the upside, it's an early error whenever you try to run this in a js engine, so...*
totally agree, but it's nevertheless unsettling, and isn't one of the biggest point of jshint to help bypassing this annoying process of correcting small forgotten syntax mistakes one by one with a tiresome go-and-back game between browser and editor?
i admit *this* particular example is probably improbable, but i wonder if there wouldn't be others less improbable... overall it's a bit annoying that the asi option be not written in accordance with the rules of ASI of JS (which are quite simple by the way), that it seem that the option was simply to mute every single missing-semicolon warnings, even the ones not connected with ASI... i find it a bit "cheap", and, clearly buggy for the least.
