### ISSUE TITLE
New option: nobom (Disallow ByteOrderMark)

### ISSUE THREAD

**Issue by Krinkle** [jshint/jshint#2284]
Downstream: https://phabricator.wikimedia.org/T40233

PHPCS equivalent: [Sniffs/Generic.Files.ByteOrderMark](https://github.com/squizlabs/PHP_CodeSniffer/blob/2.3.0/CodeSniffer/Standards/Generic/Sniffs/Files/ByteOrderMarkSniff.php)

Ref #187, #253.
Ref jscs-dev/node-jscs#1225

**Comment by caitp** [comment]
doesn't sound too bad to me I guess (although maybe more of a JSCS thing). Either way, I need some GH activity today.

Do you care if only the first ~3 bytes of a file are tested, or would you prefer to warn on any unexpected BOM sequence within the stream?

**Comment by Krinkle** [comment]
> Maybe more of a JSCS thing.

Hehe, funny guy.

(@mikesherov at jscs-dev/node-jscs#1225)
> Yeah, this is definitely JSHint territory.

**Comment by jugglinmike** [comment]
[As noted](https://github.com/jshint/jshint/pull/2285#issuecomment-115428246) in gh-2285, this behavior is specific to the CLI. By removing the BOM-filtering functionality there, we can avoid adding additional configuration (which would be limited to controlling the CLI anyway).
