### ISSUE TITLE
Incorrect variable warnings based on order of `let` declarations 

### ISSUE THREAD

**Issue by ratbeard** [jshint/jshint#2292]
I noticed this in my app.  It is reproducible on http://jshint.com/ with the esnext option checked:

```js
let a = 1;
let b = () => a;
```
is ok

---

```js
let b = () => a;
var a = 1;
```
is ok

---

```
let b = () => a;
let a = 1;
```
Has Error: 

```
One undefined variable
1	a
```

**Comment by rwaldron** [comment]
Confirmed

**Comment by lukeapage** [comment]
I'm working on this one.

latedef and the unused implications of latedef is broken for block scoped variables (its not implemented and the function scoped implementation is function scoped...)

**Comment by lukeapage** [comment]
@rwaldron is this actually a bug?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/let

it seems that let and const do not get hoisted to the top of the block they are in, but generate a reference error in strict mode and a global without.

**Comment by caitp** [comment]
@lukepage, it's not exactly that the variables do not get hoisted to the top of the block --- the variables are created but uninitialized, and it's an error to access them before they're initialized (the "temporal dead zone").

So the following is perfectly legal:

```js
let f = () => a;
let a = 1; // or just `let a;`
f();
```

The following is not legal:

```js
let f = () => a;
f();
let a = 1; // or `let a;`
```

**Comment by caitp** [comment]
also note, there's a limit to how much TDZ handling we can do, because it's not always possible to know statically that a TDZ violation occurred. It's a runtime check (although currently in V8, we get rid of the runtime check if the reference occurs after the declaration, but I'm pretty sure that causes some bugs)

**Comment by lukeapage** [comment]
Aha,  makes sense, thanks.

**Comment by lukeapage** [comment]
@caitp any idea if this example from the jshint tests is valid? I've looked through the spec, some examples and tried babeljs.io out and it looks invalid, but I could be wrong..

```
export {
  varDefinedLater,
  letDefinedLater,
  constDefinedLater
};
var unusedGlobalVar = 41;
let unusedGlobalLet = 41;
const unusedGlobalConst = 41;
```

**Comment by lukeapage** [comment]
aha seems you agree, found https://github.com/jshint/jshint/pull/1891#discussion_r18475719
