### ISSUE TITLE
npm install jshint -g keep installing, doesn't finish.

### ISSUE THREAD

**Issue by littlee** [jshint/jshint#2293]
I'm on Windows 7 x64, Node version 0.12.0

after typed `npm install -g jshint`, it just keep installing, I waited for half of a hour, still installing.

My internet connection is working, I chekc the npm/node_modules/, it did download all files, but in command line it keep installing.

**Comment by jugglinmike** [comment]
I have not been able to reproduce this on my Windows VM. I expect this was a temporary problem with npm and/or the network. Are you still unable to successfully install JSHint?

**Comment by littlee** [comment]
Maybe just because GFW, thanks.
