### ISSUE TITLE
Feature request: treat every var as let?

### ISSUE THREAD

**Issue by Epaminaidos** [jshint/jshint#2295]
Is it possible to add an option to treat each var-statement as if the developer wrote a let-statement?

My javascript-code is currently filled with warnings for variables declared twice:

    for(var i = 0; i < array1.length; i++) {
        //Do something
    }
    for(var i = 0; i < array2.length; i++) {
        //Do something else
    }

This is pretty annoying, since the code is totally fine in my opinion. Moving the var-statements to the top would IMO not improve readability at all.
This issue could be easily resolved if each var-statement is simply treated like a let by jshint.
Could this be implemented as an option?
Since it will still take a lot of time until all browsers support let, this would IMO still be worth it.

**Comment by bob-eel** [comment]
i quite agree for the need for an option like that; i guess it could be added to the already relatively crowded "shadow" function.

the main argument for forcing var statements at start of functions is due to the hoisting problem, and the supposed danger of putting one loop inside another one with doubly declared same-named variables.

fact is, it nearly never happens, does it? however, to copy paste code from one function to another is common thing, isn't it, and what happens if this copy-pasting doesn't take account of the loop variable declared possibly very very above in the source function? well the destination function will nicely create a global variable at first call.

now of course jshint would take care of that kind of error too, but this is i think, despite current norm, quite a bad habit to take in the case where one ends up in a place where a l/hinter isn't accessible.

anyhow, i think that, better than var === let, it would be more bulletproof to make an added suboption to the "shadow" option that only warns about shadowing for more-than-one-level-nested blocks, that is, only if there's at least two levels of non-functional blocks inside the same scope with a shadowing problem.

this would prevent the rare but possible nested loop (or whatever) trouble, but would nicely reduce negative verbosity.

**Comment by Epaminaidos** [comment]
Can you post an example of what you mean by "doubly nested blocks"?

BTW: Detecting the special for-syntax would not solve my problem. Rather often, I do also declare variables inside if-blocks:

    if (x) {
        var y = 12;
        //Do something with y.
    } else {
        var y = 13;
        //Do something else with y.
    }

**Comment by bob-eel** [comment]
<i>Can you post an example of what you mean by "doubly nested blocks"?</i>

Sorry, i have a long history of not being clear at all. ^^
The best sentence that resumed what i meant was this one: 

<i>anyhow, i think however that, better than var === let, it would be more bulletproof to make an added sub-option to the "shadow" option that warns about shadowing only if there's at least two levels of non-functional blocks inside the same scope with a shadowing problem.</i>

non functional blocks == if/for/while/etc blocks, two levels would mean a for loop in a for loop that would redeclare a variable of the first for loop or of the functional block that contain both for loops, or else.
i tried to resume everything in the following explicative snippet:
<pre><code>function foo()
{
	for (var i = 0; i<10; i++) // first for loop
	{
		//...
		
			//second for loop
		for (var i = 5; i<10; i+=2) {}
			/*	this [[i]] variable is being redeclared inside
				this second for loop's block
					(
						proof just in case:
						
						the for loop special "(a;b;c)" structure
						is indeed part of the for loop (potentially fake) scope:
						if it were a let declaration,
						it would be considered as inside this
						second for loop's scope
						
						in other terms:
							for (var a = 0;;) {}
						is scope-equivalent to:
							for (;;){var a = 0}
						although of course it doesn't do the same thing.
					).
				
				But, the first declaration of i was inside a nested block
				(the first for loop's), itself inside the functional block
				of foo()
				
				Thus, with this second for loop's block,
				it makes a double nesting of non-functional blocks,
				that is of blocks that share the same scope.
				
				Schematically:
					foo scope <= first for <= second for
				each arrow representing a nesting of non-scoping block.
				
				=> to raise a warning seems statistically relevant,
				because there's a true risk of having done the shadowing
				of the variable [[i]] by mistake.
			*/
		
		//...
		
		function foo2()
		{
			var i = 42
		
			//here obviously, there's a double nesting of blocks:
				//foo scope <= first for <= foo2 scope
			//but since this last foo2 block is functional, and consequently,
			//creates a real true scope, well the classical rule applies:
			//no warning.
		}
	}
	
	//...
	
	var i = 5, max = 20
	for (; i<max; i++)  {}
			/*
				third for loop, [[i]] again redeclared, here inside foo's block.
				
				now, it's gonna be tricky:
				since for loops don't create scope, we can consider that the very
				first declaration of [[i]] was inside foo's block.
				In other terms, we forget about all preceding non fonctional 
				blocks that were already walked through.
				we flatten them to only keep the idea that all previously
				declared variables were declared inside foo's scope, thus,
				as if, directly inside foo's block.
				
				thus no double nesting because [[i]] is being redeclared in the same
				block where it was declared (or so we consider)
				hence, no warning.
				
				note: in my idea, [[i]] could also be declared inside that
				third for's block
				ie inside its (;;) special structure or inside its body
				since it would still do only one block nesting.
			*/
}</code></pre>

i'm not sure it's quite clear, don't hesitate questioning me.

**Comment by caitp** [comment]
Are you suggesting that you don't think JSHINT should warn if you do

```js
for (var i = 0; i < 10; ++i) {
  for (var i = 0; i < 5; ++i) {}
}
```

? Because it's an endless loop

**Comment by rwaldron** [comment]
> Is it possible to add an option to treat each var-statement as if the developer wrote a let-statement?

No.

**Comment by Epaminaidos** [comment]
Thank you very much for the nice clarification, why this does not make any sense for you.

Currently, our JS-Code is in a very clean state. A justified warning here and there, but that's it - except several pages of redeclarations in the jsHint-output.
IMO, this change would be very easy to implement, would not interfere with anything else and would help many developers a lot.

**Comment by bob-eel** [comment]
caitp: i probably haven't expressed myself clearly enough, once more ^^
no, your endless loop case *would* be part of what my idea of option would warn for: there's (at least) two for loops = two blocks that aren't functions, that is, which share the same scope, and shadowing => danger, warning.
