### ISSUE TITLE
singleGroups another invalid case

### ISSUE THREAD

**Issue by szarouski** [jshint/jshint#2300]
```js
//jshint singleGroups: true
$(".Interests ul li:gt(" + (interestsColumnNum - 1) + ")").addClass("interestsColumn2");
```

I believe if I remove parentheses, code will not work properly.

**Comment by caitp** [comment]
is this a regression? not sure

**Comment by szarouski** [comment]
I've seen it happening before 2.7.0 if that is what you're asking about.

**Comment by jugglinmike** [comment]
I can't reproduce this with version 2.7.0 . I *can* reproduce in 2.6.3, though:

    $ echo '//jshint singleGroups: true' > gh-2300.js
    $ echo '$(".Interests ul li:gt(" + (interestsColumnNum - 1) + ")").addClass("interestsColumn2");' >> gh-2300.js
    $ cat gh-2300.js
    //jshint singleGroups: true
    $(".Interests ul li:gt(" + (interestsColumnNum - 1) + ")").addClass("interestsColumn2");
    $ git checkout 2.7.0
    HEAD is now at da0e77f... v2.7.0
    $ ./bin/jshint gh-2300.js
    gh-2300.js: line 2, col 1, '$' is not defined.
    gh-2300.js: line 2, col 29, 'interestsColumnNum' is not defined.

    2 errors
    $ git checkout 2.6.3
    Previous HEAD position was da0e77f... v2.7.0
    HEAD is now at 983fc8d... v2.6.3
    $ ./bin/jshint gh-2300.js
    gh-2300.js: line 2, col 28, Unnecessary grouping operator.
    gh-2300.js: line 2, col 1, '$' is not defined.
    gh-2300.js: line 2, col 29, 'interestsColumnNum' is not defined.

    3 errors
    $

Specifically, I believe 896bf821d9da1bee7ac409ddb17b88f9dc3d4a87 (concerning operator associativity) has resolved this. [We only released the new version a few days ago](https://github.com/jshint/jshint/releases/tag/2.7.0), though, so this might just be a `~` thing. @szarouski can you verify that this is still a problem with version 2.7.0 specifically?

**Comment by szarouski** [comment]
@jugglinmike, yes I believe you're right. I'm sorry for false alarm, I got confused by my IDE and by node_modules, they were claiming they updated to 2.7.0, however it wasn't true.
