### ISSUE TITLE
Bitwise operations reported as unsupported

### ISSUE THREAD

**Issue by cmacleod42** [jshint/jshint#2303]
The following code is reported as having the bit ^ | << operands as unexpected

function CheckSwitch(nVnum, nOffSet)
{
	return ((V[nVnum] & (1 << nOffSet)) != 0) ? "True" : "False";
}

function SetSwitch(nVnum , nOffSet, nVal)
{
	if (nVal.toLowerCase() == "true") V[nVnum] = V[nVnum] | (1 << nOffSet);
	else V[nVnum] = V[nVnum] & (~(1 << nOffSet));
}

**Comment by rwaldron** [comment]
"operands" => "operators"

Have you tried the "bitwise" option? http://jshint.com/docs/options/#bitwise

**Comment by cmacleod42** [comment]
I was just using the online version at http://jshint.com/ and there is no such option

**Comment by rwaldron** [comment]
WFM

![](http://i.gyazo.com/d9f2662354086a0c18db12aa57e12aea.png)
