### ISSUE TITLE
JSHint v2.7.0: ./dist/jshint.js bundles lodash@2.4.1 instead of lodash@3.6.x

### ISSUE THREAD

**Issue by segrey** [jshint/jshint#2305]
According to package.json, expected lodash version is 3.6.x:
https://github.com/jshint/jshint/blob/2.7.0/package.json#L44

Actual bundled lodash version is 2.4.1:
https://github.com/jshint/jshint/blob/2.7.0/dist/jshint.js#L1518

Using different lodash versions for node and non-node (browser, rhino) versions might result in bugs that can be reproduced in one environment only and can't be reproduced in others.

**Comment by segrey** [comment]
I think this issue could be closed, because jshint@2.7.0 has already been released. Just wanted to let you know about such an inconsistency.

**Comment by rwaldron** [comment]
Ugh. I forgot to npm install before doing the build. Thanks for the heads up.

**Comment by segrey** [comment]
Great, thanks!

**Comment by rwaldron** [comment]
@segrey this will be fixed shortly.
