### ISSUE TITLE
singlegroups and boolean operators

### ISSUE THREAD

**Issue by david-gang** [jshint/jshint#2307]
This is a feature request/ question.

When i enable singleGroups I get for the following code a warning:

```javascript
return (x !== 'Y') && z
```
> Unnecessary grouping operator

I think that in case of boolean operators there should be an option to avoid the warning, because i don't want my fellow programmers to go around with the operator associativity precedence table of javascript :-)

What do you think?

**Comment by jugglinmike** [comment]
Can you elaborate on why boolean operators should be special cased? I can see how it would be helpful in the code that you've shared, but we should have some more formal rationale for implementing that behavior.

**Comment by david-gang** [comment]
You are right.
Till i will have a better definition i will close the issue.
Thanks.
