### ISSUE TITLE
Support for ES7 decorators?

### ISSUE THREAD

**Issue by eviltrout** [jshint/jshint#2310]
Support for decorators has landed in Babel.js 5.0.0. However, it seems that the `esnext` validation for jshint does not correctly validate them. 

Example (from https://github.com/rwjblue/ember-computed-decorators).

```
import computedDecorator from 'ember-computed-decorators';

// ..... <snip> .....
@computedDecorator('someKey', 'otherKey')
foo(someKey, otherKey) {
  // Do Stuff
}
```

Error received:

`Unexpected '@'`

**Comment by rwaldron** [comment]
Babel users will be very disappointed if that features changes. Currently, decorators are still at Stage 1: https://github.com/tc39/ecma262

**Comment by jugglinmike** [comment]
"esnext" refers to "ES6". It was never the most forward-thinking option name, to be sure, but we're hoping to avoid this confusion in the future (see gh-2124).

Anyway, 

You can prevent the error by demarcating non-standard portions with an ignoreDelimiter:

```js
//start-non-standard
@computedDecorator('someKey', 'otherKey')
//end-non-standard
foo(someKey, otherKey) {
  // Do Stuff
}
```

.jshintrc

```
...
ignoreDelimiters: [
  { start: "start-non-standard", end: "end-non-standard" },
],
esnext: true
...
```

I can't say if interleaving comments like this will interfere with Babel's parsing (or with the stage 1 grammar). For that, you'll have to keep your eye on the proposal as it matures over time.

**Comment by glittershark** [comment]
`ignoreDelimiters` doesn't seem to be working for me

**Comment by lukeapage** [comment]
@glittershark I've just tested @jugglinmike example with jshint 2.8.0 ;- it works. The only slightly incorrect thing is that the example shows invalid json for the `.jshintrc` this works...
```
  "ignoreDelimiters": [
    { "start": "start-non-standard", "end": "end-non-standard" }
  ]
```

**Comment by lukeapage** [comment]
@glittershark the alternative reason may be a number of issues with ignore that have been fixed on master, if its that catching you out (you might find ignore sometimes doesn't work) then you will need to wait for the next release after 2.8.0

**Comment by mattma** [comment]
@jugglinmike 

Now 2.8.0 is landed, is 

```
  "ignoreDelimiters": [
    { "start": "start-non-standard", "end": "end-non-standard" }
  ]
```

Still the state of the art? 

I encounter exact same problem on the same package like @eviltrout in Ember app. Some examples of Failing jshint:

```
components/xx/component.js should pass jshint.
components/xx/component.js: line 10, col 3, Unexpected '@'.
components/xx/component.js: line 2, col 10, 'alias' is defined but never used.
components/xxx/component.js: line 2, col 8, 'computed' is defined but never used.

3 errors: expected false to be truthy

3 errors: expected false to be truthy
```

**Comment by jugglinmike** [comment]
The blog post you referenced correctly cites JSHint's policy on this:

>  The policy of JSHint is to support features that are Stage 2 of standardization process, which is not the case yet for decorators.

You can read more about the reasoning on this blog post on jshint.com: http://jshint.com/blog/new-lang-features/ . And you can track the status of language feature proposals here: https://github.com/tc39/ecma262 . Class decorators are still "stage 1", so they are not recognized by JSHint.

**Comment by mattma** [comment]
@jugglinmike Thank you for replying. It makes perfect sense to me. The `start-non-standard` alternative works out of the box for me. I will stick around with it until Decorators pass the stage 1.
