### ISSUE TITLE
JSHint should allow bitwise by default (and just forbid eager evaluation: &, |)

### ISSUE THREAD

**Issue by henvic** [jshint/jshint#2311]
On the description of bitwise on http://jshint.com/docs/options/ we have:
>This option prohibits the use of bitwise operators such as ^ (XOR), | (OR) and others. Bitwise operators are very rare in JavaScript programs and quite often & is simply a mistyped &&.

Now, something like `a && b()` vs. `a & b(a)` might be hard to see, but
`a ^ b` or `~x` or `a >> 2` aren't error-prone (even a notice programmer can easily spot something new is being used there and find out what's going on).

What do you think?

# References
[Logical Operators - Short-Circuit Evaluation - MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_Operators#Short-Circuit_Evaluation)
[Bitwise Operators - MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Bitwise_Operators)
[Short-circuit evaluation](http://en.wikipedia.org/wiki/Short-circuit_evaluation)
[Eager evaluation](http://en.wikipedia.org/wiki/Eager_evaluation)

**Comment by rwaldron** [comment]
> What do you think?

Set `bitwise: false`.
