### ISSUE TITLE
jshint ignores /* jshint browserify: true */

### ISSUE THREAD

**Issue by vizmi** [jshint/jshint#2313]
I have tried to use jshint to validate my very simple js file genrated by browserify (from a .jsx file).
As there were many errors, I have added the mentioned comment to the top of the file, but it did not help: I can see the same error message.
## versions ##
os: Windows 7 Enterprise
node --version = 0.12.0
npm --version = 2.5.1
jshint --version = 2.6.3
command: jshint client/app.js
## source ##
```javascript
/* jshint browserify: true */
(function e(t, n, r) {
  function s(o, u) {
    if (!n[o]) {
      if (!t[o]) {
        var a = typeof require == "function" && require;
        if (!u && a) return a(o, !0);
        if (i) return i(o, !0);
        var f = new Error("Cannot find module '" + o + "'");
        throw f.code = "MODULE_NOT_FOUND", f
      }
      var l = n[o] = {
        exports: {}
      };
      t[o][0].call(l.exports, function(e) {
        var n = t[o][1][e];
        return s(n ? n : e)
      }, l, l.exports, e, t, n, r)
    }
    return n[o].exports
  }
  var i = typeof require == "function" && require;
  for (var o = 0; o < r.length; o++) s(r[o]);
  return s
})({
  1: [function(require, module, exports) {
    var master;
    $.ajax({
        url: "data/master.json",
        dataType: "json"
      })
      .done(function(data) {
        master = data;
        React.render(
          React.createElement("h1", null, master.species[3].name),
          document.getElementById('example')
        );
      })
      .fail(function(request, errorMsg, exception) {
        alert('fail ' + errorMsg);
      });


  }, {}]
}, {}, [1])
//# sourceMappingURL=blahblah
```
## output ##
```
client/app.js: line 10, col 29, Missing semicolon.
client/app.js: line 10, col 30, Expected an identifier and instead saw '='.
client/app.js: line 10, col 30, Expected an assignment or function call and instead saw an expression.
client/app.js: line 10, col 31, Missing semicolon.
client/app.js: line 10, col 52, Expected an assignment or function call and instead saw an expression.
client/app.js: line 10, col 53, Missing semicolon.
client/app.js: line 17, col 36, Missing semicolon.
client/app.js: line 18, col 41, Missing semicolon.
client/app.js: line 20, col 28, Missing semicolon.
client/app.js: line 24, col 13, Missing semicolon.
client/app.js: line 45, col 12, Missing semicolon.

11 errors
```

**Comment by jugglinmike** [comment]
The `browserify` option is intended to suppress warnings relating to global variables that are specific to that environment. Here's [the description](https://github.com/jshint/jshint/blob/dd768c243af2bd3a8beb5e47768eef3ec7ab2e5e/src/options.js#L675-L679):

> This option defines globals available when using [the Browserify tool](http://browserify.org/) to build a project.

The option is not intended to suppress any warnings that might be emitted by code that has been generated with Browserify. You can avoid these warnings by running JSHint against your code *before* you build it. Does that make sense?

**Comment by vizmi** [comment]
Understood, and makes sense. I am closing the issue now.

FYI I tried to use browserify and reactify to translate jsx syntax to pure js files. That leaves me with a jsx file (does not lint) and a browserified file (also does not lint).
The root of the problem is conceptional: browserify wants to produce the most effective and smallest code, which does not lint too well.
I am experimenting with the following workflow:
- translate jsx to js with react-tools
- lint the files
- run browserify
