### ISSUE TITLE
`let` marked as "Read only" in cases in inner-blocks

### ISSUE THREAD

**Issue by SlexAxton** [jshint/jshint#2315]
As far as I know, `let` variables aren't read-only in ~any case and should be available in child-blocks of the block that it was declared in.

```js
function generateName() {
  let name = `generated-string-${this.foo}`;
  if (this.bar) {
    name += `-${this.bar}`; // JShint doesn't like this line, outputs: "Ready only"
  }
  return name;
}
generateName();
```

Output in jshint.com --

![https://s3.amazonaws.com/f.cl.ly/items/1N2P0Z17391r0b1R1M14/Screen%20Shot%202015-04-15%20at%205.36.39%20PM.png](https://s3.amazonaws.com/f.cl.ly/items/1N2P0Z17391r0b1R1M14/Screen%20Shot%202015-04-15%20at%205.36.39%20PM.png)

Link to babel output for this code:

http://slex.me/0H2O2w0c3I3g

**Comment by jugglinmike** [comment]
Hey Alex! I believe this was resolved via gh-2214 and released in JSHint 2.7.0 (the website is still running 2.6.3--sorry about that). Can you tell me what version you are using? If it's 2.7.0, then we've got some splaining to do.

**Comment by etlovett** [comment]
I just ran into this when running 2.6.3, and upgrading to 2.7.0 does resolve it.  Thanks!

**Comment by jugglinmike** [comment]
Thanks @etlovett . In absence of further information from @SlexAxton, I'm going to close this issue. Please chime in if there's still a problem, Alex

**Comment by SlexAxton** [comment]
(Ah, sorry, I missed these followups til the mention. Looks fixed to me! Thanks!!)
