### ISSUE TITLE
feature request: ban var statement (must use let / const)

### ISSUE THREAD

**Issue by lukeapage** [jshint/jshint#2323]
Similiar but very different to #2295 .

After using es6 for some time it creates clearer code if all variable definitions are `let` or `const`. Combining `var` and `let` in one function means the developer must think even harder to understand the function than they did when there was just `var`.

So, I would like to enforce no new code gets written using `var`.

Does this sound like a good idea for a jshint flag? or is this a style concern that should be taken up with jscs?

**Comment by jugglinmike** [comment]
[JSHint now implements a `varstmt` option for this purpose.](https://github.com/jshint/jshint/pull/2234) It's a little confusing to use (set it to `true` to *disallow* `var` statements), but it should do the trick!

**Comment by lukeapage** [comment]
I missed that sorry!
