### ISSUE TITLE
Jshint with esnext fails on file

### ISSUE THREAD

**Issue by kharandziuk** [jshint/jshint#2324]
If I use jshint for file like http://pastebin.com/MQRH5nHb it newer completes

```
node /usr/local/bin/jshint -v
jshint v2.7.0
```
my .jshintrc:
```
{
    "esnext": "true"
}
```

**Comment by jugglinmike** [comment]
Thanks for the report!

I'm inlining the input to keep things organized:

```js
var React = require('react');
var {DOM} = React;
 
 
class App extends React.Component {
    constructor(props) {
      super(props);
    }
    render() {
      return DOM.div(
          {className: 'container'},
          DOM.div({className: 'col-lg-offset-3'}, [
            DOM.form([
              DOM.div(
                {
                  className: 'form-inline',
                  children:  [
                  DOM.div({className: 'form-group'}, [
                    DOM.label('First Name'),
                    DOM.input({className: "form-contol"})
                  ]),
                ]
              ),
            ]),
            //DOM.table({className: 'table'})
          ])
      );
    }
}
 
React.render(
    React.createElement(App),
    document.body
);
```
```

**Comment by jugglinmike** [comment]
Minimal test case:

```js
class a { b
```

I've submitted a patch for this at gh-2338.

**Comment by lselden** [comment]
If it helps, here's another example that can trigger the failure.

    class Foo {
      constructor (config = {}) {
        config =
      }
    }

I found that I was able to avoid problems with incomplete class definitions by adding a "(end)" token guard in the classbody function (around line 3761):

      if (!checkPunctuators(state.tokens.next, ["("])) {
        // error --- class properties must be methods
        error("E054", state.tokens.next, state.tokens.next.value);
        while (state.tokens.next.id !== "}" &&
               !checkPunctuators(state.tokens.next, ["("])
               && state.tokens.next.id !== '(end)') { // THIS IS THE LINE I ADDED
          advance();
        }
        if (state.tokens.next.value !== "(") {
          doFunction({ statement: c });
        }
      }
