### ISSUE TITLE
How do you keep in sync with new options of jshint?

### ISSUE THREAD

**Issue by jakub-g** [jshint/jshint#2331]
Hello,
thanks for everyone for contributing to jshint, it's an invaluable tool.

The biggest pain point I've noticed is that I fail to keep up with new features :)
Every now and then new flags land in jshint but I did not find any simple way to find them out - other than iterating over http://jshint.com/docs/options/ and comparing the options to the ones in my `.jshintrc`.

The Github release notes are also not that helpful since they usually list all the commits, unfiltered.

Is there some changelog hidden  somewhere that documents which new options are added in which jshint version?

**Comment by jugglinmike** [comment]
A more user-friendly change log would definitely be a good thing. Related: gh-1864

**Comment by jugglinmike** [comment]
We're now using conventional-changelog to generate a formal CHANGELOG.md file, which is consumed by the jshint.com build process to generate blog posts. Hopefully these new resources will be useful when updating!
