### ISSUE TITLE
Fails to properly parse for..of loops with const bindings

### ISSUE THREAD

**Issue by jkrems** [jshint/jshint#2334]
The following is valid ES6 code that prevents accidental assignments to `x` inside of the loop body:

```js
/*jshint esnext:true, node:true*/
'use strict';
for (const x of [ 1, 2, 3 ]) { console.log('x', x); }
```

Running with io.js 1.8:

```
> node -e "/*jshint esnext:true, node:true*/ 'use strict'; for (const x of [ 1, 2, 3 ]) { console.log('x', x); }"
x 1
x 2
x 3
```

But jshint doesn't seem to expect a `const` token in that position, interpreting it as an identifier:

```
> jshint <(echo "/*jshint esnext:true, node:true*/ 'use strict'; for (const x of [ 1, 2, 3 ]) { console.log(x); }") 
/dev/fd/11: line 1, col 54, Creating global 'for' variable. Should be 'for (var const ...'.
/dev/fd/11: line 1, col 60, Expected 'of' and instead saw 'x'.
/dev/fd/11: line 1, col 68, Expected ']' to match '[' from line 1 and instead saw ','.
/dev/fd/11: line 1, col 70, Expected ')' to match '(' from line 1 and instead saw '2'.
/dev/fd/11: line 1, col 71, Expected an identifier and instead saw ','.
/dev/fd/11: line 1, col 71, Expected an assignment or function call and instead saw an expression.
/dev/fd/11: line 1, col 72, Missing semicolon.
/dev/fd/11: line 1, col 73, Expected an assignment or function call and instead saw an expression.
/dev/fd/11: line 1, col 74, Missing semicolon.
/dev/fd/11: line 1, col 75, Expected an identifier and instead saw ']'.
/dev/fd/11: line 1, col 75, Expected an assignment or function call and instead saw an expression.
/dev/fd/11: line 1, col 76, Missing semicolon.
/dev/fd/11: line 1, col 76, Expected an identifier and instead saw ')'.
/dev/fd/11: line 1, col 76, Expected an assignment or function call and instead saw an expression.
/dev/fd/11: line 1, col 77, Missing semicolon.
/dev/fd/11: line 1, col 62, 'of' is not defined.
/dev/fd/11: line 1, col 92, 'x' is not defined.

17 errors
```

The same code does work as expected with `var` or `let` instead of `const`.

**Comment by caitp** [comment]
I think #2326 is sort of a blocker for this, but I've got a quick patch... 90% sure it just reverts something that was removed because `const` is broken atm

**Comment by jkrems** [comment]
Wow, that was quick! Thanks for taking this on. :)

**Comment by caitp** [comment]
@jkrems it's still going to be broken because they're not correctly block-scoped, so you'll see a lot of "cont variable redeclared" errors until the other thing is fixed

**Comment by jkrems** [comment]
Thanks for the warning! Will keep that in mind.

**Comment by jayphelps** [comment]
@caitp Even with this fix, I'm getting the same error when destructuring:

```js
for (const { foo } of bar) {}
```

[babel REPL](https://babeljs.io/repl/#?experimental=false&evaluate=false&loose=false&spec=false&playground=true&code=for%20(const%20%7B%20foo%20%7D%20of%20bar)%20%7B%7D&stage=0)

Can you confirm if this syntax is *suppose* to be supported by jshint? If so, I'll open a new ticket or you can repurpose this one...
