### ISSUE TITLE
Inline option to force error?

### ISSUE THREAD

**Issue by danShumway** [jshint/jshint#2337]
Would it be possible to get an inline option similar to ```jshint ignore``` but the opposite?  

I often find myself writing temp code for debugging purposes that ought not to be in a final build or developing workarounds for features that will later be supported, then forgetting to take go back and fix that code.  I'd love to be able to mark that code as temporary at the time of writing, and then have my jshint scan just throw an error or warning if I've missed any of it.

Some possible examples:
```javascript
window.testingVar = privateVar; //jshint error:line "remove global"

/*jshint warn:start "swap this out to use printNumbers function" */
var i;
for (i= 0; i < 20; i++) {
   console.log(i);
}
/*jshint warn:end*/
```

**Comment by jugglinmike** [comment]
JSHint is certainly positioned in your workflow to provide this service, but the functionality seems like an over-extension to me. That said, there are a lot of ways you could approximate the behavior you're looking for using JSHint now--just choose warning that you have enabled and intentionally violate it.

```js
window.testingVar = privateVar;; // "remove global"

;; // swap this out to use printNumbers function
var i;
for (i= 0; i < 20; i++) {
   console.log(i);
}
```

Other ideas: insert expression statements without side effects:

```js
0; // don't forget to do something else
```

Does that work for you?

**Comment by danShumway** [comment]
Heck yes, the ```;;``` syntax there works brilliantly, can't believe I never thought to do that.

Thanks a ton.

**Comment by jugglinmike** [comment]
Great!

**Comment by danShumway** [comment]
Just as an update in case someone else is looking for other strategies for large object literals
```js
var default_opts = {
   '':.0, //Switch to a constant before committing
   myNum : 10,

   myFunc : 10 || .0, //Change name to something more appropriate
};
```
It's a couple of extra keystrokes, and it has the downside of sometimes throwing two errors instead of one (duplicate keys if you have more than one error using ``''``, and beginning your decimal with ``.`` instead of ``0``), so the inline version is the more useful of the two.

If you want something that looks a bit less ugly at the cost of 4 more characters
```js
var x = {
    myFun : 10 || eval(), //use a better name here
};
```

It's really easy to tell that ``eval`` isn't supposed to be there, so it makes the code a tiny bit more readable, and has the advantage to still evaluating to ``null``, so ``myFun : null || eval()`` probably won't cause any runtime errors.
