### ISSUE TITLE
jshint ddos

### ISSUE THREAD

**Issue by yanfali** [jshint/jshint#2339]
I was experimenting with es6, with the es6next flag turned on and I accidentally wrote this piece of code.

```
class Test {
  constructor: {
    this.test = true;
  }
}
```
Not the incorrect class syntax. Instead of bailing and telling me I'm an idiot, node starts consuming 98% of CPU on a single core and never comes out of it. Accidentally DDOSing my self while editing. Thanks for jshint, best tool ever.

**Comment by caitp** [comment]
filing a bug is cool, but maybe tone down the passive aggressive language a bit =)

I think @jugglinmike's new patch will probably fix this

**Comment by yanfali** [comment]
@caitp sorry. Did not mean for it to come across as passive aggressive. I was going for self deprecating. I really do mean it about jshint though. It's one of my favorite tools.

**Comment by caitp** [comment]
okay, anyways I think this should be fixed in the next patch release. 99% sure

**Comment by yanfali** [comment]
thank you! glad I was able to provide a test case.

**Comment by jugglinmike** [comment]
Yup, gh-2338 covers this. I've added your test case to be safe. Thanks!

**Comment by jugglinmike** [comment]
gh-2338 has landed; this should be resolved in the next release of JSHint (version > 2.7.0).
