### ISSUE TITLE
Can let be redeclared with a var etc.

### ISSUE THREAD

**Issue by lukeapage** [jshint/jshint#2342]
There are some tests that specifically check var's shadowing let (make sure var variables can shadow let variables)

but is that right? testing in chrome in strict mode, it seems redeclaring a let or a const with a let/const/var throws an error and reclaring a var with a let or const also throws an error - that seems to make sense (I have no idea what would happen otherwise?)

so is it strict mode only? is it a bug in chrome? is it a bad jshint test?

heres what I wrote before I realised I shouldn't add it to an existing pr...

```
exports.testLetRedeclaration = function (test) {

  // consts cannot be redeclared, but they can shadow
  var src = [
    "let a = 1;",
    "let a = 2;",
    "if (a) {",
    "  let a = 3;",
    "}",
    "for(let a in a) {",
    "  let a = 4;",
    "}"
  ];

  TestRun(test)
      .addError(2, "'a' has already been declared.")
      .test(src, {
        esnext: true
      });

  test.done();
};

exports.testLetAndConstRedeclarationOfVar = function (test) {

  // consts cannot be redeclared, but they can shadow
  var src = [
    "var a = 1;",
    "let a = 2;",
    "if (a) {",
    "  let a = 3;",
    "}",
    "var b = 1;",
    "const b = 2;",
    "if (b) {",
    "  const b = 3;",
    "}"
  ];

  TestRun(test)
      .addError(2, "'a' has already been declared.")
      .addError(7, "'b' has already been declared.")
      .test(src, {
        esnext: true
      });

  test.done();
};
```

then this has to change

```
            // only look in the latest scope because we can shadow
            if (funct["(blockscope)"].current.labeltype(t.id) === "const") {
              warning("E011", null, t.id);
            }
```

(and the equivalent for the var statement) to use .has, not just const.

As well as detecting in the block statement that there isn't an existing var.

**Comment by caitp** [comment]
@lukeapage see [13.1.1](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-block-static-semantics-early-errors), [13.1.1.1](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-switch-statement-static-semantics-early-errors), [13.14.1](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-try-statement-static-semantics-early-errors), and [14.1.2](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-function-definitions-static-semantics-early-errors) --- there are a lot of early errors for a name of LexicallyDeclaredNames appearing in VarDeclaredNames or BoundNames of formal parameters. Engines are not getting this 100% right all the time, but yeah the spec is pretty clear about this I think

**Comment by rwaldron** [comment]
Check let and const here: https://github.com/tc39/test262/tree/master/test/language/statements I think you may be right (I'm mobile, so I can't really read through atm)

**Comment by lukeapage** [comment]
So at the moment we have as this error message - "const 'a' has already been declared." - when I broaden it to apply to vars, functions shadowing blockscope and redeclaring let and const within the same scope, should it stay under E011 and what should the error message be?

I guess it should stay under E011 since it is a syntax error unlike shadowing which isn't.

I guess also it should stay the same but make the first part of the message say "let" or "const" depending on what it is you are re-declaring?
