### ISSUE TITLE
Stricter undef checks

### ISSUE THREAD

**Issue by kevinburke** [jshint/jshint#2343]
Say you have code that looks like this:

```javascript
var foo = function() {
    var b;
    b = 3;
    return 7;
};
foo();
```

In theory, this could warn because you're defining and allocating a value for `b`, but not ever using it; it's wasteful. (For example, the above is not a valid Go program; you get the message "`b` is declared and not used"). Basically, you need to use it on the right side of an equals sign, or in a function call.

This may not be a case for `jshint`, if it's too advanced of a hint check, or Javascript doesn't provide a reliable environment for dealing with these. If that's the case, are there other tools that can warn about issues like this?

**Comment by caitp** [comment]
this doesn't seem totally unreasonable, since `unused` will catch this if the variable is initialized during declaration.

**Comment by kevinburke** [comment]
Could also in theory flag

```javascript
var b;
b = 2;
b = 3;
```

since the first assignment is wasteful

**Comment by caitp** [comment]
We could translate the source code into a static simulation of the programme, and warn people whenever licm or constant folding or dead code removal will make code pointless --- but vms already eliminate dead code and perform licm and constant folding anyways, and almost certainly do a better job of it than we could.

Let's keep it simple and deal with one thing at a time, which is in this case linting variables which are stored but never loaded

**Comment by lukeapage** [comment]
related/duplicate: #2277 #2259 #2166 #1994

**Comment by lukeapage** [comment]
Duplicate of #1994 which has pr
