### ISSUE TITLE
Unused arrow-function parameters not ignored by "unused": "vars"

### ISSUE THREAD

**Issue by Rantanen** [jshint/jshint#2345]
Setting `"unused": "vars"` disables all warnings concerning unused normal function parameters. However the new arrow functions don't seem to be supported by this option:

    on().then( thing => console.log( 'done' ) );

    'thing' is defined but never used.

I feel these should behave the same as normal function parameters when it comes to raising warnings.

**Comment by rwaldron** [comment]
Agreed
