### ISSUE TITLE
Proposal: noemptystatements

### ISSUE THREAD

**Issue by rwaldron** [jshint/jshint#2346]
```
noemptystatements: true
```

- Disallows _EmptyStatement_
- Disallows _ClassElement_: `;`

**Comment by jugglinmike** [comment]
Good news! No new option necessary--[JSHint already warns about semicolons used in the statement position](https://github.com/jshint/jshint/blob/2b673d92107be93df80e48471dced0432a127f25/src/jshint.js#L1662-L1664). All that's needed to satisfy this is to extend the parser to recognize the semicolon token while parsing class bodies--see gh-2354
