### ISSUE TITLE
CLI extract=always option fails to extract normal .js files

### ISSUE THREAD

**Issue by dturner** [jshint/jshint#2347]
Steps to reproduce:

Create a test.js file with the contents: 
    `print("hello world")`

Run: 
`jshint --extract=always test.js`

Expected output: 

    test.js: line 1, col 27, Missing semicolon.
    1 error

Actual output: No output

**Comment by BenoitZugmeyer** [comment]
The `extract` option tells jshint when to extract JavaScript code contained in an HTML file. `--extract=always` means : "all input files are HTML files". So if you give a file without any `<script>` tag, it won't extract anything.

**Comment by dturner** [comment]
Ah right, thanks for clarifying. Just to add some background I'm using jshint through SublimeLinter-jshint and that only allows a single configuration for calling the CLI which means (for me) it needs to work for both Django template files and .js files.
