### ISSUE TITLE
[es6] "Bad invocation" when an immediately-invoked arrow function hasn't parenthesis around its argument

### ISSUE THREAD

**Issue by nicolo-ribaudo** [jshint/jshint#2351]
This works:
```javascript
/*jshint esnext: true */

((b) => {})(0);
```

This doesn't work: (But is the same of the first example)
```javascript
/*jshint esnext: true */

(b => {})(0);
```

With the second I get this warning: `Bad invocation`

**Comment by jugglinmike** [comment]
Confirmed. Thanks for the report!

**Comment by lukeapage** [comment]
@nicolo-ribaudo would you like to make a PR for your fix commit referenced above? I can't find it...
