### ISSUE TITLE
JSHINT('function') causes infinite loop in 2.7.0

### ISSUE THREAD

**Issue by Rich-Harris** [jshint/jshint#2362]
Apologies if this was already reported, I couldn't find the issue if so. Title says it all - running `JSHINT('function')` works as expected in 2.6.3, but 2.7.0 falls into an infinite loop.

**Comment by jugglinmike** [comment]
Thanks for the report! This should be resolved by gh-2338 (currently under review)

**Comment by Rich-Harris** [comment]
Sweet! Thanks @jugglinmike, you guys are on the :tennis:

**Comment by jugglinmike** [comment]
Sometimes :)

**Comment by jugglinmike** [comment]
gh-2338 has landed; this should be resolved in the next release of JSHint (version > 2.7.0).

**Comment by Rich-Harris** [comment]
:metal:
