### ISSUE TITLE
Unused Variables and ES6 Template Strings

### ISSUE THREAD

**Issue by danprince** [jshint/jshint#2364]
If I use `esnext` and `unused` then the unused linter will throw an error if a variable is only used in a string interpolation.

```
this.get = function(name) {
  return $http.get(`static/assets/json/${name}.json`);
};
```

I get a `'name' is defined but never used.` error. I guess that interpolated variables don't show up in the same way with static analysis, but is there a better way to circumvent this, than just wrapping it in ignore comments?

**Comment by caitp** [comment]
I think you're using a very old version of jshint --- this has been reported before and was since fixed in v2.5.3 (https://github.com/jshint/jshint/commit/6ca9e4152becc2c6f24e9f52a19af9943b9c7aa1)

**Comment by caitp** [comment]
See #1705

**Comment by danprince** [comment]
Ah, I'm using v2.5.1. Misread the version and thought I was up to date. Updated to 2.7.0 and fixed. Thanks!
