### ISSUE TITLE
Functions within loops (W083) should be allowed for bultin synchronous function executors

### ISSUE THREAD

**Issue by aldendaniels** [jshint/jshint#2366]
As I understand it, the problem addressed by [W083](https://jslinterrors.com/dont-make-functions-within-a-loop) only applies for async functions. Synchronous functions such as `Array.prototype.forEach`, `Array.prototype.filter`, etc. are not subject to these scoping issues.

Here's [an example](http://jsbin.com/hebevapeqe/1/edit?html,js,output) using `forEach`.

Would it make sense to whitelist builtin synchronous function executors?

**Comment by rwaldron** [comment]
> As I understand it, the problem addressed by W083 only applies for async functions.

Misunderstood—there is no lexical scope capture:

```js
var fns = [];

for (var i = 0; i < 5; i++) {
  fns[i] = function() { console.log(i); };
}

fns[0]() === 0; // false because...
fns[0](); // 5

```

**Comment by aldendaniels** [comment]
@rwaldron - Ah, that's true. The absence of lexical scope capture has the potential to be confusing even for sync functions if you maintain a reference to the function. It's just that with the built-in sync function executors such as `forEach`, `filter`, etc. it's highly unusual to do so.
