### ISSUE TITLE
Firefox Add-on, content scripts, 'self' is not defined.

### ISSUE THREAD

**Issue by nschloe** [jshint/jshint#2370]
I'm developing a Firefox Add-on and try to have the JS code checked by jshint. In popups, one can use `self` to initiate communication. Where `self` is defined, I don't know, but sure enough it works and jshint (understandably) fails. See http://stackoverflow.com/a/24412212/353337 for an example.

Is there anything that can be done about this on the jshint side?

**Comment by lukeapage** [comment]
You can add self to the list of globals..
