### ISSUE TITLE
JSHint hangs with ES6

### ISSUE THREAD

**Issue by dennisli92** [jshint/jshint#2383]
I was playing around with ES6, and ran into a case that caused jshint to freeze up:

```
class Foo {
  static foo(bar) = (bar) => new Foo(bar.baz, bar.baz)
}
```

Obviously, this is incorrect syntax, but I don't think jshint is supposed to hang as a result :)

Strangely, changing it to the following allowed jshint to produce the expected error messages.
```
class Foo {
  static foo(bar) = (bar) => new Foo(bar.baz)
}
```

```
> jshint test.js
test.js: line 1, col 1, 'class' is available in ES6 (use esnext option) or Mozilla JS extensions (use moz).
test.js: line 2, col 17, 'function closure expressions' is only available in Mozilla JavaScript extensions (use moz option).
test.js: line 2, col 19, Expected an identifier and instead saw '='.
test.js: line 2, col 21, Expected an operator and instead saw '('.
test.js: line 2, col 25, Class properties must be methods. Expected '(' but instead saw ')'.
test.js: line 2, col 41, Expected ')' to match '(' from line 2 and instead saw '.'.
test.js: line 2, col 41, 'function closure expressions' is only available in Mozilla JavaScript extensions (use moz option).
test.js: line 2, col 45, Unexpected ')'.
```

I'm running jshint v2.7.0

**Comment by jugglinmike** [comment]
Thanks for the report! We resolved this class of bugs via gh-2338; you can expect the next release of JSHint (version > 2.7.0) to correctly halt on input like this.

**Comment by manodupont** [comment]
I am stil having this problem with 2.9.1 ?!?!?

**Comment by manodupont** [comment]
``` javascript
./lib/scorch/scorch-engine-job-queue.js: line 35, col 11, Class properties must be methods. Expected '(' but instead saw '='.
./lib/scorch/scorch-engine-job-queue.js: line 35, col 40, 'function closure expressions' is only available in Mozilla JavaScript extensions (use moz option).
./lib/scorch/scorch-engine-job-queue.js: line 35, col 42, Expected an identifier and instead saw '=>'.
./lib/scorch/scorch-engine-job-queue.js: line 35, col 28, 'pollInterval' is defined but never used.
./lib/scorch/scorch-engine-job-queue.js: line 35, col 14, 'engineRunner' is defined but never used.

**Comment by caitp** [comment]
@manodupont please post a reproduction, thanks!

**Comment by manodupont** [comment]
the code is : 

```javascript
class EngineJobQueue {

    constructor(model) {
        this.model = model;

        //This global is for the rendering server to know which job is in progress
        this.currentJob = null;
    }


    /**
     * Start up the engine rendering jobs queue and start listening for jobs to manage.
     * Likely usage - call once from Meteor.startup if env.SCORCH_ENGINE_ENABLE.
     *
     * @param {Function} startEngine Launch a rendering job when called - params(scoreId, scoreUrl, identity, jobType, transString, callback(err))
     * @param {number} [pollInterval] How frequently to check for jobs in ms; default 500ms
     * @public
     */
    start = (engineRunner, pollInterval) => {
        // already started?
        if (this.isRunning()) {
            return true;
        }
....
.....
```

**Comment by caitp** [comment]
That's the whole file? and what configuration are you using?

**Comment by manodupont** [comment]
Oh forget it. Sorry. I mislead something.  Can close this.

Thanks.

**Comment by rwaldron** [comment]
To the next person that wants to post on this thread:  arrow functions cannot be used as class method definition syntax.

**Comment by maicss** [comment]
What about this:

```
class aa {
    static p = {
        name: ''
    }
}
```

```
[jshint] Class properties must be methods. Expected '(' but instead saw '='. (E054)
```

**Comment by rwaldron** [comment]
That's not, and never was, supported in ES6.

**Comment by sSeewald** [comment]
@rwaldron The error is shown for string values too.

**Comment by 40sherrin** [comment]
I just installed jslint and jshint, nothing is wrong with my code I guess. But I wonder why I got the error message for the right code.

`const durationInput = document.querySelector("#duration")
const startButton = document.querySelector("#start")
const pauseButton = document.querySelector("#pause")
class Timer {
    constructor(durationInput, startButton, pauseButton) {
        this.durationInput = durationInput;
        this.startButton = startButton;
        this.pauseButton = pauseButton;
        this.startButton.addEventListener("click", this.start);
    }
    **start = () => {
           @@@this.importantMethodToCall();
    }**
    importantMethodToCall() {
        console.log("Important method to call has worked");
    }
}

const timer = new Timer(durationInput, startButton, pauseButton);
timer.start()`
**Error:** **"Class properties must be methods. Expected '(' but instead saw '='. jshint(E054)"**

**Comment by jugglinmike** [comment]
Hi there, @40sherrin. Your code uses a new language feature that isn't support by JSHint. We have an issue to track that particular feature request: gh-3361.

(By the way, on GitHub.com, you can use three "backtick" characters in a row to designate a block of code to be displayed with a fixed-width font.)
