### ISSUE TITLE
ES6: Expected ',' and instead saw '='

### ISSUE THREAD

**Issue by monolithed** [jshint/jshint#2387]
```js
let foo = {
  bar ({a, b, c = {}}) {
      return arguments;
  }
};

foo(0, 1);
```

**Expected ',' and instead saw '='**

**Comment by caitp** [comment]
Yeah, last I looked at it the method parsing code  didn't deal with optional arguments, maybe not destructing either. Should be a good first big if anyone else is interested in sending a PR

**Comment by nicolo-ribaudo** [comment]
Duplicate of #1941 :wink: 

(I'm working on this)
