### ISSUE TITLE
jshint incorrectly supports the module x from 'y' format?

### ISSUE THREAD

**Issue by lukeapage** [jshint/jshint#2395]
I noticed this is allowed...

```
module x from 'y';
```

Is that right? I haven't seen it in es6 or am I wrong? I'm not a spec expert.

should it be removed from jshint or put into mozilla javascript extensions, which has other non es6 stuff in like the strange let statement.

**Comment by nicolo-ribaudo** [comment]
It was previously defined at http://wiki.ecmascript.org/doku.php?id=harmony:modules. That page's content is now defined at https://people.mozilla.org/~jorendorff/es6-draft.html#sec-scripts-and-modules but `ModuleDeclaration` is not specified, so it is deprecated.

(Also both [babel](http://babeljs.io/repl/#?experimental=false&evaluate=false&loose=false&spec=false&playground=false&code=module%20a%20from%20%22b%22%3B) and [traceur](https://google.github.io/traceur-compiler/demo/repl.html#module%20a%20from%20%22b%22%3B) don't support it)

**Comment by caitp** [comment]
Yep. Either if you care to send a patch getting rid of it?

**Comment by lukeapage** [comment]
I can do it,  but if someone is enthusiastic, shout and i will leave you to
it,  my work fixing used label bugs is showing no sign of finishing.

**Comment by jamestaylr** [comment]
I wouldn't mind tackling this.
I'm pretty sure [this one block](https://github.com/jshint/jshint/blob/master/src/jshint.js#L1588) needs to be altered through throw a warning or be removed all together. What's the expected behavior?

**Comment by lukeapage** [comment]
yes, thats the code i came across. If I were you I'd try taking it out and making sure you get a ok error message in a test if the old module format is used - but I'm not a maintainer, @caitp etc might have more specific requirements.

**Comment by caitp** [comment]
i'd rather just remove it from the parser

**Comment by jamestaylr** [comment]
Okay I'm authoring a pull request that removes it completely from the parser and also removes the associated test. Let me know if I'm missing anything!
