### ISSUE TITLE
Not catching variables 'not defined'

### ISSUE THREAD

**Issue by mmerkes** [jshint/jshint#2396]
```
function square(n) {
  result = n * n;  
  return result;
}

square(5);
```

`result` in the above should throw an jshint error since it doesn't use `var`, correct? I did a clean install the latest from npm (v2.7.0), and I'm expecting to get `result' is not defined.`

I run straight `jshint filename.js` on OS X 10.9.5. Also, I checked all of the way up my file chain, and there was no JSHint that might have configured it to allow such nonsense!

I've used JSHint quite a bit, so I'm confused about this. Perhaps, a bug? Am I the only one?

**Comment by nicolo-ribaudo** [comment]
Is `result` defined in an outer scope?

**Comment by jugglinmike** [comment]
`undef` is an "enforcing option", meaning it is not enabled by default. You'll need to enable it explicitly, either through a .jshintrc file, through the JSHint API, or through an in-line comment. An example of that last approach:

```js
/* jshint undef: true */
function square(n) {
  result = n * n;  
  return result;
}

square(5);
```

When I run JSHint v2.7.0 against that code, it reports the warnings you are expecting:

    ../gh-2396.js: line 3, col 3, 'result' is not defined.
    ../gh-2396.js: line 4, col 10, 'result' is not defined.

**Comment by mmerkes** [comment]
Ok, my assumption had been that it was a set by default, which is really surprising to me that it isn't. Thanks for the clarification!
