### ISSUE TITLE
Switching to lodash breaks jshint.github.io

### ISSUE THREAD

**Issue by caitp** [jshint/jshint#2397]
If you upgrade the jshint.github.io branch to the 2.7.0 tag, you'll see that we detect the global object incorrectly. It seems like this version of lodash doesn't play very well with web workers or whatever browserify build steps we're using.

You end up with something like:

```js
/* ... */, [function(require,module,exports){
(function (global){
  /**
 * @license
 * Lo-Dash 2.4.1 (Custom Build) <http://lodash.com/>
 * Build: `lodash modern -o ./dist/lodash.js`
 * Copyright 2012-2013 The Dojo Foundation <http://dojofoundation.org/>
 * Based on Underscore.js 1.5.2 <http://underscorejs.org/LICENSE>
 * Copyright 2009-2013 Jeremy Ashkenas, DocumentCloud and Investigative Reporters & Editors
 * Available under MIT license <http://lodash.com/license>
 */
;(function() {
  // ...
  /** Used as a reference to the global object */
  var root = (objectTypes[typeof window] && window) || this;
  // ...
})();
}).call(this, ....);
```

In a worker, we don't have"window", and "this" is whatever weird browserify non-global object. So lodash breaks and jshint doesn't work.

Lets fix that ^_^

**Comment by nicolo-ribaudo** [comment]
Use Lodash 3.0
https://github.com/lodash/lodash/issues/313#issuecomment-71365917

**Comment by jugglinmike** [comment]
see gh-2329

**Comment by caitp** [comment]
So this is fixed already, but we can't really update the version on the site until the next release which will incorporate that fix. Closing for now
