### ISSUE TITLE
jshint runs forever on this file

### ISSUE THREAD

**Issue by AgentME** [jshint/jshint#2402]
jshint (2.7.0) runs at full cpu never completing on this incomplete file for me:

```
import url from 'url';

export default function foo(a, b) {
  
}

export function
```

I noticed this while writing the above file, and my CPU fans sped up because Atom started another instance of jshint every couple of keystrokes, and none of them ever completed.

**Comment by jugglinmike** [comment]
Thanks for the report! We resolved this class of bugs via gh-2338; you can expect the next release of JSHint (version > 2.7.0) to correctly halt on input like this.
