### ISSUE TITLE
ignore node_modules directory

### ISSUE THREAD

**Issue by ORESoftware** [jshint/jshint#2408]
please allow us the option to run `jshint .` (at root of a node.js project) and ignore the `./node_modules` folder, thank you

this could be with a command-line flag

e.g.

jshint . --ignore ./folder1 ./**/folder2 ./node_modules --someFlag dothis

or

in the .jshintrc file like so (this might allow you specify whether a file or a directory is to be ignored):

`ignore: [{"dir":"./node_modules"},{"file":"./myFile"},{"dir","./data*"}]`

**Comment by jugglinmike** [comment]
Have you seen the `--exclude` flag on [the JSHint website](http://jshint.com/docs/cli/) (and in the CLI's `--help` prompt)?

> `--exclude`
>
> Allows you to specify directories which you DON'T want to be linted.

For instance:

    $ jshint --exclude ./node_modules .

(There's also the [undocumented](https://github.com/jshint/jshint/issues/1745) `.jshintignore` file, but [the expected format of that file is likely to change soon](https://github.com/jshint/jshint/issues/1917).)

**Comment by ORESoftware** [comment]
thank you, the command line flag will work for now I guess

**Comment by jugglinmike** [comment]
Great! Glad it's working for you

**Comment by ORESoftware** [comment]
thx

**Comment by hughrawlinson** [comment]
How about excluding multiple directories?

**Comment by adriancmiranda** [comment]
@hughrawlinson 
jshint scripts/ --exclude scripts/bundle.js,scripts/vendors/
Comma-separated list work's to me
