### ISSUE TITLE
already defined error if you use from the parent scope and then re-declare

### ISSUE THREAD

**Issue by lukeapage** [jshint/jshint#2410]
The following errors
```
/* jshint shadow: inner */
function test() {
	var a = 1;
  (function() {
    a++;
    var a;
  })();
}
```
`'a' is already defined.`

but only when the variable is used (remove `a++` and it will not error).

I don't think it should error based on shadow: inner. It should error with shadow outer (and it does - you get 2 errors).

to give an example of working code

```
/* jshint shadow: inner */
function test() {
	var a = 1;
  (function() {
    (function () {
      a = 2;
    }());
    a++;
    var a;
  }());
}
```

I've already fixed this, but want to get confirmation in case there is something I am missing.

**Comment by jugglinmike** [comment]
I agree that the first example shouldn't produce an error. I'm not sure what you mean by "working code" with the second example, though--that triggers the same (currently incorrect) warning on `master`.

On a related note, the "inner" option never really made sense to me. @rwaldron and I have discussed a simpler enforcing option named `noshadow` that would behave as `shadow: outer` does today. Not necessarily in-scope for your current work, but I thought you might be interested anyway.

**Comment by lukeapage** [comment]
> I'm not sure what you mean by "working code" with the second example, though--that triggers the same (currently incorrect) warning on master.

it was just constructing an example that doesn't do a ++ on undefined.

Thanks for the feedback.
