### ISSUE TITLE
Add a configurable stage property to support linting of more experimental javascript features

### ISSUE THREAD

**Issue by hannahhoward** [jshint/jshint#2414]
It seems like people are increasingly adopting experimental TC39 stage 0/1 JS features like decorators and class properties in their code.

So that those people aren't left unable to lint until these features reach stage 2, why not add a stage option, as Babel.js did, that allows you to turn on support for linting JS features that are earlier in development. So for example, I would run JSHint with stage = 1 to get support for decorators. Then, time permitting add support for these features in JSHint (though not turned on by default) so that people who are writing code that uses these features (via transpilation) can still have proper linting.

**Comment by lukeapage** [comment]
related/duplicate - https://github.com/jshint/jshint/issues/1939
lots of discussion there about how to support experimental features.
