### ISSUE TITLE
missing info on exported in documentation

### ISSUE THREAD

**Issue by Daniel-Hug** [jshint/jshint#2415]
In the documentation under "[Inline configuration](https://github.com/jshint/jshint/wiki/Documentation#inline-configuration)" the following statements are made. The part in bold below is wrong, right?

> In addition to using configuration files you can configure JSHint from within your files using special comments. **These comments start either with `jshint` or `global`** and are followed by a comma-separated list of values.

Comments can start with [`exported`](https://github.com/jshint/jshint/wiki/Documentation#exported) too.

**Comment by jugglinmike** [comment]
Thanks for the report! We addressed this when improving the documentation
published on jshint.com--the relevant text there reads:

> These comments start with a label such as jshint or globals (complete list
> below)

source: http://jshint.com/docs/#inline-configuration

I can't see any reason to maintain the documentation on both jshint.com and the
GitHub-provided wiki, so I'm going to close down the latter.
