### ISSUE TITLE
Unexpected default behavior

### ISSUE THREAD

**Issue by dmin** [jshint/jshint#2417]
I'm new to JSHint, so forgive me if I'm missing something. One of the first things I started playing around with was checking for undefined variables. As I understand it, the default setting for the ```undef``` option is ```true``` (I assume this based on [/src/options.js](https://github.com/jshint/jshint/blob/master/src/options.js#L248). I did not see any information on the website which listed the default settings.)

When running the following code:
- I had no .jshintrc file (and no other .jshintrc files further down the file system)
- I had no jshintConfig property in package.json
- I'm using version 2.7.0.

I expected the following code to give an error about an undefined variable but it gave no warnings: 

```javascript
undefinedVar = "Hello";
```

If I add an inline config it then reports an error.

```javascript
// jshint undef: true
undefinedVar = "Hello";
```
```
$ jshint source/test.js 
source/test.js: line 2, col 1, 'undefinedVar' is not defined.

1 error
```

As a new user my expectation was that undefined variables should produce an error by default (without manually setting the option to true). Was this an incorrect assumption? 

If JSHint's default option settings are different than that found in /src/options I'd be happy to submit a pull request documenting the default options if someone could point me to the place they are actually defined (its not immediately obvious to me).

Thanks!

#1448

**Comment by jugglinmike** [comment]
The `options.js` source code file is not meant to describe default behavior. This is covered by the options' classification as "enforcing" or "relaxing". A while back, [it was suggested that we expose all options as "enforcing" options](https://github.com/jshint/jshint/issues/1223), which would effectively mean, "All warnings are disabled by default". I like that idea, but it's a really big change, so it would have to wait for the next release (assuming that we want to make that commitment at all).

In the mean time, I wonder if better documentation would have helped you here. Care to chime in on this (currently closed) issue filed against the JSHint web site? https://github.com/jshint/jshint.github.io/pull/20
