### ISSUE TITLE
Linting CoffeeScript makes JSHint hang

### ISSUE THREAD

**Issue by MarcelGerber** [jshint/jshint#2421]
(adobe/brackets#11159)

* Create a `test.js` file consisting of this (rather simple) CoffeeScript snippet:
``` coffee
class X
    foo: -> 'bar'
```
* Run `jshint test.js`

Result:
JSHint hangs.

Expected:
Even though JSHint obviously is not supposed to lint CoffeeScript, it shouldn't hang either way.
In this case, the user accidentally saved his .coffee file as .js, and with Brackets automatically linting every .js file, JSHint made the editor hang.

JSHint 2.7.0, installed via `npm install -g jshint`

**Comment by jugglinmike** [comment]
Thanks for the report! We resolved this class of bugs via gh-2338; you can expect the next release of JSHint (version > 2.7.0) to correctly halt on input like this.
