### ISSUE TITLE
Please, add directive: skip $pattern

### ISSUE THREAD

**Issue by unera** [jshint/jshint#2431]
For example You write a code:

```js
 
var str = 'message '
  + 'message tail begin'
  + 'message tail end';

...
```

And jshint showes complain message:

```

Bad line breaking before '+'

```

And if You don't know what to write to comment `jshint bla: true/false` You are forced to look through documentation.

So

It would be nice to have UNIVERSAL jshint direcrtive to skip next complain message by text-pattern.

It could be looked like:

```js
 
/* jshint skip 'Bad line breaking' */
var str = 'message '
  + 'message tail begin'
  + 'message tail end';

...
```

`skip`'s argument is a substring in next skipped warning/error message.
If argument is absent, jshint could skip any (and one) next message.

**Comment by nicolo-ribaudo** [comment]
Why don't use `ignore`?

```js
/*jshint ignore:start */
var str = 'message '
  + 'message tail begin'
  + 'message tail end';
/*jshint ignore: end */
```

**Comment by unera** [comment]
In case 'skip $pattern' only one complain message will be skipped - by pattern.

If You use ignore:start ... end, You disable jshint fully.

So I prefer to disable messges by its option-name/number.

**Comment by nicolo-ribaudo** [comment]
> So I prefer to disable messges by its option-name/**number**.

```js
/*jshint -W014 */
var str = 'message '
  + 'message tail begin'
  + 'message tail end';
/*jshint +W014 */
```

**Comment by caitp** [comment]
@unera you can already do this

```js
// jshint -W018
if (!!((foo && bar) || (biz && !baz))) {
// jshint +W018
  // carry on
}
```

**Comment by unera** [comment]
> /*jshint -W014 */

Yes, skip 'Bad line breaking' will do the same and be liked more informatively

**Comment by unera** [comment]
> you can already do this

I don't seek a way to do something :) I've just found it.
I write feature request for new functional: new directive :)

**Comment by caitp** [comment]
> Yes, skip 'Bad line breaking' will do the same and be liked more informatively

It would be informative, but it also means adding a lot of new magic words and complexity to the jshint parser, which is really a non-starter for something like this.

The best thing to do is just leave a comment when you disable/enable warnings inline

```js
// Make jshint happy with double-negation
// jshint -W018
```

**Comment by unera** [comment]
> but it also means adding a lot of new magic words and complexity

The option has the same format like the other options: name[ argument] :)

**Comment by caitp** [comment]
No, the simplest way to do what you want would be a regexp match on the message, which will have false positives --- anything else would be adding new ways to reference the same message, which would be a problem

**Comment by jugglinmike** [comment]
It's also very useful for us to reserve the ability to change the warning/error text at any time--that allows us to tweak and re-use existing messages for new patterns. If we were to allow consumers to configure JSHint based on the message content, we'd no longer have this flexibility.

**Comment by jugglinmike** [comment]
I'm closing this for the reason cited above. Exposing error codes to consumers
(rather than limited configuration to human-readable option names) has made
JSHint more fragile. This would continue with that tend, without adding much
benefit beyond the error-code-with-comment approach that @caitp recommended.
