### ISSUE TITLE
Expected an assignment with object.setStuff(new Stuff())

### ISSUE THREAD

**Issue by martensms** [jshint/jshint#2437]
Hey,

with this code I get the following error - and I'm not sure whether that is an issue or not. If it's not legit code, what's the issue?

Do I really need to do an assignment before?
If so, what's the VM-reasoning behind?

```
background.color = '#32afe5';
background.addEffect(new lychee.effect.Color({
    type:     lychee.effect.Color.TYPE.easeout,
    duration: 300,
    color:    '#404948'
}));
```

**Comment by caitp** [comment]
You can disable this warning with the option `nonew: false` in your jshint config. The reasoning for it is to prevent using "new" for side effect purposes. However, in this case, you are actually doing an assignment, so it's a false positive for the "just for side effects" case, which is very hard to figure out in static analysis of JS code.

I believe this option came from crockford originally, but I could be wrong. Feel free to turn it off.

**Comment by martensms** [comment]
Thanks for the hint, I turned the flag off :)
