### ISSUE TITLE
How to run jshint.js with node.exe and get output?

### ISSUE THREAD

**Issue by AlbertWiersch** [jshint/jshint#2442]
I'm the developer of CSE HTML Validator for Windows. CSE HTML Validator currently uses JSLint and runs JSLint with something like
node.exe wrapper.js test.js

The wrapper.js uses jslint.js (in the same folder as wrapper.js) to generate the results and output them to the console. The setup program for CSE HTML Validator only has to install node.exe, wrapper.js, and jslint.js on a user's system to get it to work.

I want to be able to support jshint in a similar manner.
 
I see there is a large “jshint.js” file in the dist folder here:
https://github.com/jshint/jshint/tree/master/dist
 
I’m hoping I can simply distribute just that file (jshint.js) with CSE HTML Validator (similar to JSLint), and call jshint.js with node.exe and the name of the file to check. I am already installing node.exe on the user’s system to support JSLint.
 
So basically what I would like to know is what files I need (the minimum number) to install on the user’s system (when they install my application) and how to call JSHint (I am already installing node.exe for JSLint). I hope to find a way to only install jshint.js and maybe a support file (like wrapper.js which I use for JSLint), and be able to execute something like “node.exe jshint.js test.js” and get the results in a similar way to JSLint.
 
Hopefully I won’t have to install all the JSHint files in the “src” folder or any modules folder or npm or a bunch of other files.
 
Perhaps I only need an appropriate wrapper.js file for jshint? However, I'm not totally sure and would like some help from someone who knows a lot about jshint.

Can someone help me get this working this way? I would really appreciate any help. I want to make jshint the default JavaScript linter instead of jslint because I think it's more practical and better overall.

**Comment by lukeapage** [comment]
jshint was forked from jslint and I believe it follows a similiar API. You should be able to do what you want, I used to use jshint in this way for the jslint for visual studio plugin, but I haven't tried the api in a while.

**Comment by AlbertWiersch** [comment]
That's what I was hoping for but it's not working.

For example, this is what I get when I run "node.exe wrapper.js test.js":

T:\JSHint>node.exe wrapper.js test.js
evalmachine.<anonymous>:2194
    var arrayProto = Array.prototype,
                          ^
TypeError: Cannot read property 'prototype' of undefined
    at runInContext (evalmachine.<anonymous>:2194:27)
    at Object.<anonymous> (evalmachine.<anonymous>:13258:11)
    at Object.<anonymous> (evalmachine.<anonymous>:13289:3)
    at Object.require (evalmachine.<anonymous>:13291:4)
    at s (evalmachine.<anonymous>:6:262)
    at evalmachine.<anonymous>:6:313
    at Object.require.jshint../lex.js (evalmachine.<anonymous>:17432:16)
    at s (evalmachine.<anonymous>:6:262)
    at evalmachine.<anonymous>:23042:10
    at evalmachine.<anonymous>:23044:2


If someone who knows more about this can help, I'd much appreciate it. If you extract the files here into a 'JSHint' folder, then you will probably be able to reproduce this if node.exe is in your path:
https://www.htmlvalidator.com/private/JSHint.zip

Perhaps this is a bug in jshint.js?

**Comment by lukeapage** [comment]
See

https://github.com/lodash/lodash/issues/223

Somone has the same issue,  seems caused by lodash ran using runincontext (jshint bundles lodash). 

I would try 1. Updating node 2. Comtinue searchimg google (with runincontext and the error you are getting connected with lodash or browserify 3. Ask on that issue i linked

**Comment by AlbertWiersch** [comment]
Thanks. I'm using the latest version of node (v0.12.4). I'll have to do the research you suggest when I have time... maybe by then the issue will be resolved. :)
