### ISSUE TITLE
strict option requires "use strict" in double quotes (regardless of quotmark set to single)

### ISSUE THREAD

**Issue by gaboom** [jshint/jshint#2452]
Using JSCS to enforce use of single quotation marks. At the same time JSHint enforces strict mode.

The two are in conflict, because JSHint enforces "user strict" with double quotes, does not accept 'use strcit' in single quotes. This behavior is exhibited regardless of JSHint quotmark is set to single.

Expected is that 'use strict' is accepted and enforcable with single quotes.

Using "grunt-contrib-jshint": "~0.11.2",

**Comment by jugglinmike** [comment]
I can't reproduce this in the latest release of JSHint (2.8.0):

```
$ ./bin/jshint -
// jshint strict: true
(function() {
  return;
}());    
(function() {
  "use strict";
  return;
}());
(function() {
  'use strict';
  return;
}());
stdin: line 3, col 3, Missing "use strict" statement.

1 error
$ ./bin/jshint --version
jshint v2.8.0
```

[The module you referenced is depends on JSHint at `^2.6.0`](https://github.com/gruntjs/grunt-contrib-jshint/blob/edf46ca03971b48da5a5df3d152ddddff255e423/package.json#L19), so I tried that version as well. Still nothing:

```
$ ./bin/jshint -
// jshint strict: true
(function() {
  return;
}());    
(function() {
  "use strict";
  return;
}());
(function() {
  'use strict';
  return;
}());
stdin: line 3, col 3, Missing "use strict" statement.

1 error
$ ./bin/jshint --version
jshint v2.6.0
```

Can you share some sample code that demonstrates the issue?

**Comment by lukeapage** [comment]
Closing after no response, we can re-open if a test case can be given.
