### ISSUE TITLE
== null should be forgiven when surrounded by extra parens

### ISSUE THREAD

**Issue by Flimm** [jshint/jshint#2456]
As discussed in issue #13 , `x == null` is a useful construct that evaluates to true only if `x` is `undefined` or `null`. The only way to avoid a warning currently is to enable `boss:true`.

It would be useful if you could also suppress this warning by surrounding the comparison with an additional pair of parenthesis. This would match another similar case, described in the documentation for `boss`:

> You can silence this error on a per-use basis by surrounding the assignment with parenthesis, such as:
for (var i = 0, person; (person = people[i]); i++) {}

**Comment by lukeapage** [comment]
I think `== null` is now only controlled by the eqnull option.

Try this out on the website.

```
/* jshint eqeqeq: true, eqnull: true, boss: false */

var a = 1 == null;

for(var b = 1; b == null; b++) {
  
}
```

Since eqnull only controls this very specific point, is it necessary to add a specific type of override? I would vote it is fine as it is.

**Comment by amigrave** [comment]
Well, then the same question could be raised about `boss` for assignment as expression, right ?

Personally I like being able to silent those cases by using extra parens because it's explicit in the code and somewhat points out that the author knows what he's doing (even if he have a `~/.jshintrc` with `eqnull`).

When working on a collaborative project, it's then easier to spot responsible usage vs potential mistake.

My 2 cents.

**Comment by jugglinmike** [comment]
The "supress-via-parens" pattern is incompatible with the `singleGroups` option. If we decide that `eqnull` is somehow not sufficient, we shouldn't consider unnecessary parenthesis an acceptable solution because it's not valid in `singleGroups: true` contexts.

**Comment by lukeapage** [comment]
> Well, then the same question could be raised about boss for assignment as expression, right ?

I would think eqnull is more likely to want a consistent approach, where as a for loop in a specific scenario might need an override more often. 

What would code look like if every rule was ignored via parens and you used it? It would look pretty bad.  Also what about false positives - would we require 2 parens in case someone was already using parens for aesthetic or ordering reasons.

**Comment by Flimm** [comment]
I'm happy with the `eqnull` option which I didn't realise existed, so don't keep this open on my account.
