### ISSUE TITLE
Reports error for Object Destructuring assignment with default arguments in esnext mode

### ISSUE THREAD

**Issue by baileyparker** [jshint/jshint#2457]
With `"esnext": true` in my `.jshintrc`, the following code is incorrectly reported to be an error by jshint:

    function foobar({someProperty = 10} = {}) { // <-- error here
        // baz
    }

The error reported is:

> Expected ',' and instead saw '='

However, this a combination of object destructuring and default arguments and is valid ES6. A similar example is listed on [MDN's destructuring reference page](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment#Function_argument_defaults):

    	function drawES6Chart({size = 'big', cords = { x: 0, y: 0 }, radius = 25} = {}) 
	{
	  console.log(size, cords, radius);
	  // do some chart drawing
	}

	drawES6Chart({
	  cords: { x: 18, y: 30 },
	  radius: 30
	});

A similar error is reported for instance methods (declared with the new shorter syntax):

    class Foobar {
        construct({someProp = 'bar'} = {}) {  // <-- error here
            // ...
        }

        otherMethod({someOtherProp = 'bar'} = {}) {  // <-- error here also
            // ...
        }
    }

**Comment by nicolo-ribaudo** [comment]
> This is a duplicate of gh-1941, but a fix is on it's way! See gh-2391
