### ISSUE TITLE
How to express:   return (!!this.srcId === !!this.destId);  // True if both are present, or both are undefined/false.

### ISSUE THREAD

**Issue by MichaelJCole** [jshint/jshint#2460]
Hi, I'm getting a warning on this code:

      return (!!this.srcId === !!this.destId);  // True iff: both are defined/true or both are undefined/false.

What's the recommended way to express this re: jshint?

```
  line 61  col 13  Possible strict violation.
  line 61  col 30  Possible strict violation.
  line 61  col 11  Confusing use of '!'.
  line 61  col 28  Confusing use of '!'.
```

**Comment by jugglinmike** [comment]
I would write that as:

```js
return !!this.srcId && !!this.destId || !this.srcId && !this.destId;  // True iff: both are defined/true or both are undefined/false.
```

This is definitely more verbose than your version, but I think that's warranted because the value you are returning is complex. In this version, the code matches the comment so closely that the latter may not even be necessary.

Or if you prefer, you can disable the warning:

```js
// jshint -W018
return (!!this.srcId === !!this.destId);  // True iff: both are defined/true or both are undefined/false.
```

**Comment by nicolo-ribaudo** [comment]
Or you can write that as
```js
return Boolean(this.srcId) === Boolean(this.destId);
```
(I think this is less confusing than the version @jugglinmike suggested)

**Comment by lukeapage** [comment]
Or even.. 
```
return Boolean(this.srcId ? this.destId : !this.destId);
```

**Comment by MichaelJCole** [comment]
Thanks, these are great suggestions!  Appreciate it :-)
