### ISSUE TITLE
ComputedPropertyName, StringLiteral and NumericLiteral in object destructuring

### ISSUE THREAD

**Issue by nicolo-ribaudo** [jshint/jshint#2467]
Consider this (valid) code:
```js
const { ["z"]: a, 1: b, "x": c } = { z: 2, 1: 3, x: 4 };
```
Errors reported by JSHint:
```
Expected an identifier and instead saw '['.
Expected ',' and instead saw 'z'.
Expected an identifier and instead saw ']'.
Expected an identifier and instead saw '1'.
Expected an identifier and instead saw 'x'.
```
---
Spec:
[12.14.5 Destructuring Assignment](http://people.mozilla.org/~jorendorff/es6-draft.html#sec-destructuring-assignment)
> *AssignmentPattern*<sub>[Yield]</sub> :
> &nbsp; *ObjectAssignmentPattern*<sub>[?Yield]</sub>
> &nbsp; ...
>
> ObjectAssignmentPattern[Yield] :
> &nbsp; ...
> &nbsp; **{** *AssignmentPropertyList*<sub>[?Yield]</sub> **}**
> &nbsp; **{** *AssignmentPropertyList*<sub>[?Yield]</sub> **, }**
>
> *AssignmentPropertyList*<sub>[Yield]</sub> :
> &nbsp; *AssignmentProperty*<sub>[?Yield]</sub>
> &nbsp; *AssignmentPropertyList*<sub>[?Yield]</sub> **,** *AssignmentProperty*<sub>[?Yield]</sub>
>
> *AssignmentProperty*<sub>[Yield]</sub> :
> &nbsp; ...
> &nbsp; *PropertyName* **:** *AssignmentElement*<sub>[?Yield]</sub>

Definition of *PropertyName*:
[12.2.5 Object Initializer](http://people.mozilla.org/~jorendorff/es6-draft.html#sec-object-initializer)
> *PropertyName*<sub>[Yield,GeneratorParameter]</sub> :
> &nbsp; *LiteralPropertyName*
> &nbsp; [+GeneratorParameter] *ComputedPropertyName*
> &nbsp; [~GeneratorParameter] *ComputedPropertyName*<sub>[?Yield]</sub>
>
> *LiteralPropertyName* :
> &nbsp; *IdentifierName*
> &nbsp; *StringLiteral*
> &nbsp; *NumericLiteral*

**Comment by lukeapage** [comment]
and supported by babel.js - http://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&code=const%20{%20[%22z%22]%3A%20a%2C%201%3A%20b%2C%20%22x%22%3A%20c%20}%20%3D%20{%20z%3A%202%2C%201%3A%203%2C%20x%3A%204%20}%3B%0A
