### ISSUE TITLE
Validthis breaks when adding function definition?

### ISSUE THREAD

**Issue by erwinw** [jshint/jshint#2471]
The following code gives no jshint warnings:

	'use strict';
	
	/*jshint validthis:true*/
	function a(){
		this.foo = 'bar';
	}
	/*jshint validthis:false*/

	a();

The following code does give a jshint warning:
	
	'use strict';
	
	function foo(){}

	/*jshint validthis:true*/
	function a(){
		this.foo = 'bar';
	}
	/*jshint validthis:false*/

	a();
	foo();

In other words, adding that (completely unrelated) function definition somehow makes jshint ignore the validthis flag.

**Comment by nicolo-ribaudo** [comment]
Duplicate - #2436
