### ISSUE TITLE
Gulp task cannot be killed with Ctrl-C?

### ISSUE THREAD

**Issue by adjavaherian** [jshint/jshint#2475]
I'm wondering why I'm unable to SIGINT my hint task when I'm using gulp-jshint?

```javascript
var gulp        = require('gulp');
var jshint      = require('gulp-jshint');
var config      = require('../config').jsHint;
var stylish     = require('jshint-stylish');
var plumber     = require('gulp-plumber');
var react       = require('gulp-react');
var jscs        = require('gulp-jscs');

gulp.task('hint', function() {

    return gulp.src([config.appjsx, config.config, config.server])
        .pipe(plumber())
        .pipe(react())
        .pipe(jscs())
        .pipe(jshint())
        .pipe(jshint.reporter(stylish))
        .pipe(jshint.reporter('fail'));

});

```
w/ gulp-jshint@1.11.0

gulp-jshint@1.11.0 node_modules/gulp-jshint
├── minimatch@2.0.8 (brace-expansion@1.1.0)
├── through2@0.6.5 (xtend@4.0.0, readable-stream@1.0.33)
├── rcloader@0.1.2 (rcfinder@0.1.8, lodash@2.4.2)
└── jshint@2.8.0 (strip-json-comments@1.0.2, exit@0.1.2, shelljs@0.3.0, console-browserify@1.1.0, cli@0.6.6, htmlparser2@3.8.3, lodash@3.7.0)

It just lints and hangs after the last notification, then it becomes un-killable. Should at least return, no?

SIGKILL (ctrl-) works, but it dumps core.

gulp folks seem to think this is a locking issue with jshint rather than gulp

https://github.com/spalger/gulp-jshint/issues/112

**Comment by lukeapage** [comment]
Please can you make a repro case available? Have you tried using the jshint cli? If that works it points mire towards something else I would think.

**Comment by adjavaherian** [comment]
Err, my bad.  Not a good idea to recursively hint into a big ugly webpack bundle.  Works well when I remove the bundle from the source.  Thanks.
