### ISSUE TITLE
[bug] Handle embedded template strings.

### ISSUE THREAD

**Issue by trusktr** [jshint/jshint#2480]
For example, it says there's an error here:

```
    var stringArrayRegex        = `${String.raw`\[(\s*(${stringRegex}\s*,?)\s*)*\]`}`
```

The error is

```
Unexpected '`'.
``` 

I think the inner template string should be fine since it's inside of the `${}`. Anything in the `${}` can be a legal JavaScript expression, including ones that have template strings.

Babel handles it like [this](https://babeljs.io/repl/#?experimental=false&evaluate=false&loose=false&spec=false&playground=false&code=function%20regex(literals%2C%20...substitutions)%20%7B%0A%20%20%20%20let%20result%20%3D%20%22%22%3B%0A%0A%20%20%20%20%2F%2F%20run%20the%20loop%20only%20for%20the%20substitution%20count%0A%20%20%20%20for%20(let%20i%20%3D%200%3B%20i%20%3C%20substitutions.length%3B%20i%2B%2B)%20%7B%0A%20%20%20%20%20%20%20%20result%20%2B%3D%20literals%5Bi%5D%3B%0A%20%20%20%20%20%20%20%20result%20%2B%3D%20substitutions%5Bi%5D%3B%0A%20%20%20%20%7D%0A%0A%20%20%20%20%2F%2F%20add%20the%20last%20literal%0A%20%20%20%20result%20%2B%3D%20literals%5Bliterals.length%20-%201%5D%3B%0A%0A%20%20%20%20return%20result%3B%0A%7D%0A%0A%20%20%20%20var%20raw%20%3D%20String.raw%0A%20%20%20%20var%20stringRegex%20%20%20%20%20%20%20%20%20%20%20%20%20%3D%20regex%60%24%7BString.raw%60%5B'%22%5D%5B%5E'%22%5D*%5B'%22%5D%60%7D%60%0A%20%20%20%20var%20stringArrayRegex%20%20%20%20%20%20%20%20%3D%20regex%60%24%7BString.raw%60%5C%5B(%5Cs*(%24%7BstringRegex%7D%5Cs*%2C%3F)%5Cs*)*%5C%5D%60%7D%60%0A).

**Comment by nicolo-ribaudo** [comment]
Fixed in JSHint 2.6.1 - #2152

**Comment by lukeapage** [comment]
confirmed thanks @nicolo-ribaudo

**Comment by trusktr** [comment]
Awesome, all the red marks and warnings in my neovim gutter are gone now. :smile:
