### ISSUE TITLE
Bad Invocation(W067) on immediate invocation of function from es6 import 

### ISSUE THREAD

**Issue by lyonlai** [jshint/jshint#2485]
Hi there, I've run into this issue recently. the example code is just like this.

    import Radium from 'radium';

    export default Radium(somthing);

does anyone knows why this is happening? I can't even find a flag to turn it off.

we use babel to do the transform.

**Comment by jugglinmike** [comment]
I cannot reproduce this warning. Does the code sample you shared trigger the warning on its own? Also, which version JSHint are you using?

**Comment by lyonlai** [comment]
the JSHint version I'm using is the latest(2.8.0). I load the jshint via the jshint loader. here is the module part of my webpack config.  

     module: {
        preLoaders: [
          {
            exclude: /node_modules/,
            loader: 'babel',
            test: /\.jsx?$/
          }
        ],
        loaders: [
          {
            exclude: /node_modules/,
            loader: 'jshint-loader',
            test: /\.jsx?$/
          }
        ]
      },

**Comment by jugglinmike** [comment]
Can you share the JavaScript source code and configuration that is producing the error?

**Comment by lyonlai** [comment]
right, here's the example file failing.

    import Radium from 'radium';
    import React from 'react/addons';

    export default Radium(React.createClass({
      displayName: 'test',

      render: function() {
        return (
          <div></div>
        )
      }
    }));

jshint results in errors
  Bad invocation. @ line 17 char 46
    exports['default'] = (0, _radium2['default'])(_reactAddons2['default'].createClass({

**Comment by lyonlai** [comment]
my webpack config looks like the following

    webpack: { 
      devtool: 'eval', 
      module: {
        preLoaders: [
          {
            exclude: /node_modules|bower_components|vendor|public|assets/,
            loader: 'babel',
            test: /\.jsx?$/
          }
        ],
        loaders: [
          {
            test: /\.jpe?g$|\.gif$|\.png$|\.svg$|\.woff$|\.ttf$|\.wav$|\.ico$/,
            loader: 'file-loader?name=assets/[name].[ext]?[hash]'
          },
          {
            exclude: /node_modules|bower_components|vendor|public|assets/,
            loader: 'jshint-loader',
            test: /\.jsx?$/
          }
        ]
      },
    },

**Comment by jugglinmike** [comment]
Okay, it looks like you are linting code that has been transpiled from another language. The generated JavaScript contains patterns like:

```js
exports['default'] = (0, _radium2['default'])();
```

...which would be very suspicious and error-prone if written by a human. That's why JSHint generates a warning. Check out the JSHint documentation for details on how to silence this (or any other) warning: http://jshint.com/docs/

**Comment by englishextra** [comment]
```
/* (0, _show.initSections)(doSlide, doSlide.config.initIndex || 0); */
_show.initSections(doSlide, doSlide.config.initIndex || 0);
```
