### ISSUE TITLE
Warn when comparing typeof result with non-string

### ISSUE THREAD

**Issue by Slayer95** [jshint/jshint#2496]
Comparison to `undefined` is a common enough error to merit this:

```
var foo;
if (typeof foo === undefined) {
    // do stuff
    // (actually don't because bug)
}
```

An arguably less-common case is the presence of a custom variable with a similar name to `typeof` results, such as a function intended to cast input to a type. E.g:

```
function string (str) {
    if (typeof str === 'string' || typeof str === 'number') return '' + str;
    return '';
}
```

```
if (typeof bar === string) {
    // code unfortunately never executed
}
```

**Comment by jugglinmike** [comment]
This is a really small edge case, and generally it isn't a bad practice.



 but I think it could make sense as a black list on variable names

**Comment by jugglinmike** [comment]
For instance,

```js
return typeof value === type;
```

may make sense in context, so JSHint shouldn't disallow this pattern generally. But it might be safe to warn on the following

```js
typeof value === string;
typeof value === number;
typeof value === boolean;
typeof value === undefined;
typeof value === object;
typeof value === symbol; // (if ES6)
```

Although one might also argue that those aren't very good variable names!

**Comment by Slayer95** [comment]
Good points.

One doesn't need to define an ``undefined`` variable to experience bugs that could be caught by ``typeof`` validation though.

Regarding the other cases, either a customizable whitelist or a blacklist with sensible defaults sounds good to me!

**Comment by Slayer95** [comment]
Nowadays, this sort of thing is checked by well-known alternative tools.
