### ISSUE TITLE
coveralls comments no longer on PR's

### ISSUE THREAD

**Issue by lukeapage** [jshint/jshint#2498]
@jugglinmike @rwaldron @caitp did you turn off coveralls commenting on pull requests?
https://github.com/lemurheavy/coveralls-public/issues/93

I can't see the option as I'm a contributor, not an owner.

I've tried reverting the change in where coveralls is run
https://github.com/jshint/jshint/pull/2497
but that doesn't seem to make any difference.

**Comment by caitp** [comment]
coveralls is just really buggy, to be honest. I've found that this happens sometimes and the only way I've found to fix it is to disable the repo on the coveralls account and then re-add it

**Comment by lukeapage** [comment]
@jugglinmike or @caitp etc.  Please could you try what Cait suggests?

**Comment by jugglinmike** [comment]
I've tried making a few different changes to the service configuration, and while Coveralls continues to generate reports for new pull requests (as made available through its web interface), I am still unable to trigger a GitHub comment (see https://github.com/jshint/jshint/pull/2522). I've opened a support ticket with the service that references this issue; we'll see if anything comes out of that in the next few days.

**Comment by lukeapage** [comment]
If you try to view source you get this message:

"The owner of this repo needs to re-authorize with github; their OAuth credentials are no longer valid so the file cannot be pulled from the github API."

that is probably also the reason for the missing comments.

@jugglinmike @rwaldron Please can someone do this?

**Comment by lukeapage** [comment]
(see https://coveralls.io/builds/3099384/source?filename=src%2Fjshint.js)

**Comment by jugglinmike** [comment]
Thanks, Luke. I just re-authorized, but Coveralls is still silent: https://github.com/jshint/jshint/pull/2586 . They are currently in "Read-only mode", though: http://status.coveralls.io/ It's not clear what that means, exactly. There have been no builds logged in a few days, so I'm guessing that could be effecting this latest test. I'll try again tomorrow!

**Comment by lukeapage** [comment]
coveralls is back up, but it is still reporting jshint as unauthorised. this is the bot that apparantly needs to be authorised - https://github.com/coveralls

**Comment by lukeapage** [comment]
maybe this?

https://coveralls.zendesk.com/hc/en-us/articles/201342479-Quick-help-For-Common-Problems

```
I can't see the repo's token.

You need to have admin permissions on Github for the repo in order to access/regenerate its token on Coveralls.

If you do and our data is out of sync, please re-sync your repos here: https://coveralls.io/refresh
```

**Comment by jugglinmike** [comment]
[We tried debugging this last year](https://github.com/jshint/jshint/pull/2586) to no avail. I'm happy to report that after all this time, and for no apparent reason, Coveralls has returned! Here's an example from a recent pull request: https://github.com/jshint/jshint/pull/2917#issuecomment-213777334
