### ISSUE TITLE
the URL of JSHint integration for the Eclipse IDE does not work

### ISSUE THREAD

**Issue by NorthFacing** [jshint/jshint#2505]
When i try to add JSHint plugin to the Ecllpse IDE, I just got the wrong msg like below :

![image](https://cloud.githubusercontent.com/assets/5105535/8426199/79f0e65e-1f40-11e5-8cf5-735ac0dbf505.png)

So, how could I fix it ?

**Comment by nicolo-ribaudo** [comment]
You should report the bug to eclipse, this isn't a JSHint issue
