### ISSUE TITLE
Catch blocks reported as functions in JSHINT.data().functions

### ISSUE THREAD

**Issue by nicolo-ribaudo** [jshint/jshint#2510]
```js
> JSHINT("try {} catch(e) {}");
true
> JSHINT.data().functions
[ { name: '(catch)',
    param: null,
    line: 1,
    character: 15,
    last: 1,
    lastcharacter: 18,
    metrics: { complexity: 1, parameters: 0, statements: 0 } } ]
>
```

**Comment by lukeapage** [comment]
Isnt this fixed in master? I changed catch blocks to not be functions...

**Comment by nicolo-ribaudo** [comment]
> Isnt this fixed in master?

No, because catch blocks are still pushed into `functions` ([src/jshint.js line 3801](https://github.com/jshint/jshint/blob/master/src/jshint.js#L3801))

**Comment by lukeapage** [comment]
Ah thanks.  It should be trivial to remove the not needed code.
