### ISSUE TITLE
Empty destructuring gives a parse error

### ISSUE THREAD

**Issue by lukeapage** [jshint/jshint#2513]
E.g.
```
let a = ({}) => ({});
```
Maybe this should parse fine but give a warning? or it should just parse fine?

**Comment by nicolo-ribaudo** [comment]
Also using arrays:
```js
let [] = [];
```

Spec:
> ArrayAssignmentPattern<sub>[Yield]</sub> :
> &nbsp; [ Elision<sub>opt</sub> AssignmentRestElement<sub>[?Yield]opt</sub> ]

(Everything is optional)

**Comment by jugglinmike** [comment]
It should definitely parse, and I think a warning is a good idea.

**Comment by lukeapage** [comment]
I wonder if It's actually useful for ignoring params - could you use `unused: strict` and do this for unused
```
function({}, a)  {
  return a.x;
}
```

**Comment by lukeapage** [comment]
@jugglinmike re: warning, how about only warning when not in function params ? or do you think my idea for using it for unused params is crazy (I'm not sure myself!)
ha just thought of this too.. yuck...
```
function(...args) { var [,a] = args; return a.x; }
```

**Comment by jugglinmike** [comment]
@lukeapage: I thought that was an interesting use-case for destructuring assignment, but I'm having second thoughts. Doing that makes the function a little brittle:

```js
function a(_, __, final) {
  print(final);
}

function b({}, {}, final) {
  print(final);
}
```

Function `a` can be invoked with any type/number of arguments, but `b` will throw errors if invoked with non-Object values as the first or second argument. For some situations, this might be desirable, but as an implicit type check (and one that might not be immediately apparent to readers), it also seems a little more strict than typical programming patterns in JavaScript.

In light of the ambiguity, I think we're better off being conservative here and waiting for our users to decide that this is a common pattern that they want to allow.

**Comment by lukeapage** [comment]
> but b will throw errors if invoked with non-Object values as the first or second argument.

oh yes, I forgot that.. Seems my 2nd example is the only way to do it consistently without creating identifiers. Still, not like its easy to do it in any other languages I know of.
