### ISSUE TITLE
W004 bug?

### ISSUE THREAD

**Issue by laidbackclimber** [jshint/jshint#2520]
Thank you for this fantastic, indispensable tool!

The following code provokes a W004 error, which I believe is erroneous, since the second declaration is in a different scope than the first:

  function w(){}
  function x(){
    w();
    function w(){}
  }

Note that the W004 error is not triggered if the call to w() is omitted, or placed after the second declaration of w().

**Comment by lukeapage** [comment]
yep, this seems like a bug to me. It should only warn if `shadow: outer` is on.
In addition the `w` that is reported as unused is wrong - it says the last `w` function is unused, but it is the first.
All these bugs are fixed on master though and will be included in the next release, which has a new scope manager to work out variable scopings.
