### ISSUE TITLE
Support JSON output

### ISSUE THREAD

**Issue by steelbrain** [jshint/jshint#2534]
I am working on the transition of atom package `linter-jshint` to the latest API and it's really a deal breaker for me that I have to extract values via regex, `hh_client`, `coffeelint` and a lot others support JSON output and for a package written in JS, it should be fairly simple.
It would greatly cut the parsing costs of jshint.

Ref: https://github.com/AtomLinter/linter-jshint/pull/103

**Comment by jugglinmike** [comment]
JSHint supports custom reporters. Have you looked at https://github.com/sindresorhus/jshint-json ? I haven't tried it, but it sounds like it might be what you need.

**Comment by lukeapage** [comment]
How are you using jshint? Via api or cli?
Because via the api you can get the errors programmatically..

**Comment by steelbrain** [comment]
Yes Mr Luke, we can get errors programmatically when we use it as a module, but if we do the parsing and cpu intensive stuff in the main thread, we might block the experience for users, so we're using the CLI version.
Thanks @jugglinmike , gonna check it out.

**Comment by steelbrain** [comment]
@jugglinmike Your suggestion worked great for my needs.
