### ISSUE TITLE
Accept filePath when input is provided via stdin

### ISSUE THREAD

**Issue by steelbrain** [jshint/jshint#2536]
It'll help us from re-inventing the wheel everytime to provide a valid `.jshintrc` to jshint,
JsHint should accept the buffer from stdin and filePath as an arg to use it's existing file finding functions to find the files.

`less` has it, and it comes in handy when it resolves the imports.

**Comment by jugglinmike** [comment]
This sounds like a job for the `--filename` flag--would this help?

```
$ ./bin/jshint --help
Usage:
  jshint [OPTIONS] [ARGS]

Options: 
  -c, --config STRING    Custom configuration file
      --reporter STRING  Custom reporter (<PATH>|jslint|checkstyle|unix) 
      --exclude STRING   Exclude files matching the given filename pattern 
                         (same as .jshintignore) 
      --exclude-path STRINGPass in a custom jshintignore file path
      --filename STRING  Pass in a filename when using STDIN to emulate config 
                         lookup for that file name 
      --verbose          Show message codes
      --show-non-errors  Show additional data generated by jshint
  -e, --extra-ext STRING Comma-separated list of file extensions to use 
                         (default is .js) 
      --extract [STRING] Extract inline scripts contained in HTML 
                         (auto|always|never, default to never)  (Default is never)
      --jslint-reporter  Use a jslint compatible reporter (DEPRECATED, use 
                         --reporter=jslint instead) 
      --checkstyle-reporter Use a CheckStyle compatible XML reporter 
                            (DEPRECATED, use --reporter=checkstyle 
                            instead) 
  -v, --version          Display the current version
  -h, --help             Display help and usage details
```

**Comment by steelbrain** [comment]
OH MY GOD! It's embarrassing, I swear I read that several times, maybe I need to get some sleep.

**Comment by bostrom** [comment]
Perhaps I'm not getting how this ```--filename``` option is intended to be used, especially in combination with the "overrides" configuration option. Given an erroneous file and this configuration

```
{
  "undef": false,
  "overrides": {
    "src/app/**/*.js": {
      "undef": true
    }
  }
}
```
the command

```jshint --verbose src/app/main/js/main.js```

will notice the undefined variables.

but the command 

```jshint --verbose --filename src/app/main/js/main.js - < src/app/main/js/main.js```

**won't**. 

However, if I change the matching pattern to ```**/src/app/**/*.js```, then the second command will work as intended. 

Is the ```overrides``` file pattern supposed to work like this in the case of using the ```--filename``` CLI option? 

I made a simple [test repo](https://github.com/bostrom/jshint-filename-test) to showcase this possible bug.
