### ISSUE TITLE
Request option to suppress semicolon

### ISSUE THREAD

**Issue by SidNM** [jshint/jshint#255]
Hi,

I just started using JSHint and it nicely found several problems.  However, in my coding style, it seems that I place semicolons in places where it's not necessary in JavaScript (a holdover from programming in other languages where it is necessary, I suppose).

Would it be possible to add an option to suppress messages such as: "Line 190 }; Unnecessary semicolon."

Thanks.

**Comment by ohfang** [comment]
Just an option please!!
