### ISSUE TITLE
ES6 destructuring & defaults

### ISSUE THREAD

**Issue by tobireif** [jshint/jshint#2552]
If this is legal ES6 `const [a=1] = [] ` it would be great if it would be supported by JSHint.

A page where JSHint currently reports errors for similar lines:
http://tddbin.com/#?kata=es6/language/destructuring/defaults
(Also see https://github.com/tddbin/es6katas.org/issues/16 .)

**Comment by lukeapage** [comment]
duplicate of https://github.com/jshint/jshint/issues/1941 and a fix has been merged,  its awaiting a release.

**Comment by tobireif** [comment]
Great! Thanks!
