### ISSUE TITLE
"Possible strict violation" error behavior

### ISSUE THREAD

**Issue by gdorsi** [jshint/jshint#2553]
Why there jshint return a "possible strict violation" error

``` javascript
(function m(){
    this.hello = 'hello';
    function say(){ console.log(this); }
    say();
})();
```

And there no?

``` javascript
(function m(){
    this.hello = 'hello';
    var say = function(){ console.log(this); };
    say();
})();
```

**Comment by lukeapage** [comment]
possibly it could look at function expressions and also give the warning if assigned directly to a single variable (e.g. excluding `a.b =` and `a = { say: function...`).
