### ISSUE TITLE
in sublime text 3

### ISSUE THREAD

**Issue by shaunstanislaus** [jshint/jshint#2554]
<img width="1440" alt="screen shot 2015-07-15 at 18 26 21" src="https://cloud.githubusercontent.com/assets/1703530/8696479/3210753a-2b1f-11e5-9d4c-21eb5d4e1c81.png">
how do i prevent auto jshint configuration everytime i save?

No configuration found. Add a .jscsrc file to your project root or use the -c option

**Comment by shaunstanislaus** [comment]
<img width="1440" alt="screen shot 2015-07-15 at 18 26 21" src="https://cloud.githubusercontent.com/assets/1703530/8696452/05d39768-2b1f-11e5-8e38-ee7281444704.png">

**Comment by nicolo-ribaudo** [comment]
.jscsrc is for JSCS, not JSHint

**Comment by lukeapage** [comment]
and you are better off asking on a sublime forum or sublime product support.
