### ISSUE TITLE
dist/jshint.js version is 2.7.0 even though package version is 2.8.0

### ISSUE THREAD

**Issue by kevinb7** [jshint/jshint#2558]

**Comment by jugglinmike** [comment]
Thanks for the report! This was first reported in gh-2432; you'll find more info there. The good news is that only the comment is incorrect--the code itself really is version 2.8.0 of JSHint.

**Comment by kevinb7** [comment]
@jugglinmike thanks quick response.  Nice to know the code is for the right version.

**Comment by jugglinmike** [comment]
Sure thing!
