### ISSUE TITLE
Warning about the 'module' option when setting function-level flags

### ISSUE THREAD

**Issue by gustavderdrache** [jshint/jshint#2560]
This input:
```javascript
/* jshint esnext: true, module:true */

function bar() {
  /* jshint validthis:true */
  return this;
}
```
warns "The 'module' option cannot be set after any executable code." on line 4 (`validthis: true`).

**Comment by jugglinmike** [comment]
Confirmed. Thanks for the report!

**Comment by nicolo-ribaudo** [comment]
@jugglinmike I didn't see you self-assigned this and I fixed the issue... can I open a pr or you have already started resolving this issue?

**Comment by jugglinmike** [comment]
I have already started

**Comment by nicolo-ribaudo** [comment]
Ok

**Comment by lukeapage** [comment]
This has been merged and will be fixed in the next version of jshint.
