### ISSUE TITLE
Parse errors with ES6 export {} declaration

### ISSUE THREAD

**Issue by gustavderdrache** [jshint/jshint#2567]
Both of these lines cause an error about an expected identifier, but [the grammar](http://www.ecma-international.org/ecma-262/6.0/#sec-exports) indicates they should be allowed:

```
/* jshint esnext:true */

export {};
export {x,};
```

**Comment by nicolo-ribaudo** [comment]
I think JSHint should warn on line 3: it is valid, but it is probably a mistake.

**Comment by lukeapage** [comment]
I think you could argue that both are possibly mistakes.. the 2nd case could be covered by `elision` but then possibly so should
```
/* jshint elision: false */
var [a,] = [a];
var {x,} = a;
```
neither of which give warnings.

**Comment by lukeapage** [comment]
> you could argue that both are possibly mistakes.

(but to clarify they shouldn't *error*, they should possibly *warn*)

**Comment by nicolo-ribaudo** [comment]
> the 2nd case could be covered by elision but then possibly so should

JSHint doesn't warn about trailing commas, as they are ignored. I think this is more JSCS territory.

```js
var a = [ 1, ]; // No warnings
var b = [ 1, , 2]; // Empty array elements require elision=true.
```

**Comment by lukeapage** [comment]
> JSHint doesn't warn about trailing commas, as they are ignored. I think this is more JSCS territory.

You're right, it didn't occur to me it could be a style choice.

I agree on a warning for line 3.

**Comment by gustavderdrache** [comment]
It'd probably be good to warn on the equivalent import statement, too:
```javascript
import {} from 'module';
```

It's more likely that the user messed up since there's the syntax `import "module"` for including a module only for its side-effects.

**Comment by lukeapage** [comment]
@gustavderdrache, @nicolo-ribaudo already did this on the  pr ;) but its a breaking change so likely one for v3
