### ISSUE TITLE
`singleGroups` forbids grouping unary operations

### ISSUE THREAD

**Issue by jugglinmike** [jshint/jshint#2570]
The binding power of unary operations is not considered when `singleGroups` is enabled. For example, the grouping operator in the following expression has a substantive effect on the expression, but JSHint considers is unnecessary:

```js
(-3).toString();
```

**Comment by jugglinmike** [comment]
Patch incoming!

**Comment by lukeapage** [comment]
A fix for this has been merged and will be in the next release after the current 2.8.0
