### ISSUE TITLE
JSHint aborted due to warnings. Why?

### ISSUE THREAD

**Issue by rclaes1995** [jshint/jshint#2580]
![image](https://cloud.githubusercontent.com/assets/11699918/8872479/a8ef7342-31fd-11e5-9af6-190a38cdea0a.png)

Hi! I'm trying Grunt for the first time. Installed JSHINT and running it but it keeps aborting no matter what. I've tried several files; not limiting to Gruntfile.js, but still the same issue.

This is my config:

    jshint: {
        options: {
            curly: true,
            immed: true,
            latedef: true,
            newcap: true,
            noarg: true,
            sub: true,
            undef: true,
            boss: true,
            eqnull: true,
            browser: true
        },
        all: ['Gruntfile.js']
    }

**Comment by jugglinmike** [comment]
You have enabled the `undef` option, so JSHint is warning you about the reference to an undefined variable `module` on the first line of your script. You can resolve this in a few ways:

1. disable the `undef` option
2. enable the `node` option
3. declare `module` in the `globals` configuraton

Also, given that your script is intended to run in Node.js, it probably isn't necessary to enable the `browser` option. Be sure to check out http://jshint.com for documentation about configuring JSHint for your project.
