### ISSUE TITLE
Add other fetch globals: Response, Request, Headers

### ISSUE THREAD

**Issue by TheSavior** [jshint/jshint#2582]
With the introduction of `fetch`, [`Response`](https://developer.mozilla.org/en-US/docs/Web/API/Response), [`Request`](https://developer.mozilla.org/en-US/docs/Web/API/Request), and [`Headers`](https://developer.mozilla.org/en-US/docs/Web/API/Headers) are now globals in the browser.

**Comment by xieranmaya** [comment]
+1

**Comment by surfjedi** [comment]
+1

**Comment by jugglinmike** [comment]
Hi folks: GitHub.com's web interface allows you to signal your support of an
issue through a feature called "reactions." If you don't have anything
substantive to add to a conversation but would like to help raise awareness on
a given issue, please use that feature. Thanks!
