### ISSUE TITLE
Performance regression

### ISSUE THREAD

**Issue by SirZach** [jshint/jshint#2594]
After much time, I've narrowed down to a commit https://github.com/jshint/jshint/commit/813d97a8f5d96f2ab8320ad5da63662195f79d6c that has caused JSHINT to take ~30 seconds longer to complete. I can consistently produce faster JSHINT times by going back one commit to https://github.com/jshint/jshint/commit/8a231e29422deddd8aef5e9bd65632a9bebf4528, the commit right before the culprit was merged in.

TBH, I'm not familiar with the JSHINT codebase and don't fully understand what the culprit commit is doing but based on the commit message, that commit was supposed to improve performance.

Please let me know if there's anything I can do. Thanks!

**Comment by nicolo-ribaudo** [comment]
Maybe this is a duplicate of #2532? (And fixed by #2538)

**Comment by SirZach** [comment]
This does appear to be a duplicate and will close it as such. Thanks!
