### ISSUE TITLE
using undefined `self` variable shows no warning.

### ISSUE THREAD

**Issue by StyMaar** [jshint/jshint#2600]
In strict mode 
```
function bar(){
    foo.bar();
}
```
shows a warning because foo isn't defined. But 

```
function bar(){
    self.bar();
}
```
doesn't show anything even though self is never defined anywhere.
Is that on purpose ?

**Comment by lukeapage** [comment]
You are probably defining self as a global e.g. when you have `worker: true`
Try it: http://jshint.com/
```
// jshint worker:true
function bar(){
    self.bar();
}
```

**Comment by StyMaar** [comment]
Dammit you're right. Thanks for the insanely quick answer !
