### ISSUE TITLE
Experimental support for exponentiation operator

### ISSUE THREAD

**Issue by jugglinmike** [jshint/jshint#2602]
Proposal: https://github.com/rwaldron/exponentiation-operator

Is now at stage 3: https://github.com/tc39/ecma262

Depends on gh-2601

**Comment by nicolo-ribaudo** [comment]
The `**` operator is in the es2016 draft (https://tc39.github.io/ecma262/#sec-exp-operator). Should it be implemented under `esversion: 7/2016`?

**Comment by nicolo-ribaudo** [comment]
This is now a standard: does anyone wants to implement this or can I do it?

**Comment by jugglinmike** [comment]
I'm on it. We just need to get a patch release out before we can accept new features in `master`.

**Comment by sok0** [comment]
Will this be included in a patch anytime soon? Asking with respect but issue is still open after quite a long time.

**Comment by jugglinmike** [comment]
Good news, @sok0: we implemented support for the exponentiation operator in gh-3060 and [released it in JSHint version 2.10.0](https://jshint.com/blog/2019-02-05/release-2-10-0/). If you're using that version or later, you can enable it by setting the `esversion` option to `7` (or later). This issue's "open" status is a error of omission on my part. Rectifying that now.
