### ISSUE TITLE
Who's behind JSHint?

### ISSUE THREAD

**Issue by dandv** [jshint/jshint#2605]
The bottom of http://jshint.com/about/ only mentions  Anton Kovalyov / @valueof.

[The README mentions](https://github.com/jshint/jshint#the-jshint-team) a completely different set of contributors.

**Comment by lukeapage** [comment]
at the moment, a few people - https://github.com/orgs/jshint/people
some come and go, see the github activity for the most up-to-date view

**Comment by dandv** [comment]
Thanks @lukeapage. I'll let you guys update the README since you know best who should be credited.

**Comment by jugglinmike** [comment]
[The project's `README.md` file has been updated](https://github.com/jshint/jshint/commit/f5012931eb40a7e5e30c6f32ed3094847e5f0561), and http://jshint.com/about is [now generated from that file](https://github.com/jshint/jshint.github.io/commit/fce4c46172922ae97d8e3efcec8d46919aae3d30).
