### ISSUE TITLE
Bad invocation on ES6 import method

### ISSUE THREAD

**Issue by alicoding** [jshint/jshint#2616]
I'm getting Bad invocation warning on this

```
import analytics from '../public/js/analytics.js';

module.exports = React.createClass({
  mixins: [IntlMixin],
  componentDidMount: function() {
    analytics(); // line 12 is here
  },
...
...
```

```
pages/thank-you.jsx: line 12, col 42, Bad invocation.
```

I'm not sure why is this not okay when using `import` but doing it like the old way using `var` then it's fine.

**Comment by lukeapage** [comment]
Are you sure it isn't something else in the file- it has a jsx extension which jshint doesn't support...

If I try this on jshint.com...

```
/* jshint esnext: true */
import analytics from '../public/js/analytics.js';

module.exports = React.createClass({
  mixins: [IntlMixin],
  componentDidMount: function() {
    analytics(); // line 12 is here
  }
});
```

I don't get any errors.

**Comment by alicoding** [comment]
I'm using jsxhint which I believe it's a wrapper around JSHint and I just tried the same on the online tools and I don't get the error as well. I guess this could be JSXHint using an older version or something that cause this bug to occur since my file doesn't have anything else in it and I still get that same error.

**Comment by lukeapage** [comment]
okay please raise with `jsxhint` and feel free to report something back here if there is a jshint issue.
