### ISSUE TITLE
jshint reporting a different number of errors on Linux and OS X for identical project

### ISSUE THREAD

**Issue by philipobrien** [jshint/jshint#2624]
As the title says I have a meteor project that I want to lint. I have cloned the project to my mac and when I run `jshint .` from the root directory of the project I get `160 errors` reported. 

When I clone the identical project to my build server running on Ubuntu 14.04 and again, run `jshint .` from the root directory, this time I get `21 errors` reported. Any ideas what is causing this discrepancy?

I have verified that I'm running the same versions of node.

**Comment by nicolo-ribaudo** [comment]
Do you have any `.jshintrc` in a folder ancestor of your project root?

**Comment by philipobrien** [comment]
Sorry, my bad. I was sure I had committed my `.jshintrc` file but I hadn't. I didn't notice it's absence because another `.jshintrc` was being detected.

**Comment by philipobrien** [comment]
OK, there is something funky going on. I just navigated to the actual Jenkins workspace directory on my build server, and ran `jshint .` myself from the root directory and now it's reporting 262 violations.

**Comment by philipobrien** [comment]
Turns out an issue with my build server, not jshint. For some reason even though the repo in Git had a directory removed, it was being left behind on my build server even after a fresh `git pull`. This was a source of extra violations which caused the variance.
