### ISSUE TITLE
var inside for loop with varstmt=true

### ISSUE THREAD

**Issue by g-ortuno** [jshint/jshint#2627]
I set `varstmt` to true, but when I have some code like this:
```javascript
for (var test in [1,2,3,4]) {
  // code here
}
```
JsHint doesn't warm about the use of `var`

**Comment by lukeapage** [comment]
confirmed
```
// jshint varstmt: true

for (var test in [1,2,3,4]) {
  // code here
}
```

**Comment by lukeapage** [comment]
and still a problem on master

**Comment by g-ortuno** [comment]
Huzzah! I'm not familiar with JSHint's release process. Does this get merged into some sort of `stable` branch or do we have to wait until the next release?
