### ISSUE TITLE
Possible latedef regression

### ISSUE THREAD

**Issue by jugglinmike** [jshint/jshint#2628]
@lukeapage The following code issues a warning on `master` (but not v2.8.0):

```js
// jshint latedef: true
var a = function() { return a; };
```

Although we can't statically differentiate patterns like that from patterns like

```js
// jshint latedef: true
var a = function() { return a; }();
```

I think we need to be lax in this case (e.g. forgive all references in the right-hand side of binding statements). Patterns like this are actually fairly common (I discovered it while running the `master` branch against a co-worker's code base):

```js
var myModule = {
  method1: function() { /* etc. */ },
  method2: function() { myModule.method1(); }
};
```

If included in a minor release, this change in application of `latedef` would likely cause trouble for our consumers. I think we ought to be conservative in this case: continue to allow references to the identifier being initialized within the right hand side of a binding. For example:

```js
// jshint latedef: true
void a; // warning
var a;
var b;
void b; // accepted
var c = c; // accepted
```

What do you think?

**Comment by lukeapage** [comment]
I agree it is a common problem that needs a fix.

The easy fix is just to move the binding in the var statement before running through the value. A better fix would be to add it with a flag that it is as yet undeclared for use in this function e.g.

```
var c = c; // warning
var d = function() { d; }; // accepted
```

which would make it match `let` and `const` behaviour (though in that case its an error in the case `c` above). I *might* have time later tonight to look at it, but I may not... maybe better go to the quick fix for this release.

**Comment by jugglinmike** [comment]
I'm also a bit strapped for time. If/when you are able to get to this, self-assign this issue (I'll do the same).

I know we talked about releasing soon, but I'm happy to wait as long as it takes, so don't feel pressured!

**Comment by nicolo-ribaudo** [comment]
The regression was introduced in 6d2cc19
