### ISSUE TITLE
Reported Global JS Variable not Global

### ISSUE THREAD

**Issue by donatj** [jshint/jshint#2634]
The variable is defined on line 29, so it's not bleeding to global. "use strict"; is fine w/ it.

see https://scrutinizer-ci.com/g/capdig/myon/issues/dev/files/public/js/app/packages/Admin/UserData.js?selectedLabels%5B0%5D=3&orderField=path&order=asc&issueId=fb41805a-d0da-4b69-a0ac-0993696e782a

**Comment by jugglinmike** [comment]
I've having trouble accessing that document. Would you mind including the example code in this bug report directly?

**Comment by donatj** [comment]
Is this enough? It's a private repo and I didn't realize this wasn't part of scrutinizer - it bumped me here to report the bug.

<img width="801" alt="screen shot 2015-08-23 at 14 44 38" src="https://cloud.githubusercontent.com/assets/133747/9429902/c66efa22-49a5-11e5-88d8-20aeffb2599a.png">

**Comment by jugglinmike** [comment]
Thanks! This looks like a bug that we resolved in version 2.5.7 (see commit b55b3e1b0ec2425d5aedf9e67b3a28c0290e2b65). Are you running an earlier version of JSHint?

**Comment by lukeapage** [comment]
Hi @donatj,

I'm closing this after not getting a response, we will re-open if you are getting this in the latest version.

**Comment by donatj** [comment]
I don't know how to check what version scrutinizer is using, and its not in an area of the code I'm actively working on so closing this is fine.
