### ISSUE TITLE
Possible Performance Regression

### ISSUE THREAD

**Issue by jugglinmike** [jshint/jshint#2635]
It looks as though a recent change in `master` has significantly decreased the
performance of JSHint in some cases:

```
[mike@bruce jshint]((detached from d09a219))$ git checkout ae4896670a46247ef59df9d3ea9cf3814c864559
Previous HEAD position was d09a219... [[TEST]] Automate browser build testing
HEAD is now at ae48966... [[FIX]] Allow object destructuring assignment
[mike@bruce jshint]((detached from ae48966))$ time ./bin/jshint tests/regression/libs/jquery-1.7.js  > /dev/null

real  0m1.628s
user  0m1.765s
sys 0m0.047s
[mike@bruce jshint]((detached from ae48966))$ time ./bin/jshint tests/regression/libs/jquery-1.7.js  > /dev/null

real  0m1.600s
user  0m1.749s
sys 0m0.041s
[mike@bruce jshint]((detached from ae48966))$ time ./bin/jshint tests/regression/libs/jquery-1.7.js  > /dev/null

real  0m1.678s
user  0m1.833s
sys 0m0.040s
[mike@bruce jshint]((detached from ae48966))$ time ./bin/jshint tests/regression/libs/jquery-1.7.js  > /dev/null

real  0m1.630s
user  0m1.781s
sys 0m0.027s
[mike@bruce jshint]((detached from ae48966))$ git checkout ae4896670a46247ef59df9d3ea9cf3814c864559~
Previous HEAD position was ae48966... [[FIX]] Allow object destructuring assignment
HEAD is now at d09a219... [[TEST]] Automate browser build testing
[mike@bruce jshint]((detached from d09a219))$ time ./bin/jshint tests/regression/libs/jquery-1.7.js  > /dev/null

real  0m1.180s
user  0m1.303s
sys 0m0.053s
[mike@bruce jshint]((detached from d09a219))$ time ./bin/jshint tests/regression/libs/jquery-1.7.js  > /dev/null

real  0m1.287s
user  0m1.474s
sys 0m0.037s
[mike@bruce jshint]((detached from d09a219))$ time ./bin/jshint tests/regression/libs/jquery-1.7.js  > /dev/null

real  0m1.207s
user  0m1.346s
sys 0m0.044s
[mike@bruce jshint]((detached from d09a219))$ time ./bin/jshint tests/regression/libs/jquery-1.7.js  > /dev/null

real  0m1.226s
user  0m1.365s
sys 0m0.051s
```

This small sample size is for instructive purposes only; my testing has been
a little more thorough and indicates a significant difference in performance
while linting jQuery 1.7.

That said, I'm not seeing anything similar for the other library code we
include. On the one hand, I'm inclined to write this off as non-important, but
on the other, the jQuery source is not ES6 code, so the change really ought not
to have effected performance there.

@rwaldron @lukeapage Do you have any thoughts about this?

Performance is not something we normally test for, so I don't mean to surprise
you with brand new acceptance criteria (especially not after approving the
patch almost a month ago). Still, we should try to avoid regressions when we
can identify them and if we do consider them unwarrented. I've been working on
an automated procedure as part of my work reviewing gh-2413 and gh-2538. I just
happened to stumble across this while doing so.

**Comment by lukeapage** [comment]
I remember thinking about a performance regression during the object destructuring assignment work..  and that it was unavoidable without significant extra complexity. 

though if we are prepared to throw parse error on es6 if you do not have the es6 flag rather than detect es6 and give a nice error, it could be faster. 

I think a nice error is better than a small sacrifice in speed. 

of course i may have missed a potential performance improvement,  but i did look for one.

**Comment by jugglinmike** [comment]
Unlike behavioral regressions, there is a fair amount of subjectivity in deciding what makes something a performance regression. As you've pointed out, some tasks are simply computationally expensive, so there are certainly cases where slower operation is to be expected. I trust your judgment on this; if it comes to be a problem in the future, we can always optimize at that time.
