### ISSUE TITLE
Where did the 'boss' option get its name?

### ISSUE THREAD

**Issue by dsernst** [jshint/jshint#2638]
It's hard to remember what this one does. Why is it named "boss"?

> This option suppresses warnings about the use of assignments in cases where comparisons are expected. More often than not, code like `if (a = 10) {}` is a typo. However, it can be useful in cases like this one:
> 
> `for (var i = 0, person; person = people[i]; i++) {}`
You can silence this error on a per-use basis by surrounding the assignment with parenthesis, such as:
> 
> `for (var i = 0, person; (person = people[i]); i++) {}`

**Comment by jugglinmike** [comment]
A quick search through the project's history has your answer; see commit 08943a907b2ad326881ae84592590fff12652794:


```diff
commit 08943a907b2ad326881ae84592590fff12652794
Author: Anton Kovalyov <anton@kovalyov.net>
Date:   Sun Jan 23 22:34:14 2011 -0800

    Added an option to use assigments in the control statements like a boss

diff --git a/jshint.js b/jshint.js
index b18afe4..30ddc6f 100755
--- a/jshint.js
+++ b/jshint.js
@@ -317,6 +317,7 @@ var JSHINT = (function () {
         boolOptions = {
             adsafe     : true, // if ADsafe should be enforced
             bitwise    : true, // if bitwise operators should not be allowed
+            boss       : true, // if assignments inside if/for/while/do should 
             browser    : true, // if the standard browser globals should be pre
             cap        : true, // if upper case HTML should be allowed
             css        : true, // if CSS workarounds should be tolerated
```

**Comment by dsernst** [comment]
Ah. Thank you! :smile:
