### ISSUE TITLE
Remove preferGlobal

### ISSUE THREAD

**Issue by monolithed** [jshint/jshint#2642]
```
➜ npm install
npm WARN prefer global jshint@2.8.0 should be installed with -g

├─┬ grunt-contrib-jshint@0.11.2
│ └─┬ jshint@2.8.0
```

Could you remove [`"preferGlobal": true`](https://github.com/jshint/jshint/blob/master/package.json#L74)?
It's no any sense and bad practice as well.

**Comment by lukeapage** [comment]
actually I'm not sure it should be an issue with a modern version of npm - https://github.com/npm/npm/issues/1648

**Comment by lukeapage** [comment]
yep this doesn't happen in npm v3 and from the linked issue it shouldn't happen with a later v2 either.

```
$ npm i grunt-contrib-jshint
npmtest@1.0.0 c:\git\npmtest
└── grunt-contrib-jshint@0.11.3  extraneous

npm WARN EPEERINVALID grunt-contrib-jshint@0.11.3 requires a peer of grunt@>=0.4.0 but none was installed.
npm WARN EPACKAGEJSON npmtest@1.0.0 No description
npm WARN EPACKAGEJSON npmtest@1.0.0 No repository field.
```

**Comment by asselin** [comment]
@lukeapage This issue is still happening in current npm.  See for example https://github.com/npm/npm/issues/8517 and https://github.com/npm/npm/issues/11652.

An easy way to repro is `npm i swagger-js-codegen`, which includes jshint as a dependency.

Would you merge a PR that removes preferGlobal?
