### ISSUE TITLE
Return statement on two lines

### ISSUE THREAD

**Issue by tforgione** [jshint/jshint#2644]
Hi everyone,

I don't know if it's wanted or not, but when you do something like

``` js
function main() {
  return  
  	'Hello, World!';
}

main();
```

there are two warnings : 	
  - Missing semicolon.
  - Expected an assignment or function call and instead saw an expression.

Is this a wanted behavior ?

**Comment by caitp** [comment]
It is hard to word this error more clearly, but this particular asi warning should inform the user that the expression on the second line is dead code, which is not what the caller wants

**Comment by tforgione** [comment]
Ok,

in fact, I'm just bad at javascript, sorry for the useless issue... I thought that it actually returned the value on the next line...

In fact, the message is really clear, the `return` instruction is missing its semicolon, and the next line is a unused expression.

Thanks for the fast response !
