### ISSUE TITLE
Browser crashes when selecting a jQuery element that uses yuilibrary

### ISSUE THREAD

**Issue by davidorr-optly** [jshint/jshint#2653]
I have an issue that occurs when an open parem is introduced to a series of classes created by Yui js/css framework. Here is an example:

$('.name-view, small, .progress')

When an ( is introduced midway such as here:

$('.name-view, ( small, .progress')

The browser would crash. 

This happens even if the line of code is commented out. 

For context, here is the URL for the JS library: yuilibrary.com/

**Comment by lukeapage** [comment]
Hi @davidorr-optly,

I may have misunderstood, but it looks like you meant to raise this with the yui-library team? This is the repo for jshint.

**Comment by davidorr-optly** [comment]
Hi Lukeapage,

The issue is related with JSHint causing browsers to crash when YUI selectors are used. Have you ever had any instances where specific selectors would cause a browser to freeze? 

David

**Comment by lukeapage** [comment]
Hi, 

Can you be more specific? why/how are you running jshint in the browser? what kind of crash? what browsers?

**Comment by davidorr-optly** [comment]
Hi Luke,

This is happening on Chrome on a Mac. The program the client is using is Optimizely. Optimizely is using jshint as a validator. The site in question is https://www.ixl.com/membership/family/subscribe/ 

The browser freezes whenever a parenthesis or any other character is inserted between the following code:

$(' .name-view, small, .crisp-button, .secure-server, .summary-section');

This may not be an issue with JSHint. What I am trying to understand is if JSHint is the cause of the browser crashing.

**Comment by lukeapage** [comment]
the page you linked to does not allow adding javascript code.. jshint is a static analyser, you run it on javascript before deploying to verify it is valid and meets certain quality rules. I doubt jshint is included in that page and I very much doubt it is the cause of your issue. It sounds like a YUI issue.
