### ISSUE TITLE
[Regression] Function scope of "use strict" is now required even in node mode

### ISSUE THREAD

**Issue by mzgol** [jshint/jshint#2657]
As of JSHint 2.9.0 function scope of `"use strict"` is now required even in `node` mode. This is breaking current jQuery `master` build so it's pretty blocking for us.

**Comment by TuckerWhitehouse** [comment]
+1

**Comment by ice2morrow** [comment]
+1. Breaking change

**Comment by andyk1989** [comment]
+1

**Comment by andyk1989** [comment]
Looks like https://github.com/jshint/jshint/blob/9e33d37739ddcb8021d15a2c8a70b2ee7df30e88/src/jshint.js#L5290 is the culprit

It is no longer checking for `state.option.node` and other values as it was in v2.8.0 https://github.com/jshint/jshint/blob/2.8.0/src/jshint.js#L5377

**Comment by andrespr** [comment]
+1

**Comment by tran2** [comment]
+1

**Comment by nightpool** [comment]
+1

**Comment by ice2morrow** [comment]
Is there any updates on this?

**Comment by lukeapage** [comment]
@ice2morrow the linked pr is under review
