### ISSUE TITLE
lack of "use strict" directive doesn't always warn

### ISSUE THREAD

**Issue by lukeapage** [jshint/jshint#2668]
This code:
```
// jshint strict: true, globalstrict: true
a = 1;
```
(or its 2.9.x + equivalent)
```
// jshint strict: global
a = 1;
```
both do not warn about missing a `"use strict"` directive.

I'm guessing only very short code files suffer this problem (or this would be a big problem) but it requires investigation.

Found during investigation of #2663

**Comment by nicolo-ribaudo** [comment]
Another test case:
```js
// jshint strict: global
a + b;
```

**Comment by nicolo-ribaudo** [comment]
JSHint doesn't warn if the statement is a function or a punctuator (`a = 2` is `=`, so JSHint doesn't warn, while `var a = 2` is `var`, so JSHint warns)
