### ISSUE TITLE
When is 2.9.0 due to be published to npm?

### ISSUE THREAD

**Issue by johnnyreilly** [jshint/jshint#2670]
I notice there's a number of issues tagged as regressions - are you holding off publishing until these issues are resolved?

**Comment by jugglinmike** [comment]
Version 2.9.0 of JSHint has been released and revoked. You can expect a release candidate for 2.9.1 as soon as we've resolved the known regressions.

**Comment by johnnyreilly** [comment]
Thanks @jugglinmike

**Comment by ahumphreys87** [comment]
@jugglinmike any idea when 2.9.1 will be ready?
