### ISSUE TITLE
Major Performance Drop

### ISSUE THREAD

**Issue by NicBright** [jshint/jshint#2671]
Hi there,

I've just noticed a performance drop after upgrading jshint.
I could narrow down the drop after a little downgrade session. It must have been introduced from 2.6.0 to 2.6.1:
https://github.com/jshint/jshint/compare/2.6.0...2.6.1

The drop is about factor 3-4 (previously 12s compared to 40s now).
I've done a quick V8 profiling but am unable to draw conclusions from it as I don't know the jshint code:

![jshint-performance-issue](https://cloud.githubusercontent.com/assets/1225659/9735648/78bbf08e-563c-11e5-8b29-adfaf2aecd30.PNG)

The version used for profiling this is 2.8.0.

I do not expect any immediate actions (or actions at all). I just wanted to let you know that some changes have had a very negative impact on performance ...

Otherwise. Great work. Keep it up! :-)

Regards,
Nicolas

**Comment by jugglinmike** [comment]
Thanks for the report! We recently merged a very coarse-grained performance optimization to `master`. Would you be able to run your test against `master`? We're currently resolving some regressions, so there may be unexpected errors, but I'm curious if this is still an issue.

**Comment by lukeapage** [comment]
The fixed problem was much worse in large files..  are you linting one
large file or lots of small ones?

**Comment by NicBright** [comment]
Thanks for the very quick reply. Now my response looks quite late in contrast ;)

@jugglinmike Wow, perfect! It's even about 10% faster than with 2.6.0 :-) No unexpected errors by the way. Super duper!

@lukeapage in my case it is lots of small files

Regards,
Nicolas

**Comment by lukeapage** [comment]
Great news, thanks.
