### ISSUE TITLE
Have a javascript obj, {a:1,} don't warning or error

### ISSUE THREAD

**Issue by 3Q-** [jshint/jshint#2675]

**Comment by nicolo-ribaudo** [comment]
Can you provide some code to reproduce the issue, the errors/warnings you get and the errors/warning you expect to get?

**Comment by lukeapage** [comment]
Heres some info:
http://www.2ality.com/2013/07/trailing-commas.html

If you try this: (notice es3 option is on rather than default es5)
```
// jshint es3: true
var a = {a:1,};
```
You get a warning `Extra comma. (it breaks older versions of IE)`
