### ISSUE TITLE
TypeError when running on Windows command line with node.exe

### ISSUE THREAD

**Issue by AlbertWiersch** [jshint/jshint#2676]
I'm not sure why I'm getting a TypeError when I try to use JSHint in this manner. Can anyone assist? I'd really like to switch to using JSHint instead of JSLint in my application but won't be able to if I can't get it working.

A simple test ZIP can be downloaded from here (extract to a folder and try running the command): https://www.htmlvalidator.com/test/JSHintTypeError.zip

This command:
node.exe wrapper.js test.js

Results in:
evalmachine.<anonymous>:2198
    var arrayProto = Array.prototype,
                          ^

TypeError: Cannot read property 'prototype' of undefined
    at runInContext (evalmachine.<anonymous>:2198:27)
    at Object.<anonymous> (evalmachine.<anonymous>:13621:11)
    at Object.<anonymous> (evalmachine.<anonymous>:13652:3)
    at Object.require.12 (evalmachine.<anonymous>:13654:4)
    at s (evalmachine.<anonymous>:6:262)
    at evalmachine.<anonymous>:6:313
    at Object.require.jshint../lex.js (evalmachine.<anonymous>:18694:20)
    at s (evalmachine.<anonymous>:6:262)
    at evalmachine.<anonymous>:24088:10
    at evalmachine.<anonymous>:24090:2

**Comment by nicolo-ribaudo** [comment]
If you pass `global` to the context you create in the `doLint` function, everything works:
```js
var doLint = function(filepath) {
	var src = fs.readFileSync(filepath, "utf-8");
	var sandbox = {
		SRC: src,
		OPTS: opts,
		global: global // <---
	};
	var code = LINT.root + "(SRC, OPTS); var data = " + LINT.root + ".data();";
	vm.runInNewContext(jslint + "\n" + code, sandbox);
	// ...
```

```
$ node wrapper.js test.js
test.js:3:9:Expected an identifier and instead saw '='.
test.js:3:10:Unrecoverable syntax error. (25% scanned).
```

**Comment by AlbertWiersch** [comment]
Thank you! It looks like that did the trick and I will be checking it out more today.
