### ISSUE TITLE
require object keys to be in alphabetical order

### ISSUE THREAD

**Issue by charlierudolph** [jshint/jshint#2682]
Keeping things in alphabetical order just makes things easier to find. 
```js
{a: 1, b: 2} // good
{b: 2, a: 1} // bad
```
Possible configuration: minimum number of keys before the rule is enforced

**Comment by caitp** [comment]
Seems like a style issue. Maybe more appropriate for jscs? See what others think though

**Comment by jugglinmike** [comment]
@caitp I agree. I can't think of any hazard resulting from ad-hoc key ordering. For lengthy object initializers, it might increase the chances of duplicate keys (which is definitely hazardous), but JSHint already warns about that.

**Comment by jugglinmike** [comment]
And it's already a feature there :) http://jscs.info/rule/validateOrderInObjectKeys

**Comment by charlierudolph** [comment]
Cool. Thanks for the feedback
