### ISSUE TITLE
release 2.9.0 on npmjs.com

### ISSUE THREAD

**Issue by nikolas** [jshint/jshint#2689]
The latest version of jshint here is 2.8.0: https://www.npmjs.com/package/jshint

even though 2.9.0 is available here: https://github.com/jshint/jshint/releases

**Comment by nicolo-ribaudo** [comment]
> JSHint 2.9.0 unpublished due to regressions.

(https://twitter.com/JSHint/status/639564453852356608)

**Comment by nikolas** [comment]
woops, should have seen #2670
