### ISSUE TITLE
How to handle ES6 alongside ES5 (Promises)

### ISSUE THREAD

**Issue by m90** [jshint/jshint#2694]
I'm trying to lint a codebase that contains ES6 (on the server) as well as ES5 (on the client).

I'm running into problems as ES6 will ship Promises by default but ES5 won't.

So in my `.jshintrc` things look like:
```json
{
....
"predef":  ["-Promise"],
"esnext": "true"
....
}
```
Of course this will now give me `'Promise' is not defined.` when using it in an `.es6` file. So I was thinking of doing:

```es6
/* global Promise: true  */
var foo = Promise.resolve('Yes, please!');
```
which will still give me the `not defined` error alongside something I do not really understand:

```
routes/foo.es6: line 2, col 10, 'Promise' is not defined.
routes/foo.es6: line 1, col 1, 'Promise' is defined but never used.
```

Am I doing something wrong? Is there a way to handle this properly? Is this a bug?

**Comment by nicolo-ribaudo** [comment]
Does this work?

```
.jshintrc <-- Common rules
server/
  .jshintrc
  index.es6
client/
  .jshintrc
  index.js
```

`server/.jshintrc`
```js
{
  "extends": "../.jshintrc", // This file should inherit rules from the .jshintrc file at the root of your project

  "esnext": true
  // Other server-specific rules
}
```

`client/.jshintrc`
```js
{
  "extends": "../.jshintrc",
  
  // Other client-specific rules
}
```

And then you run `jshint server && jshint client`

**Comment by m90** [comment]
Extending a base rc file works, yes. Yet I am still puzzled by the "is undefined but never used" combo. Is there a one-rc-fits-all way to do this?

Thanks in any case.

**Comment by nicolo-ribaudo** [comment]
You could write //jshint esnext: true in every es6 file (and not in the rc file) instead of disabling an re-enabling promises.

**Comment by m90** [comment]
But is `Promise` really related to the `esnext` option?  In ES5 I will get `Redefinition of Promise` when doing

```
var Promise = require('promise');
```

since 2.5, see: https://github.com/jshint/jshint/issues/1747

**Comment by nicolo-ribaudo** [comment]
> But is Promise really related to the esnext option?

Yes: Promises are defined in ES6 (`esnext`, `esversion: 6` since next JSHint release), so JSHint considers `Promise` a predefined varables only if you are linting ES6 code

> In ES5 I will get `Redefinition of Promise` when doing
```js
var Promise = require('promise');
```

I don't:
```js
// .jshintrc
{
  // JSHint lintes code as ES5 by default
  "node": true
}
```
```js
// demo.js
var Promise = require("promise");

new Promise();
```
```
nicol@DESKTOP-EDGLMME MINGW64 ~/Documents/jshint ((2.8.0))
$ bin/jshint --version
jshint v2.8.0

nicol@DESKTOP-EDGLMME MINGW64 ~/Documents/jshint ((2.8.0))
$ bin/jshint demo.js
                              <-- No errors!
```

**Comment by m90** [comment]
You're totally right, I encountered the ES5 thing sth around last December and sticked to it since then, yet it looks like: https://github.com/jshint/jshint/commit/da52aa096a1a5c3c40e731c9bcceb038e410deeb changed this back to what you are describing.

Thanks for the help & thanks for maintaining jshint.

**Comment by therightstuff** [comment]
I just found myself struggling with this, what I needed to do was set "esversion" property in .jshintrc to 6 ( http://jshint.com/docs/options/ )
