### ISSUE TITLE
Configuration file with `eqeqeq:"false"` does not work

### ISSUE THREAD

**Issue by jeff1evesque** [jshint/jshint#2697]
The following [doesn't work](https://travis-ci.org/jeff1evesque/machine-learning/builds/82717412#L1124-L1256) in my [`jshint.json`](https://github.com/jeff1evesque/machine-learning/blob/e7a04e081a383ad69f937a31fb81087d8cec7421/test/config/jshint.json):

```
eqeqeq:"false"
```

But, the following [works](https://travis-ci.org/jeff1evesque/machine-learning/builds/82720439#L1125-L1222) in my [`jshint.json`](https://github.com/jeff1evesque/machine-learning/blob/d52131efd3351dbf83fff4fdd7e5b60a4ce21b36/test/config/jshint.json):

```
"-W041": false
```

**Comment by nicolo-ribaudo** [comment]
JSHint always warns against `==` when comparing with a falsy value (`0`, `""`, `undefined`, `null`), `true` and `false`.
You can disable warnings about `smething == null` using `eqnull: true`

**Comment by jeff1evesque** [comment]
Is `eqeqeq:"false"` intended to be valid syntax in a *jshint* configuration file, such as the one I attempted to  implement, or `~/.jshintrc`?

**Comment by nicolo-ribaudo** [comment]
Quotes should be around `eqeqeq`, not around `false`: `"eqeqeq": false`.

**Comment by jeff1evesque** [comment]
I implemented the [suggested changes](https://github.com/jeff1evesque/machine-learning/commit/11b7d23215bf5aeee2f49b0305b113ff1b242361#diff-f657c18fb51b7ca42475ece63e7ddfd4R11).  However, my travis CI indicates that it was [not recognized](https://travis-ci.org/jeff1evesque/machine-learning/builds/82804186#L1125-L1256).  Should I revert back to `"-W041": false`?

**Comment by nicolo-ribaudo** [comment]
I apologize if I was not clear.

> JSHint always warns against ...

always = even if eqeqeq is false.

eqeqeq allows you to compare with
- a variables
- a number != 0
- a string != 0
- an object

To compare with `null`, you should use `eqnull: true`

**Comment by jeff1evesque** [comment]
@nicolo-ribaudo, thank you!  I [implemented](https://github.com/jeff1evesque/machine-learning/commit/1b00239a59c662d7585c673b5438e709ee733143) just `"eqnull": true`.
