### ISSUE TITLE
jshint v2.9.0 release not int npm

### ISSUE THREAD

**Issue by minj** [jshint/jshint#2700]
Is there a reason v2.9.0 is missing in [npm](https://www.npmjs.com/package/jshint)?

**Comment by nicolo-ribaudo** [comment]
> Version 2.9.0 of this library was revoked shortly after being released: https://twitter.com/JSHint/status/639564453852356608

**Comment by minj** [comment]
I see. I guess it's worthwhile to follow @JSHint on twitter. Thanks
