### ISSUE TITLE
Quoted key in destructuring assignment causes Expected an identifier

### ISSUE THREAD

**Issue by lolmaus** [jshint/jshint#2706]
Valid JS:

```js
/* jshint esnext:true */
const {
  'foo-bar': fooBar
} = obj;
```

yields:

> Expected an identifier and instead saw 'foo-bar'.

**Comment by nicolo-ribaudo** [comment]
This has been fixed on master - #2495

**Comment by lolmaus** [comment]
Cool, thanks! Any plans on releasing it?

**Comment by lolmaus** [comment]
I'm still seeing this in `2.9.0`:

```js
  const {
    'exam-block-session':  actualEBS,
    'question-occurrence': actualQuestion,
    'answer-occurrence':   actualAnswerChoice
  } =
    relations.relateOneToOne(server.db, {
      'exam-block-session':  expectedEBS,
      'question-occurrence': expectedQO,
      'answer-occurrence':   expectedAnswerChoice
    });
```

> tests/mirage-helpers/relations-test.js: line 60, col 5, Expected an identifier and instead saw 'exam-block-session'.
> tests/mirage-helpers/relations-test.js: line 61, col 5, Expected an identifier and instead saw 'question-occurrence'.
> tests/mirage-helpers/relations-test.js: line 62, col 5, Expected an identifier and instead saw 'answer-occurrence'.

**Comment by lolmaus** [comment]
Pardon, a dependency is still using `2.8.0`.
