### ISSUE TITLE
[DOCS] CLA link not working?

### ISSUE THREAD

**Issue by jsr6720** [jshint/jshint#2709]
https://github.com/jugglinmike/jshint/commit/832f1680a7dd782b7259df1002626cc7247a2a2c

Changeset updated the link but the server isn't up? I signed the old agreement google docs. Is this still valid?

**Comment by jugglinmike** [comment]
Hmm. The link is still working for me:

https://www.clahub.com/agreements/jshint/jshint

Could you try again in a few minutes and report back?

**Comment by jsr6720** [comment]
Seems to be a proxy issue at my work. Thanks for checking.
