### ISSUE TITLE
Parse error on spread operator in an arrow function

### ISSUE THREAD

**Issue by ptarjan** [jshint/jshint#2712]
If I do this:

```
foo(...args => bar(args))
```

It dies with

```
  line 19  col 24  Expected '(' and instead saw '{'.
```

But if I change my code to:

```
foo((...args) => bar(args))
```

jshint works. The former is valid syntax so please allow it.

**Comment by nicolo-ribaudo** [comment]
It isn't valid syntax:

- [14.2](http://www.ecma-international.org/ecma-262/6.0/index.html#sec-arrow-function-definitions)
  ```
  ArrowFunction[In, Yield] :
    ArrowParameters[?Yield] [no LineTerminator here] => ConciseBody[?In]

  ArrowParameters[Yield] :
    BindingIdentifier[?Yield]
    CoverParenthesizedExpressionAndArrowParameterList[?Yield]
```

- [12.1](http://www.ecma-international.org/ecma-262/6.0/index.html#sec-identifiers)
  ```
  BindingIdentifier[Yield] :
    Identifier
    [~Yield] yield
```

- [12.2](http://www.ecma-international.org/ecma-262/6.0/index.html#sec-primary-expression)
  ```
  CoverParenthesizedExpressionAndArrowParameterList[Yield] :
    ( Expression[In, ?Yield] )
    ( )
    ( ... BindingIdentifier[?Yield] )
    ( Expression[In, ?Yield] , ... BindingIdentifier[?Yield] )
```

**Comment by ptarjan** [comment]
oh wow, the `...` does't bind tightly? Thanks @nicolo-ribaudo!

**Comment by caitp** [comment]
there is a bit of a push to allow this, from Microsoft IIRC. I'm not sure how that will work in a backwards compatible way, given the rest parameter issue.
