### ISSUE TITLE
W069 warning when ignoring that rule on a line in some cases

### ISSUE THREAD

**Issue by ricardograca** [jshint/jshint#2723]
In the following code jshint will complain that the first line "is better written in dot notation", even though it has a comment directive that tells it to ignore that rule on that particular line:

```javascript
var appName = process.env['npm_package_name'] // jshint -W069
var port = process.env['npm_package_config_port'] // jshint -W069
```

The second line is correctly ignored. If I change the order of the variables, so that `port` is declared first, then that one gets the warning. Basically, the first warning is always displayed even though it should be ignored.

If using a block style ignore, then everything works as expected and there are no warnings:

```javascript
/* jshint -W069 */
var appName = process.env['npm_package_name']
var port = process.env['npm_package_config_port']
/* jshint +W069 */
```

I'm using jshint version 2.8.0.

**Comment by nicolo-ribaudo** [comment]
Except for `// jshint ignore:line`, JSHint options are applied *after* the comment, not starting from the first character of the comment's line. So your first code is parsed like this one:
```js
var appName = process.env['npm_package_name']
/* jshint -W069 */
var port = process.env['npm_package_config_port']
/* jshint -W069 */
```

**Comment by ricardograca** [comment]
Interesting. Somehow I was expecting that a particular directive's line comment would apply to the line it's in just like the `ignore` one does. Thanks for the clarification.
