### ISSUE TITLE
jshint unused: false doesn't work

### ISSUE THREAD

**Issue by AnatoliyLitinskiy** [jshint/jshint#2731]
```javaScript
function run () {
  // ...
  definedLater();
  // ...
}

/* jshint unused: false */
function definedLater () {
  // do something
}
```
code above will produce such error (ignoring unused: false directive):

'definedLater' is defined but never used

my config file looks like this:

```javaScript
{
  "unused": true,
}
```

**Comment by jugglinmike** [comment]
Linting that source code using that `.jshintrc` (minus the trailing comma) on JSHint 2.8.0 produces a different warning for me:

>     index.js: line 1, col 10, 'run' is defined but never used.

I see the same behavior when the initial configuration is declared in-line (i.e. without a separate RC file):

```
$ ./bin/jshint -
// jshint unused: true
function run () {
  // ...
  definedLater();
  // ...
}

/* jshint unused: false */
function definedLater () {
  // do something
}
stdin: line 2, col 10, 'run' is defined but never used.

1 error
```

Could you share which version of JSHint you are using?

**Comment by jugglinmike** [comment]
We won't be able to help without more information. If anyone experiences this problem, please share a complete standalone example and the version of JSHint that produces the warning.
