### ISSUE TITLE
2.9.0 doesn't appear to be published to npm

### ISSUE THREAD

**Issue by jasonkarns** [jshint/jshint#2737]
It appears that 2.9.0 was released 

![image](https://cloud.githubusercontent.com/assets/119972/10831729/a51a66a8-7e5d-11e5-9589-aaa718c0e8f7.png)

but hasn't been published to npm
```
$ npm view jshint dist-tags
{ latest: '2.8.0' }
```

![image](https://cloud.githubusercontent.com/assets/119972/10831748/bd940766-7e5d-11e5-81f8-c1e664ddd914.png)

**Comment by jugglinmike** [comment]
Version 2.9.0 of JSHint has been released and revoked. See:

- https://twitter.com/JSHint/status/639564453852356608
- gh-2670
- gh-2689

You can expect a release candidate for 2.9.1 as soon as we've resolved the known regressions.

**Comment by jasonkarns** [comment]
thanks
