### ISSUE TITLE
using esnext, const in multiple blocks

### ISSUE THREAD

**Issue by shaunc** [jshint/jshint#2748]
Given that `const` is block scoped, using `esnext` the following should be ok, but causes an error (`const 'name' has already been declared. (E011)`:

    if(predicate) {
      const name = 'foo';
     ...  [use name]
    }
    else {
      const name = 'bar';
      ... [use name]
    }

**Comment by nicolo-ribaudo** [comment]
Which version of JSHint are you using?

**Comment by shaunc** [comment]
master

**Comment by nicolo-ribaudo** [comment]
I can't reproduce this issue...

![gh-2748](https://cloud.githubusercontent.com/assets/7000710/10979386/894fdf3a-83fc-11e5-8809-6d558f9ce640.JPG)

**Comment by jugglinmike** [comment]
I can reproduce this in JSHint 2.7.0, but not in 2.8.0 or `master`. Can you share a reduced case that is valid JavaScript?

**Comment by nicolo-ribaudo** [comment]
This should have been fixed by 1bb80f9

**Comment by shaunc** [comment]
Ah -- my bad -- had jshint pointing to master, but mocha-jshint was using its own version. Sorry, and thanks!
