### ISSUE TITLE
not working on rhino-1.7.7

### ISSUE THREAD

**Issue by yas99en** [jshint/jshint#2751]
jshint 2.9.0 does not work on rhino 1.7.7

$ java -jar js.jar ../jshint-2.9.0/dist/jshint-rhino.js
js: uncaught JavaScript runtime exception: TypeError: Cannot read property "prototype" from undefined

**Comment by nicolo-ribaudo** [comment]
This issue may be a duplicate if #2308

**Comment by jugglinmike** [comment]
Thanks for the report, @yas99en! Issue gh-2308 already tracks this problem, so I'm going to close this issue in favor of that one.
