### ISSUE TITLE
Let scope in for...of loop might be screwy?

### ISSUE THREAD

**Issue by marcoscaceres** [jshint/jshint#2756]
I have the following, and jshint is complaining that "'name' is defined but never used." in the for of loop.  

If I switch from `let` to  `var`, it works ok tho. 

```ES
function trimRedundantProps(obj) {
  let defaultProps = Object.getOwnPropertyNames(defaultLocale);
  let redudantProps = [];
  for (let name of Object.getOwnPropertyNames(obj)) {
    if (defaultProps.indexOf(name) === -1) {
      redudantProps.push(name);
      delete obj[name];
    }
  }
  if (redudantProps.length) {
    let msg = `${warn("WARNING:")} Redundant props in ${this.locale}:`; // jshint ignore:line
    msg += notice(`
 * ${redudantProps.join("\n * ")}`);
    console.warn(msg);
  }
  return obj;
}
```

**Comment by nicolo-ribaudo** [comment]
Which version of JSHint are you using? I can't reproduce this issue using v2.8.0

**Comment by marcoscaceres** [comment]
v2.8.0 also. 

If it helps, here is the complete file: 
https://raw.githubusercontent.com/mozilla/remote-newtab/l10nStringGetter/bin/fetchl10nstrings.js

**Comment by nicolo-ribaudo** [comment]
I copied and pasted that file on [jshint.com](http://jshint.com) (which uses JSHint 2.8.0), added `// jshint unused: true` and replaced `for (var name of Object.getOwnPropertyNames(obj)) {` with `for (let name of Object.getOwnPropertyNames(obj)) {`, but I still am not able to reproduce the issue.

**Comment by marcoscaceres** [comment]
Seems to have fixed itself for me too :/
