### ISSUE TITLE
I003 (ES5 option is now set per default) should not be displayed when esversion=5 overrides  esversion=6

### ISSUE THREAD

**Issue by vcarel** [jshint/jshint#2766]
I'm using the following project structure:
```
client/
        somefile.js
        .jshintrc
server/
        another_file.js
gulpfile.js
.jshintrc
```

I'm writing all my JS files in ES6 *except* my client sources which are in ES5.
So I defined a global .jshintrc file with the property (among others):
```
{
  ...
  esversion: 6
  ...
}
```

And in my client directory, I have another .jshintrc file which contains:
```
{
    "extends": "../.jshintrc",
    "esversion": 5,
}
```

But in all my client files I'm getting the warning message: ```I003 ES5 option is now set per default```
In this case, this message is wrong. My default is ES6 as per the global .jshintrc file and if I don't specify esversion=5, I will be in ES6 in my client app.

**Comment by jugglinmike** [comment]
We've resolved this by removing the "info" message entirely--see gh-2900.
