### ISSUE TITLE
line 0, col 0, Bad option: 'esversion'.

### ISSUE THREAD

**Issue by ganzux** [jshint/jshint#2771]
Hi there!

I am using **jshint v2.8.0** with **node v0.12.7** and trying to use the following **.jshintrc** config file:
```json
{
    "globals": {
        "jQuery": true,
        "d3": true
    },
    "browser": true,
    "boss": true,
    "curly": true,
    "eqeqeq": true,
    "eqnull": true,
    "expr": true,
    "immed": true,
    "noarg": true,
    "quotmark": "single",
    "undef": true,
    "unused": true,
    "esversion": 3,
    "devel":false,
    "jquery": true
}
```
I am trying to validate a .js file but I always get the error **line 0, col 0, Bad option: 'esversion'.**

If I remove  **"esversion": 3**, it works perfectly, but the option **"es3"** is deprecated.

Thanks in advance,

**Comment by nicolo-ribaudo** [comment]
`esversion` was introduced in v2.9.0

**Comment by ganzux** [comment]
Thanks, @nicolo-ribaudo . Is any way to get the documentation from other release?

**Comment by nicolo-ribaudo** [comment]
You can browse to the version of which you are looking for documentation ([v2.8.0](https://github.com/jshint/jshint/tree/e6611af2d180bd2317d5762e85807a481de99ccb)) and read the comments in `src/options.js`

**Comment by ganzux** [comment]
Thanks a lot, @nicolo-ribaudo.

**Comment by jugglinmike** [comment]
@ganzux I know that's kind of a hassle; thanks for being a good sport about it. I have hopes that the website will some day serve your use case: https://github.com/jshint/jshint.github.io/issues/29
