### ISSUE TITLE
Incorrect warning "unnecessary grouping operator" from `singleGroups` when using Object Destructuring Assignment without declaration (ES6 feature).

### ISSUE THREAD

**Issue by myrdd** [jshint/jshint#2775]
[Citation from MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment#Assignment_without_declaration_2):

> Destructuring assignment can be made without a declaration in the assignment statement.
>
> ```javascript
> var a, b;
>
> ({a, b} = {a:1, b:2});
> ```
>
> > The `( .. )` around the assignment statement is required syntax when using object literal destructuring assignment without a declaration.

JSHint should not warn in that case.

**Comment by jugglinmike** [comment]
You are correct! Complete test case:

```js
// jshint esnext: true, singleGroups: true
var x;
({ x } = {});
```

**Comment by myrdd** [comment]
Thank you @nicolo-ribaudo! However, note that the parens are necessary _only_ for object destructuring assignment, _not_ for array destructuring assignment. The following code _does_ work:

```javascript
var a, b;

[a, b] = [1, 2];
```

See [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment#Assignment_without_declaration)

**Comment by jugglinmike** [comment]
@myrdd Yup, the patch over at gh-2862 takes that into account.

**Comment by myrdd** [comment]
Oh, you're right! I should have checked what `addError()` actually does. :] Great work!
