### ISSUE TITLE
supress warning does not work for nested function

### ISSUE THREAD

**Issue by yohny** [jshint/jshint#2776]
Hello,
in the following code
```javascript
function outer()
{
  function inner()
  {
    console.log('sample');
  }
}

outer(0;
```
I get warning W098 - for `inner`function. on order to suppress it I added `  /* jshint -W098 */` inside the `outer` function, just above `inner` function declaration like so:
```javascript
function outer()
{
  /* jshint -W098 */
  function inner()
  {
    console.log('sample');
  }
}

outer();
```
but it does not work. However when added in front of `outer` function:
```javascript
/* jshint -W098 */
function outer()
{
  function inner()
  {
    console.log('sample');
  }
}

outer();
```
then it works as expected. Should it not suppress work also when put inside the function?

**Comment by jugglinmike** [comment]
Thanks for the report! This issue has since been resolved (see 6d2cc19a0708af5f45d8d44f6194e8a1fcaa43e4). The fix isn't yet available in a stable release, but if you'd like to try the latest release candidate (2.9.1-rc1 at the time of this writing), you can enjoy the fix today.
