### ISSUE TITLE
"Warning: Invalid array length" when running jshint

### ISSUE THREAD

**Issue by MartinRixham** [jshint/jshint#2778]
Running jshint on my project gives the following output:

```
Running "jshint:all" (jshint) task

   src/Binding.js
     69 |    for (key in bindings) {
Warning: Invalid array length Use --force to continue.
```

It's possible that this is just an unhelpful message but it looks to me like a JavaScript error.

`npm list jshint` gives:

```
└─┬ grunt-contrib-jshint@0.11.3
  └── jshint@2.8.0 

``` 

The issue can be reproduced by cloning my project from here:
https://github.com/MartinRixham/Datum
and running `grunt`.

**Comment by nicolo-ribaudo** [comment]
I cloned your project and ran `grunt`, but I can't reproduce the error:

```
$ grunt
Running "jshint:all" (jshint) task
>> 25 files lint free.

Running "jscs:src" (jscs) task
>> 25 files without code style errors.

Running "concat:dist" (concat) task
File target/Datum.js created.

Running "uglify:my_target" (uglify) task
>> 1 file created.

Done, without errors.
```

**Comment by nicolo-ribaudo** [comment]
Using the jshint cli to lint your project I get these errors:

```
$ node_modules/jshint/bin/jshint src/*.js tests/*.html --extract=auto
src/Binding.js: line 69, col NaN, Creating global 'for' variable. Should be 'for (var key ...'.
src/Binding.js: line 74, col NaN, Don't make functions within a loop.

2 errors
```

The error you reported may be related to `grunt-contrib-jshint`

**Comment by MartinRixham** [comment]
Hi thanks for doing that.

I agree the bug must be with the grunt plugin.

**Comment by jugglinmike** [comment]
Thanks for getting to the bottom of that! You can follow up on the project for the plugin itself: https://github.com/gruntjs/grunt-contrib-jshint

**Comment by JanZerebecki** [comment]
This seems to be the same issue as https://github.com/gruntjs/grunt-contrib-jshint/issues/242 .

**Comment by AMoo-Miki** [comment]
The problem is with the way the result of `extractOffsets` is handled by jshint at https://github.com/jshint/jshint/blob/master/src/cli.js#L663.

`offsets` is an array, partially populated with numeric values with the rest `undefined`. When `+` is applied to `undefined` it results in a `NaN`. That is why [nicolo-ribaudo's comment above](https://github.com/jshint/jshint/issues/2778#issuecomment-162234368) has `col NaN`.

Changing that line would fix the problem:
`var offset = offsets[line] || 0;`

 gruntjs/grunt-contrib-jshint simply trusts that jshint will provide a numeric `e.character` at https://github.com/gruntjs/grunt-contrib-jshint/blob/master/tasks/lib/jshint.js#L118.

**Comment by nicolo-ribaudo** [comment]
@AMoo-Miki Thank you for having investigated into this issue! Would you mind opening a pr? I think it would also fix #2880

**Comment by AMoo-Miki** [comment]
@nicolo-ribaudo done :)

While this should fix the symptoms of #2880, I will check back later to dig deeper, if it doesn't solves the root cause.

**Comment by mariohmol** [comment]
Getting this error using latest versions of jshint and grunt-contrib on Gruntfile.js. Is this the same issue?
@MartinRixham what u did to avoid that?

```
Running "jshint:all" (jshint) task

   Gruntfile.js
     61 |      custom_concat: {
Warning: Invalid array length Use --force to continue.
```

**Comment by mariohmol** [comment]
If i change custom_concat to customconcat , it works.

**Comment by trelltron** [comment]
I just had the same issue as mariohmol. Looks like it was flagging all instances of underscores in attribute names with the "Warning: Invalid array length" error.
