### ISSUE TITLE
Strange behaviour with the combination of `unused: true` and `-W117: true`

### ISSUE THREAD

**Issue by kt3k** [jshint/jshint#2779]
Hello

I think I found a strange behaviour about `usused` and `-W117` options.

With the following settings, the latest version (v2.8.0) of jshint outputs a lint error.

.jshintrc
```json
{
  "unused": true,
  "-W117": true
}
```

test.js
```js
a();
function a() {
  console.log(1);
}
```

```
$ jshint test.js
test.js: line 2, col 10, 'a' is defined but never used.
```

v2.6.0 doesn't output the above error and v2.6.1 does. I guess this started at v2.6.1.

Thanks,

**Comment by nicolo-ribaudo** [comment]
This issue has been fixed by 08eb4e25962eb71f94c09f79b3b08288b91a7bce.

**Comment by jugglinmike** [comment]
@nicolo-ribaudo Is correct. If you update to JSHint version 2.9.1, you will find that the spurious warning is gone.

**Comment by kt3k** [comment]
OK. Thanks!
