### ISSUE TITLE
jslint ignore:start end block hides variables between the block

### ISSUE THREAD

**Issue by lateau** [jshint/jshint#2780]
Here's a example code.

```js
'use strict';  // jshint ignore:line

// External modules
/* jshint ignore:start */
var fs = require('fs'),
    path = require('path');
/* jshint ignore:end */

path.resolve('./path/to/file');
```

And this is a output.

```
JSHint 9:1 'path' is not defined. 
```

Is this a proper way what jshint does?

**Comment by jugglinmike** [comment]
JSHint is reporting the variable as undefined because the definition is within a section of ignored code. You can avoid this by declaring the variable outside of the ignored section:

```diff
 'use strict';  // jshint ignore:line

 // External modules
+var fs, path;
 /* jshint ignore:start */
-var fs = require('fs'),
+fs =require('fs');
-    path = require('path');
+path = require('path');
 /* jshint ignore:end */
 
 path.resolve('./path/to/file');
```

Hope this helps!

**Comment by lateau** [comment]
@jugglinmike Thanks :+1:

**Comment by dailytabs** [comment]
Why does `ignore:line` not exhibit this behavior?

**Comment by jugglinmike** [comment]
The semantics of `ignore:start` and `ignore:line` are subtle different. The former causes JSHint to discard the source text prior to parsing, behaving as though the included lines were empty. The latter causes JSHint to parse the code but ignore any warnings that originated on that line.

Put another way: `ignore:start` ignores the code, while `ignore:line` only ignores warnings.

Consistency would be much better, but this behavior has been around for many years, so changing it now would do more harm than good.
