### ISSUE TITLE
incorrect 'only available in ES6' warning (W119) with options `moz: true, esversion: 6`

### ISSUE THREAD

**Issue by myrdd** [jshint/jshint#2785]
__How to reproduce:__

Code:

```javascript
function toArray(...rest) {
  return rest;
}
```

Options:

```json
{
  "esversion": 6,
  "moz": true
}
```

__What happens?__

JSHint says: `'spread/rest operator' is only available in ES6 (use 'esversion: 6'). (W119)`

__What should happen?__

There should be no warning.

__Additional notes__

* I noticed that when `moz` is set to `false` the warning doesn't appear.
* I'm using jshint `v2.9.1-rc1`.

**Comment by myrdd** [comment]
Looks like it happens for more (or all) `W119` warnings, for example when using arrow functions:

```javascript
let fn = (a, b) => a + b;
```

**Comment by caitp** [comment]
It's a one line fix, just remove the requirement that `moz` is false.

**Comment by myrdd** [comment]
I'm trying to understand this case. Referring to `jshint.js` and `state.js`, why is there a "strict" parameter to `inES6()`?
```javascript
// In `jshint.js`:

      if (!state.inES6(true)) {
        warning("W119", state.tokens.next, "spread/rest operator", "6");
      }

// in `state.js`:

  /**
   * @param {boolean} strict - When `true`, only consider ES6 when in
   *                           "esversion: 6" code and *not* in "moz".
   */
  inES6: function(strict) {
    // ...
  },
```

Btw, I also wonder why in commit cf5a699 somewhere [`state.option.esnext` has changed to `state.inES6(true)`](https://github.com/jshint/jshint/commit/cf5a699b0f6fbe2be61f4972ea0a2bbef51a0bd2#diff-7cd6d0e1db309008199ead0cb3a0b76fL1457).

**Comment by nicolo-ribaudo** [comment]
> Btw, I also wonder why in commit cf5a699 somewhere state.option.esnext has changed to state.inES6(true).

It's my fault. I added that parameter because, without it, `...` and arrow functions would be allowed even if `esversion` isn't set and `moz` is true. To maintain the same behaviour of JSHint 2.8.0, `inES6(true)` should be replaced with `esversion === 6`

**Comment by caitp** [comment]
No, Just remove the requirement that moz is false in inES6, it's not rocket science
