### ISSUE TITLE
Custom rules not taken into account after "return" statement

### ISSUE THREAD

**Issue by matthieusieben** [jshint/jshint#2788]
Custom rules only apply on function defined after a `return` statement if they are written right after the `return`statement.

In this first example, the `maxcomplexity` is *not* taken into account.

```js
function foo() {
  function bar() {}

  return bar;

  function privateBar() {}

  // jshint maxcomplexity:15
  function privateBarWithHighComplexity() {}
}
```

In this second example, the `maxcomplexity` *is* taken into account.

```js
function foo() {
  function bar() {}

  return bar;

  // jshint maxcomplexity:15

  function privateBar() {}
  function privateBarWithHighComplexity() {}
}
```

**Comment by nicolo-ribaudo** [comment]
Does it works if you put *something* between the function and the comment?

```js
function foo() {
  function bar() {}

  return bar;

  function privateBar() {}

  console.log("foo");

  // jshint maxcomplexity:15
  function privateBarWithHighComplexity() {}
}
```

If it does, this issue is a duplicate of #2436

**Comment by matthieusieben** [comment]
It does indeed.
