### ISSUE TITLE
Feature request - show error or warning when two functions have the same name

### ISSUE THREAD

**Issue by olsonpm** [jshint/jshint#2790]
Is there a reason JSHint doesn't show an error or warning when two function declarations exist with the same name in the same scope?  Since JSHint catches variable names, I was wondering why not function names.

Use case:
 - I was writing test cases and using abbreviated function names - eventually writing two with the name "getPIP".  The test case failed for the first one appropriately and after realizing it was the result of an overwritten function, I wondered why jshint doesn't catch that.

If this was in a previous issue I apologize, I did wade through quite a few both open and closed without finding anything.

**Comment by nicolo-ribaudo** [comment]
This is a duplicate of #1304 and #1019.

**Comment by olsonpm** [comment]
Ah "redefinition" was the word I should have searched.  Thanks for pointing those out.
