### ISSUE TITLE
Preparing the JSHint set-up for the next release

### ISSUE THREAD

**Issue by JanisE** [jshint/jshint#2793]
"laxbreak" is deprecated as it relates more to code style, not correctness.

However, as it is a relaxing option, actually _not setting_ it means I'm using a deprecated functionality. If I do not want to use the deprecated functionality, I need to set a deprecated option.

It seems that, at this point I actually am unable to get rid of using JSHint in a non-deprecated mode?

**Comment by nicolo-ribaudo** [comment]
Related - #2625

**Comment by JanisE** [comment]
Thank you for the reference!
