### ISSUE TITLE
JSHint from CLI hangs

### ISSUE THREAD

**Issue by khrome83** [jshint/jshint#2800]
I am trying to add JSHint to run with JShint Stylish to my NPM Test scripts. 
When I add the Lint script, it hangs. I am not 100% sure how I can fix it from hanging. 

```
  "scripts": {
    "lint": "./node_modules/.bin/jshint . --reporter=node_modules/jshint-stylish",
    "checkStyle": "./node_modules/.bin/jscs .",
    "pretest": "npm run-script lint && npm run-script checkStyle",
    "test": "./node_modules/.bin/mocha --reporter spec"
  }
```

**Comment by jugglinmike** [comment]
Does the process hang if you use the default reporter packaged with JSHint (by removing the `--reporter` option)?

**Comment by khrome83** [comment]
It appears that it was also processing the node modules folder. When I switched the paths to be more specific, this solved the problem.
