### ISSUE TITLE
JSHint Option "unused" does not detect unused var

### ISSUE THREAD

**Issue by Rorkal** [jshint/jshint#2804]
Hi !

Seems like the "unused" option does not detect my unused variable.

For example : 

Code below will found : [JSHint]: 'b' is defined but never used.
```javascript
(function() {
    'use strict';

    function main(a, b) {
        return a == null;
    }

    main();
}());
```

But code below won't find out that 'a' is never used.
```javascript
(function() {
    'use strict';

    function main(a, b) {
        return b == null;
    }

    main();
}());
```

Am I missing something with my configuration or is that a bug ?
Thanks.

**Comment by jugglinmike** [comment]
Check out [the docs on the `unused` option](http://jshint.com/docs/options/#unused):

>This can be set to `vars` to only check for variables, not function parameters, or `strict` to check all variables and parameters. The default (true) behavior is to allow unused parameters that are followed by a used parameter.

**Comment by Rorkal** [comment]
Thanks a lot @jugglinmike ! 
Shame on me reading the half the docs...
I close this issue.
