### ISSUE TITLE
[Errno 2] No such file or directory

### ISSUE THREAD

**Issue by FlashFMA** [jshint/jshint#2807]
Linux Mint 17.3 MATE x64
Sublime Text 3
Recently began to learn JavaScript
Using Package Control i've installed JSHint but when i tried to use it with Alt+j got this:
```
[Errno 2] No such file or directory: 'jshint'
```
This is JSHint.py:
```Python
import os

import sublime
import sublime_plugin


class JshintCommand(sublime_plugin.TextCommand):
    def run(self, edit):
        filepath = self.view.file_name()
        packages = sublime.packages_path()
        args = {
            "cmd": [
                "jshint",
                filepath,
                "--reporter",
                os.path.join(packages, "JSHint", "reporter.js")
            ],
            "file_regex": r"JSHint: (.+)\]",
            "line_regex": r"(\d+),(\d+): (.*)$"
        }

        if sublime.platform() == "windows":
            args['cmd'][0] += ".cmd"
        elif sublime.platform() == "osx":
            args['path'] = "/usr/local/share/npm/bin:/usr/local/bin:/opt/local/bin"

        self.view.window().run_command('exec', args)
```
in Sublime Text console using "jshint test.js"
```javascript
console.log('test');
console.log(a)
```
got this:
```
>>> jshint test.js
  File "<string>", line 1
    jshint test.js
              ^
SyntaxError: invalid syntax
```

**Comment by jugglinmike** [comment]
This looks to be a problem with the way you have installed JSHint, not with JSHint itself. I can try helping anyway, though!

I would start by verifying that you can run the `jshint` executable directly in a terminal. From there, you can use `which jshint` to learn where the binary is located. This should be in the PATH of the process running that Python script you shared.

**Comment by FlashFMA** [comment]
Thank you for help!
`which jshint` doesn't showing anything and i decided installing `npm` and jshint through it `sudo npm install -g jshint`(it's my second attempt, first time there was a different error) and now i have this:
```
/usr/bin/env: node: No such file or directory
[Finished in 0.0s with exit code 127]
```
i fixed it with `sudo ln -s /usr/bin/nodejs /usr/bin/node`
All seems to be working but after results there is it 
```
[Finished in 0.4s with exit code 2]
```
It is okay?

**Comment by jugglinmike** [comment]
In order for globally-installed npm packages to be available, the Node.js's `bin` directory needs to be in your PATH environment variable. If you're new to Node, it's generally better to rely on a package manager to install the runtime for you--it will take care of all these details.

**Comment by FlashFMA** [comment]
Thank you

**Comment by jugglinmike** [comment]
Glad it worked out for you!
