### ISSUE TITLE
Docs: "notypeof" should be moved from "Enforcing options" to "Relaxing options"

### ISSUE THREAD

**Issue by vais** [jshint/jshint#2812]
[notypeof](http://jshint.com/docs/options/#notypeof) is actually a relaxing option, not an enforcing option, since setting it to `true` makes JSHint complain _less_, so it should be listed in the [Relaxing options](http://jshint.com/docs/options/#relaxing-options) category.

**Comment by nicolo-ribaudo** [comment]
This will be fixed by pr #2273

**Comment by vais** [comment]
Thank you @nicolo-ribaudo!

**Comment by jugglinmike** [comment]
Resolved via gh-2273.
