### ISSUE TITLE
Docs: "plusplus" should be moved from "Relaxing options" to "Enforcing options"

### ISSUE THREAD

**Issue by vais** [jshint/jshint#2813]
[plusplus](http://jshint.com/docs/options/#plusplus) is actually an enforcing option, not a relaxing option, since setting it to `true` makes JSHint complain *more*, so it should be listed in the [Enforcing options](http://jshint.com/docs/options/#enforcing-options) category.

**Comment by nicolo-ribaudo** [comment]
This is a duplicate of #2048

**Comment by vais** [comment]
:scream:
