### ISSUE TITLE
unused variable missed when variable declaration separated from initialization 

### ISSUE THREAD

**Issue by saifelse** [jshint/jshint#2814]
Executing:

    echo '/* jshint unused: true */ var x; x=1; var y=2; var z;' | jshint -                                                                                                          

Outputs:

    stdin: line 1, col 43, 'y' is defined but never used.
    stdin: line 1, col 52, 'z' is defined but never used.
    
    2 errors

`y` and `z` are found to be unused, even though `x` is unused as well. It seems odd that the assignment of `x` results in a usage of `x`.

For comparison, `eslint`, correctly identifies all 3 variables as being unused:

    echo '/*eslint no-unused-vars: 2*/ var x; x=1; var y=2; var z;' | eslint --stdin                                                                                                                      

Outputs:

    <text>
      1:34  error  "x" is defined but never used  no-unused-vars
      1:46  error  "y" is defined but never used  no-unused-vars
      1:55  error  "z" is defined but never used  no-unused-vars
    
    ✖ 3 problems (3 errors, 0 warnings)

This is particularly annoying when using https://github.com/Clever/coffee-jshint as it is unable to detect unused variables, since `coffee` compiles a declaration into `var x; x = value` and `jshint` cannot detect this as an unused variable.

**Comment by jugglinmike** [comment]
Thanks for the report! This has previously been reported with gh-1994, and I'd prefer to track the bug with the existing issue. I'll close this in favor of that one.
