### ISSUE TITLE
no-return-assign

### ISSUE THREAD

**Issue by ekkis** [jshint/jshint#2816]
doesn't seem to be documented in the main page

**Comment by nicolo-ribaudo** [comment]
It is an ESLint option: http://eslint.org/docs/rules/no-return-assign.html

**Comment by jugglinmike** [comment]
JSHint does not implement a linting option by that name.

**Comment by ekkis** [comment]
according to this it does: https://jslinterrors.com/did-you-mean-to-return-a-conditional  it's just called `-W093` instead, but that's just the code.  I presume the option name is as stated.

**Comment by jugglinmike** [comment]
I think you're looking for the JSHint option called `boss`

>This option suppresses warnings about the use of assignments in cases where comparisons are expected.

http://jshint.com/docs/options/#boss

**Comment by ekkis** [comment]
yes, that looks like it.  boss? whatever that means?
