### ISSUE TITLE
Remove eqnull option

### ISSUE THREAD

**Issue by jacksonrayhamilton** [jshint/jshint#2818]
Sometimes I read or hear that "`==` is useful for checking `null` and `undefined`;" and this "trick" seems to be elevated and legitimized by JSHint's eqnull option. But this practice is unnecessary; one could instead use `===` to check for either value in an `||` expression. Because this is the way one generally checks for a value in a finite set of values, I think it is clearer.

I believe such special exceptions are a bad thing. They shift attention away from real problems into obscurities of a language. It is always an eye-opener, and a waste of time, for someone to discover and come to understand this "trick" when first encountering it. The rule "always use `===`" is easier to remember than "always use `===`, except when comparing against a value that might be `null` or `undefined`."

I expect someone will claim that `value == null` is faster than `value === null || value === undefined`; if so, I'd like to see benchmarks in some practical application proving that the difference is significant (I highly doubt it). Such an argument is more likely an argument for micro-optimization, which also detracts from real problems (including real performance problems) in applications.

And from https://github.com/jshint/jshint/issues/1310, which addresses a similar special exception (which could be justified by "saving bytes;" I expect an insignificant amount).

> There is irrefutably no benefit to abstract equality comparisons and therefore no reason to ever use them.
> . . .
> Objectively, it's always a mistake to conflate null and undefined—which are two things, each with its own meaning.

Therefore, I think this rule should be removed. It permits an unnecessary and bad thing.

**Comment by jugglinmike** [comment]
Removing that option would be contrary to the spirit of JSHint. While we have
strong opinions about code clarity and safety, we try to avoid forcing any
particular decision on users. I think you've made a strong argument, and it's
why I don't personally enable `eqnull` on any of my projects. As a so-called
"relaxing option", `eqnull` is disabled by default. I think that clearly
indicates our recommendations while still allowing for flexibility.

(As a side note: a "hands off" attitude is also helpful from a project
maintenance standpoint. It allows the maintainers to sidestep many subjective
arguments about what is a "best practice," and what is "unnecessary.")

That said, if you're interested in a more opinionated tool, you may want to try
out JSLint: http://jslint.com/

**Comment by caitp** [comment]
The "== is good for testing if something is undefined or null" thing can introduce some bizarre false positives. For instance, `winsow.all == null` is true as HTMLAllCollection masquerades as null/undefined. Things like this are bizarre and can sneak bugs into code, it has happened before

**Comment by jugglinmike** [comment]
> Things like this are bizarre and can sneak bugs into code, it has happened before

Agreed! While I don't think `== null` is worth the risk, either, it *is* valid JavaScript. JSHint does not require conformance to any subjective criteria, and I don't think it should start now.

**Comment by jacksonrayhamilton** [comment]
> While we have strong opinions about code clarity and safety, we try to avoid forcing any particular decision on users.

Understood; off by default is probably good enough, then.

**Comment by jugglinmike** [comment]
Glad you agree :)
