### ISSUE TITLE
Deep nested template strings

### ISSUE THREAD

**Issue by KenanSulayman** [jshint/jshint#2820]
Hi,

just came over to report an issue with the linting of deep nested template strings:

```
const foo = `${someVariable || `r${something + 1}`} bar`
```

Jshint will refuse to accept that syntax that despite it being valid ES6 (unexpected '`').

**Comment by nicolo-ribaudo** [comment]
Which version of JSHint are you using? This has been fixed in 2.6.1 (3da1eaf14398dc9b178e6c678b5e4fb09afef2d5)

**Comment by KenanSulayman** [comment]
It seems *Jshint Gutter*, the inline-linter for sublime text is shipping with 2.5.1. I'll upgrade locally until they go with a modern version of jshint.
