### ISSUE TITLE
undef & esnext: export default doesn't "define" a thing

### ISSUE THREAD

**Issue by gnarf** [jshint/jshint#2834]
Given the following example:

```js
class Pass {
}

export default class Fail {
}

Pass.prop = true;
// test.js: line 9, col 1, 'Fail' is not defined.
Fail.prop = true;
```

Note that if you define the `class Pass` you can then set properties on it, but `export default class Fail` doesn't also define `Fail` in the list of identifiers defined.

**Comment by jugglinmike** [comment]
I'm having trouble reproducing this. Can you share which version of JSHint you are using? Also, could you in-line the necessary directives (to rule out problems from loading/parsing/merging RC files)?

**Comment by gnarf** [comment]
So something strange happening - I had done a `npm install jshint -g` to update my version, and it worked, but the terminal I was testing it still said:

```
$ jshint -v
jshint v2.5.11
```

opened a new one, and the problem is gone, sorry for the noise...

**Comment by jugglinmike** [comment]
No worries!
