### ISSUE TITLE
Incompatible values for the 'strict' and 'globalstrict' complains after upgrading to jshint@2.9.1

### ISSUE THREAD

**Issue by amrish7** [jshint/jshint#2836]
On upgrading to `2.9.1`, jshint has started complaining about `Incompatible values for the 'strict' and 'globalstrict'` for the inline comments I put in to bump up the `maxcomplexity` threshold  

```
foo(data, callback) {
    /*jshint maxcomplexity:11 */
   .
   .
   .
}
```

Wondering what is the right way to do the overrides going forward?

**Comment by jugglinmike** [comment]
Could you share a small example that demonstrates this problem all on its own? Please include the necessary configuration values as in-line directives (e.g. `// jshint strict: true`) to help us reproduce the problem.

**Comment by amrish7** [comment]
I have created `cyclomaticComplexity.js` file in https://github.com/amrish7/jshint-failure explaining the issue that I am running into. After upgrading to jshint@2.9.1, this [line] (https://github.com/amrish7/jshint-failure/blob/master/cyclomaticComplexity.js#L4) does not seem to help with bumping the max complexity

**Comment by jugglinmike** [comment]
Thanks for taking the time to put that together! This is a regression. Here's a simplified test case:

```js
// jshint strict: true, globalstrict: true
// jshint maxcomplexity: 1
```

To reproduce this, the `maxcomplexity` option must be set in a separate directive.

This is a high priority bug--thanks for reporting!

**Comment by ooskapenaar** [comment]
@jugglinmike, any idea when this fix will make it into a version of jshint?

**Comment by jugglinmike** [comment]
@ooskapenaar Good news--there's a patch over at gh-2843. I wrote it myself, so it just needs another maintainer's review, and then it can land in `master`. I plan to follow that up with a patch release promptly.

**Comment by jishi** [comment]
I see this for what I can tell, is any overrides in any file, for example:

/*jshint unused:false */

Reverting to 2.8 fixed it. Just FYI, will test next version when it is released.

**Comment by ooskapenaar** [comment]
@jishi, I am seeing the same.
