### ISSUE TITLE
'Bad invocation' on single-argument IIFE Arrow Function without parentheses

### ISSUE THREAD

**Issue by RevanProdigalKnight** [jshint/jshint#2837]
`(arg => /* stuff */)(argument); // Bad Invocation`

`((arg) => /* stuff */)(argument); // passes`

**Comment by nicolo-ribaudo** [comment]
This is a duplicate of #2351 (fixed by #2544)

**Comment by RevanProdigalKnight** [comment]
Sorry, didn't see that one.
