### ISSUE TITLE
Incorrect "used before declared" warning for const value

### ISSUE THREAD

**Issue by twhb** [jshint/jshint#2838]
Given the following code:

```javascript
/* jshint esversion: 6, devel: true */

window.foo = function () {
  alert(x);
};

window.bar = function () {
  alert(x);
};

const x = 1;
```

I get a single warning: "15: 'x' was used before it was declared, which is illegal for 'const' variables."

The code runs fine. I'm not sure if some people consider this bad style, but either way it doesn't seem to be something JSHint means to enforce, as you get no warning if you comment out either `foo` or `bar`.

Tested in v2.9.1.

**Comment by jugglinmike** [comment]
Thanks for the report! This has been fixed and will be available in the next release of JSHint (post 2.9.1)
