### ISSUE TITLE
whitelist unused variables by name

### ISSUE THREAD

**Issue by ToadJamb** [jshint/jshint#2839]
If I have the following:

``` javascript
// static.js
let foo = 'bar';
let baz = 'quz';
// do a bunch of work...
const MyHash = {foo: foo};

// logic.js
let aValue = MyHash.foo;
// do something with aValue;
```

I want to be able to specify that `MyHash` is ok to be left unused, while I want to be notified that `baz` is not used.

In this scenario, `baz` was perhaps used at one point, but the code got changed with it left behind. `MyHash` will never be used inside `static.js`, but will be used in many other files.

**Comment by nicolo-ribaudo** [comment]
You can use `/* exported MyHash */`

**Comment by ToadJamb** [comment]
That appears to do the trick! I was having a hard time believing there wasn't a way to do that. Thank you so much!

**Comment by nicolo-ribaudo** [comment]
@ToadJamb Can you close this issue?
