### ISSUE TITLE
On error I'm not getting file name of file where error occurred

### ISSUE THREAD

**Issue by mryarbles** [jshint/jshint#2841]
For instance, for a missing semicolon I only get the following:

```
126 | $log.log(toState)
                                   ^ Missing semicolon.

>> 1 error in 122 files

```

**Comment by nicolo-ribaudo** [comment]
Which reporter are you using?

**Comment by Splaktar** [comment]
I'm seeing this as well using the default reporter.

**Comment by jugglinmike** [comment]
There is a related issue filed against the grunt-contribu-jshint npm module: https://github.com/gruntjs/grunt-contrib-jshint/issues/240 . It looks as though this is an issue with that module. This is supported by @Splaktar's experience described above (where using a different reported solved the problem).

I'm going to close this issue based on those observations. If anyone is having this problem and can demonstrate it by using JSHint directly, please let us know and we'll re-open.
