### ISSUE TITLE
JSHint throws an "Invalid Reporter" error whenever the code for Reporter is updated

### ISSUE THREAD

**Issue by subzworld** [jshint/jshint#2847]
Hi,
I have created a reporter for JSHint that worked fine. The reporter mainly exports the log reports as an HTML file. However when I updated the codebase to include CSS support, the gulp task started throwing an error for "Invalid Reporter". The code for the reporter doesn't contain any error and I have included the module as a dev dependency in my package.json

**Comment by nicolo-ribaudo** [comment]
Can you share the reporter and the command you are using to run JSHint?

**Comment by subzworld** [comment]
This the code I have used

```
gulp.task('lint', function(){
    var deferred=queue.defer();
    setTimeout(function() {
        deferred.resolve();
        return gulp.src(config.data.lint.source).pipe(jshint()).pipe(jshint.reporter('gulp-html-log', {filename:config.data.lint.destination}));
    }, 1);
    
    return deferred.promise; 
});
```

'gulp-html-log' is the node module i have created. It was working fine with its version 1.0.0, the error appeared after upgrading to 1.0.1.

**Comment by nicolo-ribaudo** [comment]
`gulp-jshint` implements [its own reporter logic](https://github.com/spalger/gulp-jshint/blob/master/src/reporters/index.js): can you open an [issue to their repo](https://github.com/spalger/gulp-jshint/issues)?

**Comment by jugglinmike** [comment]
Yup, this looks like a problem with the gulp-jshint project (/cc @spalger). I'm going to close this issue, but if you can demonstrate the error by using JSHint directly, we can re-open it.

**Comment by subzworld** [comment]
Sure makes sense i'll do that right away. Thanks guys for the quick
turnaround!

*Thanks*,
*Subroto.*
