### ISSUE TITLE
Default export line does not require a semi-colon

### ISSUE THREAD

**Issue by rrees** [jshint/jshint#2864]
According to the [MDN page on export](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/export), this syntax does not require a semi-colon:

`export default myFunction`

I've tried enabling `esversion` 5 in the config file but this still gets flagged up as requiring a semi-colon.

Is there a way to get jshint to accept this?

**Comment by nicolo-ribaudo** [comment]
From the page you linked:
>
```js
export default expression;
```

It has a semicolon.
Anyway, you can use the `asi` option.

> I've tried enabling `esversion` 5

It should be `6` (or `2015`)

**Comment by rrees** [comment]
Thanks for the comments, sorry the MDN page wasn't clear (it has both forms). Hopefully [the spec](http://www.ecma-international.org/ecma-262/6.0/#sec-exports) is clearer that if the export is default and a hoistable or a class declaration the semi-colon is not present.

I tried setting `esversion 6` but it still declares it invalid.

I don't want to apply a global setting for semi-colons just because one line is being incorrectly parsed. I'm currently just using a comment ignore statement to avoid the issue.

**Comment by nicolo-ribaudo** [comment]
@rrees Sorry, I misinterpreted the code you posted in the first comment. (I thought your code was `function myFunction() {} \n export default myFunction`)

I can't reproduce this issue on [jshint.com](http://jshint.com):

```js
export default function () {} // No warnings
```

```js
export default function () {}; // 'Unnecessary semicolon.'
```
