### ISSUE TITLE
laxcomma doesn't work in jasmine tests

### ISSUE THREAD

**Issue by a11smiles** [jshint/jshint#2869]
my .jshintrc config:

```
{
  "browser": true,
  "jquery": true,
  "jasmine": true,
  "node": true,
  "phantom": true,
  "laxbreak": true,
  "laxcomma": true,
  "globals": {
    "angular": false
  }
}
```

the `laxcomma` switch works for all of my application files.  However, in my jasmine unit tests, I still receive the error message about unsafe line breaks with a comma. 

I, therefore, have had to add `/* jshint laxcomma:true */` to the first line of my jasmine scripts.

**Comment by jugglinmike** [comment]
My initial guess is that there is an additional `.jshintrc` file in an intermediate directory between your test file and the RC file whose contents you have shared here. Without more detail, though, it's difficult to say what is going wrong. Is the source code of your project available online?

**Comment by a11smiles** [comment]
Nope, no additional .jshintrc anywhere except in the main project folder.  JSHint was never added to the project until I did so.  And, unfortunately, this is a private project - not on github.

**Comment by jugglinmike** [comment]
I'm not sure what it could be about your test files that are causing the configuration to be ignored. Without an example, I'm not able to diagnose further, though. Could you put together a demonstration that you are able to share publicly?

**Comment by jugglinmike** [comment]
Without more information, we won't be able to resolve this issue, so I'm going to close it. If anyone is able to share a minimal test case, we can re-open and continue the investigation.
