### ISSUE TITLE
Minor issue (throws Unknown Exception) with cause

### ISSUE THREAD

**Issue by ice-o-metric** [jshint/jshint#2873]
This syntax error causes an exception in JShint:

In an otherwise working piece of JS code, add the following line "**typeof();**" and attempts to use JShint in that file will now instead create an alert with the text 'Unknown Exception'

**Comment by nicolo-ribaudo** [comment]
Which version are you using? This might have been fixed by a32cf50

**Comment by jugglinmike** [comment]
I'm going to close this for lack of information. @ice-o-metric if you can provide the version you are using, we can re-open and discuss a solution.
