### ISSUE TITLE
"ES5 option is now set per default" exits code 2

### ISSUE THREAD

**Issue by emaiax** [jshint/jshint#2874]
I'm getting "ES5 option is now set per default" when using `esversion: 5` on my `.jshintrc`. After that, `jshint` exits code 2.

Is that normal since it's an Info Message? I can't get rid of that message.

```
$ jshint --verbose test.js
test.js: line 0, col 0, ES5 option is now set per default (I003)

1 error
$ echo $?
2
$ jshint --version
jshint v2.9.1
```

**Comment by jugglinmike** [comment]
This has been the case for a long while (at least going back to 2.5.0), but I can see no reason to keep the behavior. Wondering what @rwaldron thinks

**Comment by wjdenny** [comment]
Having the same problem. Downgrading to 2.8.0 and commenting out the esversion: 5 option in .jshintrc seems to fix it enough for me to keep working.

**Comment by jugglinmike** [comment]
I've opened https://github.com/jshint/jshint/pull/2900 to address this.

**Comment by jugglinmike** [comment]
We've resolved this by removing the "info" message entirely--see gh-2900.
