### ISSUE TITLE
How to suppress warning: `Unreachable 'break' after 'return'`

### ISSUE THREAD

**Issue by jaepage** [jshint/jshint#2878]
For CSSLint, I add an `"ignore"` array to my SublimeLinter `"linters"` object, and I name the warnings/errors I want to suppress as strings. I can't find documentation for how to do this with JSHint, please. 

I'm also aware of a method of listing prefs in a `~/.jshintrc` config file, but I don't see the option listed at: http://jshint.com/docs/options/

**Comment by nicolo-ribaudo** [comment]
You can suppress warnings (but not errors) using their code:

```json
{
  "-W027": true
}
```

**Comment by jaepage** [comment]
That flag appears to suppress all warnings, which is not desired.

**Comment by jugglinmike** [comment]
Disabling a warning by code suppresses only warnings matching that code. It sounds like exactly the functionality you are looking for. You can read more about it on the main documentation page here: http://jshint.com/docs/

**Comment by jaepage** [comment]
By disabling via code, do you mean inline code? I am looking to set a global preference.

**Comment by jugglinmike** [comment]
In this context, by "code" I mean "machine-readable identifier"--that's `W027` in the example above. As @nicolo-ribaudo's comment demonstrates, you can disable in this manner either by special comments within the JavaScript source file itself or through an external configuration file named `.jshintrc`.

**Comment by jaepage** [comment]
I've double-checked, and adding `"-W027": true` to my `~/.jshintrc` file indeed suppresses only the unwanted error type, and not all error types. I'm unsure why this appeared not to be the case the first time. 

Would anyone be able to point me to where this W flag is documented? [Searching `site:jshint.com W027`](https://www.google.com/search?q=site%3Ajshint.com+W027&oq=site%3Ajshint.com+W027&aqs=chrome..69i57j69i58.2046j0j4&sourceid=chrome&es_sm=91&ie=UTF-8) produces no results. Thank you.

**Comment by nicolo-ribaudo** [comment]
If you run JSHint using the `--verbose` flag, it will print the error code next to each message.

```
jshint file.js --verbose
```

**Comment by jugglinmike** [comment]
Glad it worked out for you!
