### ISSUE TITLE
Disable W*** errors on command line

### ISSUE THREAD

**Issue by brandonros** [jshint/jshint#2896]
Is there a way to add errors such as:

* W061
* W002
* W100
* W051

to a configuration file or command line? It seems that if a cute nickname doesn't exist, the error needs to be documented individually in each file in a header?

Any way to circumvent that?

**Comment by jugglinmike** [comment]
This is certainly possible! You'll want to check out the project's
documentation for all the details (http://jshint.com/docs/), but I'll summarize
from that page:

> There are three main ways to configure your copy of JSHint: you can either
> specify the configuration file manually via the --config flag, use a special
> file .jshintrc or put your config into your projects package.json file under
> the jshintConfig property.

And a little later further on the same page:

>     $ jshint --verbose myfile.js
>     myfile.js: line 6, col 3, Unnecessary directive "use strict". (W034)
>
> Then, to hide this warning, just add the following snippet to your file:
>
>     /* jshint -W034 */

...though of course, you can also add `"-W034": true` to your .jshintrc file.

Hope that helps!

**Comment by brandonros** [comment]
@jugglinmike I can't thank you enough!

I'm sorry that I found the documentation unclear and had to open this issue.

**Comment by jugglinmike** [comment]
I'm glad you found a solution. If you have any ideas for how the documentation could be improved, please file an issue on the website's repository: https://github.com/jshint/jshint.github.io
