### ISSUE TITLE
GitHub Release entry for v2.9.0 lacks a description

### ISSUE THREAD

**Issue by cvrebert** [jshint/jshint#2897]
Compare https://github.com/jshint/jshint/releases/tag/2.9.0
vs. https://github.com/jshint/jshint/releases/tag/2.9.1

**Comment by jugglinmike** [comment]
The 2.9.0 tag describes a release that was revoked. There is actually no GitHub "release" entry for that tag--that it appears as a description-less release is a peculiarity of the GitHub UI, not an error in the release process.

**Comment by cvrebert** [comment]
My point is that there's no way, looking at only the GitHub Releases, to see what changed since 2.8.0 (other than the bug fixes after 2.9.0 that resulted in 2.9.1).

Here's [2.9.1's GitHub Release description:](https://github.com/jshint/jshint/releases/tag/2.9.1)
> This release comprises all changes from the release candidate phase along with the improvements initially released as version 2.9.0.

How am I supposed to know what those improvements are?

> This release does not itself contain any changes to the codebase. If you are upgrading from version 2.8.0 or earlier, please refer to the previously-published release notes for details on bug fixes and features.

But 2.8.0 has no release notes to detail those features...

**Comment by jugglinmike** [comment]
Oh, now I understand! The canonical source for release notes is the file named
`CHANGELOG.md` in the root of this repository. The GitHub-specific "releases"
are copies of that.

I'm reluctant to re-make a release for this purpose because that would likely
be taken as an endorsement of the project at that tag. That said, your confusion
is understandable and may be shared by others. I've updated the release notes
(and corresponding GitHub "release" page) to be more explicit about the term
"release notes":

```diff
diff --git a/CHANGELOG.md b/CHANGELOG.md
index 246ae80..8e089ae 100644
--- a/CHANGELOG.md
+++ b/CHANGELOG.md
@@ -8,7 +8,8 @@ such regressions. This release comprises all changes from the release candidate
 phase along with the improvements initially released as version 2.9.0. This
 release does not itself contain any changes to the codebase. If you are
 upgrading from version 2.8.0 or earlier, please refer to the
-previously-published release notes for details on bug fixes and features.
+previously-published release notes for details on bug fixes and features--these
+can be found in the project's `CHANGELOG.md` file and on the project's website.
 
 
 <a name="2.9.1-rc3"></a>
@@ -74,6 +75,10 @@ try in your projects and let us know about any surprising behavior!
 <a name="2.9.0"></a>
 # [2.9.0](https://github.com/jshint/jshint/compare/2.8.0...v2.9.0) (2015-09-03)
 
+**Note** This release was revoked shortly following its publication. Please
+refer to the release notes for version 2.9.1 for more information (found in the
+project's `CHANGELOG.md` file and on the project's website).
+
 This release was a long time in the making, but it may not be the most exciting
 version we've published. Most of the changes are internal refactorings that
 were necessary to properly fix bugs. And fix bugs we did! Special thanks go to
```

In the future, I'll try to keep in mind that the notes may be viewed from a number of locations. Does that work for you?

**Comment by cvrebert** [comment]
Perhaps also hyperlink the phrase "2.9.0's release notes" in https://github.com/jshint/jshint/releases/tag/2.9.1-rc1 to https://github.com/jshint/jshint/blob/master/CHANGELOG.md#290-2015-09-03 ?

**Comment by jugglinmike** [comment]
Couldn't hurt

**Comment by cvrebert** [comment]
Good enough for me. Thanks.
