### ISSUE TITLE
Regression: es3:false not working if jshintrc sets es3: true

### ISSUE THREAD

**Issue by Krinkle** [jshint/jshint#2907]
JSHint 2.9.1 is warning for this line:

https://github.com/wikimedia/portals/blob/4c670a7e4b9b9ae8c8c3730214dbc9beec8f5a06/site-stats.js#L38

``` js
    return preq.get( url, preqOptions )
        .then( function( request ) {
            return BBPromise.resolve( request.body );
        } )
        .catch( function( err ) {
```

```
site-stats.js: line 38, col 10, Expected an identifier and instead saw 'catch' (a reserved word).
site-stats.js: line 176, col 55, Missing radix parameter. 
```

The project's `.jshintrc` contains:

``` json
{
    "es3": true
```

But the file overrides it:

```
/* jshint node:true, es3:false */
/* jscs:disable */
```

I can reproduce this at http://jshint.com/ with the following snippet:

``` js
/*jshint es3:true */
/*jshint node:true, es3:false, es5:true */

function httpGet( url ) {
    return url.catch();
}
```

**Comment by jugglinmike** [comment]
Thanks for the report! Here's a further reduced test case:

```js
// jshint es3: true
// jshint es3: false, es5: false

void [].catch;
```

We'll need to fix this, but the preferable solution should actually work for you right now--use the new `esversion` option to specify this. (Of course, that has its own issues--https://github.com/jshint/jshint/pull/2900, but based on your use case, I don't think that will be a problem.)
