### ISSUE TITLE
yield statement in nested try/catch block triggers warning

### ISSUE THREAD

**Issue by eloquence** [jshint/jshint#2911]
Issue #1505, which was resolved in 2014, addressed issues with the warning "A yield statement shall be within a generator function" being triggered in try/catch blocks. There continues to be an issue with parsing nested try/catch blocks like the below, however:

```javascript
function* gen() {
  try {
    // Some code
  } catch(e) {
    try {
      // Some code
    } catch(e) {
      yield; // Triggers warning
    }
  }
  yield;
}
```

I don't see anything wrong with the statement which triggers the warning: it's still inside a generator function.

**Comment by jugglinmike** [comment]
I can't reproduce the reported behavior in JSHint 2.9.1, but if I revert to
2.8.0, then I do see the warning for `yield`. Could you share the version of
JSHint you are using, and (if prior to 2.9.1) try upgrading to see if that
resolves the problem?

**Comment by eloquence** [comment]
Upgrading resolved the issue for me, thank you. :-) I've closed it, hope that's appropriate.

**Comment by jugglinmike** [comment]
Yup, that sounds good to me. Glad things are working for you again!
