### ISSUE TITLE
_.contains is not a function

### ISSUE THREAD

**Issue by vtdave** [jshint/jshint#2916]
I recently did a `npm cache clear` then `npm install` and now my app complains on start saying:
``` 
Debugger listening on port 5858
c:\Company\my-project\node_modules\jshint\src\jshint.js:5309
        throw err;
        ^

TypeError: _.contains is not a function
    at Object.fud (c:\Company\my-project\node_modules\jshint\src\jshint.js:3605:13)
    at expression (c:\Company\my-project\node_modules\jshint\src\jshint.js:881:32)
    at statement (c:\Company\my-project\node_modules\jshint\src\jshint.js:1632:9)
    at statements (c:\Company\my-project\node_modules\jshint\src\jshint.js:1677:16)
    at itself (c:\Company\my-project\node_modules\jshint\src\jshint.js:5288:9)
    at c:\Company\my-project\node_modules\gulp-jshint\src\lint.js:89:21
    at respond (c:\Company\my-project\node_modules\rcloader\index.js:68:7)
    at respond (c:\Company\my-project\node_modules\rcfinder\index.js:140:7)
    at c:\Company\my-project\node_modules\rcfinder\index.js:124:17
    at c:\Company\my-project\node_modules\rcfinder\index.js:77:13
    at _combinedTickCallback (node.js:376:9)
    at process._tickCallback (node.js:407:11)
```
_.contains was removed from lodash in the 4.x version.

**Comment by jugglinmike** [comment]
That's odd. [JSHint uses "3.7.x" as a version specifier for lodash](https://github.com/jshint/jshint/blob/b554ffe61eabf6e3e3a2876a3a377271da308811/package.json#L52), so it should be insulated from breaking changes in version 4 of that library.

Can you run share the output of `npm ls`, and also the contents of the `package.json` file from JSHint (as installed in your project)?

**Comment by vtdave** [comment]
well...there must have been some gremlins in my folders, I did a HUGE purge and re-ran `npm install` and it seems to work now.

Sorry for the noise.

**Comment by jugglinmike** [comment]
No worries. npm's a great tool, but it can be a little confusing sometimes!

**Comment by francisrod01** [comment]
This problem had never happened before with me until today.

```
[13:57:54] Starting 'scripts'...
Building app scripts now...
/home/myfolder/myproject/node_modules/jshint/src/jshint.js:5493
        throw err;
        ^

TypeError: _.contains is not a function
    at checkPunctuators (/home/myfolder/myproject/node_modules/jshint/src/jshint.js:4996:16)
    at lookupBlockType (/home/myfolder/myproject/node_modules/jshint/src/jshint.js:4888:9)
    at Object.nud (/home/myfolder/myproject/node_modules/jshint/src/jshint.js:2715:21)
```

And the snippet of the problem code.

```js
  ...
/**
   * Test whether a given token is a punctuator matching one of the specified values
   * @param {Token} token
   * @param {Array.<string>} values
   * @returns {boolean}
   */
  function checkPunctuators(token, values) {
    if (token.type === "(punctuator)") {
      return _.contains(values, token.value);
    }
    return false;
  }
...
```

I type the command `npm ls jshint` and ...

```
$ npm ls jshint
website@0.0.2-beta /home/myfolder/myproject
├─┬ gulp-htmlhint@0.3.1
│ └─┬ htmlhint@0.9.13
│   └── jshint@2.8.0 
└── jshint@2.9.5 
```

I run `npm clean cache --force` and the bug remains.
Is it a version bug?

This project doesn't use `lodash` in its dependencies.

**Comment by jugglinmike** [comment]
Make sure you run `npm cache clean`, since `npm clean cache` is not a supported command. Next, you will need to remove your `node_modules` folder and re-install using `npm install`.

Are you still experiencing the error after doing that?

**Comment by francisrod01** [comment]
I run cache clean again and later I updated all of libs of `jshint` node modules and after update the three again with npm update and solved.

**Comment by liberty2015** [comment]
I try to run ```npm cache clean``` , delete the the folder ```node_modules``` and run ```npm install```,but it is not effective.
Then I found my solution as follow:
1. run ```npm uninstall lodash```---->delete the lodash of wrong version
2. run ```npm install lodash@3.7.0```---->install the lodash of right version for jshint
3. then it works well!

**Comment by s0apii** [comment]
Nothing helped, except @liberty2015's comment. Thank you so much!
