### ISSUE TITLE
JS Hint should warn about usage of window.scrollY and scrollX

### ISSUE THREAD

**Issue by tmotyl** [jshint/jshint#2918]
window.scrollY is not available in IE < edge, window.pageYOffset should be used instead.
So JS Hint should warn about it.

**Comment by jugglinmike** [comment]
JSHint already does warn about that:

    $ ./bin/jshint -
    // jshint browser: true, undef: true
    var x = scrollY;
    stdin: line 2, col 9, 'scrollY' is not defined.

    1 error

Are you seeing different behavior than this? Or are you expecting JSHint to
warn about accessing the `scrollY` property of the `window` object
specifically?

**Comment by tmotyl** [comment]
Thanks for the quick answer.
I'm talking specifically about warning that window.scrollY might be undefined (depending on the browser you use). This property is present in Chrome, FF, Safari, but not defined in IE 11.
see
http://help.dottoro.com/ljqklmpm.php

**Comment by jugglinmike** [comment]
Got it. This is essentially a special case of the feature request at gh-2914.
You can see my response there for why we're reluctant to support it. Although,
if many users are interested in this kind of weak check, there might be value
in a configurable option to black list "static" property names.
