### ISSUE TITLE
built-in ES6 typedArray names

### ISSUE THREAD

**Issue by leobalter** [jshint/jshint#2920]
With the exception of `ArrayBufferView` the typedArray global names (including `ArrayBuffer` and `DataView`) should be considered when setting `esversion: 6`.

Ref: https://github.com/jshint/jshint/blob/b1c8d5b68e467f9eea830cd7289fb733a1f8131b/src/jshint.js#L211-L213

**Comment by jugglinmike** [comment]
Thanks for the report! You're right: we need to extend the global identifiers for ES2015 environments.

In the mean time, you may use [the `typed` environment option](http://jshint.com/docs/options/#typed) as a shorthand to introduce those identifiers.

**Comment by sstern6** [comment]
@jugglinmike && @leobalter if no one has started on this I would like to make a PR for this issue.  

From what I understand we would just need to add `ArrayBuffer` and `DataView` here as keys with values of `false`? 

https://github.com/jshint/jshint/blob/b1c8d5b68e467f9eea830cd7289fb733a1f8131b/src/vars.js#L44

Let me know if I can take this one and if this seems like the correct general approach. 

Thank you

**Comment by leobalter** [comment]
This is the list: https://github.com/jshint/jshint/blob/b1c8d5b68e467f9eea830cd7289fb733a1f8131b/src/vars.js#L540-L553

The only item that is not an ES6 global is ArrayBufferView, the other are valid globals.

**Comment by sstern6** [comment]
Sorry misunderstood, thank you, so then `ArrayBufferView` would be added to the list of `ecmaidentifiers['6']` on line 44 to confirm?

**Comment by leobalter** [comment]
actually is the opposite. The items that should be added to `ecmaidentifiers['6']` are:

- ArrayBuffer
- DataView
- Int8Array
- Int16Array
- Int32Array
- Uint8Array
- Uint16Array
- Uint32Array
- Uint8ClampledArray
- Float32Array
- Float64Array

**Comment by sstern6** [comment]
Got it, thank you will have a PR open in the next day or so

**Comment by sstern6** [comment]
@leobalter && @jugglinmike PR open for this issue, let me know if anything else is needed.  Thank you

**Comment by jugglinmike** [comment]
Resolved via gh-2995.
