### ISSUE TITLE
Warning: Path must be a string. Received null Use --force to continue

### ISSUE THREAD

**Issue by xtianus79** [jshint/jshint#2922]
The path seems correct and I even went root to root and it is still giving this error. 

when I run -v it is 

outputing this: 

options: force=false, reporterOutput=null, jshintrc="client/.jshintrc", reporter="/theAppHere/node_modules/jshint-stylish/stylish.js"
Warning: Path must be a string. Received null Use --force to continue.

Update: 

Just to add... this is happening since upgrading from 5.11 to 6.0

**Comment by MrSwitch** [comment]
What version of jshint are you using? I received this error when using v2.5, but not the latest, v2.9.2.

FYI: i was using it through grunt-contrib-jshint (and updated that to resolve this error)

**Comment by xtianus79** [comment]
@MrSwitch my jshint is jshint v2.9.2

**Comment by jeffpeck-intellify** [comment]
I am having the same issue, using jshint v2.9.2

**Comment by jeffpeck-intellify** [comment]
I have found the issue to be when the `reporterOutput` option is set to null. If you change that option to refer to an empty string, jshint will work as expected:

```
options: {
      jshintrc: '<%= baseDir %>/.jshintrc',
      reporterOutput: "",
      ...
```

**Comment by jeffpeck-intellify** [comment]
It appears that the latest not-yet-released version of `grunt-contrib-jshint` does not have this problem. To get the most recent unreleased version:
```
npm install https://github.com/gruntjs/grunt-contrib-jshint.git
```

Alternatively, this can be resolved by simply using `reporterOutput: ""` in your options.

**Comment by MythicAngel** [comment]
Explicitly setting "reporterOutput" fixed the warning in travis-ci build in my case. Thanks.

**Comment by shershen08** [comment]
```"options": {
        "jshintrc": "<%= baseDir %>.jshintrc",```
worked for me, mind no slash "/" after ```<%= baseDir %>```

**Comment by jugglinmike** [comment]
This looks to me like an issue with the Grunt plugin, not JSHint itself. Can anyone who has responded so far demonstrate this problem using JSHint without the plugin?

**Comment by coryasilva** [comment]
I do not have this problem with gulp, but opened an older project today with grunt and observed this issue.  Thanks to @jeffpeck-intellify for the work around; you saved me some time today!

**Comment by Lekensteyn** [comment]
@jugglinmike If I may guess, it is fixed in grunt-contrib-jshint via https://github.com/gruntjs/grunt-contrib-jshint/commit/a0cd3db0638ad860e562e7e12bfff734aa04ac9f.

**Comment by jarimbi** [comment]
Thanks for much for the tip of 'reporterOutput: "",'
I had no clue what was going wrong!

**Comment by flyher** [comment]
After i update the grunt-contrib-jshint from version 0.9 to 1.0, the bug fixed.
my node version: 6.0 and i test it in node version 5.0.
This table is my record.

|node version|grunt-contrib-jshint|grunt dev|message|
|--|--|--|--|
|4.4.3|~0.9.2|success||
|6.11|~0.9.2|build failed|Warning: Path must be a string. Received null Use --force to continue|
|6.11|~1.1.0|success||

**Comment by jugglinmike** [comment]
At this point, it seems fairly conclusive that this problem is with the
`grunt-contrib-jshint` module. Happily, this has been resolved in recent
versions, and for those who can't upgrade just yet, the comments above have
some ideas for workarounds. Thanks, all.
