### ISSUE TITLE
bug in call function without declared

### ISSUE THREAD

**Issue by uxitten** [jshint/jshint#2934]
```
var storage={
  set:function(){
   return 1;
  },
  get:function(){
    this.read();
    return false;
  }
};
```

storage.read not declare

**Comment by nicolo-ribaudo** [comment]
`this` can't be known statically. For example, if you call storage.get like this, this.read *is* declared:

```js
storage.get.call({
    read() {
        return 2;
    }
});
```

**Comment by jugglinmike** [comment]
@nicolo-ribaudo is correct. It would be great if we could catch these bugs, but it's not possible.
