### ISSUE TITLE
[es6] Bad invocation on IIFCs

### ISSUE THREAD

**Issue by aubergine10** [jshint/jshint#2935]
**Version of JSHint being used:** 2.9.2 (I think... installed today via npm)

**Input source code:**
```javascript
( function() {
  // ... code
} )()
```
also for arrow functions:
```javascript
( () => {
  // ... code
} )()
```

**Expected behaviour:** No errors or warnings

**Actual behaviour:** "Bad Invocation"

**Configuration values:**
```
// jshint esversion: 6
// jshint forin: true
// jshint freeze: true
// jshint maxdepth: 4
// jshint node: true
// jshint maxstatements: 11
// jshint singleGroups: true
// jshint futurehostile: true
// jshint curly: false
// jshint strict: global
// jshint undef: true
// jshint unused: true
// jshint varstmt: true
// jshint asi: true
```

**Editor:** Sublime Text 3
Using [SublimeLinter package](http://www.sublimelinter.com/en/latest/) with the [SublimeLinter-jshint package](https://github.com/SublimeLinter/SublimeLinter-jshint), both installed via [Package Control](https://packagecontrol.io/installation).

I followed [these instructions to install jshint](https://github.com/SublimeLinter/SublimeLinter-jshint#linter-installation).

**Possibly related to:** https://github.com/jshint/jshint/issues/2351

**Comment by nicolo-ribaudo** [comment]
I can't reproduce this issue on http://jshint.com

Is there any code before that IIFEs? (Something like this:)

```js
let a = 2

(function () { // JSHint throws an error because you are actually invoking 2() with the function as parameter
    console.log(a)
})()
```

**Comment by aubergine10** [comment]
This is the actual code (which generates same bad invocation error on jshint.com):

```javascript
// jshint esversion: 6
// jshint forin: true
// jshint freeze: true
// jshint maxdepth: 4
// jshint node: true
// jshint maxstatements: 11
// jshint singleGroups: true
// jshint futurehostile: true
// jshint curly: false
// jshint strict: global
// jshint undef: true
// jshint unused: true
// jshint varstmt: true
// jshint asi: true

'use strict'

const sym =(key)=> Symbol.for(`lingo-${key}`)

const LINGO = {
  'content'  :sym('content'),
  'does'     :sym('does'),
  'flag'     :sym('flags'),
  'flags'    :sym('flags'),
  'hasFlag'  :sym('hasFlag'),
  'means'    :sym('means'),
  'method'   :sym('method'),
  'on'       :sym('on'),
  'otherwise':sym('when'),
  'role'     :sym('role'),
  'router'   :sym('router'),
  'when'     :sym('when'),
}

( function() {

  const lingos = [
    LINGO.when, LINGO.otherwise, LINGO.flag, LINGO.flags,
    LINGO.method, LINGO.content, LINGO.role, LINGO.does,
    LINGO.router
  ]

  const builder =(symbol)=> {
    // jshint freeze: false
    // symbols are acceptable way of extending native prototypes
    Array.prototype[symbol] = function(...args) {
      this.forEach( (route,i)=> {
        this[i] = route[symbol](...args)
      } )
      return this
    }
    const fn = function(...args) {
      return (new Route(this))[symbol](...args)
    }
    Function.prototype[symbol] = fn
      Number.prototype[symbol] = fn
      RegExp.prototype[symbol] = fn
      String.prototype[symbol] = fn
  }

  for ( let symbol of lingos )
    builder(symbol)

} )()
```

The `Route` class is defined later in the file...

```javascript
class Route {
 // ...
}
```

It's my understanding that classes aren't hoisted until the whole file has been parsed/compiled, but that [shouldn't cause issue](http://exploringjs.com/es6/ch_classes.html#_class-declarations-are-not-hoisted) with code that's not immediately run (such as the `fn` function which won't be called until much later).

**Comment by nicolo-ribaudo** [comment]
```js
// Try to paste this code in a browser...

const LINGO = { /* ... */ }

( function() {
    /* ... */
} )()
```

is interpreted like this:
```js
const LIGO = ({ /* ... */ }( function () {
    /* ... */
} ))();
```

You need a semicolon before `( function () {` (e.g. `;( function () {`)

**Comment by aubergine10** [comment]
The semicolon before the function did make the warning go away. I wasn't aware of that scenario with asi - looks like I have some reading to do! Thanks for your help!

**Comment by aubergine10** [comment]
Just in case anyone else makes same mistake as I did and finds this ticket, the issue is explained in [this blog post](http://inimino.org/~inimino/blog/javascript_semicolons).

> Unfortunately, there are five tokens that can appear both at the start of a statement, and as an extension of some complete statement A. These tokens are the open parenthesis "`(`", open square brace "`[`", slash or solidus "`/`", and "`+`" and "`-`". Of these, the first two are problematic in practice.

```javascript
a = b + c
(d + e).print()
```

`(d + e)` could be interpreted as parameters for a function `c`:

```javascript
a = b + c(d + e).print()
```
