### ISSUE TITLE
Complaining about arrow functions even with "esversion": "6"

### ISSUE THREAD

**Issue by MtDalPizzol** [jshint/jshint#2966]
I'm using this:

Atom 1.7.3
linter 1.11.11
linter-jshint 2.1.0

My ```.jshintrc``` file only contains ```"esversion": "6"``` and it is located  one level up my project's folder. I'm still getting the following message:

```'arrow function syntax (=>)' is only available in ES6 (use 'esversion: 6')```

Ideas?

**Comment by rwaldron** [comment]
`.jshint` or `.jshintrc`?

**Comment by MtDalPizzol** [comment]
```.jshintrc```. Sorry for that...

**Comment by jugglinmike** [comment]
I believe the problem here is that the value of "esversion" must be a number, not a string. Can you change your .jshintrc file for read as follows, and let us know if that fixes the problem for you?

```json
{
  "esversion": 6
}
```

**Comment by MtDalPizzol** [comment]
Thanks @jugglinmike , that did the trick...

**Comment by jugglinmike** [comment]
Glad to hear it!

For the record, I do not consider this a satisfactory state of affairs. JSHint should issue an error for invalid input, but also accept equivalent String values. I'm going to leave this issue "closed" because we already have one to track this problem: gh-2902.

**Comment by andela-cofor** [comment]
Hound CI Error 'arrow function syntax (=>)' is only available in ES6 (use 'esversion: 6'). I am using eslintrc

**Comment by nicolo-ribaudo** [comment]
JSHint uses `.jshintrc`
