### ISSUE TITLE
NetBeans plugin

### ISSUE THREAD

**Issue by panga** [jshint/jshint#2967]
Hi,

I've developed a NetBeans integration for JSHint, it's available as a verified NetBeans plugin for almost a year.

Please refer it as a IDE plugin in the documentation.

NetBeans Plugin Portal: http://plugins.netbeans.org/plugin/58580
GitHub Repo: https://github.com/panga/netbeans-jshint

**Comment by caitp** [comment]
Hi, would you submit a pull request?

**Comment by panga** [comment]
@caitp Yes, didn't see there was a github pages repository.
Created a pull request https://github.com/jshint/jshint.github.io/pull/43
