### ISSUE TITLE
Line not ignored with single comment 

### ISSUE THREAD

**Issue by rugk** [jshint/jshint#2969]
jshint v2.9.2

I am using Jekyll with Liquid syntax, which is of course not considered valid in JS files by JSHint.
The full description of this problem can be found here: https://github.com/eslint/eslint/issues/6560

So basically you're doing a quite good job as I can use `/* jshint ignore:start */` and `/* jshint ignore:end */` to ignore these lines. 

However ignoring single lines does not work:

```js
/* jshint ignore:start */

// this is successfully ignored
window.myGlobalVar = {{ site.varApplyingForWholeProject }}

/* jshint ignore:end */

// this shows multiple errors and warnings
window.myGlobalVar = {{ site.varApplyingForWholeProject }}  // jshint ignore:line

```

**Comment by nicolo-ribaudo** [comment]
This is related to gh-2858

**Comment by jugglinmike** [comment]
Thanks for the report! This is indeed a problem, but since it is more completely described by the previously-submitted gh-2858, I am going to close it as a duplicate.
