### ISSUE TITLE
Security issue on dependencie

### ISSUE THREAD

**Issue by Peltoche** [jshint/jshint#2973]
Hey! You have a security issue with the dependencie minimatch, you should upgrade the version to >=3.0.2

More info: https://nodesecurity.io/advisories/118

**Comment by jugglinmike** [comment]
Thanks for the report! [Search our issue tracker for "minimatch"](https://github.com/jshint/jshint/search?q=minimatch&type=Issues&utf8=%E2%9C%93) and you'll find that this issue has been reported and fixed on the `master` branch. The next release will include the latest version of that library.

**Comment by odino** [comment]
@jugglinmike can you publish a new release soon? :)
