### ISSUE TITLE
[[FEAT Request]] Add new `no_console_log` check

### ISSUE THREAD

**Issue by moylop260** [jshint/jshint#2979]
Many projects use `console.log` as normal script process... but other ones use `console.log` just to debug but many times the developer missed remove the line after finish the debug.

Other lint tools of other languages catching the `print` sentence, disabled by default, but with the option to enabled if you want.
Example [pylint-print-for-python](https://github.com/PyCQA/pylint/blob/7303fd6948f38867c32b32f9584d1fd768b3b6d6/pylint/checkers/python3.py#L85-L94), [flake8-print-for-python](https://github.com/JBKahn/flake8-print/blob/893f6fa5fe5ea90ed1b91a4ac513329cf389afb7/flake8_print.py#L1) 

Do make sense to add this new check for `jshint` project?

**Comment by jugglinmike** [comment]
Check out [the documentation for the `devel` option](http://jshint.com/docs/options/#devel):

> This option defines globals that are usually used for logging poor-man's
> debugging: console, alert, etc. It is usually a good idea to not ship them in
> production because, for example, console.log breaks in legacy versions of
> Internet Explorer.

So actually, JSHint does not recognize `console.log` by default. If you enable
the `undef` option, then JSHint will warn when it encounters references to the
global `console`.

**Comment by moylop260** [comment]
I got it
Thanks for reply.

**Comment by moylop260** [comment]
For record, I enabled the check `undef` and disabled environment `devel`
I saw the message `'console' is not defined.` Good!
The problem is that I saw too much `'other_var' is not defined`, I was adding manually to `globals` my custom variables but they are too much and very dynamic (for a static check) after that I decided disable the check `undef`

Then I have the same initial problem of a missed check to detect just `console.log`

Do make sense to add this new check for jshint project?
