### ISSUE TITLE
Provide an option to suppress warnings about the `||` construct

### ISSUE THREAD

**Issue by strugee** [jshint/jshint#2980]
It's common to see code like this:

```js
var something = something || {}
```

However, this code throws this warning in JSHint:

> leet.js: line 13, col 37, Expected an assignment or function call and instead saw an expression.

Maybe we should introduce an option to turn off the expression warning for this specific usecase, since this clearly isn't a typo (which is what the `expr` option was designed for, AFAICT).

Although, on the other hand, the `||` operator is more complicated than people expect, and might possibly be misused - see http://stackoverflow.com/a/34707750/1198896 for details. What do people think?

**Comment by jugglinmike** [comment]
I agree about the use case, but actually, JSHint should not currently be issuing a warning for that code. This may be a bug, but I am having trouble verifying. For example, JSHint is not reporting that warning when invoked with that input from the command line:

```
$ echo 'var something = something || {}' | ./bin/jshint -
stdin: line 1, col 32, Missing semicolon.

1 error
```

I've verified this behavior on the `master` branch, version 2.9.1, and a few prior releases as well. To get to the bottom of this, we'll need a few more details--from [the project's contribution guidelines](https://github.com/jshint/jshint/blob/f34428efee2b19da2f97dd168f5d56172649ae85/CONTRIBUTING.md#bug-reports):

> - Version of JSHint being used
> - Input source code (simplified to only contain details necessary to demonstrate the problem)
> - Configuration values
> - Description of expected behavior
> - Description of actual behavior

Thanks!

**Comment by strugee** [comment]
So sorry! I just assumed this was a missing feature, and not a bug. Will add details when I'm home.

**Comment by jugglinmike** [comment]
No problem at all :)

**Comment by strugee** [comment]
OK. So. Here's the offending code:

```js
var setup = function() {
    foo = foobar(),
    bar = baz || "something"+hostname;
};
```

Obviously there's probably a typo in there (`,` instead of `;`). This still doesn't seem like quite the right warning, but fixing the typo _does_ squelch it? So feel free to go ahead and close this if it's not an actual issue.

**Comment by jugglinmike** [comment]
The warning is correct, but the message could probably use some improving.
The details about "assignment or function call" are a bit too specific, and
it's also not clear *why* this expectation is in place. A better phrasing would
be something like, "Expected an expression that typically has a side effect but
encountered an expression that does not."

(In the case of this code, the "expression that does not [typically have a side
effect]" is the capital-E expression itself, as in `foo, bar`.)
