### ISSUE TITLE
Too strict when checking usage of exclamation mark (!).

### ISSUE THREAD

**Issue by wulechuan** [jshint/jshint#2985]
JSHint warns "Confusing use of !" when encouts codes like below:
```
function myFunction(intergerA) {
	intergerA = parseInt(intergerA);
	if (!(integerA > 0)) { // in case the parsed integerA being NaN, the "!(integerA > 0)" is still false
		throw('Invalid intergerA');
	}
}
```

however:
```
function myFunction2(intergerB) {
	intergerB = parseInt(intergerB);
	if (integerB <= 0) { // in case the parsed integerB being NaN, the error wont throw
		throw('Invalid intergerB');
	}
}
```

**Comment by nicolo-ribaudo** [comment]
Please see #780

**Comment by jugglinmike** [comment]
In this case, if you would like to handle NaN values, I would recommend being
explicit:

```diff
 function myFunction(intergerA) {
   intergerA = parseInt(intergerA);
-  if (!(integerA > 0)) {
+  if (integerA <= 0 || Number.isNaN(integerA)) {
     throw('Invalid intergerA');
   }
 }
```

Reason being: expressing this with `!(integerA > 0)` implicitly relies on the
behavior of `NaN > 0`, and the result of that operation is not especially
intuitive. Using `Number.isNaN` is a clear signal that the condition is
intended to recognize (and reject) NaN values.

That said, you may also disable the relevant warning, W018 in one of two ways:

1. for your entire project by placing `"-W018": true` in your `.jshintrc` file
2. For just this case: surround the expression with `/* jshint -W018 */` and
   `/*jshint -W018 */`, as in

   ```diff
    function myFunction(intergerA) {
      intergerA = parseInt(intergerA);
   +  /* jshint -W018 */
      if (!(integerA > 0)) {
   +  /* jshint +W018 */
        throw('Invalid intergerA');
      }
    }
   ```
