### ISSUE TITLE
Upgrade lodash dependency to 4.14.0

### ISSUE THREAD

**Issue by Aashima89** [jshint/jshint#2989]

**Comment by jugglinmike** [comment]
Can you give some explanation as to why you would like this change?

**Comment by Aashima89** [comment]
Shldn't all dependencies be the latest version one's . My project gives me warnings regarding old lodash version since am using jshint as one of dev dependencies.

**Comment by jugglinmike** [comment]
Every new software release has the potential to modify behavior and introduce
bugs. That's an acceptable risk to take if an upgrade will address a known
issue. This is why I asked about the motivation for the request. In the absence
of any tangible benefit, "if it ain't broke, don't fix it."
