### ISSUE TITLE
Object "spread" properties (stage 2 proposal) not supported

### ISSUE THREAD

**Issue by CoericK** [jshint/jshint#2991]
I got something like this

``` js
  args: {
    ...connectionArgs,
  },
```

And jshint its complaining about 
`xpected '}' to match '{' from line 167 and instead saw '...'.`

What should i add to my `.jshintrc`file to allow destructing?

**Comment by jugglinmike** [comment]
JSHint does not currently support this proposed language feature. It recently reached "Stage 2" in the standardization process, though, so we are interested in adding support in a future version.

**Comment by CoericK** [comment]
Oh thank you @jugglinmike, any idea about how can i make jshint ignore it at least?

**Comment by jugglinmike** [comment]
Sure, you'll want to use [the in-line directives](http://jshint.com/docs/#inline-configuration) `jshint ignore:start` and `jshint ignore:end`:

```diff
  args: {
+   // jshint ignore:start
    ...connectionArgs,
+   // jshint ignore:end
  },
```

**Comment by kevlarr** [comment]
Would be great to have JSHint support for this, since it's now Stage 3

**Comment by derwaldgeist** [comment]
+1 for supporting this. It's already widely used in React/Redux

**Comment by saidkholov** [comment]
+1

**Comment by danorton2** [comment]
It's now at Stage 3: https://github.com/tc39/proposal-object-rest-spread

**Comment by israbbani** [comment]
+1 for getting this done. Thanks guys!

**Comment by dcantatore** [comment]
+1 would enjoy this very much

**Comment by elmargasimov** [comment]
+1

**Comment by leonardolessa** [comment]
+1

**Comment by jugglinmike** [comment]
Support for this language feature has been merged to the `v2.10.0` feature branch (via gh-3150), so we expect it to be included in the next minor release of JSHint. I'll label this issue as "has PR" to better communicate this status.

**Comment by iSkore** [comment]
Just a few days ago they announced:

>Support for this language feature has been merged to the v2.10.0 feature branch (via gh-3150), so we expect it to be included in the next minor release of JSHint. I'll label this issue as "has PR" to better communicate this status.

But this is how I fixed it:

Add *BOTH* `esnext` and `esversion` to your `.jshintrc` file:

```
...
"esnext": true,
"esversion": 6,
...
```

**Comment by renphi** [comment]
+1 can't wait for v2.10.0 to be released. Good job! Is there any timeline for v2.10.0?

**Comment by deadlyicon** [comment]
When I have both

```json
{
  "esnext": true,
  "esversion": 6,
}
```

I get the following error:

`Incompatible values for the 'esversion' and 'esnext' linting options. (0% scanned).`

**Comment by chaddjohnson** [comment]
I also get `Incompatible values for the 'esversion' and 'esnext' linting options.` even after installing directly from the `v2.10.0` branch on GitHub.

**Comment by caitp** [comment]
The idea of that error is really "don't use both 'esversion' and 'esnext' (or 'es3', or 'es5'), afaiu.

The text could be clearer, but the goal of the error seems to be "emit warnings so that eventually we can remove these options and people just use 'esversion').

@jugglinmike do you think we should just make it a non-fatal error instead, or otherwise allow explicit 'esversion' to override the legacy version options?

**Comment by jugglinmike** [comment]
@chaddjohnson That branch is available to promote transparency and to enable collaboration. You are of course welcome to run any code in this project, but please understand that we do not endorse the use of unreleased code because we do not have the bandwidth to support it.

@caitp I'd prefer to disallow ambiguity rather than attempt to interpret it. I'll share more detail in a response to your pull request.

**Comment by NatoBoram** [comment]
https://github.com/jshint/jshint/issues/2991#issuecomment-349636400

```
[jshint] Incompatible values for the 'esversion' and 'esnext' linting options. (0% scanned). (E059)
```

https://github.com/jshint/jshint/issues/2991#issuecomment-396695974

```
[jshint] Bad option: 'unstable'. (E001)
```

**Comment by jugglinmike** [comment]
Not at all, @NatoBoram. I'm discouraging the use of unpublished versions of the project.

**Comment by rip3rs** [comment]
Hmmm as anyone found a solution for the:

> Incompatible values for the 'esversion' and 'esnext' linting options. (0% scanned). (E059)

**Comment by ainthek** [comment]
any resolution of this ? when will jshint support LATEST syntaxes ?

**Comment by stefanuddenberg** [comment]
Any word on this? I really appreciate this tool, but needing to litter my scripts with "ignore" comments is the worst.

**Comment by mleonhard** [comment]
Would someone have time to take a look at this?  I'm running 2.9.7 which is the latest version of jshint, inside Atom editor, and my React Native app code is littered with syntax errors about the spread operator in object literals.  Setting "esnext":true in .jshintrc doesn't help.  The tool refuses to work when both "esnext":true and "esversion":6 are set.

If anyone has a workaround that works right now, would you please post it?

**Comment by jugglinmike** [comment]
Support for this feature will be available in JSHint version 2.10.0 which [we expect to release early next
week](https://github.com/jshint/jshint/pull/3273#issuecomment-460023310). I'll mark this issue as "resolved" once that's published.

**Comment by jugglinmike** [comment]
We just released support for object rest/spread in [JSHint version 2.10.0](https://jshint.com/blog/2019-02-05/release-2-10-0/).

**Comment by MJosipovi** [comment]
I am late to the party, but maybe this helps someone.

I had this:
`var tempobject = {};

tempobject.values ={...tempobject.values, name1]: batt}
tempobject.values ={...tempobject.values, name2: temp}`

and replaced it with this:

`var tempobject = {};

var obj1 ={ name1: batt };
var obj2 ={ name2: temp };

Object.assign(tempobject, obj1);
Object.assign(tempobject, obj2);`

Same result for my use case.
Sorry if I got something wrong about this thread, I am still new to all of this. 
Gl&hf.
