### ISSUE TITLE
Computed names for object getters and setters in global scope throws error for missing semi colon

### ISSUE THREAD

**Issue by sstern6** [jshint/jshint#2994]
If you run in global scope of a file:
```
// jshint esversion: 6
let x = 'foo';
get [x]() {
	return 'bar';
}
```
JSHint Throws an Error ` line 3, col 10, Missing semicolon.`.
Jshint seems like it wants a semicolon here `get['x'](); {  return 'bar'; }` to solve the issue.
This happens for setters as well.

This was discovered while making a PR for https://github.com/jshint/jshint/issues/2871.  I do not mind making a PR for this as well.  Let me know if the community would like a PR for this.

Thank you

**Comment by jugglinmike** [comment]
I think there may be a typo on the example you've shared--that is not valid JavaScript. Could you verify?

**Comment by sstern6** [comment]
@jugglinmike sorry!

Must have made an assumption when testing out another patch and applied here.  Youre right, misread the documentation on MDN.  Will  be closing this issue.
