### ISSUE TITLE
latedef: true should warn about right-hand-side uses of variable being defined

### ISSUE THREAD

**Issue by sabberworm** [jshint/jshint#2996]
I have this code:

```javascript
var a = a*2;
```

I would expect jshint with `latedef: true` warning me that my variable `a` is used before it was defined (since the right-hand-side expression of the assignment is evaluated first).

However, no such warning occurs (as of jshint v2.9.2).

**Comment by sabberworm** [comment]
This isn’t even solely a case of `latedef`. Maybe jshint should add an option warning me of using any defined but as-of-yet unassigned variables so that even

```javascript
var a;
var b = a;
```

would yield an error.

**Comment by rwaldron** [comment]
Your understanding of the evaluation order is incorrect. The `var a` is hoisted, and `a` is initialized to `undefined`. Then, the expression on the right hand side is evaluated and its result is assigned to `a`. The evaluation of `a * 2` will result in `undefined * 2` and produces a NaN.

"defined but as-of-yet unassigned" isn't a significant source of syntactic or runtime bugs to qualify as demanding a new rule in JSHint.

**Comment by sabberworm** [comment]
Defined but as-of-yet unassigned is a *very* significant source of bugs that’s why static analyzers will show you any code paths that leave a variable unassigned if it is later used.

As for the hoisting: this is not the point. The aim of jshint is to catch more mistakes than the (very forgiving) language runtime does. That’s the entire point of the “latedef” option. If the option were to take variable hoisting into account, it would be moot since any variable can be used before it is defined if it’s in the same scope…

**Comment by sabberworm** [comment]
Maybe I should add a little context: the reason I filed this bug is that I often make the following mistake:

```javascript
function someThing() {
    return {an: 'object'};
}
function doStuff() {
    var someThing = someThing();
    // do stuff with someThing
}
```

Most of the time this is trivial to find and fix since it’s a `TypeError` as soon as `doStuff` is invoked. But still, it would be really helpful if jshint could catch this for me before I need to run it. And the only thing (apart from the unused `someThing` function) of how jshint could potentially know something fishy is going on is because there was a reference to the `someThing` variable in the same statement as the variable is declared.
