### ISSUE TITLE
check for expected use of typeof operator

### ISSUE THREAD

**Issue by SPGWhistler** [jshint/jshint#2997]
I typed this javascript code:
```javascript
if (someVariable === 'function') {
...
}
```
I expected to check to make sure that someVariable was a function, then execute the code in the condition. I of course, forgot the typeof operator. And obviously, the above is valid javascript code, so no error was thrown.

Jshint could look for standard usages of typeof - and see if there were typical typos around them, like the above, and alert about them.

The obvious problem is that the above is valid javascript - I could actually be trying to detect the string 'function', but its not likely.

**Comment by rwaldron** [comment]
That's definitively lint.
