### ISSUE TITLE
Syntax error when a function expression with a nonempty body is a default parameter in an arrow function

### ISSUE THREAD

**Issue by McBrainy** [jshint/jshint#3002]
I'm using JSHint version 2.9.2. The following code is valid es6 that compiles fine with Babel:

```JavaScript
// jshint esversion: 6
const foo = (x = function () { return; }) => x;
```

But JSHint gives this output:

```
jshint-error.js: line 2, col 46, Expected '(' and instead saw 'x'.
jshint-error.js: line 2, col 47, Expected an identifier and instead saw ';'.
jshint-error.js: line 3, col 1, Unrecoverable syntax error. (100% scanned).

3 errors
```

Notably, there are no errors if the inner function body is empty:
```JavaScript
const foo = (x = function () {}) => x;
```
Nor if the outer function is a function declaration:
```JavaScript
function foo(x = function () {}) {}
```
Nor even if the outer function is a function expression using the old syntax:
```JavaScript
const foo = function(x = function () {}) {};
```

**Comment by jugglinmike** [comment]
Thanks for the report, Brian! I've submitted a fix at gh-3003.

In case you're curious: the `return` statement is a bit of a red herring. The
actual source of the bug is the semicolon token. Weird!

**Comment by McBrainy** [comment]
Wow, that was quick. In case you're wondering what kind of a crazy use case I could have for this, it's [here](https://gist.github.com/McBrainy/9affcb2a0c991613806dda1e9fee45ab), specifically the factorial example, where I first wrote `factAcc` as a long-form function before I realized that recursive arrow functions are possible in default params.
