### ISSUE TITLE
False positive on missing semicolon

### ISSUE THREAD

**Issue by evansb** [jshint/jshint#3005]
The semicolon is not detected on these statements. Tried on the online demo.
```
'Hello' + 'World'; // Missing semicolon
'Hello' + 3; // Missing semicolon
1 + 2; // But this is fine
```

**Comment by DPeled** [comment]
where is the code that need to check if there is semicolon?

**Comment by nicolo-ribaudo** [comment]
This is fixed by gh-2716 and should work in the next JSHint version.

**Comment by rwaldron** [comment]
Thanks @nicolo-ribaudo
