### ISSUE TITLE
Update dependencies (security)

### ISSUE THREAD

**Issue by rwaldron** [jshint/jshint#3008]
According to the badge, these are insecure: https://david-dm.org/jshint/jshint

**Comment by sstern6** [comment]
@rwaldron looks like the security warning is coming from using the temporary lock_file and log_file in cli.js where a user can overwrite the file.  Is there a way to freeze the data or protect the file from being overwritten? 

If I am understanding the problem correctly, I would like to collaborate to make a PR for this if thats ok.  Havent experienced this before but seems like an interesting problem to tackle.

Thanks

**Comment by jugglinmike** [comment]
@sstern6 dependency management is unfortunately a chore that can only be responsibly handled by project maintainers. Thanks for the offer, though.

**Comment by sstern6** [comment]
@jugglinmike no worries, thought I would ask, @rwaldron per https://github.com/jshint/jshint/issues/3007 gave me the go ahead but put the responsibility on you to manage the oversight on the PR  😄 .  Unless you also give me the go ahead as well I will leave this to the core team.

**Comment by jugglinmike** [comment]
Resolved via gh-3010.
