### ISSUE TITLE
Incorrect "used before it was declared" error with default param

### ISSUE THREAD

**Issue by webbedspace** [jshint/jshint#3015]
```
/*jshint esversion:6*/
let x = "";
function f(x = x) {
  return x;
}
```

**Comment by nicolo-ribaudo** [comment]
The error is correct:
![default-params-tdz](https://cloud.githubusercontent.com/assets/7000710/17833602/f9fcbae2-6721-11e6-9d73-0fc94b1793fb.jpg)

**Comment by webbedspace** [comment]
***Is it???***
![](https://i.imgur.com/KxYg522.png)

**Comment by jugglinmike** [comment]
A binding for the `x` parameter is created as "uninitialized" before the
initializer is evaluated. (That outer `x` binding from the `let` statement is
irrelevant.) If you invoke `f` with a value other than `undefined` as the first
parameter, the runtime will attempt to assign that value to the uninitialized
binding and produce a ReferenceError. [Here's the relevant specification
text](https://tc39.github.io/ecma262/#sec-destructuring-binding-patterns-runtime-semantics-iteratorbindinginitialization), in case you're into that sort of thing.

Anyway, it looks like JSHint's behavior is correct here, so I'm going to close
this.
