### ISSUE TITLE
A comment contains a Private Use Area character

### ISSUE THREAD

**Issue by LMLB** [jshint/jshint#3018]
(originally added by by commit 87378cca3c98e1ff4d5be11f6c16a9f24a212e3e)

https://github.com/jshint/jshint/blob/master/src/jshint.js#L4664

> ```
>      //      export default [lookahead  { function, class }] AssignmentExpression[In] ;
> ```

After the word `lookahead`.

Characters from the Private Use Area don't have any inherent meaning or appearance associated with them.

In the [Symbol font](https://en.wikipedia.org/wiki/Symbol_(typeface)), U+F0CF is ∉ (U+2209, 'not an element of'). Maybe this is the intended character?

**Comment by jugglinmike** [comment]
This was likely copy-and-pasted from the spec itself. As a code comment, it
seems pretty benign, but there's no reason to keep the character. Would you
have any interest in replacing it?
