### ISSUE TITLE
Bad option: 'esversion'

### ISSUE THREAD

**Issue by vernak2539** [jshint/jshint#3024]
* Version of JSHint being used: **2.3.0**
* Input source code (simplified to only contain details necessary to demonstrate the problem): below

*cmd run -->* `./node_modules/jshint/bin/jshint ./controllers/**/*.js --config ./gulp/config/jshintrc-node.js`

* Configuration values
./gulp/config/jshintrc-node.js. Also tried with `esversion` as an integer
```json
{
  "esversion": "6", 
  "devel": true,
  "browser": false,
  "node": true,
  "boss": true,
  "bitwise": true,
  "curly": true,
  "debug": false,
  "eqeqeq": true,
  "latedef": false,
  "laxcomma": true,
  "newcap": true,
  "undef": true,
  "shadow": false,
  "strict": true,
  "unused": true,
  "globals": {
    "require": true,
    "requirejs": true,
    "define": true,
    "describe": true,
    "it": true,
    "expect": true
  }
}
```

* Description of expected behavior: Using the esversion flag should work and not give me a bad option

* Description of actual behavior: below
```
$ ./node_modules/jshint/bin/jshint ./controllers/**/*.js --config ./gulp/config/jshintrc-node.js

./controllers/config/config.js: line 0, col 0, Bad option: 'esversion'.

./controllers/config/controllerRegistrar.js: line 0, col 0, Bad option: 'esversion'.

./controllers/error-handlers.js: line 0, col 0, Bad option: 'esversion'.

./controllers/globalisation.js: line 0, col 0, Bad option: 'esversion'.

./controllers/index.js: line 0, col 0, Bad option: 'esversion'.

./controllers/rest.js: line 0, col 0, Bad option: 'esversion'.
```

when using jshint-stylish reporter I get the following message for each file when it sees JS that's ES6 `'import' is only available in ES6 (use esnext option).` It says to use the `esnext` option, but when looking at the docs, it says this will be deprecated and not to use.

**Comment by vernak2539** [comment]
I have tried with v2.9.3 and it works correctly, but v2.3.0 does not

**Comment by rwaldron** [comment]
The `esversion` option didn't exist in v2.3.0—it was introduced in v2.9.0 (original PR: https://github.com/jshint/jshint/pull/2519)

**Comment by vernak2539** [comment]
Wow, i didn't even realise. Go me. Thanks for the spot @rwaldron
