### ISSUE TITLE
Detect duplicates in inner function parameters

### ISSUE THREAD

**Issue by HernanZh** [jshint/jshint#3025]
It seems that jshint doesn't detect duplicate parameters in nested functions. For example:

```
var outer = function(param) {
  var a;
  var b;
  var c;
  var inner = function(param) {
    // outer param can not be reached
  }; 
  // ...
};
```

Another example is when an outer var takes the same name as an inner parameter:
```
var outer = function() {
  var param;
  var inner = function(param) {
    // outer param can not be reached
  }; 
  // ...
};
```
It would be nice if jshint would warn about duplicate variables in both these cases.

The only time when jshint does correctly warn about parameters is when an inner var is named the same as a parameter inside the same context:
```
var outer = function(param) {
  var param;
  //  'param' is already defined.
};
```

**Comment by jugglinmike** [comment]
I think your use case would be addressed by [the `shadow` option](http://jshint.com/docs/options/#shadow).

> This option suppresses warnings about variable shadowing i.e. declaring a
> variable that had been already declared somewhere in the outer scope.
>
> - "inner" - check for variables defined in the same scope only
> - "outer" - check for variables defined in outer scopes as well
> - false - same as inner
> - true - allow variable shadowing

Can you try running with `shadow: outer` and let us know if that's what you're looking for?

**Comment by HernanZh** [comment]
Aha, yes this does the trick! Thank you!
