### ISSUE TITLE
Option to disable "unused" warnings with unused /* global */ definitions

### ISSUE THREAD

**Issue by alphanull** [jshint/jshint#3027]
In my code I use a console wrapper (which is a global) to output debug messages, and I also use the `unused: true` setting, so in order to prevent the resulting warnings if I use this global I added this setting to all my modules: `/* global Consolero */`

So far so good. But the problem is that I use this lib only _sometimes_ in my modules. Some of them have logging, some not. And with newer jshint versions I get the `'Consolero' is defined but never used` error when I do not actually use this global in my code. Now, it would be very tedious for me to always change the jshint options if I need to quickly add (or remove) a log message in a certain module, but I _still_ want to be alerted if I _actually_ define a variable and do not use it.

As I see it actually defining something in my code is not really the same as "defining" something via `global` (you could see it as an indicator that there _may_ be a global instead of that it _has to be_ a global as it works now). So it would be nice if I had an option to specify if `unused: true` only applies to the actual code (as it was before) or if it also checks for unused vars defined in `global` (as it is now).

**Comment by jugglinmike** [comment]
Are you able to use a `.jshintrc` file? If so, the following configuration will
register the global for the entire project without enforcing that it be
referenced in any particular file:

```json
{
  "globals": {
    "Consolero": true
  }
}
```

This would also save you from repeating the configuration across many files.

**Comment by alphanull** [comment]
Yes that solution seems fine. Thank you!
