### ISSUE TITLE
Error fetch failed https://github.com/ariya/esprima/tarball/master

### ISSUE THREAD

**Issue by vicky171981** [jshint/jshint#3028]
while running "npm install" command i am getting below error message:
   error fetch failed https://github.com/ariya/esprima/tarball/master

I saw so many threads with respect to the above issue but no where it is mentioned that how to resolve this issue. looks like a known issue.

**Comment by jugglinmike** [comment]
We'll need more detail before we can help.

- What version of Node.js and npm are you using?
- Can you share the complete output of the command?
- Are you running `npm install` with any arguments? If not, can you try `npm
  install jshint` and report if that fails as well?
- Is JSHint listed as a dependency of your project?

I suspect this is an issue with network connectivity (issues with fetching
dependencies are rarely related to the application code served by npm), but I'm
going to leave this issue open until we have more conclusive evidence.

**Comment by vicky171981** [comment]
Hi, I am new to node, jshint and github usage. I am not using Jshint.
I am working as a CI developer and need to integrate angular js application in Bamboo. While trying to build the application it is throwing the above error message. Yes you are right this is network issue OR precisely it is proxy issue. I am not able to build the application on Bamboo because of proxy settings. 
  If you know how can i bypass the proxy settings so that i can download the necessary node modules that will be really helpful.

**Comment by dkuerner** [comment]
This problem is not related to network connectivity but to the fact that the esprima project moved:
 https://github.com/ariya/esprima
is now
 https://github.com/jquery/esprima

jshint depends on https://github.com/gotwarlost/istanbul/ which in turn depends on esprima.
Make sure your have the latest version of jshint/istanbul. This should then not attempt to fetch
the outdated github link.

**Comment by arunamat** [comment]
I also facing the same issue. All on a sudden the build started failing. It was working perfectly few hours ago.

**Comment by jugglinmike** [comment]
We haven't received any new reports of this issue in about a year, so I think it's safe to conclude that the dependency resolution is all cleared up. If anyone experiences it again, make some noise here and we'll re-open.

**Comment by akshaybsg** [comment]
Still facing above issue.

**Comment by bitmvr** [comment]
Still running into this as well...

```
http fetch GET 401 https://github.com/ariya/esprima/tarball/master 504ms
npm verb stack Error: 401 Unauthorized: esprima@https://github.com/ariya/esprima/tarball/master
npm verb stack     at fetch.then.res (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/fetch.js:42:19)
npm verb stack     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
npm verb stack     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
npm verb stack     at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
npm verb stack     at Promise._settlePromise0 (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
npm verb stack     at Promise._settlePromises (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
npm verb stack     at Async._drainQueue (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
npm verb stack     at Async._drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
npm verb stack     at Immediate.Async.drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
npm verb stack     at runCallback (timers.js:794:20)
npm verb stack     at tryOnImmediate (timers.js:752:5)
npm verb stack     at processImmediate [as _immediateCallback] (timers.js:729:5)
npm verb cwd /Users/jriddle/Projects/Employer/DefaultApplicationName
npm verb Darwin 18.7.0
npm verb argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--verbose"
npm verb node v8.10.0
npm verb npm  v5.6.0
npm ERR! code E401
npm ERR! 404 401 Unauthorized: esprima@https://github.com/ariya/esprima/tarball/master
npm verb exit [ 1, true ]
```

**Comment by Scieon** [comment]
Yeah seems to be an issue with artifactory auth. You can bypass by temporarily removing your `.npmrc` from home directory and directly installing esprima `npm install esprima@https://github.com/ariya/esprima/tarball/master`

**Comment by EugeneBlizniuk** [comment]
while running "npm install" faced the next error:

npm ERR! code E404
npm ERR! 404 Not Found - GET https://codeload.github.com/ariya/esprima/legacy.tar.gz/master
npm ERR! 404 
npm ERR! 404  'esprima@https://github.com/ariya/esprima/tarball/master' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'jshint'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

I've found no solution to resolve the issue, because of this I am making some noise as it was asked above

**Comment by cope** [comment]
or maybe it has to do with the fact that esprima does not have a **master** branch anymore, but has renamed it to **main**, instead?
