### ISSUE TITLE
The image speaks a thousand words. The thousand words: Reassignment within catch block results in "x is already defined" and "x used out of scope" upon using variable

### ISSUE THREAD

**Issue by CrazyPython** [jshint/jshint#3031]
An image says a thousand words:
![image](https://i.imgur.com/GjhlK7p.png)

The red underlines are by JSHint. I'm using the try then ask for forgiveness idiom.
Version 2.9.2

**Comment by nicolo-ribaudo** [comment]
`// jshint funcscope: true, shadow: true`

**Comment by rwaldron** [comment]
@nicolo-ribaudo 👍 

@CrazyPython you've encountered jshint doing what jshint does: catching weird syntax/semantics issues that you should avoid, in this case it's creating vars in blocks that don't actually have block scope. It's clearer to just declare the `var` at the top of the scope and assign as needed: 

```js
function f() {
  var x;
  try {
    x = 1; 
  } catch (error) {
    x = 2; 
  }
  
  console.log(x);
}

f();
```


FWIW, the same warnings exist when written like this: 

```js
function f() {
  if (true) {
    var x = 1; 
  } else {
    var x = 2; 
  }
  
  console.log(x);
}

f();
```
