### ISSUE TITLE
npm script not working with wild cards

### ISSUE THREAD

**Issue by TokenElt** [jshint/jshint#3032]
I am using windows 10.  standard command prompt.  tried jshint *.js  also tried writing a script "lint": "jshint *.js **/*.js"   and both just say they cannot open file *.js or **/*.js  any way to to get this to work in cmd?

c:\Users\Jason.Armstrong\Desktop\TestProjects\npmBuildProcess>npm run lint

> npmbuildprocess@1.0.0 lint c:\Users\Jason.Armstrong\Desktop\TestProjects\npmBuildProcess
> jshint *.js

ERROR: Can't open *.js

c:\Users\Jason.Armstrong\Desktop\TestProjects\npmBuildProcess>

**Comment by jugglinmike** [comment]
JSHint's CLI accepts paths to directories and files. If the path is a directory, it will recursively lint all the files with a `.js` extension contained within (although the extension can be modified with the `--extra-ext` option). For for your NPM script, can you try:

```
   "lint": "jshint ./"
```

**Comment by jugglinmike** [comment]
In lieu of further information, I'm going to consider this resolved. If the above command doesn't suite your needs for whatever reason, please don't hesitate to re-open!
