### ISSUE TITLE
"asi": ture with javascript generator will require semicolon after yield

### ISSUE THREAD

**Issue by likegun** [jshint/jshint#3034]
.jshintrc

``` json
{
    "esversion": 6,
    "asi": true
}
```

---

``` javascript
function *test() {
    yield console.log()
}
```

Warning missing semicolon.

**Comment by jugglinmike** [comment]
I am able to reproduce this bug n JSHint version 2.9.2, but not in JSHint version 2.9.3 (released on August 18, 2016). Can you confirm that you are running version 2.9.3?

**Comment by jugglinmike** [comment]
It's been a couple months since we've heard from you, so I'm assuming that my previous comment cleared up the problem. Drop us a line if you find you're having problems with the JSHint module.
