### ISSUE TITLE
Customize the JSHint 

### ISSUE THREAD

**Issue by Chamiishan** [jshint/jshint#3038]
Hi,

I have created a java script editor which allows to write code in customise java script. I am annotating error and waning in js code using JSHint. It annotates the normal js code but I have some custom apis which I wants to validate. 

Can anyone help me to change the logic of JSHint logic to validate my defined apis?

Thanks
Ishan Jain

**Comment by jugglinmike** [comment]
We may be able to help, but we'll need some more information first. You mention
"custom" JavaScript, which may be an issue. Are you interested in linting code
written in a language that is itself an extension of ECMAScript? Or is your
editor simply providing custom APIs in a standard JavaScript runtime?

**Comment by Chamiishan** [comment]
It is itself an extension of ECMASCRIPT and we use JShint for annotating the error in js source. It supports ECMASCRIPT standard and we have to customize it for annotation of our own custom methods.

**Comment by jugglinmike** [comment]
Linting arbitrary language extensions would require an advanced plugin system
that exposed most of JSHint's internals. There are currently no plans to
implement such a system.

You do have a few options, though:

- You may use [the `ignore` directive](http://jshint.com/docs/) to instruct
  JSHint to skip over blocks of non-standard code
- If you are compiling to standard ECMAScript, you may use the output of your
  compilation process as input to JSHint

Hope this helps!
