### ISSUE TITLE
Erroneous super in class should throw error

### ISSUE THREAD

**Issue by RevanProdigalKnight** [jshint/jshint#3042]
JSHint is not throwing an error when you try to accidentally call `super()` inside of a class constructor when the class is not extending another class.

Example (JSHint 2.9.2 does not complain about this code):
```javascript
class Foo {
  constructor {
    super(); // SyntaxError: super() is only valid in derived class constructors
    ...
  }
}
```

**Comment by nicolo-ribaudo** [comment]
This is addressed by #2572
