### ISSUE TITLE
“Don't make functions within a loop” warning only for functions referencing outside variables?

### ISSUE THREAD

**Issue by mtfurlan** [jshint/jshint#3056]
I'm not sure if this is expected behavior, it's just odd to me that the warning for “Don't make functions within a loop” only warns for some functions created inside a loop.

```
(function(){
  for(var i=0; i<5; ++i){
    var age = 9001;
    //This has a jshint warning, as it uses age
    var cutoffs = [1800,12000].map(function(cutoff){
      return cutoff < age;
    });
    //but this doesn't cause a warning, despite creating a function inside a loop
    var cutoffs2 = [1800,12000].map(function(cutoff){
      return cutoff < 42;
    });
  }
})();
```

**Comment by nicolo-ribaudo** [comment]
It is expected, because functions which don't reference outside vars cannot have unexpected results:

```js
for (var i = 0; i < 3; i++) {
  var x = i * 2;
  setImmediate(function() {
    console.log(x); // This logs 4, 4 and 4
  });
}

for (var i = 0; i < 3; i++) {
  var x = i * 2;
  setImmediate(function(x) {
    return function() {
      console.log(x); // This logs 0, 2 and 4 (because x isn't defined in the for's scope
    };
  }(i * 2));
}

```

**Comment by mtfurlan** [comment]
Yes, I know that is a thing to be careful of, but the warning is not "do not use outside vars, may have unexpected behavior", the warning is “don't make functions within a loop”, which is not the same thing at all.

**Comment by jugglinmike** [comment]
Thanks for the report! This warning was initially reported for *all* functions
within a loop. It wasn't until gh-1887 (released in version 2.5.7) that the
warning was limited to specific cases according to the bindings around which it
closed. The text probably should have been updated at that time, as well.
@mtfurlan would you like to take a stab at re-writing the message?

**Comment by mtfurlan** [comment]
Maybe something like

"Functions inside loops using outside variables can lead to unintended results, understand what you are doing."

Dunno if that fits the tone of jshint, I've only started using it recently. Please modify as necessary.

**Comment by mtfurlan** [comment]
Something like

"Functions declared inside loops using outside variables can lead to unintended results, understand what you are doing."

would accurately describe the warning, I  think.

**Comment by jugglinmike** [comment]
That's much better! I have a few additional ideas:

- "unintended results" is a little vague. Something along the lines of
  "confusion about binding values" would more clearly describe the intent
- The suggestion to "understand what you are doing," isn't particularly helpful
  and may even be taken as condescending by some users (people can be sensitive
  about their code!)

So what do you think about:

> Functions declared inside loops that reference variables in an outer scope
> may cause confusion about binding values.

**Comment by mtfurlan** [comment]
Well that's not much more helpful than "unintended results", it still
doesn't explain it if you don't already know what's going on.

Maybe a short link to a full explanation?

**Comment by iamlikeme-x** [comment]
Perhaps:

> Functions declared within loops referencing an outer scoped variable may lead to ambiguous semantics

or 

> Functions declared within loops referencing an outer scoped variable may lead to confusing semantics

As for a link to a more detailed explanation, this isn't really the job of jshint (imo), and also requires a static page explanation; blog posts etc. can be deleted or modified, meaning the referenced content is either no longer there or invalid.

**Comment by mtfurlan** [comment]
Yeah, links aren't the best idea. As long as it's a unique warning, someone will make a blog post and get linked by google.

I like your second suggestion.

**Comment by jugglinmike** [comment]
@iamlikeme-x followed up with a patch to improve the message (see gh-3058), and that was subsequently released in JSHint version 2.9.5. Thanks for the help, folks!

**Comment by nova76** [comment]
Hi. The following code still gives an error message ("Functions declared within loops referencing an outer scoped variable may lead to confusing semantics.") Why?

`function getPromise(ms){
    return new Promise(function(resolve){
        setTimeout(function(){
            resolve (ms);
        }, ms);
    });
}

var a = [1000,2000,3000];
a.forEach(function(elem){
    getPromise(elem).then(function(d){
        console.log(d);
    });
});

var a = [1500,2500,3500];
for (var index in a){
    getPromise(a[index]).then(function/* here */(d){ 
        console.log(d);
    });
}`
jshint v2.10.2

**Comment by jugglinmike** [comment]
@nova76 The complete warning message includes the name of the variable:

>     Functions declared within loops referencing an outer scoped variable may lead to confusing semantics. (console)

You can avoid this by telling JSHint that `console` won't change:

    /* globals console: false */

Though note that if you end up reassigning that variable elsewhere, this configuration will cause JSHint to warn about the reassignment.

**Comment by nova76** [comment]
@jugglinmike  
There are two similar examples. The first (forEach) is flawless, only the second (For) is faulty. Why? What is the difference?

**Comment by jugglinmike** [comment]
JSHint does not infer that iteration is occurring in the case of the `forEach` callback.
