### ISSUE TITLE
Npm run wont work

### ISSUE THREAD

**Issue by ButuzGOL** [jshint/jshint#3073]
When i run -> jshint ```./**/ui/src/**/*.js``` it works

When i defined it in package.json
"jshint": "jshint ```./**/ui/src/**/*.js```",
and run it -> npm run jshint 
it gives me error ERROR: Can't open ```./**/ui/src/**/*.js```

jshint version v2.9.4

**Comment by jugglinmike** [comment]
JSHint does not perform file glob expansion--this is a feature implemented by
command interpreters like GNU Bash. It appears as though your system is using
two separate shells:

1. When you invoke the `jshint` binary directly, the shell you are using is
   providing the file glob substitution feature
2. When you invoke `npm run jshint`, the `npm` utility is executing the command
   using a shell that does *not* support file glob substitution

It looks like npm allows you to change the shell that it uses, though:

https://stackoverflow.com/questions/23243353/how-to-set-shell-for-npm-run-scripts-in-windows

Hope this helps!
