### ISSUE TITLE
Not getting warnings

### ISSUE THREAD

**Issue by govindrai** [jshint/jshint#3075]
Hello there.

Suppose this is my js file:

```
function o() {
  var x;
  console.log(x);
  x = 3;
}
```

I think i should be getting at least two warning in my Sublime editor: 1) unused function, 2) latedef. I am using SublimeLinter-JSHint in Sublime Text 3.

**Comment by jugglinmike** [comment]
A warning along the lines of "unused function" would be produced for that input if [the `unused` linting option](http://jshint.com/docs/options/#unused) were enabled, as in:

```diff
+// jshint unused: true
 function o() {
   var x;
   console.log(x);
   x = 3;
 }
```

Although you could also enable it via a `.jshintrc` file. If you have this configuration in a `.jshintrc` file and your editor's plugin is not reporting the warning, then there may be a bug in the plugin.

I'm not sure what you mean by, "2) latedef", though. JSHint defines [a linting option named `latedef`](http://jshint.com/docs/options/#latedef), but according to its description, it would not apply to your example--`x` is used after it is defined. Can you give more information about the warning you are expecting?

**Comment by jugglinmike** [comment]
Closing in the absence of further information. If you have a moment to get back to us, we'll be happy to re-open this issue!
