### ISSUE TITLE
No eval warning on var e = eval; e("1+1");

### ISSUE THREAD

**Issue by Xomnom** [jshint/jshint#3081]
http://jshint.com/ doesn't warn about eval in the following code:

var e = eval;
e("1+1");

**Comment by jugglinmike** [comment]
That's true, but unfortunately, identifying this pattern for all but the most
trivial cases is a very difficult problem. For example,

```js
function foo() { return 'eval'; }
var e = window[ foo() ];
e('1 + 1');
```

So while I'm no fan of `eval`, I don't think there is any meaningful way to
address the larger issue here. There's just no substitute for careful code
review!
