### ISSUE TITLE
atom-jshint plugin crashing on jshint Bash script

### ISSUE THREAD

**Issue by xarxziux** [jshint/jshint#3095]
I've been using jshint from the command line for some time now with no problems, but I cannot get the Atom plugin working.  Atom, the atom-jshint plugin and jshint itself are all at the latest versions, but every time the plugin tries to do something it crashes with the following error message:

    Error: c:\Users\me\AppData\Local\node\jshint:2
    basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
              ^^^^^^^

    SyntaxError: missing ) after argument list
        at exports.runInThisContext (vm.js:53:16)
        at Module._compile (module.js:387:25)
        at Object.Module._extensions..js (module.js:422:10)
        at Module.load (module.js:357:32)
        at Function.Module._load (module.js:314:12)
        at Function.Module.runMain (module.js:447:10)
        at startup (node.js:154:18)
        at node.js:416:3
        at ChildProcess.<anonymous> (C:\Users\me\.atom\packages\linter-jshint\node_modules\sb-exec\lib\index.js:56:20)
        at emitTwo (events.js:100:13)
        at ChildProcess.emit (events.js:185:7)
        at maybeClose (internal/child_process.js:850:16)
        at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)

Per that error message, the problem is not with Atom or the plugin but with jshint itself.  Specifically, it's complaining about the second line in this script:

    #!/bin/sh
    basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

    case `uname` in
        *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
    esac

    if [ -x "$basedir/node" ]; then
      "$basedir/node"  "$basedir/node_modules/jshint/bin/jshint" "$@"
      ret=$?
    else 
      node  "$basedir/node_modules/jshint/bin/jshint" "$@"
      ret=$?
    fi
    exit $ret

I'm using Windows 7 with git-bash installed.  I've tried running the line ```basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")``` in Bash and it seems to work fine.  I can run jshint from the Bash command line with no problems, but the Atom plugin can't get past that line.

Do you have any idea what could be the problem here?

**Comment by jugglinmike** [comment]
That error is being reported by the Node.js interpreter, not JSHint. It looks
like you are attempting to parse the Bash script you have shared as though it
were a Node.js program. Based only on the information in your report, I can't
say how this invocation is occurring, but I would start by inspecting the value
of the `$basedir` variable, since the call site seems to be this line:

    node  "$basedir/node_modules/jshint/bin/jshint" "$@"

I don't think this is an issue with JSHint, but I'll keep this issue open for a
bit in case I'm mistaken. Please let me know what you find.

**Comment by xarxziux** [comment]
You're right.  Running the bash script in Node gets the same error message, so something is trying to call a script through Node but I've not been able to trace it down.

I'm closing the issue as it's not directly related to this package.

**Comment by jugglinmike** [comment]
Thanks for getting back to us, and good luck with the bug hunt!
