### ISSUE TITLE
API not working properly in angular 2.

### ISSUE THREAD

**Issue by vidur149** [jshint/jshint#3096]
I am getting javascript from a bin( jsbin ). After that i pass it to JSHINT(soure) to check for errors. But unfortunately an error occurs when i try to do this. The javascript code is as follows,
`window.addEventListener('load',function(){
    var ele = document.getElementById("haha");
    ele.innerHtml = " empty";
});` 

And, i am writing this in my angular2 component:
`this.jsBinService.getBinJs().subscribe( data => { 
    	jshint.JSHINT(data);
    	console.log(jshint.JSHINT.data());
    });`

**Comment by jugglinmike** [comment]
Hmm, I can't reproduce the error (I've included my attempt to reproduce below).
Can you provide some more information:

- The error you are experiencing. Is this a linting error being reported by
  JSHint, or is it JavaScript error being thrown by the run time?
- The version of JSHint you are using

Thanks!

```js
var jshint = require('../jshint');
var src = 'window.addEventListener(\'load\',function(){ var ele = document.getElementById("haha"); ele.innerHtml = " empty"; });'

jshint.JSHINT(src);
console.log(JSON.stringify(jshint.JSHINT.data(), null, '  '));
```

```json
{
  "functions": [
    {
      "name": "(empty)",
      "param": null,
      "line": 1,
      "character": 41,
      "last": 1,
      "lastcharacter": 114,
      "metrics": {
        "complexity": 1,
        "parameters": 0,
        "statements": 2
      }
    }
  ],
  "options": {
    "indent": 4,
    "maxerr": 50
  },
  "implieds": [
    {
      "name": "window",
      "line": [
        1
      ]
    },
    {
      "name": "document",
      "line": [
        1
      ]
    }
  ],
  "member": {
    "addEventListener": 1,
    "getElementById": 1,
    "innerHtml": 1
  }
}
```

**Comment by jugglinmike** [comment]
It's been a few weeks, so I'm assuming you've worked this out. Let me know if that's not the case, and we can re-open this issue.

**Comment by vidur149** [comment]
Issue is resolve d thanks:)😃
