### ISSUE TITLE
Feature request: Add --cache flag to speedup linting

### ISSUE THREAD

**Issue by niroyb** [jshint/jshint#3107]
## Description of problem the feature solves
This will speedup linting by caching the files that have already been linted and only check them if they have been modified.
## Outline of the feature's intended operation
When jshint is run with `--cache=true` create a cache file named `.jshintcache` containing the cached results.
## List of any edge cases/exceptional circumstances, and how they should be addressed
This is a feature of eslint that would be nice to have here.
The format of .eslintcache is:
```
{
"FILEPATH": CACHE,
"FILEPATH": CACHE
}
```

Where CACHE is
```
{"size":1194,"mtime":1487283060085,"hashOfConfig":"dchznq","results":{"filePath":"FILEPATH","messages":[],"errorCount":0,"warningCount":0}}
```

**Comment by jugglinmike** [comment]
This sounds like a great idea! I suggestion one modification to your proposal:
the cache file should specify the version of JSHint that wrote it. This would
avoid confusion around the state of the cache (and the behavior of the CLI)
immediately following upgrades, and it would allow us to change the cache file
format between major releases.

I would definitely entertain a patch implementing this feature.
