### ISSUE TITLE
switch case if/else confuses parser

### ISSUE THREAD

**Issue by SheetJSDev** [jshint/jshint#3108]
JSHint correctly determines that a case block with a simple if statement will terminate:

```js
switch(x) {
  case 1:
    if(x) return;
    return;
  default: break;
}
```

However JSHint is tripped up if the main path is replaced by an else:

```js
switch(x) {
  case 1:
    if(x) return;
    else return; // <-- Expected a 'break' statement before 'default'.
  default: break;
}
```

Other static analyzers like flow correctly recognize that all paths return.  To verify, here's a sample where JSHint accepts the code but flow complains that a line is unreachable:

```js
switch(x) {
  case 1:
    if(x) return;
    else return;
    break; // <-- JSHint thinks this is reachable, flow does not
  default: break;
}
```

**Comment by jugglinmike** [comment]
Thanks for the report! This is a bit of an edge case, but it is definitely
incorrect, so I'm assigning it a mid-level priority. Is there any chance you'd
like to help us out with a fix?

**Comment by jugglinmike** [comment]
Whoops! We'll need to keep this open to avoid forgetting about the bug

**Comment by SheetJSDev** [comment]
There are actually simple workarounds in this case, as shown in the first code block.  That was our original way to address the issue.

Since then we've discovered other bugs like #3116 and internally decided to move away from jshint.  Feel free to make a new issue if it's still relevant for you.
