### ISSUE TITLE
Comparison operators `==`/`!=` reported too aggressively

### ISSUE THREAD

**Issue by jugglinmike** [jshint/jshint#3109]
The `eqeqeq` option's description states, "This options prohibits the use of ==
and != in favor of `===` and `!==`." Enabling it will cause JSHint to issue
warning W118 for offending code. However, JSHint will issue a separate warning
(W041) if either side of the comparison is a "falsey" literal value,
*regardless of the value of the `eqeqeq` option*.

**If you are a contributor looking to submit a fix for this bug**, remove W041
altogether. This is a shame because it makes JSHint less strict by default, but
the current behavior is inconsistent and confusing. And while the warning
message for W041 is far more descriptive (and therefore a better choice to keep
around), we can't change W118 in-place outside of a major version release. This
should be relatively straightforward, so I'm marking this issue as a "good
first bug."

**If you are a user struggling with this bug today**, disable W041 in your
project configuration, either with an in-line directive:

```js
// jshint -W041
```

Or within a JSHint configuration file:

```js
{
  "-W041": true
}
```

**Comment by sunilkumarc** [comment]
@jugglinmike I would like to work on this bug.

**Comment by jugglinmike** [comment]
It's all yours, @sunilkumarc!

**Comment by sunilkumarc** [comment]
Hi @jugglinmike. Which version of Node.js should I use to test the project? I have version 6.9.5 installed and the below test is failing when I do `npm test`

![image](https://cloud.githubusercontent.com/assets/3911000/24075216/249f9f2e-0c3d-11e7-93bc-2043e29856dd.png)

**Comment by jugglinmike** [comment]
It looks like you've found a bug in JSHint's browser testing code when run on
Windows. I believe updating to the latest Node packages will resolve the
issue, so I've done that. Could you fetch the latest version of the `master`
branch and try again?

(We're not currently running browser tests in the Windows continuous
integration environment but only because doing so would not surface any new
bugs in JSHint itself. That said, it would help us catch development problems
like this, so I've enabled that as well.)

**Comment by sunilkumarc** [comment]
@jugglinmike It is working now. Thanks a lot for taking care of it.

Btw, this is what I'm thinking of to fix this issue. Search for all the occurrences of *W041* in the project and remove all the code related to this message. Is this fine? Or there will be some issue with this fix?

**Comment by jugglinmike** [comment]
> Thanks a lot for taking care of it.

My pleasure!

> Is this fine? Or there will be some issue with this fix?

That sounds about right to me.

**Comment by sunilkumarc** [comment]
Since this is my first time contributing to jshint, I have some questions regarding running jshint locally.  
I have a demo.js file which consists of the below code:
````
var x = 10;

if (x == 0) {}
````

When I run `node bin/jshint demo.js`, I'm getting the error message W116, instead of the expected W041. When I run `node src/jshint demo.js`, I'm not getting any error. Below is the summary of the things that I have tried:
![image](https://cloud.githubusercontent.com/assets/3911000/24078702/e62b9dca-0c9a-11e7-9faf-a0d471fca225.png)

When I run the same code on jshint.com, I get: 
![image](https://cloud.githubusercontent.com/assets/3911000/24078711/4b26ffe4-0c9b-11e7-8ab9-5f1a16e80f76.png)

I'm confused with the different behaviors in different scenarios. So, below are my questions:
+ Which is the main jshint file that I should check my code against?
+ Why W116 is being shown instead of W041 in the first scenario?

**Comment by jugglinmike** [comment]
> When I run `node bin/jshint demo.js`, I'm getting the error message W116,
> instead of the expected W041.

Because you have placed your `demo.js` file in the root of the JSHint project, that command is using the project's existing `.jshintrc` file. [That configuration file enables the `eqeqeq` option](https://github.com/jshint/jshint/blob/6c34960eab150046d0c6b73f280e5ac645840281/.jshintrc#L4), which triggers JSHint to report W116 instead of W041. This is the message we want to preserve. If you'd like to verify the bug, you can either modify your local copy of the `.jshintrc` file, move `demo.js` to a location outside of the JSHint repository, or write the code as a unit test.

> When I run `node src/jshint demo.js`, I'm not getting any error.

That is not a supported usage. If there is any documentation that suggests otherwise, please let me know so we can fix that.

**Comment by sunilkumarc** [comment]
@jugglinmike I have sent a pull request. Please do review it and merge. If it is not correct, please let me know. Thanks :)
