### ISSUE TITLE
Reporting unused variable when it is used in clearTimeout

### ISSUE THREAD

**Issue by Mattwmaster58** [jshint/jshint#3110]
```
function bunction() {
    var hey = setTimeout(function(){alert("hey")}, 250);}
}
clearTimeout(hey)
```
JShint reports that "hey" is a unused variable, even though it's clearly used in clearTimeout.

**Comment by nicolo-ribaudo** [comment]
It is not used: that variable isn't accessible outside of the `bunction` function

**Comment by jugglinmike** [comment]
@nicolo-ribaudo has it right: JSHint is correctly detecting a variable that is not used.
