### ISSUE TITLE
duplicate case statements are not detected

### ISSUE THREAD

**Issue by SheetJSDev** [jshint/jshint#3116]
JSHint should detect and warn if a case clause is duplicated:

```js
  switch(2) {
    case 2: break;
    case 2: break;
    case 3: break;
  }
```

**Comment by jugglinmike** [comment]
Thanks for the report! This is certainly something JSHint could warn about in
limited circumstances. I'd imagine that the instances where this functionality
would be most helpful are the same ones that cannot be detected statically:
when the `case` expression is not a literal value. Prioritizing accordingly.

**Comment by SheetJSDev** [comment]
This is something google closure picked up in our code, and the offending cases were actually static in nature (a really large switch/case block).  That being said, we solved the issue by adding closure to our static checks
