### ISSUE TITLE
Unrecoverable syntax error

### ISSUE THREAD

**Issue by Jawdat-A** [jshint/jshint#3119]
Hi,

 

Does anyone know why I get an unrecoverable syntax error in JSHint?
Below is a script that I have tweaked. The original version was animated.

 

$(document).ready(function(){

$.ajax({
    url: "http://s1.adform.net...4036/8970.xml",
  type: "GET",
    dataType: "xml",
    success: function (xml) {
      
      $(xml).find("Group[name='9']").each(function () {
      var belopp = $(this).find("TextVar[name='summa']").attr("value");
      belopp = belopp.substring(0, belopp.length-3);
      $(".jackpot").html('<h3>Just nu '+belopp+'</h3>');
      });
    }
});
});

 

_________________________________________

 

**The original version**

 

 $(document).ready(function(){

$.ajax({
    url: "http://s1.adform.net...4036/8970.xml",
  type: "GET",
    dataType: "xml",
    success: function (xml) {
      
      $(xml).find("Group[name='9']").each(function () {
      var belopp = $(this).find("TextVar[name='summa']").attr("value");
      belopp = belopp.substring(0, belopp.length-3);
      $(".jackpot").html('<h3>Dr&ouml;mvinsten &auml;r just nu <br /> '+belopp+'</h3>');
        
        var txt = $(".txt");
        var txtIndex = -1;
        var playAnimation = 0;
        
        function playAgain() {
        if (playAnimation <= 4) {
          showNextTxt();
        } else {
          ++txtIndex;
          $(".endframe").show();
          $(".jackpot").hide();
        }
      }
    
      function showNextTxt() {
        ++txtIndex;
        ++playAnimation;
        txt.eq(txtIndex % txt.length).fadeIn(200).delay(3000).fadeOut(300, playAgain);
      }
      
      showNextTxt();
      
      });
    }
});
});

Best,

A

**Comment by nicolo-ribaudo** [comment]
I don't get the error using JSHint v2.9.4.

Does your code work in a browser? If yes, which version of JSHint are you using?

**Comment by jugglinmike** [comment]
I am also unable to reproduce the error with either code sample. Can you please share the version of JSHint you are using, along with any linting options that need to be set in order for the error to occur? Also, please enclose sample code in three "backtick" characters (```) (more detail on Markdown is available here: https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code). This will avoid confusion from GitHub.com's treatment of comment text.

**Comment by Jawdat-A** [comment]
Hi, 
I'm using the latest JSHint v2.9.4. in Firefox. My code seems to work I think. 

```
$.ajax({
  
    url: "https://s1.adform.net/Banners/Elements/Templates/14036/8970.xml",
  type: "GET",
    dataType: "xml",
    success: function (xml) {
      
      $(xml).find("Group[name='9']").each(function () {
      var belopp = $(this).find("TextVar[name='summa']").attr("value");
      belopp = belopp.substring(0, belopp.length-3);
      $(".jackpot").html('<h3>Just nu '+belopp+'</h3>');
      });
    }
});
});

```
![screen](https://cloud.githubusercontent.com/assets/26968482/24902496/a6884390-1eaa-11e7-9b43-ab42067b44b8.jpg)

Thanks,
A

**Comment by jugglinmike** [comment]
The two programs in the initial report contained an invocation of `$.fn.ready` with a callback function that itself contained an invocation of `$.ajax`. Simplified:

```js
$(document).ready(function() {
  $.ajax({
    // etc.
  });
});
```

On my system, JSHint parsed this code without reporting any syntax errors because it is syntactically valid JavaScript. On the other hand, [the sample](https://cloud.githubusercontent.com/assets/26968482/24902496/a6884390-1eaa-11e7-9b43-ab42067b44b8.jpg) in [your latest comment](https://github.com/jshint/jshint/issues/3119#issuecomment-293204598) omits the initial invocation of `$.fn.ready`, as in:

```js
  $.ajax({
    // etc.
  });
});
```

This omission makes the code invalid and explains the reported syntax error. Since your code has always worked, I'm wondering if this was just a case of an erroneous copy-and-paste operation.

**Comment by jugglinmike** [comment]
It's been a few months since we've heard from you, so I'm going to assume that the original report was a copy-and-paste mistake, after all. If you have any more information, please share it here--we'll re-open the issue and continue investigating.
