### ISSUE TITLE
jshint won't load js file that doesn't end in .js

### ISSUE THREAD

**Issue by jmichae3** [jshint/jshint#3122]
jshint won't even load the engine, finds no errors, but browser doesn't load it either.
after 8 seconds on an i7-3970x machine with 64GB RAM, it says
~~~~
atoi64.js-4-15-2017
atoi64.js
l:\atoi64.js:0: can't open file: No such file or directory
~~~~
browsers do work with nonstandard filename extensions, and so should this program.
problem is, the filename is atoi64.js-4-15-2017
http://Jesusnjim.com/atoi64.js-4-15-2017
you can use it for test purposes, I am basically trying to get this debugged.

**Comment by jmichae3** [comment]
j.bat:
~~~~
cls
:lupe
l:\jsl\jsl.exe -nologo -conf l:\jsl\jsl.default.conf -process %1
shift
if not .%1.==.. goto lupe
~~~~

**Comment by jmichae3** [comment]
...if this is the program associated with http://www.javascriptlint.com/ so if it's not, you can close this. for jshint, I would like a windows version that doesn't require npm.

**Comment by jugglinmike** [comment]
JSHint is indeed distinct from "JavaScript Lint." Closing this issue as requested!
