### ISSUE TITLE
Allow the `u` flag in regexes

### ISSUE THREAD

**Issue by thany** [jshint/jshint#3129]
Issue #2369 suggests that this flag has been added, but it's not working yet. I still get this error:
```
Expected ')' and instead saw 'u'
```
When encountering a regex with the `u` flag. The same PR seems to also have fixed allowing the `y`, and that one does indeed work.

I'm using the latest version, 2.9.4.

**Comment by jugglinmike** [comment]
A quick search for "regexp u" returns the following issue:

https://github.com/jshint/jshint/issues/2361

Good news: a patch for this is currently under review at:

https://github.com/jshint/jshint/pull/2369

**Comment by thany** [comment]
You sure? It looked to me like that one only fixes allowing the "y" flag.

**Comment by jugglinmike** [comment]
Yup, from [a comment later on in the discussion](https://github.com/jshint/jshint/pull/2369#issuecomment-272724074)

> Note that we merged support for the y flag in gh-2999 (opened in the time
> since this pull request was first submitted), so this patch now only concerns
> the u flag.
