### ISSUE TITLE
Allow the `**` operator

### ISSUE THREAD

**Issue by thany** [jshint/jshint#3130]
I'm getting an error when using the `**` operator:
```
Expected an identifier and instead saw '*'
```
But it's perfectly fine to use it like that:
```
let x = 2 ** 10;
```
It's not disallowed by a setting, because then it would at least understand the syntax.
And browser support for it these days is [excellent](http://kangax.github.io/compat-table/es2016plus/#test-exponentiation_(**)_operator).

This is on the latest version, 2.9.4.

**Comment by jugglinmike** [comment]
A quick search for "exponentiation" returns this issue:

https://github.com/jshint/jshint/pull/3060

Note that this has been implemented and will be available in JSHint 2.10.0: https://github.com/jshint/jshint/pull/3060
