### ISSUE TITLE
ignore:line option has no effect on scripts with type of text/template

### ISSUE THREAD

**Issue by binarykitchen** [jshint/jshint#3131]
this is probably a rare case. developing a wordpress plugin here using a html file as a template to inject an inline script which works fine. the only problem is that jshint in my atom editor is complaining with this warning

"Expected an assignment or function call and instead saw an expression. (no-unused-expressions)"

understand, it's because of the `{{{` part which makes sense. but the problem is that the `// jshint ignore:line` part at end of this line does not seem to have any effect.

```js
<script id='tmpl-nf-field-videomail' type='text/template'>
  <div id='nf-field-{{{ data.id }}}' name='nf-field-{{{ data.id }}}' class='{{{ data.classes }}} nf-element videomail'> // jshint ignore:line
   ...
</script>
```

maybe this exotic use case isn't covered in jshint?

**Comment by jugglinmike** [comment]
JSHint will only lint the content of a `<script>` tag within HTML if it has no `type` attribute, or if the value of the `type` attribute matches the string "text/javascript". Here's the relevant source code:

https://github.com/jshint/jshint/blob/cc215bde53610e861d5a679131e7095add1bb3f8/src/cli.js#L276-L277

This makes me wonder if the warning you are seeing is being issued by some other code.

As it stands, I'm unable to reproduce the reported behavior with that input. A reproducible test case (either verified via the CLI or via the web site) would help us troubleshoot.

Also concerning is the error message's reference to "no-unused-expressions". [That is the name of an ESLint option](http://eslint.org/docs/rules/no-unused-expressions), and it is not recognized by JSHint.

**Comment by binarykitchen** [comment]
apologies, that error message comes from linter-js-standard. reported it there https://github.com/ricardofbarros/linter-js-standard/issues/188

**Comment by jugglinmike** [comment]
Got it. Thanks for getting back to me!
