### ISSUE TITLE
Export configuration from the website as .jshintrc file

### ISSUE THREAD

**Issue by Sirvasile** [jshint/jshint#3132]
It would be great if we could export the configuration from the website into a .jshintrc file.
Maybe by adding a simple "export" button.
<img width="380" alt="schermata 2017-05-22 alle 00 17 24" src="https://cloud.githubusercontent.com/assets/13590581/26287867/3e0fa4f8-3e84-11e7-8d92-dccb456523bf.png">

**Comment by jugglinmike** [comment]
Nice idea! Would you mind re-filing this against the website repository? https://github.com/jshint/jshint.github.io

**Comment by sholladay** [comment]
The new issue is here: https://github.com/jshint/jshint.github.io/issues/51

This can be closed.
