### ISSUE TITLE
Deprecate Wiki?

### ISSUE THREAD

**Issue by piperchester** [jshint/jshint#3133]
For those three short pages, doesn't feel like there's a good reason to have the Wiki tab.

**Comment by jugglinmike** [comment]
We intentionally maintain those pages so that exiting hyperlinks on the web continue to work. They each simply reference the web page so that folks know where to go from there. I'd be open to other approaches as long as the URLs continue to help people get to where they want to go. Can you elaborate on the problem you would like to solve?

**Comment by piperchester** [comment]
Could we just move the content in the wiki to the primary README in the main repo?

**Comment by jugglinmike** [comment]
I'm wondering if maybe you are being served different content than me. For me, those three pages contain only a single sentence:

> JSHint's documentation is maintained in a dedicated repository
> (https://github.com/jshint/jshint.github.io) and published online at
> http://jshint.com.

Moving this to the project's readme file would conflict with the intention I described above.

I still think I could be more helpful if I understood your goal--could you explain the problem you are trying to solve?

**Comment by piperchester** [comment]
Just trying to reduce noise on the repo - if we can disable the Wiki tab then we'll see Code, PRs, and Insights, and all the documentation will live in the repo.

**Comment by jugglinmike** [comment]
Got it. I'm no fan of noise, but I think a superfluous tab on GitHub.com is preferable to broken links out there on the web. Since those pages are simply pointers to the actual documentation (i.e. they don't contain duplicate or outdated content), I think we'll just leave them as is.

**Comment by piperchester** [comment]
Fair enough - thanks!
