### ISSUE TITLE
Checking of whitespace

### ISSUE THREAD

**Issue by akanshgulati** [jshint/jshint#3137]
Why the latest grunt-contrib-jshint is not validating the syntax of the code. Is there any way I can validate the below code with .jshintrc
**Wrong Code: **
````
if(condition){
     Statements
}
````
**Correct Code**
```
if (condition){
     Statements
}
```
Basically checking space between if and `(`.

**Comment by jugglinmike** [comment]
While JSHint has some code style enforcement rules, they are rather limited and deprecated besides. We recommend [the JSCS project](http://jscs.info/) as a fully-featured means to validate JavaScript code style.
