### ISSUE TITLE
es6 problem

### ISSUE THREAD

**Issue by zhoujiamin** [jshint/jshint#3138]
I'm making a Javascript class,it is  vaild。
``` 
class MyClass {
  static myStaticProp = 42;

  constructor() {
    console.log(42); // 42
  }
}
```
but jshint show:
in lin2,: static myStaticProp = 42;
```
 Class properties must be methods. Expected '(' but instead saw ')'.
```

 
 
### jshint 
jshint v2.9.4

### .jshintrc
{
  "asi": true,
  "laxcomma": true,
  "es5": true,
  "node": true,
  "strict": false,
  "esnext": true
}

**Comment by jugglinmike** [comment]
The code you have shared is not valid according to the more recent language standard. Specifically, it makes use of the proposed language extension, [public class fields](https://tc39.github.io/proposal-class-public-fields/). [That proposal is currently at stage 2 in the standardization process](https://github.com/tc39/proposals/blob/6b797c96eae90064af3634155bab6aefd31618f7/README.md), however, so [in accordance with our policy on new language features](http://jshint.com/blog/new-lang-features/), we would accept a patch to support it on an experimental basis. I've created a new issue to track the status of the feature request: https://github.com/jshint/jshint/issues/3139

**Comment by williamd5** [comment]
I believe this is part of the language now, yet...
![image](https://user-images.githubusercontent.com/66572326/135753720-655ff51a-0639-4880-8aaf-38ba495fba38.png)
