### ISSUE TITLE
if (0 == (t % 6))  doesn't need a '===' warning

### ISSUE THREAD

**Issue by jbmonroe** [jshint/jshint#3147]
When the type of the non-constant argument can be determined (x % y can't produce a boolean or a string) then there's no need to use '===' for the comparison because the types are the same on both sides of the operand by definition.  I know I can 'pragma' my way around this, this seems like an easy catch.  (Perhaps not an easy fix, though, because '+' would need the test, while * and / wouldn't.)

If it's not trivial to implement or not worth the effort, feel free to close it out.  I ran into this with some new code this morning and my response was "seriously?"  Could be a personal problem. ;)

**Comment by rwaldron** [comment]
Thanks for the report, but I think you were right on when you said: 

> If it's not trivial to implement or not worth the effort

Guarding against use of `==` is general purpose, and making it subject to evaluation for every specific use, in every possible context, will be likely very expensive.
