### ISSUE TITLE
Extra column in W043 result

### ISSUE THREAD

**Issue by Arcanemagus** [jshint/jshint#3152]
When linting the following code JSHint v2.9.5 reports the error as being one column past the end of the input:

```js
var myText = "Line part1 \
Line part2"
```

It reports an error on column 28, when that line only has 27 characters:

```
> jshint .\foo.js
.\foo.js: line 1, col 28, Bad escaping of EOL. Use option multistr if needed.
.\foo.js: line 2, col 12, Missing semicolon.

2 errors
>
```

The line ending of the file doesn't seem to make a difference, but just in case here are the raw files used to test this bug: [linter-jshint_GH434.zip](https://github.com/jshint/jshint/files/1115885/linter-jshint_GH434.zip)

_Note: Originally filed as https://github.com/AtomLinter/linter-jshint/issues/434._

**Comment by jugglinmike** [comment]
Verified. Further reduced:

    "\
    ";

Output:

    gh-3152.js: line 1, col 4, Bad escaping of EOL. Use option multistr if needed. (W043)

Thanks for the report!
