### ISSUE TITLE
Should warn about unused argument

### ISSUE THREAD

**Issue by Ashutosh-Tripathy** [jshint/jshint#3154]
Shouldn't jshint warn about unused argument in below code snippet?

function one(a, b) {
    return a;
}

function two(a, b) {
    return b;
}

jshint v2.9.5
node v6.11.0
os win10

**Comment by jugglinmike** [comment]
It certainly should! It does on my system (same JSHint version, Ubuntu Linux):

```
$ ./bin/jshint -
// jshint unused: true
function one(a, b) {
  return a;
}

function two(a, b) {
  return b;
}
stdin: line 2, col 17, 'b' is defined but never used.
stdin: line 2, col 10, 'one' is defined but never used.
stdin: line 6, col 10, 'two' is defined but never used.

3 errors
```

This might seem silly, but can you verify that the `unused` option is set?

**Comment by Ashutosh-Tripathy** [comment]
<img width="710" alt="unused" src="https://user-images.githubusercontent.com/12702948/27873123-99ee1b44-61c8-11e7-94c0-055ff46162bb.png">

I think by default "unused" is false. After explicitly enabling, it is working fine (Should it warn about unused variable a in function two?)

**Comment by murilodaluz** [comment]
Hi, i noticed that the check happens from the last to the first, and stop in to the first true.
Ex:
function potato(a, b, c){
     return b;
}

The only warn is about the last variable 'c'.
Shouldn't it warn about unused variable 'a'?

**Comment by jugglinmike** [comment]
@Ashutosh-Tripathy @murilodaluz That behavior is intentional. Check out [the
documentation of the `unused` option](http://jshint.com/docs/options/#unused):

> When set to `true`, unused parameters that are followed by a used parameter
> will not produce warnings. This option can be set to `vars` to only check for
> variables, not function parameters, or `strict` to check all variables and
> parameters.

Anyway, it looks as though this is not a bug, after all. Let me know if I'm
mistaken, and we can re-open this issue.

**Comment by murilodaluz** [comment]
Thanks!
