### ISSUE TITLE
What about async/await for node 8 

### ISSUE THREAD

**Issue by Simobain** [jshint/jshint#3155]
Hi,
I'm having errors with jshint due to async/await new feature in node 8.
Is there a plan to add them ?

Thanks

**Comment by jugglinmike** [comment]
Hi @Simobain,

[Searching this project's open issues for "async"](https://github.com/jshint/jshint/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20async) turns up the following:

[gh-2604: Experimental support for async functions](https://github.com/jshint/jshint/issues/2604)

So let's track this feature request there.

**Comment by csrl** [comment]
#2604 calls it out as "experimental" and is marked as depending on #2601.  At this date, neither seems appropriate.  Perhaps #2604 could be closed out and refreshed here or else where, given that it has been fully adopted and many code bases are moving over to using it.
