### ISSUE TITLE
[Feature Request] The "forin" option doesn't parse if statements robustly enough

### ISSUE THREAD

**Issue by Zamiell** [jshint/jshint#3156]
As per the documentation, the "forin" option expects code to be in the following format:

```
for (key in obj) {
  if (obj.hasOwnProperty(key)) {
    // We are sure that obj[key] belongs to the object and was not inherited.
    console.log("Key", key, "found:", obj[key]);
  }
}
```

However, this same code is also often written as:

```
for (key in obj) {
  if (obj.hasOwnProperty(key) === false) {
    continue;
  }

  // We are sure that obj[key] belongs to the object and was not inherited.
  console.log("Key", key, "found:", obj[key]);
}
```

This second form is functionally equivalent, and in some sense neater, because it reduces nesting/indentation. However, this second form baffles jshint and it reports that you haven't coded your "for-in" loop correctly.

Can the logic be updated so that this second form doesn't result in any errors?

**Comment by jugglinmike** [comment]
JSHint could be updated to recognize that particular pattern, but I think we'd
be fighting a losing battle. There are an infinite number of ways to express a
"safe" usage of the `for/in` statement, and we'd never be able to detect them
all statically. I know you're not asking to boil the ocean here, but you are
(to my knowledge) the first person to request support for that particular
pattern. I'd like to set the bar a little higher for interest before
complicating that logic, especially considering that the new(ish) `for/of`
statement addresses this problem at the language level.

**Comment by Zamiell** [comment]
A minor quibble:
In this context, the `for/of` loop doesn't replace the `for/in` loop, does it?
It was my understanding that the new `Object.entries()` replaces it, like in the following:
```
Object.entries(obj).forEach(
    ([key, value]) => console.log(key, value)
);
```

**Comment by jugglinmike** [comment]
I was writing with the imperative style of the original example in mind. A rough equivalent might look like this:

```diff
-for (key in obj) {
+for (key of Object.keys(obj)) {
-  if (obj.hasOwnProperty(key) === false) {
-    continue;
-  }
-
   // We are sure that obj[key] belongs to the object and was not inherited.
   console.log("Key", key, "found:", obj[key]);
 }
```

...but there are many ways to skin a cat :) Your approach is certainly a viable alternative as well. It's just a little more functional in nature.
