### ISSUE TITLE
Why the W067 Bad invocation?

### ISSUE THREAD

**Issue by omalinov** [jshint/jshint#3161]
Hello,

I have the following code inside an HTML file:
```javascript 
<script class="local-events">(function(){
  document.getElementById("div3").addEventListener("click", function() { changeSceneTo(3); });
  document.getElementById("div4").addEventListener("click", function() { changeSceneTo(1); });
  document.getElementById("cupsProgress").addEventListener("click", function() { engine.trigger.apply(engine, ['ChangeMat']); });
  document.getElementById("gameSession").addEventListener("click", function() { changeSceneTo(1); });
})();
</script>
```
When I use
```shell
jshint --extra-ext=html --extract=auto --verbose .
```

I get a W067 Bad invocation on the 1st column of the row with the opening script tag. I have a similar situation in another file and it doesn't produce the error. 

Any ideas?

**Comment by rwaldron** [comment]
What version of JSHint are you using?

**Comment by omalinov** [comment]
v2.9.5

**Comment by jugglinmike** [comment]
I've created an HTML file with the supplied markup and invoked JSHint as reported, but this does not produce any warnings on my system. The sample code may be missing an important detail, a local `.jshintrc` file may contain some configuration that is necessary to produce this behavior.

[As documented in our contribution guidelines](https://github.com/jshint/jshint/blob/master/CONTRIBUTING.md#bug-reports), we will need some additional information before we can help:

> - [x] Version of JSHint being used
> - [ ] Input source code (simplified to only contain details necessary to
>   demonstrate the problem)
> - [ ] Configuration values
> - [x] Description of expected behavior
> - [x] Description of actual behavior

**Comment by omalinov** [comment]
The source code is quite big but an overview of what is contained is:
https://pastebin.com/49vCZzsx 

The script that throws the error starts at line 28 and is identical to the one in the file.
The folders of my project are as follows:
`Main [.jshintrc file is here]/Secondary/Third/Code Folder/[all the code is here]`
I use
`jshint --extra-ext=html --extract=auto --verbose .`
from the Code Folder and I get the bad invocation error.

My `.jshintrc` file looks like this:
```javascript
{
  "bitwise": true,
  "curly": true,
  "eqeqeq": true,
  "futurehostile": true,
  "latedef": true,
  "maxerr": 100,
  "nocomma": true,
  "nonbsp": true,
  "nonew": true,
  "shadow": "inner",
  "maxcomplexity": 5,
  "maxdepth": 3,
  "maxparams": 3,
  "maxstatements": 10,
  "asi": true,
  "browser": true,
  "globals": {
    "engine": true
  }
}
```

**Comment by jugglinmike** [comment]
This new demonstration file has invalid markup due to an unclosed `script` tag:

    <style >
    // A bunch of styles
    </style>
    <script>
    // Version variables
    <style>
    // Random empty style
    </style>

I can correct that locally, but the resultant document does not produce the
reported warning. I suspect that there is a critical detail of the input text
that is missing from the bug report. Please understand that it is difficult for
us to help if we only have unverified approximations of the error conditions.
It seems as though you may be unable to share the complete file directly, so I
would ask that you build some smaller version that you can verify produces the
incorrect behavior.

**Comment by jugglinmike** [comment]
We can't move forward on this without more information. Since it's been a bit since we've heard from you, I'm going to close this issue for now. We can re-open if you or anyone else can follow up.
