### ISSUE TITLE
"Functions declared within loops referencing an outer scoped variable may lead to confusing semantics."is this truly accuracy？

### ISSUE THREAD

**Issue by The0leaner** [jshint/jshint#3163]
I'm not sure if this is expected behavior,and it happened in [jshint.com](http://jshint.com/)
# 01 no warning
for (var i=0; i < 100; i++ ){
  (function(){return 1;})();
}
#02 warning like "Functions declared within loops..."   
for (var i=0; i < 100; i++){
		(function(){
      i = 10;
   
    })(a); 
   }

#03 no warning if
function foo(){
      i = 10;
   }
for (var i=0; i < 100; i++){
		(foo)(a); 
   }
I just simplified code and I will feel sorry if it is just of my own fault though I just get confused in such a situation.

**Comment by rwaldron** [comment]
- Example 1 doesn't reference any variable from an outer scope
- Example 2 attempts to assign a value to a variable from an outer scope
- Example 3 assigns the value `10` to a variable `i` which is going to be bound to the global object because there is no `var` (it's not going to refer to the `i` in the for-loop.

**Comment by Lord-Evil** [comment]
![image](https://user-images.githubusercontent.com/3912626/218607992-1313009c-1840-4580-9c6c-c2373284eac5.png)
Confirming, same bug here.

**Comment by jugglinmike** [comment]
Hi there, @Lord-Evil! [The JSHint project's contribution guidelines](https://github.com/jshint/jshint/blob/main/CONTRIBUTING.md) have a note about posting screenshots of code:

> Please avoid using screenshots to demonstrate the problem. Describing your problem in plain text (and using the "code" Markdown formatting where appropriate) will make your report more accessible to more people and easier to find via search engines.
