### ISSUE TITLE
Update kdev-jshint

### ISSUE THREAD

**Issue by ShalokShalom** [jshint/jshint#3166]
I found this implementation into Kdevelop: https://bitbucket.org/dfighter1985/kdev-jshint/src

Is it possible for me, to update it? 

I mean, can anybody spend me some advice? 

The plan is to use Kdevelop as IDE and I am really curious that such a highly developed piece of software, which ships full support for JavaScript including semantic syntax highlighting, code navigation and completion, is unsupported by JSHint. 

Can I simply copy and paste some files in that case?

I am a programmer newbie.

Thanks a lot in advance

**Comment by jugglinmike** [comment]
I'm not familiar with the "kdev-jshint" project, but from a cursory reading of the source, it seems to be a wrapper around JSHint's Node.js command-line interface. Integration issues (including tasks like upgrading the JSHint version) should be addressed within the "kdev-jshint" project itself. I recommend contacting the maintainers of that project. Good luck!
