### ISSUE TITLE
"Functions declared within loops..." warning doesn't handle let declarations differently than var declarations

### ISSUE THREAD

**Issue by mhirsch** [jshint/jshint#3167]
This is somewhat related to the discussion in #3056.

Consider this example
```
/*jslint esversion: 6 */

for ( var i = 0; i < 10; i++ ) {
	setTimeout( () => {
		console.log(i);
	}, i * 200);
}
```

If run, it prints 
```
$ node t.js
10
10
10
10
10
10
10
10
10
10
```

And jshint rightly gives the following output:
```
jshint t.js
t.js: line 4, col 17, Functions declared within loops referencing an outer scoped variable may lead to confusing semantics.
```

However, using an es6 `let` declaration, this should be no problem:
```
/*jslint esversion: 6 */

for ( let i = 0; i < 10; i++ ) {
	setTimeout( () => {
		console.log(i);
	}, i * 200);
}
```
Prints: 
```
$ node t.js
0
1
2
3
4
5
6
7
8
9
```
But jshint gives the same warning as above. In `esversion: 6` mode shouldn't jshint distinguish between these cases?

**Comment by jugglinmike** [comment]
Thanks for the report! The warning is certainly not appropriate in that case, but the bug has previously been reported. See gh-3100.

(By the way: gh-3056 was concerned with the warning message, not the linting behavior. That was subsequently addressed by gh-3058; we just forgot to close it.)
