### ISSUE TITLE
Jasmine global doesn't recognize `spyOnProperty`

### ISSUE THREAD

**Issue by mikedaly** [jshint/jshint#3183]
Jasmine 2.6 added the ability to spy on properties via the new global, `spyOnProperty`. But JSHint's `jasmine` setting doesn't recognize that as a valid global.

**Comment by jugglinmike** [comment]
Thanks for the report! The fix here is pretty straightforward--we'll just need to add an entry to [the `jasmin` object in the `vars.js` source file](https://github.com/jshint/jshint/blob/506c7d5aebd2b14a67f6077749ede799b5ce29f2/src/vars.js#L716). I'm marking this as low-priority, but I would gladly accept a patch introducing the new variable. Any chance you'd like to help out, @mikedaly?

**Comment by ebullient** [comment]
I'm your huckleberry. Happened to hit this today.

**Comment by mikedaly** [comment]
@ebullient Does that mean you are putting up a PR? I was hoping to get to this later today, but don't want to duplicate effort.

**Comment by mikedaly** [comment]
Doh - just saw that you already did. :)
