### ISSUE TITLE
Feature request: add intersection observer API globals to browser environment

### ISSUE THREAD

**Issue by cueedee** [jshint/jshint#3194]
http://caniuse.com/#feat=intersectionobserver

**Comment by jugglinmike** [comment]
Sounds good to me. As near as I can tell, that specification introduces a single global binding: [`IntersectionObserver`](https://www.w3.org/TR/intersection-observer/#intersectionobserver). If so, this should be straightforward to implement. New contributors looking to get their bearings could use the recently-landed gh-3190 as a guide. I'd be happy to give more guidance, of course.

@cueedee Do you have any interest in helping out?

**Comment by johnmryan** [comment]
I'd be interested in helping out if you're still looking for a contributor here

**Comment by jugglinmike** [comment]
Resolved via gh-3194.
