### ISSUE TITLE
E056 (used before declared) in destructured assignment when using default values of just-assigned variables

### ISSUE THREAD

**Issue by rosyatrandom** [jshint/jshint#3196]
Using JSHint 2.9.5

```
const { a=3, b=a+1} = {},
      [ x=5, y=x+1 ] = [];
      // a === 3, b === 4, x === 5, y === 6
```

E056 errors are reported on the first appearance of `a` and `x`, but the code works fine both in node and browser environments

**Comment by jugglinmike** [comment]
Thanks for the report! This bug was previously identified in gh-3026, so I'm going to close this issue to help keep things organized.
