### ISSUE TITLE
Default parameters: E056 - was used before it was declared, which is illegal for 'param' variables

### ISSUE THREAD

**Issue by JestDotty** [jshint/jshint#3197]
According to the [mozilla docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Default_parameters) in subsection **Default parameters are available to later default parameters** this should work (and it does in chrome 60 & node 6):

```js
moveAct({action, range, id, target=Game.getObjectById(id), args}={}){
```

However first `id` is underlined with error: `E056 - 'id' was used before it was declared, which is illegal for 'param' variables`

---

jshint version 2.9.5

Testing/reproduction (E056 on `a`):
```js
var test = function({a, b=a}){console.log(b)}; test({a:1});
>> 1
```

**Comment by jugglinmike** [comment]
Thanks for the report! This bug was previously identified in gh-3026, so I'm going to close this issue to help keep things organized.
