### ISSUE TITLE
Documentation: jshint accepts also directory as input

### ISSUE THREAD

**Issue by crystalfp** [jshint/jshint#3198]
jshint 2.9.5

You can call jshint with a list of directories instead of a list of js files.
This way it operates recursively on all js files present in the directories and subdirectories.

This is not documented on http://jshint.com/docs/cli/ and should be added.

Thanks for considering!
mario

**Comment by jugglinmike** [comment]
Thanks for taking the time to report this! Resolved via https://github.com/jshint/jshint.github.io/commit/216153a892aa33ba3c78f00d82d34fa9ae180c93 and deployed to production.
