### ISSUE TITLE
child_process.exec('call jshint file'path') failed

### ISSUE THREAD

**Issue by SHocker-Yu** [jshint/jshint#3200]
i try to get the result after jshinted some files, like this:
`
 var exec = require('child_process').exec;
    var shell = 'call jshint E:/jenkins/workspace/jenkinsNotify_99uIM/plugin/send_message.js';
    exec(shell, function (err, stdout, stderr) {
        if (err) {
            console.error(err);
            return;
        }
        console.log(stdout);//**the result i want**

    });
`

but it error like this:
`
{ [Error: Command failed: call jshint E:/jenkins/workspace/jenkinsNotify_99uIM/plugin/send_message.js
]
  killed: false,
  code: 2,
  signal: null,
  cmd: 'call jshint E:/jenkins/workspace/jenkinsNotify_99uIM/plugin/send_message.js' }`

i change the shell like this(does not include 'call'):
`jshint E:/jenkins/workspace/jenkinsNotify_99uIM/plugin/send_message.js`

there is the same error.

i have saw the issue: https://github.com/jshint/jshint/issues/2819
but i dont know how to get the result of files jshinted.

**Comment by SHocker-Yu** [comment]
i changed the function, use child_process.spawn(), its useful for me.
`
var spawn = require('child_process').spawn;

var spawnObj = spawn('node', ['C:/Users/Administrator/AppData/Roaming/npm/node_modules/jshint/bin/jshint', 'E:/jenkins/workspace/jenkinsNotify_99uIM/plugin/send_message.js'], { encoding: 'utf-8' });

spawnObj.stdout.on('data', function (chunk) {
    console.log('result: ' + chunk.toString());
});

spawnObj.stderr.on('data', function (err) {
    console.log('err: ' + err);
});

spawnObj.on('close', function (code) {
    console.log('close code: ' + code);
});
`

**Comment by jugglinmike** [comment]
Glad to hear that you got it worked out!
