### ISSUE TITLE
On in-loop es6 variables still warns about Functions declared within loops referencing an outer scoped variable may lead to confusing semantics.

### ISSUE THREAD

**Issue by jasco** [jshint/jshint#3203]
Even when referencing in-loop es6 `let` or `const` variables jshint **2.9.5** still issues a warning.

Here is a simple example referencing the `let` defined loop variable.  My actual use case is referencing a `const` variable defined within the loop.  I suggest the behavior in these cases is clear and should not result in a warning.

```
function test() {
    const funcs = [];
    for (let ii = 0; ii < 100; ++ii) {
        funcs.push(function () {
            console.log(ii);
        });
    }
    funcs.forEach(f => f());
}
``` 

Result:

```
test.js: line 4, col 20, Functions declared within loops referencing an outer scoped variable may lead to confusing semantics.
```

The test was conducted with the following `.jshintrc`:

```
{
    "bitwise": true,
    "curly": true,
    "eqeqeq": true,
    "eqnull": true,
    "expr": true,
    "latedef": true,
    "onevar": true,
    "noarg": true,
    "node": true,
    "trailing": true,
    "undef": true,
    "unused": true,
    "esversion": 6
}
```

**Comment by jasco** [comment]
My earlier search didn't find a duplicate issue, but I now see #3100.

**Comment by jugglinmike** [comment]
I agree with your reading: this issue describes the same problem as gh-3100. I'll close this in favor of that one to keep things organized. Thanks for taking the time to report, though. If you'd like to work on a patch, I would be happy to lend a hand!
