### ISSUE TITLE
unused: "vars" doesn't seem to be working

### ISSUE THREAD

**Issue by multimediavt** [jshint/jshint#3205]
I am working with JS code that will be part of a CMS. I have to define global functions in a single file where those functions will be used in multiple places within CMS pages, but they are not called within the main JS file itself. I set the 'unused' option to "vars" in .jshintrc, but jshint is still giving me errors saying that "[functionName] is defined but not used."

Is the "vars" value for the unused option supposed to suppress these errors or not?

I even tried defining the functions as variables and using the globals option to try to suppress them and that didn't work either. I ended up using an inline "unused: false"/"unused: true" around the functions to eliminate the errors, but would rather not have to do that for every project and rather rely on the .jshintrc options.

**Comment by jugglinmike** [comment]
The `unused` option is an "enforcing" option, meaning that it makes JSHint more strict. In this case, setting it to `vars` is what enables the warnings you have reported. If you would prefer JSHint *not* to warn about unused variables, you can avoid setting that option altogether (or if you prefer explicitness, you can set it to `false`).
