### ISSUE TITLE
Exponentiation operator

### ISSUE THREAD

**Issue by thany** [jshint/jshint#3216]
The exponentiation operator (**) doesn't seem to be supported, even when ES6 is enabled. The online linter at http://jshint.com/ has the same problem. For reference, I'm using 2.9.5 and Node 8.9.0.

Here's a super simple sample:
```javascript
const x = 2 ** 8;
```
I'm getting the following errors on this:
```
Expected an identifier and instead saw '*'.
Missing semicolon.
Expected an assignment or function call and instead saw an expression.
```
This operator is supported on all modern browsers and frameworks.
See: http://kangax.github.io/compat-table/es2016plus/

**Comment by jugglinmike** [comment]
Hi there, @thany. [If you search this project's issue tracker for the word "exponentiation"](https://github.com/jshint/jshint/search?q=exponentiation&type=Issues&utf8=%E2%9C%93), you'll find that we already have an issue to track this feature request--see gh-2602. So I'm going to close this as a duplicate. Good news, though: the feature has been implemented and is due out in the next minor release of JSHint!
