### ISSUE TITLE
JSHint Should Use HTTPS

### ISSUE THREAD

**Issue by patrickdark** [jshint/jshint#3220]
As the title indicates, JSHint should use HTTPS. And get itself added to the Google Chrome HSTS preload list: https://hstspreload.org/.

**Comment by jugglinmike** [comment]
Hi there. We maintain the JSHint website in a dedicated repository:

https://github.com/jshint/jshint.github.io

HTTPS support has previously been requested there--see
https://github.com/jshint/jshint.github.io/issues/38 . I'm going to close this
issue to keep the discussion organized.

(Being added to the Google Chrome HSTS "preload list" seems like a means to an
ends, though, so feel free to use that issue to share your perspective on how
users would benefit from HTTPS support.)
