### ISSUE TITLE
ES6 configuration is not working in global

### ISSUE THREAD

**Issue by chombor** [jshint/jshint#3225]
Almost seven hours in a row, I tried everything, but it still does not want to work in a global mode with syntax es6  😞 

![essixissue](https://user-images.githubusercontent.com/16459251/33755218-d775881e-dc00-11e7-9a17-4596dda43385.png)

![linterselintersettings](https://user-images.githubusercontent.com/16459251/33755220-d7ca883c-dc00-11e7-804e-04958f1afa90.png)

![filepath](https://user-images.githubusercontent.com/16459251/33755219-d7af3b72-dc00-11e7-8c7e-8b00f14ea183.png)

![jshintsettings](https://user-images.githubusercontent.com/16459251/33755221-d7f743f4-dc00-11e7-88ba-edc32de4dc25.png)

**Comment by jugglinmike** [comment]
The behavior you are expecting is core to JSHint, so I would be surprised if the issue stems from JSHint's source code. I think it is more likely a problem with the way your editor is configured to use JSHint, possibly because it is not properly loading the `.jshintrc` file you've shared. Could you try executing JSHint manually from the command line? Note that depending on the location of your `.jshintrc` file, you may have to specify it via the `--config` option.

**Comment by chombor** [comment]
Hey jugglinmike, I tried but nothing happened 

```
PS C:\Users\username\Desktop\es6\src> jshint --config
PS C:\Users\username\Desktop\es6\src> jshint -v
jshint v2.9.5
PS C:\Users\username\Desktop\es6\src>
```

I read about how config file is generated and cached then or something, meh, steel hard to understand

**Comment by jugglinmike** [comment]
The `--config` flag should be specified with a path to your `.jshintrc` file, and you should also provide a file to lint. For example:

    jshint --config path/to/my/.jshintrc path/to/my/javascript-file.js

Please see [the project documentation on the command-line interface](http://jshint.com/docs/cli/) for more details.

**Comment by chombor** [comment]
nah

`PS C:\Users\username\Desktop\es6\src> jshint --config .jshintrc script.js
ERROR: Can't parse config file: .jshintrc
Error:SyntaxError: Unexpected end of JSON input
PS C:\Users\username\Desktop\es6\src>`

**Comment by chombor** [comment]
Working like a charm! That console pointing is awesome, it works even without power shell commands, globally — finally!!!

Thank you man =)

![2017-12-10 1](https://user-images.githubusercontent.com/16459251/33804928-6c769a8c-ddc0-11e7-8662-532297923493.png)

**Comment by chombor** [comment]
but it doesn't work with inline js code, which is worked fine earlier heh

![2017-12-10](https://user-images.githubusercontent.com/16459251/33804938-9e25929a-ddc0-11e7-85b4-a31759700381.png)

**Comment by jugglinmike** [comment]
Hmm, that's not quite right, actually. The behavior you are seeing now is a result of the Node.js interpreter attempting to evaluate your source code. This is different than JSHint reading the file and inspecting it for problems. Node.js is certainly capable of detecting syntax errors in JavaScript, but it will will not tolerate JavaScript embedded within HTML documents (as in your latest screen shot), nor will it warn about suspicious coding patterns that are syntactically valid. And maybe most importantly: it is unlikely that you wish to evaluate the source code of the files you are linting.

My suggestion to run JSHint via the command line was intended only to isolate the problem you originally reported. We still haven't done that, so I will leave this issue open so you can still get back to us with more information.

**Comment by chombor** [comment]
It seems the situation clears up. 
It only worked for the folder I specified earlier while running the config script. 
So it not worked properly in another folder.

![2017-12-12_19-59-05](https://user-images.githubusercontent.com/16459251/33899875-db084734-df7d-11e7-80ce-be662afa007f.png)

**Comment by jugglinmike** [comment]
Ah, that's more like it! Glad we got this sorted out :)
