### ISSUE TITLE
Await / Async Experimental status should be removed.

### ISSUE THREAD

**Issue by AttilaSATAN** [jshint/jshint#3226]
We are in December of 2017. 
Nodejs 8.9.3 is in LTS.
All mainstream browsers supporting Await / Async.
JSHint's point of view for this as an "experimental" feature is just wrong.
We devs need that support and personally I don't want to switch back to eslint.
But as an architect who uses JSHint in build operations I don't have much of a choice in this situation. I could not effort time or any man power from my team to make a pull request. I wish I could. Until you solve this urgent lack of support we have to move away.

#2077 
Oct 1, 2015 
OMG!

**Comment by jugglinmike** [comment]
Hi there. We have a long-running issue to track the implementation of this feature: gh-2604. At your suggestion, I've removed the word "experimental" from the title of that issue. I'd like to keep discussion around the feature centralized to a single issue, so I'm going to close this one.
