### ISSUE TITLE
ASYNC functions are considered as error

### ISSUE THREAD

**Issue by alexandreStein** [jshint/jshint#3227]
* Version of JSHint: `npm list jshint` gives me `jshint@2.9.5`
* Input source code:
```Javascript
async function fn(ev) {
  let x = await asyncFunc();
  console.log(x);
}
```
* Configuration values: via `.jshintrc`
``` JSON
{ 
  "esversion": 6
}

```
* Description of expected behavior:
I'm expecting to have no error or warning
* Description of actual behavior:
I have errors and warning but don't really related to the source.
![capture d ecran de 2017-12-14 18-17-52](https://user-images.githubusercontent.com/5431025/34005480-4772aa1c-e0fb-11e7-81eb-45f784197fdf.png)

I'm using Atom editor and linter-jshint use call your this package if this has an importance.

I hope I'm not missing something here.

**Comment by caitp** [comment]
I’m not sure if we support parsing async functions yet or not (i’ll check in a moment), but if we do, es6 mode likely does not support it.

**Comment by caitp** [comment]
Looks like nobody has landed a patch for parsing it yet.

**Comment by alexandreStein** [comment]
You are right, it looks like `async/await` is not in the es6 version.
Sorry about this and thank you for the quick answer.

Should I close the issue or you prefer to use it to track `async/await` support?

**Comment by caitp** [comment]
We should leave it open until it gets addressed properly.

**Comment by jugglinmike** [comment]
[A quick search of this project's open issues for the word "async"](https://github.com/jshint/jshint/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+async) turns up the existing feature request for async functions: gh-2604. I'm going to close this request to keep the discussion centralized to the one issue.
