### ISSUE TITLE
mechanism and algorithm of JSHINT

### ISSUE THREAD

**Issue by shaghayegh70** [jshint/jshint#3228]
Hi,
I have question that I don't know where should ask.
How could find information about mechanism and algorithm that uses in JSHINT for analysis the code?
please help me.
thank you

**Comment by caitp** [comment]
Which algorithm specifically? The parser, the scope analysis system, methods for reporting errors, ?

**Comment by shaghayegh70** [comment]
thanks for your response,
I need to know all of these specially analysis the code for example parser ,Model checking and etc.
I want choose JSHINT for thesis subject for master.
How could find these information about JSHINT?
sorry for my bad english

**Comment by jugglinmike** [comment]
Hi there. JSHint as an example of a "Pratt" parser, so for an understanding of the general strategy, I'd recommend starting your research there. When it comes to implementation details specific to JSHint itself, the source code itself is the best reference. We've been working to improve the documentation of JSHint's internals on [the feature branch for version 2.10](https://github.com/jshint/jshint/commits/v2.10.0), so you will probably have better luck reviewing the code on that branch.

If you have any specific questions, please let us know. You can try the `#jshint` channel on the Freenode IRC network, as well.

**Comment by shaghayegh70** [comment]
Please if everybody know help me

**Comment by shaghayegh70** [comment]
hi there, there is easier way to ask my question like email , telegram , whatup , facebook?

**Comment by shaghayegh70** [comment]
I'm in freenode in jshint chaneel but there is no one here

**Comment by jugglinmike** [comment]
I haven't heard back from you in the week since out discussion on IRC, so I'll take that to mean you're all set. Please let us know if you have any specific questions
