### ISSUE TITLE
Function used but declared unused

### ISSUE THREAD

**Issue by jbmonroe** [jshint/jshint#3240]
`response.json().then(acceptData).then(start).then(() => defer(pageCreate));`

The function pageCreate definitely exists, and is used in the call to defer (a dynamic function for invoking a function at a later time), but JSHint doesn't see that as a "use."

**Comment by jugglinmike** [comment]
Hello! I'm having trouble reproducing your problem. Here's my sample code:

```js
// jshint esversion: 6, unused: true
function pageCreate() {}
response.json().then(acceptData).then(start).then(() => defer(pageCreate));
```

But when I use JSHint version 2.9.5 to lint that input, no warnings are
reported.

I've had to make a bunch of assumptions here (e.g. how `pageCreate` is defined,
the linting options enabled, the version of JSHint to use, etc.), so I imagine
I'm missing some critical detail. Could you provide the information requested
for bug reports in the project's CONTRIBUTING.md file?

> - Version of JSHint being used
> - Input source code (simplified to only contain details necessary to
>   demonstrate the problem)
> - Configuration values
> - Description of expected behavior
> - Description of actual behavior

**Comment by jbmonroe** [comment]
I would love to...two things will delay that

1. The version in which that happened had CORS issues with local testing so I changed that out, and
2. it's a version of JSHint running within VS Code, so I don't know which version of JSHint this really is.

I can get the earlier version out of source control but it might be a day or two.  I'll put it in the online version to see what JSHint finds.  It could be that I'm dealing with an older version since I have no sense of how the VS Code plug-in manages versions for JSHint.

**Comment by jbmonroe** [comment]
Probably never figure this out.  No worries.
