### ISSUE TITLE
Documentation misleading regarding bitwise option?

### ISSUE THREAD

**Issue by cherdt** [jshint/jshint#3242]
On http://jshint.com/docs/options/

`bitwise` is listed as an _enforcing_ option and says "When set to true, these options will make JSHint produce _more_ warnings about your code" (emphasis mine) and "This option prohibits the use of bitwise operators such as ^ (XOR), | (OR) and others."

However, setting:

`/* jshint bitwise: true */`

suppresses errors about bitwise operators. Based on the description, I expected the opposite, that:

`/* jshint bitwise: false*/`

would suppress errors about bitwise operators.

**Comment by jugglinmike** [comment]
That's strange. On my system, the option behaves in the way it is documented:

    $ echo '0 ^ 0;' | ./bin/jshint -
    stdin: line 1, col 5, Expected an assignment or function call and instead saw an expression.

    1 error
    $ echo '/* jshint bitwise: true */ 0 ^ 0;' | ./bin/jshint -
    stdin: line 1, col 30, Unexpected use of '^'.
    stdin: line 1, col 32, Expected an assignment or function call and instead saw an expression.

    2 errors
    $ ./bin/jshint --version
    jshint v2.9.5

Before we can help, we'll need some more information. Could you share the other info documented in [the project's contribution guidelines](https://github.com/jshint/jshint/blob/master/CONTRIBUTING.md)?

> - Version of JSHint being used
> - Input source code (simplified to only contain details necessary to
>   demonstrate the problem)
> - Configuration values
> - Description of expected behavior
> - Description of actual behavior

**Comment by cherdt** [comment]
I get the same result with your example, but the results are swapped if I change out `jshint` for `jslint` (which I assumed were synonymous to jshint). Details below:

version of jshint: 2.9.5:

`$ jshint --version
jshint v2.9.5`

Input source code:

` echo '/* jslint bitwise: false */ 0 ^ 0;' | jshint -`

Configuration values:

default (no custom config other than what is specified in the example)

Description of expected behavior:

No error re: Unexpected use of '^'

Description of actual behavior:

```
$ echo '/* jslint bitwise: false */ 0 ^ 0;' | jshint -
stdin: line 1, col 31, Unexpected use of '^'.
stdin: line 1, col 33, Expected an assignment or function call and instead saw an expression.

2 errors
```

Further details:

Comparing the results when jshint is specified versus jslint:

```
$ echo '/* jshint bitwise: false */ 0 ^ 0;' | jshint -
stdin: line 1, col 33, Expected an assignment or function call and instead saw an expression.

1 error
```

```
$ echo '/* jslint bitwise: false */ 0 ^ 0;' | jshint -
stdin: line 1, col 31, Unexpected use of '^'.
stdin: line 1, col 33, Expected an assignment or function call and instead saw an expression.

2 errors
```

```
$ echo '/* jshint bitwise: true */ 0 ^ 0;' | jshint -
stdin: line 1, col 30, Unexpected use of '^'.
stdin: line 1, col 32, Expected an assignment or function call and instead saw an expression.

2 errors
```

```
$ echo '/* jslint bitwise: true */ 0 ^ 0;' | jshint -
stdin: line 1, col 32, Expected an assignment or function call and instead saw an expression.

1 error
```

Is this the expected behavior?

**Comment by jugglinmike** [comment]
Yup, that's expected. The `jslint` directive is exposed for compatibility with the JSLint project, which defines inverse semantics for that option.

**Comment by cherdt** [comment]
Got it. Thanks for clearing that up!

**Comment by jugglinmike** [comment]
No problem!
