### ISSUE TITLE
.jshintrc not working

### ISSUE THREAD

**Issue by mmajidim** [jshint/jshint#3247]
I have installed JSHint as a plug for Eclipse on Mac.   I am keep getting the error that 'let' and 'const' are in ejs6.  I created .jshintrc on my machine but that did not change anything.

Any ideas?

**Comment by jugglinmike** [comment]
It sounds like your the plug-in for your editor is not sourcing the configuration file. We don't maintain any editor plug-ins here, so my recommendation would be to ask the maintainers (or the relevant user group) for that project.

If during the course of your investigation, you find a problem that you can replicate on http://jshint.com, then that may indicate a problem with JSHint itself. In that case, please get back to us with the details.
