### ISSUE TITLE
Is there anyway to call "jshint" on multiple files?

### ISSUE THREAD

**Issue by nemanjapetrovic** [jshint/jshint#3250]
I know I can call `jshint app.js` from my terminal when jshint is globally installed, but I would like to call it on multiple files like `jshint server.js,app.js`, is there any way to do it?

**Comment by jugglinmike** [comment]
There sure is! Just specify those files as a whitespace-delineated list:

    jshint server.js app.js

And if you want to lint all the files contained in a directory, you can specify the name of the directory itself:

    jshint src

Does that help?

**Comment by nemanjapetrovic** [comment]
@jugglinmike 

Yes, thank you!
