### ISSUE TITLE
globals property not emitted when node: true is set

### ISSUE THREAD

**Issue by ThomasHickman** [jshint/jshint#3252]
The file:
```js
var jshint = require("./jshint").JSHINT;

jshint(
    "function func(){}",
    {
        node: true
    },
    {}
)

console.log(jshint.data())
```
prints:
```
{ functions: 
   [ { name: 'func',
       param: null,
       line: 1,
       character: 15,
       last: 1,
       lastcharacter: 18,
       metrics: [Object] } ],
  options: { node: true, indent: 4, maxerr: 50 },
  unused: [ { name: 'func', line: 1, character: 10 } ] }
```
to the console, while:
```js
var jshint = require("./jshint").JSHINT;

jshint(
    "function func(){}",
    {
    },
    {}
)

console.log(jshint.data())
```
prints:
```
{ functions: 
   [ { name: 'func',
       param: null,
       line: 1,
       character: 15,
       last: 1,
       lastcharacter: 18,
       metrics: [Object] } ],
  options: { indent: 4, maxerr: 50 },
  globals: [ 'func' ],
  unused: [ { name: 'func', line: 1, character: 10 } ] }
```
to the console.
I would expect both results to contain the property `globals` (this does not happen)

**Comment by jugglinmike** [comment]
Hi there, Thomas. Thanks for taking the time to file an issue!

The behavior you've described is expected. By default, [Node.js executes input text within a function wrapper](https://github.com/nodejs/node/blob/da886d9a4cd923bd5fc33eff7df22ff7d855a00b/lib/module.js#L105-L112).  The easiest way to observe this is to include a `return;` statement or `arguments` reference in the top-level of your Node.js module.

In terms of function declarations, this means that functions defined at the top level are not global. They are local to the (invisible) wrapper function.

If you'd like to declare a global variable in Node.js, you would need to use the built-in binding, `global` (just remember that today, this is not available in other environments).
