### ISSUE TITLE
assignment inside function call should be forbidden

### ISSUE THREAD

**Issue by novalis** [jshint/jshint#3256]
```
function foo(a, b=-11) {
    console.log("Got: " + a + ", " + b);
}

let b = 1;
foo(b=3);
```
No, this doesn't pass 3 as the 2nd argument to foo -- instead, it assigns a local variable named b and passes 3 as the first argument to foo.  This is probably not what anyone ever wants.  And if they do, the usual wrap-in-parentheses thing should be made to work.

**Comment by rwaldron** [comment]
JavaScript isn't Python, so I'm not sure why anyone would expect Python semantics from the given code example.

**Comment by novalis** [comment]
I filed this because I saw someone do it in the wild. And given that jshint warns about similar things (e.g. assignment inside an if), it seems like a reasonable thing to catch.  Sure, it's a Pythonism. But there are lots of Python programmers, some of whom are occasionally forced to use JS. Wouldn't it be nice to help them avoid bugs? 

On February 28, 2018 9:32:37 PM EST, Rick Waldron <notifications@github.com> wrote:
>JavaScript isn't Python, so I'm not sure why anyone would expect Python
>semantics from the given code example. 
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/jshint/jshint/issues/3256#issuecomment-369454361

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by novalis** [comment]
https://github.com/twosigma/git-meta/pull/688/commits/6850cdd9b57be8d14e59f7a886906de6d8c8847c#diff-4068c65289d0e4673c76445a4084b6adR70 look, a completely different person also just did this.
