### ISSUE TITLE
Security warning for lodash@3x

### ISSUE THREAD

**Issue by marcysutton** [jshint/jshint#3257]
There is a known security vulnerability in lodash@3x: https://hackerone.com/reports/310443

The severity is LOW, however jshint should be updated to the latest version.

**Comment by jugglinmike** [comment]
Thanks for the report! I've submitted a patch for this here: https://github.com/jshint/jshint/pull/3260

**Comment by calvinchengx** [comment]
I am waiting for this PR to be included into the next jshint release as well.

**Comment by kamronbatman** [comment]
@jugglinmike, the update has been merged in. It has been over a year since the last release. I would love to see this annoying security vuln go away soon.  Thanks!

**Comment by Sibiraj-S** [comment]
waiting for the release. any timeline @jugglinmike

**Comment by simlu** [comment]
Would love this to be fixed as well...

**Comment by jugglinmike** [comment]
We released the patch for this today in version 2.9.6 http://jshint.com/blog/2018-07-30/release-2-9-6/
