### ISSUE TITLE
How to use jshint programmatically within node?

### ISSUE THREAD

**Issue by jfoclpf** [jshint/jshint#3261]
First of all, thanks a lot for the great free tool!

I was using npm [`jshint`][1] package in command line tool, but now I want to use it programmatically. [Documentation][2] refers to this example, but it doesn't say how to include or `require` that `JSHINT` function 

    var source = [
      'function goo() {}',
      'foo = 3;'
    ];
    var options = {
      undef: true
    };
    var predef = {
      foo: false
    };
    
    JSHINT(source, options, predef);
    
    console.log(JSHINT.data());

Documentation refers that 

> JSHint exposes a JavaScript API for programmatic access in
> environments like web browsers and Node.js.

But exposes **how**?

I installed the npm package *locally* (I want it locally)

    npm install jshint --save

and I did as it's there and I get

    JSHINT(code, JShintOpt);
    ^
    ReferenceError: JSHINT is not defined

I also tried 

    const jshint = require('jshint');

But it doesn't work either.

  [1]: https://www.npmjs.com/package/jshint
  [2]: http://jshint.com/docs/api/

**Comment by jfoclpf** [comment]
Ok, I got it :) 

`const JSHINT = require('jshint').JSHINT;`

**Comment by skanaar** [comment]
I had to find this issue thread to be able to resolve this problem myself.

This page https://jshint.com/docs/api/ does not contain the necessary information to be able to use the tool from within a node script.

And thanks for a nice tool by the way :)

**Comment by jfoclpf** [comment]
>Can you commend there to let us know if that would have helped you?

@jugglinmike yes, now it's much more clear. I think you can mark the issue as solved

>JSHint exposes a JavaScript API for programmatic interaction. When the source web browsers and [Node.js](https://nodejs.org).	file is included in web browser environments via a `<script>` tag, this API is available via a global binding named `JSHINT` (i.e.  `window.JSHINT`). When JSHint is loaded in as a CommonJS module (for example, in [Node.js](https://nodejs.org)), the API is available via the `JSHINT` property of that module (i.e.  `require('jshint').JSHINT`).

**Comment by ExtravagantBoost** [comment]
> Ok, I got it :)
> 
> `const JSHINT = require('jshint').JSHINT;`
> 
> thanks to SO :)
> 
> https://stackoverflow.com/questions/49223395/how-to-use-jshint-programmatically-within-node-js

otherwise you can write that line as this
```javascript
const { JSHINT } = require(‘jshint’);//es5 and up support this type of syntax
```
