### ISSUE TITLE
Add support for trailing commas in parameter lists

### ISSUE THREAD

**Issue by Storyyeller** [jshint/jshint#3265]
Code: `parseInt('4',);`

Expected behavior: No lint errors

Actual behavior: Parse error
```
      1 |parseInt('4',);
                      ^ Unexpected ')'.
      1 |parseInt('4',);
                      ^ Expected an identifier and instead saw ')'.
      1 |parseInt('4',);
                       ^ Expected ')' and instead saw ';'.
      1 |parseInt('4',);
                        ^ Missing semicolon.

```

Note: I tried setting `esversion: 2017`, but jshint appears to not support any value higher than 2015.

**Comment by jugglinmike** [comment]
Thanks for the report! We haven't implemented support for trailing comments yet, so I've renamed the issue so it is more clearly a feature request.

**Comment by jugglinmike** [comment]
We've added support for ES2017 in [JSHint version 2.10.0](https://jshint.com/blog/2019-02-05/release-2-10-0/), and that includes trailing commas in call expressions and parameter lists. You can enable it by setting the `esversion` linting option to `2017`.
