### ISSUE TITLE
Jshint multiple reports for single run

### ISSUE THREAD

**Issue by vivekpal83** [jshint/jshint#3266]
I am using the npm install for jshint and installed jshint-html-reporter for HTML based report .
am running the jshint twice for 2 different type of report, 
1. HTML
2. TEXT
Is there a way to run the JSHINT only once and get the above mentioned types of report in single run ?

**Comment by jugglinmike** [comment]
The project's [Fequently Asked Questions](http://jshint.com/docs/faq/) has an entry for this very topic: "Can I use multiple reporters at the same time?" Even better, the answer is "yes"--see that page for more details.
