### ISSUE TITLE
Ignoring Error codes in .jshintrc not working

### ISSUE THREAD

**Issue by vivekpal83** [jshint/jshint#3267]
I have a config.json instead default .jshintrc. Have defined some warings and errors as below
config.json
{
  "node" : true,
  "-W038" : false,
  "-E031" : false
}
JSHint is able to suppress the warning code (W038 .i.e. in my output am not seeing the W038), however it is not suppressing the error codes (E031).
Is there a way to suppress error codes similar to warning codes

**Comment by jugglinmike** [comment]
JSHint emits "errors" (as opposed to "warnings") for problems that reflect objective violations of standard JavaScript syntax. It does not support ignoring errors because unlike warnings, there are rarely cases where syntactic issues are safe to ignore.
