### ISSUE TITLE
formData.entries

### ISSUE THREAD

**Issue by etetlow** [jshint/jshint#3269]
Please could you fix jshint error on advised method of inspecting formData.entries as explained at https://developer.mozilla.org/en-US/docs/Web/API/FormData/entries

**Comment by jugglinmike** [comment]
It is not possible to determine the type of a binding statically (i.e. by only reading the source code). This means JSHint cannot know which variables hold FormData objects, so it can't effectively warn developers about misuses of that (or any) particular class.
