### ISSUE TITLE
Async/Await on NodeJS

### ISSUE THREAD

**Issue by LuigiMaestrelli** [jshint/jshint#3271]
Why JSHint throws a validation error on this code?
It does not support Async/Await? 

[jshint] Expected an assignment or function call and instead saw an expression. (W030)
[jshint] Missing semicolon. (W033)
[jshint] Unrecoverable syntax error. (81% scanned). (E041)

```
exports.myFunction = async (id) => {
    let query = [
        { 
            $match: { 
                "id": id,
                "ativo": true
            }
        }, { 
            $group: {
                _id: null,
                media: {
                    $avg: "$classificacao"
                }
            }
        }
    ];

    let group = await Model.aggregate(query);
    let media = group[0].media;

    await Model.findByIdAndUpdate(
		{ _id: id },
		{ classificacao: media },
		{ new: true }
	);
};
```

**Comment by jugglinmike** [comment]
Hi Luigi,

[Searching this project's open issues for "async"](https://github.com/jshint/jshint/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20async) turns up the following:

[gh-2604: Support for async functions](https://github.com/jshint/jshint/issues/2604)

So let's track this feature request there.
