### ISSUE TITLE
async arrow functions appear to incorrectly trigger W116

### ISSUE THREAD

**Issue by Anaerin** [jshint/jshint#3277]
JSHint version 2.9.5, With "esversion": 6 (and "node": true) the following valid code 
```
this.app.use(async (req, res, next) => {
  log.debug("Session.loggedIn = %s", req.session.loggedIn);
  /* Snipped for brevity */
});
```
throws:
```
Expected '(' and instead saw '{'. (W116)
Expected ')' to match '{' from line 1 and instead saw '.'. (E020)
Expected ')' and instead saw ';'. (W116)
Missing semicolon. (W033)
```
The code is valid and works fine, so something is wrong with jslint here.

**Comment by jugglinmike** [comment]
Thanks for the report. We already have an issue tracking this feature request (gh-2604) so I'm going to close this one in order to keep the discussion organized.
