### ISSUE TITLE
Overwritten function declarations are not detected

### ISSUE THREAD

**Issue by alxndrsn** [jshint/jshint#3288]
I cannot get `jshint` to reject the following code due to the overriding of `main`:
```javascript
function main() {
  return 'Hello, World!';
}
var main = 6;
main();
```
I would expect the code to be rejected because `main` is effectively declared twice.

I have tried the following permutations of jshint options, but none seem to have an effect:
```javascript
bitwise: [ true, false ],
curly: [ true, false ],
eqeqeq: [ true, false ],
funcscope: [ true, false ],
futurehostile: [ true, false ],
latedef: [ true, false ],
shadow: [ 'inner', 'outer', false, true ],
strict: [ 'implied', false ],
undef: [ true, false ],
unused: [ true, 'vars', 'strict' ],
```
Have I missed the relevant option, or is this kind of function/variable overriding not something that jshint currently tries to detect?

**Comment by jugglinmike** [comment]
This is not something that JSHint attempts to detect. If you are able to use a
modern version of the language, then JSHint *will* detect this pattern when
lexical bindings are involved, e.g.

```js
// jshint esversion: 6
function main() {
  return 'Hello, World!';
}
let main = 6;
main();
```

It's not always possible to upgrade language versions, though, so I'd be open
to a patch which adds this behavior for `var`s via a new option.

Also, to avoid confusion: @alxndrsn has described their experiments in terms of
a hypothetical JSHint configuration. JSHint does not accept arrays for those
values; they are used in this case to describe various combinations.

**Comment by jugglinmike** [comment]
Whoops, I spoke too soon. JSHint offers partial support for the behavior you're
looking for. It only occurs in function scope, though. The following code will
produce a warning:

```js
(function() {
function main() {
  return 'Hello, World!';
}
var main = 6;
main();
}());
```

Inserting an immediately-invoked function wrapper is far less intrusive than
upgrading language versions. That said, it's still more intrusive than not
changing anything at all. You can find a long list of issues related to this
via gh-2400, so I'm going to close this as a duplicate.

(If anyone would like to lend a hand, please keep in mind that for the sake of
backwards compatibility, the new behavior will have to be "opt in" via a new
configuration options.)

**Comment by alxndrsn** [comment]
> JSHint offers partial support for the behavior you're looking for.

Thanks, this is a great workaround :¬)
