### ISSUE TITLE
Update lodash ? (Low vulnerability)

### ISSUE THREAD

**Issue by mroberty8** [jshint/jshint#3306]
Hi Can fix this ?

https://nodesecurity.io/advisories/577 

Current version of jshint use lodash 3.7.x

Thanks in advance.
Regards

**Comment by eaviles** [comment]
@mroberty8, looks like @jugglinmike already fixed it hasn't been released. I'm actually checking this project every morning, waiting for it 🙂

**Comment by jugglinmike** [comment]
Soon! Closing this as a duplicate of gh-3257
