### ISSUE TITLE
Unrecoverable syntax error for `(function(){}/0);`

### ISSUE THREAD

**Issue by qdirks** [jshint/jshint#3308]
`var g = function() {console.log(1);};`
`var x = (function(){}/0);`
`var y = (function(){}/0/g);`
`var z = (function(){}/0/g)/g(function(){}/0/g);`

Try the above statements. It works, but jshint says there is an unrecoverable syntax error on line 2.

If you add a trailing comment to line 2, jhint will give a different error (the syntax highlighter in vscode also malfunctions).

The problem seems to be that jshint thinks the division slash is part of a regex literal.

**Comment by jugglinmike** [comment]
Thanks for the report! While I appreciate the background, there's no need to explain. JSHint is a JavaScript parser, so it should parse valid JavaScript!

Further reduced:

    void function () {} / 0
