### ISSUE TITLE
Feature request - process multiple source files as if they were concatenated

### ISSUE THREAD

**Issue by smartavionics** [jshint/jshint#3309]
Hi, I have just started using jshint and it has been very useful, thanks! However, It doesn't quite do what I would like which is that I want to be able to give it a bunch of individual js files and it will process their contents as if all of the files were concatenated. Sure, I can concatenate the files beforehand but then I lose all the file name and line number info. I've searched the documentation but can't find any way of achieving that. Thanks.

**Comment by smartavionics** [comment]
A possible simple solution could be to have a directive that goes in a comment that overrides the current file name and line number. Having put one of those directives at the top of  each js file, the files could be concatenated and jshint would then use the right file name / line numbers in the output. Such a feature could also be useful when the js is being generated from some other source as it would make it easier to locate the referenced line in the original source rather than the intermediate js code.

**Comment by smartavionics** [comment]
C has had a similar concept for years:

https://en.cppreference.com/w/cpp/preprocessor/line

**Comment by jugglinmike** [comment]
Have you tried [the `--prereq` command-line option](http://jshint.com/docs/cli/)?

> Allows you to specify prerequisite files i.e. files which include definitions of global variables used throughout your project.

**Comment by smartavionics** [comment]
> Have you tried the --prereq command-line option?

Yes, i tried that but it didn't solve my problem because I have functions defined across a number of files. All of my global variables are defined in one file and I tried specifying that as a prerequisite but it didn't help with the functions because I still end up with function symbols either being undefined or unused.

**Comment by smartavionics** [comment]
>If functions defined in a file specified via --prereq are reported as "undefined", then you may be experiencing a bug with the option. Can you file an issue which demonstrates that?

No, I haven't tried using --prerequisite with files containing functions, only variables.

> Another alternative would be to explicitly list the global variables defined in your project via the "globals" configuration.

OK, but that's a bunch of work and seems a backwards step in having to replicate symbols in various files.

I'll close this issue now, it's not important enough to worry about, bye!
