### ISSUE TITLE
ignore specific error in .jshintrc 

### ISSUE THREAD

**Issue by ddor254** [jshint/jshint#3310]
Hi all , i'm running `jshint v2.9.5` , and i want to ignore specific error , for example "E054" for all the files that i will lint, i know that adding `"-W040":true` works and suppress this warning from all files, when going with the same logic and writing `"-E054":true in the `.jshintrc` file i get:  `Bad option: '-E054'.` 

is there any way of suppressing specific error in the config file?

**Comment by jugglinmike** [comment]
Barring a few exceptions, JSHint emits warnings to identify potentially
dangerous patterns and errors for invalid syntax. Error E054 enforces expected
syntax for class properties, so ignoring it would allow code which is not valid
under ES2015. Can you say more about why you would want to ignore these syntax
errors?

**Comment by ddor254** [comment]
from what i understand there is no fully supported ES2015 support , therefor if i have an `async` method in the class i will get that error.

**Comment by jugglinmike** [comment]
JSHint supports most of ES2015. We have not yet released support for async functions, which  were introduced in ES2017. You can follow the implementation of that feature in gh-3272

In the mean time, I'm afraid ignoring that specific parsing error will not be enough for you. Parsing async functions is about much more than accepting the `async` token. Even if you were able to ignore this particular parsing error, you would find that JSHint would reject any use of the `await` keyword within the function body. So for now, the best option is to ignore the async method completely using the `ignore` directive; you can read more about that in [the project's documebtation](http://jshint.com/docs/).
