### ISSUE TITLE
jshint 2.9.6 node_modules folder uses 220MB disk space

### ISSUE THREAD

**Issue by xhronos** [jshint/jshint#3316]
An empty node project with jshint 2.9.5 uses about 6.8 MB disk space.
The node_modules folder using 2.9.6 (or ^2.9.5) consumes roughly **220 MB**.

Is this as expected?

(node.js version seems to have no effect)

**Comment by jugglinmike** [comment]
Thanks for the report! A fix is on the way: https://github.com/jshint/jshint/pull/3319

You can expect a new release within a couple days.

**Comment by eaviles** [comment]
Any updates on this @jugglinmike?

**Comment by vorg** [comment]
@jugglinmike any blockers to quickly release 2.9.7?

**Comment by alasdairhurst** [comment]
Waiting :)

**Comment by jugglinmike** [comment]
[We've released the fix as JSHint 2.9.7.](https://github.com/jshint/jshint/releases/tag/2.9.7) My apologies for the delay.
