### ISSUE TITLE
Re-drop phantomjs dependency 

### ISSUE THREAD

**Issue by martinpitt** [jshint/jshint#3318]
https://github.com/jshint/jshint/pull/3215 moved phantomjs to an optionalDependency. This is rather evil, and conceptually completely unnecessary: it is only being used to test jshint itself, but it is in no way required for *users* of jshint.

This is dragging in an extra 66 MB download for `npm install` which is just dead weight. Note that phantomjs hasn't been maintained for a long time.

Please move it back to devDependency, which is the correct place. If someone wants to run tests with an ancient npm version, then they can just install phantomjs themselves IMHO. jshint shouln't penalize every user due to that.

Thanks for considering!

**Comment by jugglinmike** [comment]
Thanks for taking the time to write this up! This problem has already been reported via gh-3316, so I'm going to close this as duplicate.
