### ISSUE TITLE
How exactly do I use 'jshintConfig' inside package.json

### ISSUE THREAD

**Issue by adityarar** [jshint/jshint#3320]
**Aim**: To use custom configuration for jshint, which is installed using _npm_.
**OS**: Windows-7 (I know, I am sorry -_-)
**Current progress**: I have already tried and succeeded in using `--config` command to load a custom config file.
**Problem**: Based on documentation [here](http://jshint.com/docs/) and many other places on the web we have to add a property `jshintConfig` in package.json file. I added this property as such:<br>
![jshint-packagejson](https://user-images.githubusercontent.com/23469679/43775062-f7871b00-9a68-11e8-8df8-d2e9da3fc1d7.png)
Also, I have added my `jshintrc` file parallel to `package.json`.
My basic `jshintrc` file looks like this: <br>
```
{
  "undef": true,
  "unused": true,
  "esversion": 6,
  "globals": {
    "MY_GLOBAL": true,
	"$": true
  }
}
```

When I use command `jshint dummy.js`, it does not use the config file.<br>
Although, it does use it if I use the command `jshint --config jshintrc dummy.js`, while placing `jshintrc` file parallel to my `dummy.js`.<br>
I understand I should be making `.jshintrc` file, but that is not allowed in windows afaik.

**Edit**: I have also tried adding json directly as value of `jshintConfig` property, but it was still not picked up.

**Comment by adityarar** [comment]
@fmartin5 Updating `jshintConfig` property directly should have worked, but it didn't. **Maybe I'm updating the wrong `package.json`**
Creating `.jshintrc` using cmd is a good way I guess, but even if I get it working, I would have to create these files for different projects or add this file in file system root(so that jshint eventually finds it).

**Comment by adityarar** [comment]
Yup, that must be it.
My project does not have a `package.json` and I was indeed modifying NPM package's JSON.
So, how should I use my custom configuration for `JSHINT`?
I was looking for a global approach rather than having multiple `.jshintrc` files.

**Comment by fmartin5** [comment]
You can still create a `package.json` file for your project (e.g. by running `npm init` in its directory) and put the `jshintConfig` therein, but it will be local to that project only.

Afaik, the only global approach is having a `.jshintrc` file somewhere in the file system above all your different projects; this is not necessarily the system root.

From what I've seen this way of using dotfiles for configuration is very common, it also applies to other linters.

**Comment by adityarar** [comment]
Yeah. So, now have a `.jshintrc` file in system root. This works for me for me.
Thanks.
