### ISSUE TITLE
Global variable defined but still get ` '{variable}' is not defined.` error

### ISSUE THREAD

**Issue by dekyfin** [jshint/jshint#3321]
I am creating a test for my project using jshint to check for valid code in all JS files. 

Using the cli `jshint jsfile.js` produces no error, but using jshint in the node context produces a ` '{variable}' is not defined.` error.

This is the `.jshintrc` file
```javascript
{
	"node": true,
	"esversion": 6,
	"strict": true,
	"unused": "vars",
	"globals": {
		"LOG": true,
		"CONFIG": true,
		"CACHE": true,
	}
}
```

This is a simplified version of the `test.js` file

```javascript
const jshint = require("jshint").JSHINT;   // Load jshint
const fs = require("fs-extra");
const config = fs.readJsonSync("./.jshintrc");    // Read .jshintrc as a json object

var content = fs.readFileSync( "jsfile.js", "utf-8" );    // Read the file to be tested into content
jshint( content, config );    // Run jshint on the file content
console.log( jshint.data().errors );
/* OUTPUT
 [ { id: '(error)',
    raw: '\'{a}\' is not defined.',
    code: 'W117',
    evidence: '\t\t\tLOG.error( err );',
    line: 10,
    character: 13,
    scope: '(main)',
    a: 'LOG',
    b: undefined,
    c: undefined,
    d: undefined,
    reason: '\'LOG\' is not defined.' 
} ]
*/
```

It is very clear from the config that `LOG` has been specified as a global attribute.
Running `console.log( jshint.data().options )` shows that the options have been loaded correctly;

**Comment by jugglinmike** [comment]
Thanks for the report! This is indeed a bug; he's a reduced test case:

```js
'use strict';
var assert = require('assert');

var JSHint = require('../jshint').JSHINT;

var options = { undef: true, globals: { LOG: true } };

JSHint('LOG();', options);

assert(!JSHint.data().errors);
```

I've submitted a fix for this in at gh-3322.

In the mean time, you can use [the `predef` parameter as documented on the
"API" page](http://jshint.com/docs/api/):

> - `predef`
>   - Description: variables defined outside of the current file; the behavior
>     of this argument is identical to the `globals` linting option
>   - Type: an object whose property names are the global variable identifiers
>     and whose property values control whether each variable should be
>     considered read-only
>   - Example: `JSHINT(mySource, myOptions, { jQuery: false });`

To demonstrate:

```diff
 const jshint = require("jshint").JSHINT;
 const fs = require("fs-extra");
 const config = fs.readJsonSync("./.jshintrc");

 var content = fs.readFileSync( "jsfile.js", "utf-8" );
-jshint( content, config );
+jshint( content, config, config.globals );
 console.log( jshint.data().errors );
```

**Comment by dekyfin** [comment]
Thanks @jugglinmike. Works as expected
