### ISSUE TITLE
jshint 2.9.6 has lots of UNMET DEPENDENCY errors

### ISSUE THREAD

**Issue by SirWumpus** [jshint/jshint#3323]
Did `npm upgrade` to `2.9.6` followed by `npm list` which gave lots of `UNMET DEPENDENCY`  errors.  The workaround from #3316: either downgrade to `2.9.5` or use `npm install --no-optional jshint@2.9.6` avoids the errors.  See the attached output from `npm list`: 
[npm-list-out.txt](https://github.com/jshint/jshint/files/2298222/npm-list-out.txt)

**Comment by jugglinmike** [comment]
[We've just released a fix for the underlying problem as JSHint 2.9.7](https://github.com/jshint/jshint/releases/tag/2.9.7), obviating the need for a workaround.
