### ISSUE TITLE
Support for RegExp "s" flag ("dotAll")

### ISSUE THREAD

**Issue by ahallicks** [jshint/jshint#3326]
According to http://xregexp.com/flags/ there are even more new flags. Yay!

I noticed as I'm using the `s` flag in one of my projects and JSHint flags it as an invalid regular expression. I did some digging and noticed the above link where there are a number of new flags to consider.

**Comment by jugglinmike** [comment]
Thanks for the report! Of the "new flags" listed on that page, only "s" is part of the ECMAScript standard (as of 2018). I've renamed the issue to help other people find it.

**Comment by jugglinmike** [comment]
Good news! We've added support for the 's' flag in [JSHint version 2.10.0](https://jshint.com/blog/2019-02-05/release-2-10-0/).
