### ISSUE TITLE
Dead code after return not detected if function precedes

### ISSUE THREAD

**Issue by MilesBHuff** [jshint/jshint#3330]
This gives an error, as expected:
`return foo;`
`console.log('Unreachable code'); // Error`
`function foo() {}`

This does not give an error:
`return foo;`
`function foo() {}`
`console.log('Unreachable code'); //No error`

This was detected twice:  in NPM with jshint v2.9.1, and in Atom's linter-jshint v3.1.9 (which I believe uses the latest version of jshint).

**Comment by jugglinmike** [comment]
Thanks for the report! [This bug has previously been reported](https://github.com/jshint/jshint/issues/2446), so I'm going to close this as a duplicate. That other issue's title was a little obscure, so I've also renamed it to help people find it.

**Comment by MilesBHuff** [comment]
Oh, wow -- looks like that other bug has been open for 3 years.  It's also much less-well explained, which I guess explains the lack of action.  Do you have a guess for when this might be fixed?

(Also, no "good first issue" tag?  :p)

**Comment by jugglinmike** [comment]
> Do you have a guess for when this might be fixed?

I have no expectations for a fix. The discussion on that issue describes a complex solution, and as you've recognized, interest from consumers and contributors is low.

> (Also, no "good first issue" tag? :p)

We have a label named ["good first bug"](https://github.com/jshint/jshint/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+bug%22).  It looks like [GitHub gives special presentation for the "good first issue" label](https://help.github.com/articles/helping-new-contributors-find-your-project-with-labels/), though, so I've renamed it.

**Comment by MilesBHuff** [comment]
Yes, it does.  I'm glad you were able to change it.

Speaking of, though -- does my bug report here count as a good first issue?
If so, it would make me feel warm and fuzzy inside to have that label on it.
No worries if not, though.  It's certainly an extraneous thing.
