### ISSUE TITLE
Spread causes "Expected '}' to match '{'..." error in object literals within *nested* callbacks

### ISSUE THREAD

**Issue by DRSAgile** [jshint/jshint#3351]
Hi,

It was an issue a few months ago when _spead_ caused errors within object literals, and it was fixed (see: http://jsfiddle.net/KooiInc/tLoc387j/ -- it does not generate errors any more).

However, it turns out that if object literal's spread is nested within callback functions, it still causes an error:
https://jsfiddle.net/fv94x5wd/2/

Can it be fixed?

Thanks in advance.

**Comment by jugglinmike** [comment]
We've added support for object rest/spread in [JSHint version 2.10.0](https://jshint.com/blog/2019-02-05/release-2-10-0/), and [JSFiddle has updated to that version](https://github.com/jshint/jshint/pull/3273#issuecomment-460052055), so the example no longer reports a syntax error.
