### ISSUE TITLE
2.10.0 marks variables as unused when they are not

### ISSUE THREAD

**Issue by bdwain** [jshint/jshint#3354]
I have a file that looks like this

```js

import {foo} from './foo';

class MyClass {
  foo(){
     return foo();
  }
}
```

and it is incorrectly marking foo as unused. This is a valid use since the call to `foo` is not referring to `this.foo` so it must be the imported `foo`

**Comment by jugglinmike** [comment]
Confirmed. Thanks for the report!

**Comment by jugglinmike** [comment]
Introduced via 6759ac902928c32e0c798134abe1fbd1353ad3a3

**Comment by jugglinmike** [comment]
Further reduced:

    // jshint esversion: 6
    var m;
    class C {
      m() {
        void m;
      }
    }

This effects:

- methods
- static methods
- accessor methods
- genereate methods
- async methods
- async generator methods

This does *not* effect constructor methods, e.g.

    // jshint esversion: 6
    var constructor;
    class C {
      constructor() {
        void constructor;
      }
    }

**Comment by jugglinmike** [comment]
Fix on the way: gh-3355
