### ISSUE TITLE
Regex literal parsing fails if character class contains unescaped slash

### ISSUE THREAD

**Issue by harmic** [jshint/jshint#3356]
The following line produces errors as shown:

`var r = /[^/]+/;
`
Errors:
```
index.js: line 1, col 9, Invalid regular expression.
index.js: line 1, col 13, Missing semicolon.
index.js: line 1, col 13, Expected an identifier and instead saw ']'.
index.js: line 1, col 15, Unclosed regular expression.
index.js: line 1, col 15, Unrecoverable syntax error. (33% scanned).
```

According to my reading of the [ES6 standard](http://www.ecma-international.org/ecma-262/6.0/#sec-literals-regular-expression-literals), a forward slash should not need escaping inside a character class within a regex literal.

I get these errors with jshint 2.10.0 or later, on default configuration.
No errors are reported when using 2.9.7 or earlier.

**Comment by jugglinmike** [comment]
A fix is on the way: https://github.com/jshint/jshint/pull/3357

This bug also effects some more edge cases involving ES6's "unicode" RegExp flag. The curious can check out the regression tests in that patch.

**Comment by jugglinmike** [comment]
Sorry for the delay on this! Version 2.10 has a lot of new features, so if you'd like to use it before we patch the bug, then you can work around this issue by creating RegExps with the RegExp constructor:

```diff
-var r = /[^/]+/;
+var r = new RegExp('[^/]+');
```
