### ISSUE TITLE
Got "Duplicate class method 'toString'" when overriding toString method in a class

### ISSUE THREAD

**Issue by skymountain2012** [jshint/jshint#3358]
Using the new 2.10.x version, the message was thrown for the following class definition. But no issue when using version up to 2.9.x. Is this the expected behavior? Thanks.

```
class Person {
   constructor(name) {
     this.name = name;
   }

   toString( ) {
     return `${this.constructor.name}(${this.name})`;
   }
}
```

**Comment by jugglinmike** [comment]
Confirmed. Thanks for the report! Further reduced:

    // jshint esversion: 6
    void class {
      toString() {}
    };

If you'd like to work around it in JSHint 2.10.1 today, you can use a computed property name:

    // jshint esversion: 6
    void class {
      ['toString']() {}
    };

Alternatively, you could disable warning W075.

I've submitted a fix for this via gh-3359; we should have it published shortly.
