### ISSUE TITLE
Typo in async jshint 2.10?

### ISSUE THREAD

**Issue by karimcambridge** [jshint/jshint#3360]
https://github.com/jshint/jshint/blob/b7faa24675c38ce27cf783bc7f8841cf143d1641/src/scope-manager.js#L348

Shouldn't this be "async function"?

**Comment by jugglinmike** [comment]
You are correct, it should! I've submitted gh-3363 to fix the typo

**Comment by karimcambridge** [comment]
Thank you.

**Comment by jugglinmike** [comment]
Sure; thanks for letting us know :)
