### ISSUE TITLE
variable name of int reports unused variable incorrectly

### ISSUE THREAD

**Issue by dlynam01** [jshint/jshint#3362]
function zeroIfNotANumber(value) {
   var int = parseInt(value);
   return isNaN(int) ? 0 : int;
   }

Reports 
(Emitted value instead of an instance of Error) jshint results in errors
  'int' is defined but never used. @ line 97 char 11
          var int = parseInt(value);

**Comment by jugglinmike** [comment]
Thanks for reporting this! The problem was introduced in version 2.10.0, owing partly to the fact that JSHint supports linting according to the ES3 specification (in that edition, `int` was a reserved word).

A patch is on the way.
