### ISSUE TITLE
lodash 4.7.11 update

### ISSUE THREAD

**Issue by bonesoul** [jshint/jshint#3365]
```
  Moderate        Prototype Pollution

  Package         lodash

  Patched in      >=4.17.11

  Dependency of   grunt-htmlhint-plus

  Path            grunt-htmlhint-plus > htmlhint > jshint > lodash

  More info       https://npmjs.com/advisories/782
```

**Comment by jugglinmike** [comment]
I've reviewed the release notes and feel confident that the new patch release will not introduce any regressions. Upgraded via commit d73467ab8d111ea39be87f32e9857aa4a9af3927; the next release of JSHint will include the more strict version requirement. Thanks for letting us know!
