### ISSUE TITLE
Unexpected 'async' produced by valid export async function syntax

### ISSUE THREAD

**Issue by rwaldron** [jshint/jshint#3367]
The following produces `Unexpected 'async'.`:

```js
export async function f() {}
```

**Comment by jugglinmike** [comment]
Nice catch! I'll try to get a fix for this done in time for our next patch release.

**Comment by jugglinmike** [comment]
It may be a few days before I can fix this. Here's a workaround for folks who need to move forward sooner:

```diff
-export async function f() {}
+async function f() {}
+export {f};
```
