### ISSUE TITLE
Destructuring/Rest Assignment inside object parameter not recognized as variable declaration

### ISSUE THREAD

**Issue by chrissly** [jshint/jshint#3377]
function functionName({attribute1,...rest}){}
will give the error

    W117 - rest is not assigned.

**Comment by jugglinmike** [comment]
Confirmed. Here's a further reduced test case:

    // jshint esversion: 9, undef: true
    var { ...x } = {};

Thanks for the report!

**Comment by jugglinmike** [comment]
Filed a patch for this here: https://github.com/jshint/jshint/pull/3378
