### ISSUE TITLE
jshint fried to load 

### ISSUE THREAD

**Issue by moradkurtu** [jshint/jshint#3380]
Failed to load jshint library. Please install jshint in your workspace folder using 'npm install jshint' or globally using 'npm install -g jshint' and then press Retry

**Comment by jugglinmike** [comment]
I don't recognize the text you have shared, so I suspect the problem you are facing is with some external tool. We'll need more information to know for sure, though. Check out [the project's contribution guidelines](https://github.com/jshint/jshint/blob/master/CONTRIBUTING.md#bug-reports) for tips on how to write a helpful bug report.

**Comment by anncoleman3** [comment]
I got that also. I just uninstalled and re installed and it did the trick.

**Comment by jugglinmike** [comment]
Without any more information, I'm going to assume it did the trick for @moradkurtu, too. We can re-open if this is still an issue.
