### ISSUE TITLE
Setter is defined without getter.

### ISSUE THREAD

**Issue by sergey-yarchuk-4ib** [jshint/jshint#3381]
```
export class Model {
	constructor(attributes = {}, options = {}) {
		//...
	}

	set(attrs, options) {
		//...
	}
}
```

I have a warning "Setter is defined without getter". I haven't setter or getter, have only method ```set()```

**Comment by jugglinmike** [comment]
Confirmed. Here's a further-reduced test case:

    // jshint esversion: 6
    void class {
      set() {}
    };

This is a regression from version 2.10.0, so we'll have a fix out for this ASAP. In the mean time, you have a few options:

You could disable the warning for that method:

    export class Model {
        constructor(attributes = {}, options = {}) {
            //...
        }
        /* jshint -W078 */
        set(attrs, options) {
            //...
        }
        /* jshint +W078 */
    }

Or you could change the way you define the method (effectively hiding it from JSHint):

    export class Model {
        constructor(attributes = {}, options = {}) {
            //...
        }
        ['set'](attrs, options) {
            //...
        }
    }

Or you could downgrade to JSHint 2.9.7

Thanks for the report!

**Comment by jugglinmike** [comment]
A fix is now up for review: https://github.com/jshint/jshint/pull/3382

**Comment by sergey-yarchuk-4ib** [comment]
Great job. Will be wait update. Thanks for the lib.

**Comment by sergey-yarchuk-4ib** [comment]
Has some one trouble with Dynamic Imports. I think this is Regression too.
```
const BillingListView = () => import(/* webpackChunkName: "billings-list" */ '../views/billings-list.vue');
const BillingDetailsView = () => import(/* webpackChunkName: "billing" */ '../views/billing-details.vue');
```

Lint message 
```
Expected an identifier and instead saw 'import' (a reserved word).
```
jshint 2.10.2
webpack 4.29.6

If necessary, I can create a separate issue.

**Comment by jugglinmike** [comment]
@sergey-yarchuk-4ib "Dynamic import" is a non-standard language feature. It's currently at stage 3 in [the language's proposal process](https://github.com/tc39/proposals), so according to [JSHint's policy for new language features](https://jshint.com/blog/new-lang-features/), we would certainly accept a patch which introduced support. Would you like to file a feature request?

**Comment by exodus4d** [comment]
@sergey-yarchuk-4ib "Dynamic imports" are st stage 4, now. https://github.com/tc39/proposal-dynamic-import/commit/43e869ce8bb38d95f6b082dbc4c49d3f0fa1bdf2
see:  #3457
