### ISSUE TITLE
Install without npm

### ISSUE THREAD

**Issue by ap-prog** [jshint/jshint#3387]
I've downloaded and installed vscode. I tried to install the extension for jshint but doing so gives me a "Failed to load jshint library..." warning and then instructs me to use npm to install it.

I don't want/need to install node as I'm using chocolatey to install software on my windows computer. Is there a way to install jshint into vscode without using npm or nvm?

**Comment by jugglinmike** [comment]
We don't maintain the VSCode editor or any extensions that integrate it with JSHint, so we can't help with this. Your best bet will be to bring this up with the maintainers of that extension.
