### ISSUE TITLE
phantomjs is an unmaintained project

### ISSUE THREAD

**Issue by ossdev07** [jshint/jshint#3391]
Hello Team,

PhantomJS is an unmaintained project and jshint uses phantomjs for its browser testing.

I am curious to know that will you be interested in replacing the phantomjs with some other suitable alternative, as it is better using up to date dependencies.

Please share your thoughts on this and any further suggestion regarding the phantomjs replacement.

**Comment by jugglinmike** [comment]
In addition to being unmaintained, PhantomJS only approximates the browser environments we're actually targeting. Something built on WebDriver would be much better!

Separately, would you be interested in rewriting some of JSHint's parsing logic? We're looking to relicense the project, and first-time contributors are in the best position to re-implement existing logic. If that sounds interesting to you, I'd be happy to share more information. If not, then no worries; we'd be grateful for any contribution.

**Comment by ossdev07** [comment]
Thanks, @jugglinmike for the quick reply.

I was wondering if we could use chromium instead of phantomjs, I checked the browser.js file of the package which is used to launch the phantomjs browser in my view we can introduce karma to achieve the similar functionality with chromium.

Please revert your views on this, I am curious to know whether you are interested in using chromium or not.

Also, regarding the rewriting jshint's parsing logic currently I don't have the bandwidth but I would surely like to help if you need in future.

**Comment by jugglinmike** [comment]
That sounds fine. Here are the requirements:

- support latest LTS release of Node.js
- support GNU/Linux, macOS, and Windows
- support running headlessly in continuous integration (currently, that's TravisCI)

I do think Firefox may be a better option for this because Firefox is usually easier to download and install than Chromium. In my experience with Karma, the browsers can be swapped out without much difficulty.

We'd be grateful for your help! Think you can swing it?

**Comment by ossdev07** [comment]
@jugglinmike Thanks for letting us know the requirements.

We are currently working on it, will get back to you once it's done.

**Comment by ossdev07** [comment]
Hi @jugglinmike 

I am able to provide support of karma in the package and ChromeHeadless browser is also getting started.
```
OK: 8 assertions (5775ms)

> jshint@2.10.2 test-browser /home/shreya/shreya/jshint
> karma start karma.conf.js

04 07 2019 17:56:04.026:INFO [karma-server]: Karma v3.1.4 server started at http://0.0.0.0:9876/
04 07 2019 17:56:04.043:INFO [launcher]: Launching browsers ChromeHeadless with concurrency unlimited
04 07 2019 17:56:04.100:INFO [launcher]: Starting browser ChromeHeadless
04 07 2019 17:56:09.808:INFO [HeadlessChrome 74.0.3729 (Linux 0.0.0)]: Connected on socket 8ZMoimtakOMLEPlQAAAA with id 55964087
```
I am facing issues, while running the test cases, the modules are not getting loaded.
```
Browser {
  id: '55964087',
  fullName: 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 ' +
    '(KHTML, like Gecko) HeadlessChrome/74.0.3729.169 ' +
    'Safari/537.36',
  name: 'HeadlessChrome 74.0.3729 (Linux 0.0.0)',
  state: 'CONFIGURING',
  lastResult: [BrowserResult],
  disconnectsCount: 0,
  activeSockets: [Array],
  noActivityTimeout: 30000,
  collection: [BrowserCollection],
  emitter: [Server],
  socket: [Socket],
  timer: [Object],
  disconnectDelay: 2000,
  log: [Logger],
  noActivityTimeoutId: Timeout {
    _idleTimeout: 30000,
    _idlePrev: [Timeout],
    _idleNext: [TimersList],
    _idleStart: 11318,
    _onTimeout: [Function],
    _timerArgs: undefined,
    _repeat: null,
    _destroyed: false,
    [Symbol(refed)]: true,
    [Symbol(asyncId)]: 124,
    [Symbol(triggerId)]: 120
  },
  pendingDisconnect: null
} ERROR
  {
    "message": "Uncaught Error: Module name \"../..\" has not been loaded yet for context: _. Use require([])\nhttps://requirejs.org/docs/errors.html#notloaded\nat node_modules/requirejs/require.js:143:9\n\nError: Module name \"../..\" has not been loaded yet for context: _. Use require([])\nhttps://requirejs.org/docs/errors.html#notloaded\n    at makeError (node_modules/requirejs/require.js:168:17)\n    at Object.localRequire [as require] (node_modules/requirejs/require.js:1436:44)\n    at requirejs (node_modules/requirejs/require.js:1797:24)\n    at tests/unit/core.js:3:15",
    "str": "Uncaught Error: Module name \"../..\" has not been loaded yet for context: _. Use require([])\nhttps://requirejs.org/docs/errors.html#notloaded\nat node_modules/requirejs/require.js:143:9\n\nError: Module name \"../..\" has not been loaded yet for context: _. Use require([])\nhttps://requirejs.org/docs/errors.html#notloaded\n    at makeError (node_modules/requirejs/require.js:168:17)\n    at Object.localRequire [as require] (node_modules/requirejs/require.js:1436:44)\n    at requirejs (node_modules/requirejs/require.js:1797:24)\n    at tests/unit/core.js:3:15"
  }
```
If you have any pointer could you please suggest me something.

**Comment by jugglinmike** [comment]
Hm, nothing comes to mind. This is a complex feature you're working on, so there are certainly more important details than what is covered by this output. I may be able to say more if you share the full source code of your work-in-progress.

**Comment by ossdev07** [comment]
Hi @jugglinmike 

To provide the karma support I have done changes in the files

 ## 1- package.json file -
 In this file, I have downloaded the karma dependencies and starting the karma through test-browser script.
```  
 "devDependencies": {
     "async": "~2.1.2",
@@ -56,16 +58,21 @@
     "coveralls": "2.11.x",
     "istanbul": "0.3.x",
     "jscs": "1.11.x",
+    "karma": "^3.0.0",
+    "karma-chai": "^0.1.0",
+    "karma-chrome-launcher": "^2.2.0",
+    "karma-mocha": "^1.3.0",
+    "karma-requirejs": "^1.1.0",
+    "mocha": "^5.2.0",
     "mock-stdin": "0.3.x",
     "nodeunit": "0.9.x",
-    "phantom": "~4.0.1",
-    "phantomjs-prebuilt": "~2.1.7",
     "regenerate": "1.2.x",
```
```
-    "test-browser": "node tests/browser",
+    "test-browser": "karma start karma.conf.js",
```
## 2- karma.conf.js file
I have created the karma.conf.js file, in this I am setting the configuration of karma.
I am using  ``` mocha, requirejs ``` framework and using ``` chromeHeadless ``` browser
```// Karma configuration
// Generated on Fri Jun 21 2019 17:32:15 GMT+0530 (India Standard Time)
const path = require('path');
module.exports = function(config) {
  config.set({

    // base path that will be used to resolve all patterns (eg. files, exclude)
    basePath: '',

    // frameworks to use
    // available frameworks: https://npmjs.org/browse/keyword/karma-adapter
    frameworks: ['mocha', 'requirejs'],

   plugins: ['karma-requirejs', 'karma-mocha', 'karma-chrome-launcher'],

    // list of files / patterns to load in the browser
    files: [
            { pattern: './test-main.js', included: true },
      { pattern: './src/jshint.js', included: false },
      { pattern: 'tests/unit/core.js', included: true }
    ],

    // list of files / patterns to exclude
    exclude: [
    ],

    // preprocess matching files before serving them to the browser
    // available preprocessors: https://npmjs.org/browse/keyword/karma-preprocessor
    preprocessors: {
    },

    // test results reporter to use
    // possible values: 'dots', 'progress'
    // available reporters: https://npmjs.org/browse/keyword/karma-reporter
    reporters: ['progress'],

    // web server port
    port: 9876,

    // enable / disable colors in the output (reporters and logs)
    colors: true,

    // level of logging
    // possible values: config.LOG_DISABLE || config.LOG_ERROR || config.LOG_WARN || config.LOG_INFO || config.LOG_DEBUG
    logLevel: config.LOG_INFO,

    // enable / disable watching file and executing tests whenever any file changes
    autoWatch: true,

    // start these browsers
    // available browser launchers: https://npmjs.org/browse/keyword/karma-launcher
    browsers: ['ChromeHeadless'],

    // Continuous Integration mode
    // if true, Karma captures browsers, runs the tests and exits
    singleRun: true,

    // Concurrency level
    // how many browser should be started simultaneous
    concurrency: Infinity
  })
}
```
When karma starts, thens it launches the ChromeHeadless browser to run the test cases.
But I am getting error 
```
> jshint@2.10.2 test-browser /home/shreya/shreya/jshint
> karma start karma.conf.js

10 07 2019 15:03:51.225:INFO [karma-server]: Karma v3.1.4 server started at http://0.0.0.0:9876/
10 07 2019 15:03:51.260:INFO [launcher]: Launching browsers ChromeHeadless with concurrency unlimited
10 07 2019 15:03:51.317:INFO [launcher]: Starting browser ChromeHeadless
10 07 2019 15:03:57.970:INFO [HeadlessChrome 74.0.3729 (Linux 0.0.0)]: Connected on socket z9uubbqSZU47hOxnAAAA with id 92219740
Browser {
  id: '92219740',
  fullName: 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 ' +
    '(KHTML, like Gecko) HeadlessChrome/74.0.3729.169 ' +
    'Safari/537.36',
  name: 'HeadlessChrome 74.0.3729 (Linux 0.0.0)',
  state: 'CONFIGURING',
  lastResult: [BrowserResult],
  disconnectsCount: 0,
  activeSockets: [Array],
  noActivityTimeout: 30000,
  collection: [BrowserCollection],
  emitter: [Server],
  socket: [Socket],
  timer: [Object],
  disconnectDelay: 2000,
  log: [Logger],
  noActivityTimeoutId: Timeout {
    _idleTimeout: 30000,
    _idlePrev: [Timeout],
    _idleNext: [TimersList],
    _idleStart: 13484,
    _onTimeout: [Function],
    _timerArgs: undefined,
    _repeat: null,
    _destroyed: false,
    [Symbol(refed)]: true,
    [Symbol(asyncId)]: 124,
    [Symbol(triggerId)]: 120
  },
  pendingDisconnect: null
} ERROR
  {
    "message": "Uncaught Error: Module name \"../..\" has not been loaded yet for context: _. Use require([])\nhttps://requirejs.org/docs/errors.html#notloaded\nat node_modules/requirejs/require.js:143:9\n\nError: Module name \"../..\" has not been loaded yet for context: _. Use require([])\nhttps://requirejs.org/docs/errors.html#notloaded\n    at makeError (node_modules/requirejs/require.js:168:17)\n    at Object.localRequire [as require] (node_modules/requirejs/require.js:1436:44)\n    at requirejs (node_modules/requirejs/require.js:1797:24)\n    at tests/unit/core.js:3:15",
    "str": "Uncaught Error: Module name \"../..\" has not been loaded yet for context: _. Use require([])\nhttps://requirejs.org/docs/errors.html#notloaded\nat node_modules/requirejs/require.js:143:9\n\nError: Module name \"../..\" has not been loaded yet for context: _. Use require([])\nhttps://requirejs.org/docs/errors.html#notloaded\n    at makeError (node_modules/requirejs/require.js:168:17)\n    at Object.localRequire [as require] (node_modules/requirejs/require.js:1436:44)\n    at requirejs (node_modules/requirejs/require.js:1797:24)\n    at tests/unit/core.js:3:15"
  }
```

I think I am missing something, because it is able to find the path of the test cases but unable to run them, if you have any input, please let me know, it will be  a great help

**Comment by jugglinmike** [comment]
It looks like there's a change missing from the code above:

```diff
$ git diff
diff --git a/package.json b/package.json
index b464db41..5e01545d 100644
--- a/package.json
+++ b/package.json
@@ -67,6 +67,7 @@
     "phantom": "~4.0.1",
     "phantomjs-prebuilt": "~2.1.7",
     "regenerate": "1.2.x",
+    "requirejs": "^2.3.6",
     "results-interpreter": "~1.0.0",
     "sinon": "1.12.x",
     "test262-stream": "~1.2.1",
```

Adding that got me to the error you've reported. (Another way to collaborate on projects like this is to create a fork of the project on GitHub and push your work-in-progress to a branch of that fork. That makes it easier to share change sets like these.)

The problem is that Karma and its RequireJS plugin assume that the input test files were written to run in the browser. JSHint's test files were written to run in Node.js. The way we work around this in the current set up is by using Browserify to build the test code into a bundle that can run in a browser (just like people typically do with their application code). We do this "on demand" whenever PhantomJS runs.

In order to share tests between Node.js and the browser environment, we'll need to continue to follow a similar practice. We may not be able to use RequireJS for this; we may have to interface with the Karma runner directly. I don't know enough about Karma to say for certain, though.

To move forward, I recommend learning about how the tests are currently run in PhantomJS. [The file
`tests/browser.js`](https://github.com/jshint/jshint/blob/2366c92b852adeb963ecb812bc32b258288663dc/tests/browser.js) is a good starting point. There, you'll find references to a few more relevant files in [the `tests/helpers/browser` directory](https://github.com/jshint/jshint/tree/2366c92b852adeb963ecb812bc32b258288663dc/tests/helpers/browser).

**Comment by ossdev07** [comment]
Hi @jugglinmike 

Thanks for the help, as per your suggestion, I have taken a look into the ```tests/browser.js ``` file and ```tests/helpers/browser``` directory. I could see, in the file ```tests/helpers/browser\server.js``` browserify is been used and it is listed as one of the dev-dependencies for the package.

So to start the ```karma```  I am using ```browserify and mocha``` framework, but I am facing issue while running the test cases.
I have updated my code at  https://github.com/ossdev07/jshint/tree/karma
It will be a great help, if you could look into it.

I was exploring the package, to learn more about its functionalities. I notice that the test cases running through command ```npm run test-unit``` are the same test cases which are running through ```phantomjs browser```. I am curious to know, that is there any specific functionality, which we are trying to achive while running the same test cases through the ```phantomjs browser.```

**Comment by jugglinmike** [comment]
When we test browser-like environments, our goal is to re-use as many existing tests as possible. The Node.js-based tests give comprehensive coverage of the source code, so by running those in the browser, we can be more confident that we're verifying all the important edge cases.

That's easier said than done, though! It takes a lot of extra code to get those Node.js tests running in the browser and reporting their results back out to the test runner.

One major source of difficulty is JSHint's use of the "nodeunit" testing framework. Tests written for that framework are well-suited to Node.js code, but they're harder to run in other environments.

Nodeunit is also a little awkward to use for many of JSHint's tests. For example, it requires tests to call the `test.done` method, even though most of JSHint's tests are synchronous.

For these reasons, I've often thought about refactoring the tests to use another framework--something that is more appropriate for our needs, and maybe something that is more actively maintained, as well. The thought crossed my mind when you opened this issue, but I didn't mention it for a few reasons:

- refactoring the tests is a lot of additional work
- refactoring the tests is very sensitive (we have to be very careful not to make a mistake that could hide failures)

At this point, it's starting to sound like it may not be worth the effort to re-implement our current PhantomJS solution exactly for Karma. It's still up to you, though. If you'd like to keep trying, I can continue to answer any specific questions you have. Or if you'd like to take on refactoring the tests, I can help with that, too. Or if both options seem like more than you can do right now, then that's fine, too! Whatever the case, we appreciate your interest and your efforts so far :)

**Comment by ossdev07** [comment]
Hi @jugglinmike 

I checked the Travis build logs and I came to know that you are not running the browser test cases on all the node versions excepts Nodejs v10.

In the Travis.yml file, there is a condition mentioned to remove the phantom dependency if the Nodejs version is not 10.
```
if [[ $(node --version) != v10* ]] ; then
      node scripts/remove-dev-dependencies.js phantom phantomjs-prebuilt;
    fi
```
Could you please enlighten me, do I need to work on Nodejs v10 only for browser test cases or any other as well.

Thanks for your help!

**Comment by ossdev07** [comment]
Hi @jugglinmike ,

I have replaced phantomjs with puppeteer, modified browser.js and testhelper files and envs.js, option.js src files and test files. I have used existing nodeunit test framework , replacing this framework with karma or grunt requires modification of all test cases. test helper files and some of the src files, which require lot of bandwidth in rewriting jshint's parsing logic and replacing with puppeteer is helpful as it is maintained.

Raised a PR for the changes. Please have a look at PR #3438 and provide feedback if any changes required.
