### ISSUE TITLE
Issue with await syntax in object

### ISSUE THREAD

**Issue by Gorden-Tseng** [jshint/jshint#3395]
jshint 2.10.2

```
async function example() {
    let promise = new Promise(resolve=>{resolve();});
    return {
        key: await promise,
    }; // E024 - Unexpected '}'
}
```

The async/await syntax above is valid, but jshint is throwing E024. The error goes away if I remove the comma in the returned object.

**Comment by jugglinmike** [comment]
Confirmed. Thanks for the report!

**Comment by zorgoz** [comment]
Same problem with async methods, just that it gives E054 instead.

**Comment by jugglinmike** [comment]
@zorgoz that may be a distinct bug, but I can't verify. Replacing the async function in the original example with an async method produces the same error:

    void {
      async f() {
        return {
          key: await 0
        };
      }
    };

Can you please share a reduced test case?
