### ISSUE TITLE
Rest in object destructuring causing undefined variable

### ISSUE THREAD

**Issue by Naddiseo** [jshint/jshint#3398]
Version: 2.10.2
Sample code (entered on https://jshint.com):
```javascript
/* jshint esversion: 9 */
const {...rest} = {};
((a) => null)(rest);
```

Expected behavious: no warnings
Actual behavious: `b` is undefined

**Comment by jugglinmike** [comment]
Thanks for taking the time to file an issue! This bug was previously reported via gh-3377. As you'll see there, a patch has been merged, so the problem will be resolved in the next release of JSHint.
