### ISSUE TITLE
How to disable errors for await without async function

### ISSUE THREAD

**Issue by tnolet** [jshint/jshint#3403]
Hi,

Im in the middle of adding JShint with Codemirror to my SaaS https://checklyhq.com. All is good just for one thing I can't seem to figure out. 

My SaaS allows users to write Javascript with `await` statement, but we implicitly wrap this in an `async` function when executing the script on our backend.

so this code is 100% valid in our use case:

```js
const puppeteer = require('puppeteer')
const browser = await puppeteer.launch()
const page = await browser.newPage()
await page.goto('https://google.com/')
await page.screenshot({ path: 'google.png' })
await browser.close()
```

However, JsHint errors on the "naked" `await statements`, which is correct in most cases. 

![image](https://user-images.githubusercontent.com/3802923/58796630-29bdc200-85fe-11e9-9c87-246f8f8069b2.png)

My question, how can I disable these specific errors, without forking the project and tweaking the source.

**Comment by jugglinmike** [comment]
JSHint isn't designed to ignore syntax errors. My first suggestion would be to apply the same transformation to the code prior to passing it to JSHint.

[Top-level `await`](https://github.com/tc39/proposal-top-level-await) is a new language feature that might be useful here. It's not yet implemented in JSHint, but it has reached [our criteria for maturity](https://jshint.com/blog/new-lang-features/), so we'd be happy to review a patch for it. Bear in mind, though, that there are some semantic differences between "top-level `await` in a module" and "`await` within an immediately-invoked function expression," so this may not be what you want.

Will either of these work for you?

**Comment by tnolet** [comment]
Hey @jugglinmike thanks for the response. For now, a fork and some code commenting is enough for my use case. I'm also pretty sure I'm not a good enough coder to add the top-level await to JSHint, although I wish I was. 

So for now, I will just wait it out and use the fork. Thanks for the response. We can close this issue.
