### ISSUE TITLE
"Invalid regular expression" warning for certain character classes when `/u` flag has been set

### ISSUE THREAD

**Issue by cueedee** [jshint/jshint#3404]
Version: `jshint@2.10.2`

```js
// jshint unused: false

var
  r1 = /\t/u
, r2 = /\r/u
, r3 = /\n/u
, r4 = /\v/u
, r5 = /\f/u
, r6 = /\0/u
;
```

For the above regular expressions jshint reports an _"Invalid regular expression"_ error.
This happens only when the `/u`unicode flag has been set. 

Afaict all these comprise valid [character classes](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Character_Classes#Types), with or  without `/u' ...

**Comment by jugglinmike** [comment]
You are correct! The only tricky part here is allowing `\0` while disallowing `\01`. `u` is so picky :) Patch under review [here](https://github.com/jshint/jshint/pull/3406), hopefully we can get that out to you within a week.

Thanks for taking the time to report this!
