### ISSUE TITLE
Arrow methods

### ISSUE THREAD

**Issue by oskarkrawczyk** [jshint/jshint#3405]
This has been risen by one of our users over at https://github.com/jsfiddle/jsfiddle-issues/issues/1457

Apparently this is valid syntax:

```js
class Bar {
   someMethod = () => {
   }
}
```

Which will throw errors and warnings in the current JSHint version.

![](https://user-images.githubusercontent.com/234804/57938666-926d2500-7903-11e9-8f7f-4563d4d194d3.png)

More details:

- https://github.com/tc39/proposal-class-fields
- https://github.com/tc39/proposal-class-fields#execution-of-initializer-expressions

**Comment by jugglinmike** [comment]
I take it your users aren't writing code for Firefox ;)

In any event, [the proposal has reached stage 3](https://tc39.es/tc39-notes/2017-07_jul-27.html#11ivc-class-fields-for-stage-3), which is well beyond [JSHint's criteria for maturity](https://jshint.com/blog/new-lang-features/). That means we're on the hook for supporting it. We have a tracking issue for that, but it referenced the proposal by an outdated name. I've fixed that, so I'd like to continue to use that issue to track implementation:

https://github.com/jshint/jshint/issues/3139

Can't say when I'll have time to implement it, but I'll be happy to guide anyone who wants to land a hand.

Thanks for taking the time to report this, Oskar!
