### ISSUE TITLE
bug report: duplicate function names are not flagged as warnings or errors

### ISSUE THREAD

**Issue by thepeoplesbourgeois** [jshint/jshint#3420]
Hiya 👋

I'm playing around with [jshint's front page](https://jshint.com/), and whichever version it's running does not detect when a file contains two functions with the same name. This feels like it should be flagged as a warning, because although JavaScript allows function shadowing, it's highly unlikely that a developer would intend to have two different function bodies that are named the same thing.

```js
function main() {
  return "blah";
}

function main(arg, blarg) {
  return arg;
}
```

Reports

```
Metrics

There are 2 functions in this file.
Function with the largest signature take 2 arguments, while the median is 1.
Largest function has 1 statements in it, while the median is 1.
The most complex function has a cyclomatic complexity value of 1 while the median is 1.
```

While containing no information about the function `main()` being shadowed by `main(arg, blarg)`

**Comment by jugglinmike** [comment]
Thanks for taking the time to report this! As it happens, it has already been reported, see gh-1304. As documented in the related issues, JSHint is only silent about this redefinition when it occurs in the global scope.
