### ISSUE TITLE
bug report: "median" counts are actually representative of the mean

### ISSUE THREAD

**Issue by thepeoplesbourgeois** [jshint/jshint#3421]
Me again 👋 

While [shadowing `main()`](https://github.com/jshint/jshint/issues/3420), I noticed that the median count of function arguments behaved a little wonkily...

```js
function main() {
  return "blah";
}

function main(arg, blarg) {
  return arg;
}
```

Reports

```
There are 2 functions in this file.
Function with the largest signature take [sic] 2 arguments, while the median is 1.
```

It struck me that this was actually the mean argument count, so I toyed around with adding a few more functions to the file.

```js
/* previous code */

function morg(){}
```

Reports
```
There are 3 functions in this file.
Function with the largest signature take 2 arguments, while the median is 0.
```

Which is indeed the median argument count out of `[0, 0, 2]`, (as well as the mode argument count), but my curiosity not sated, I added another function signature...

```js
/* ... */

function blorg(foo, bar, bat){}
```

Reports
```
There are 4 functions in this file.
Function with the largest signature take 3 arguments, while the median is 1.
```

Whereas adding another signature which accepts 3 arguments reports
```
There are 5 functions in this file.
Function with the largest signature take 3 arguments, while the median is 2.
```
It appears the behavior of this metric is summing the number of function arguments and dividing that sum by the number of functions. This is actually the mean average, as opposed to the median average. I'm unsure of whether or not the intended behavior is to report the median, which in the four-function case should be `0`, as the algorithm for finding the middlemost argument count should be `functionArgCounts[Math.floor(functionArgCounts.length / 2) - 1]`, and should be `2` in the five-function case. If the intention is to actually find the mean argument count, then the verbiage can simply be flipped from `median` to `mean`

thx

**Comment by jugglinmike** [comment]
Thanks for taking the time to file a report!

> It struck me that this was actually the mean argument count

For sets with 2 members, the median and the mean are identical.

> It appears the behavior of this metric is summing the number of function arguments and dividing that sum by the number of functions. This is actually the mean average, as opposed to the median average. 

By my reading, the input program has 5 functions, arity 0, 0, 2, 3, and 3. The median of that set is 2, so the calculation seems correct to me.

This stuff can be tricky to describe in English, and one thing that can help is a complete program with the expected and actual output.

**Comment by thepeoplesbourgeois** [comment]
Hi, sorry, I should have been more clear about which case was incorrect in the above, but I buried the incorrect case in the middle of that last paragraph. Here it is:

> the four-function case should be 0 [not 1]

**Comment by thepeoplesbourgeois** [comment]
Also, the median and mean are identical in two-member sets? I hadn't heard that before… I would expect there to technically not be a median in that case, as either the smaller or the larger member would be at the end of the set, and no number would be in the middle; but in the case of the naive index-finding algorithm being `Math.floor(functionArgCounts.length / 2) - 1`, the median ought to be the number at `functionArgCounts[0]`

**Comment by jugglinmike** [comment]
This is calculated using the average of the two "middle" numbers for sets of even length.

http://mathworld.wolfram.com/StatisticalMedian.html

That's the formula I'm used to for the median, though it might not be universally accepted.

**Comment by thepeoplesbourgeois** [comment]
Wow, maybe it was taught that way and I forgot entirely? 😅 Thank you for helping me (re-)learn something today!
