### ISSUE TITLE
Why W030 appear in "cb && cb();"

### ISSUE THREAD

**Issue by azhi09** [jshint/jshint#3422]
How do i fix it?
such as 
```javascript
function a(cb){
    cb && cb();    // W030
}
```

**Comment by jugglinmike** [comment]
You have a few options.

Place the expression inside a `void` expression:

    void (cb && cb());

Refactor to use an `if` statement:

    if (cb) {
      cb();
    }

Disable the W030 warning:

    // jshint -W030
    cb && cb();

Hope that helps!
