### ISSUE TITLE
jshint option ignored after function declaration

### ISSUE THREAD

**Issue by qdirks** [jshint/jshint#3423]
```
function nop(){}
// jshint -W104
class pie {}

// still get an error about using class declarations
```

I know this is a known issue, but I think the pull request that is supposed to fix it never got merged due to a merge conflict. :(

https://github.com/jshint/jshint/pull/2563

**Comment by jugglinmike** [comment]
Thanks for the report! The bug has previously been reported via gh-2436, so in the interest of keeping things organized, I'm going to close this issue.
