### ISSUE TITLE
unrecognized Promises

### ISSUE THREAD

**Issue by paolobenve** [jshint/jshint#3425]
the code

```
return new Promise(someStuff);
```
produces

```
Undefined variables:
...
nnnn Promise

```

**Comment by jugglinmike** [comment]
Hi there! Your message is missing some important information; [the project's contribution guidelines](https://github.com/jshint/jshint/blob/master/CONTRIBUTING.md) has advice for how to file a great support request.

I can still make some guesses, though.

By default, JSHint assumes program code is targeting an ES5 environment. In that context, there is no built-in Promise constructor. If you are writing code for an ES6 (or later) environment, you can enable it with the `esversion` option. Setting that to `6` (or higher) will cause JSHint to assume `Promise` is available globally.

If you are *not* targeting an ES6 runtime but you would still like to use a global variable named `Promise`, you can enable it with the `globals` option.

Does that help?

**Comment by paolobenve** [comment]
understood, thank you! :-)
