### ISSUE TITLE
TypeError for E012 - Cannot read property 'value' of undefined

### ISSUE THREAD

**Issue by stvcisco** [jshint/jshint#3455]
Will get a TypeError accessing undefined if you type the following Javascript code:
```
for (const)
```

The console shows this message:
```
/Users/user1/.atom/packages/linter/lib/linter-registry.js:154 [Linter] Error running JSHint Error: /Users/user1/.atom/packages/linter-jshint/node_modules/jshint/src/jshint.js:6534
        throw err;
        ^

TypeError: Cannot read property 'value' of undefined
    at Object.fud (/Users/user1/.atom/packages/linter-jshint/node_modules/jshint/src/jshint.js:5224)
```

**Comment by jugglinmike** [comment]
Crash confirmed, though the failure conditions are slightly different than reported (note the semicolon):

    $ echo 'for(const;)' | ./bin/jshint -
    ./src/jshint.js:6534
            throw err;
            ^
    
    TypeError: Cannot read property 'value' of undefined

**Comment by stvcisco** [comment]
interesting - I didn't need the semicolon to see the crash within the Atom editor (using linter-jshint), but either way it's a crash.
