### ISSUE TITLE
Bad Assignment Error

### ISSUE THREAD

**Issue by christopherpickering** [jshint/jshint#3458]
Hi!

This might be answered elsewhere and I could not locate.. I'm sorry if it is a double -

Why is it that this code gives a "bad assignment" on the line where `a == 1 && b = 1`? It runs well on the web. Is there an option that can allow this type of assignment?

```js
var a = 1;
var b;

a == 1 && b = 1; // jshint error here: E031: Bad assignment
```

Thanks!
Christopher

**Comment by jugglinmike** [comment]
Thanks for taking the time to file an issue! In this case, I believe JSHint is correctly identifying a syntax error. However, since the code works for you, we should dig deeper.

Can you try running the following code in the browser where you are running your example?

    eval('var x; x == 1 && x = 2;')

When I run that code in Node.js version 12.16.1, it reports, "Uncaught SyntaxError: Invalid left-hand side in assignment"

**Comment by christopherpickering** [comment]
Thanks,
The code you sent does have an error in safari & chrome - with the same message you have received in Node.

I tried a few other things -
```js
// this works without error in chrome & safari
// and also passes inspection by jshint
eval('var x = 1; x == 1 && alert("ok")')
```

I just pulled a few lines from googles javascript that seem to work.. and I'm not sure how theirs is different than what I had above..
```js
var a="";
a instanceof String && (a += "");

// not sure what a is in this case
a != Array.prototype && a != Object.prototype && (a[b] = c.value)

// not sure what e is in this case
null != e && (f = e.getValue());
```

In adobe products w/ scripting there is no eval command, but the code
```js
var x=1; x == 1 && x = 2;
$.writeln(x)
```
will run without error and print a 2.. but maybe their have something special going on :) 

What do you think? It seems that in browsers the && cannot be used for assignment, but can be used for an action?

**Comment by jugglinmike** [comment]
This looks like a bug in the Adobe JavaScript engine. Just like in mathematics, every expression in JavaScript has a certain precedence. The `&&` expression has a higher precedence than the `=` expression. That means we could rewrite the statement:

    x == 1 && x = 2;

To be

    (x == 1 && 1) = 2;

See how that's not quite right? We could also simplify the example a little more:

    true && x = 2;

Is just like

    (true && x) = 2;

JavaScript engines that follow the standard will report a syntax error, probably saying something like, "invalid assignment." That's what JSHint is doing, so I'm going to close this issue.

Separately, @rwaldron and I love finding and fixing mistakes like this. Could you tell us the name of the Adobe software which runs the invalid code?

**Comment by christopherpickering** [comment]
Thanks for the explanation of why that is bad code! The script I referenced above is running in InDesign.
