### ISSUE TITLE
Remove former JSHint projects

### ISSUE THREAD

**Issue by thetric** [jshint/jshint#3460]
https://github.com/jshint/jshint#who-uses-jshint lists some projects and companies that do not use JSHint anymore and migrated to ESLint:

- Bootstrap (see https://github.com/twbs/bootstrap/blob/master/package.json#L103-L106)
- pdf.js: https://github.com/mozilla/pdf.js/blob/master/package.json#L16-L24
- Brackets: https://github.com/adobe/brackets/blob/master/package.json#L41
- Apache Cordova (some recent repositories):
  - https://github.com/apache/cordova-android/blob/master/package.json#L42
  - https://github.com/apache/cordova-ios/blob/master/package.json#L37
  - https://github.com/apache/cordova-plugin-inappbrowser/blob/master/package.json#L53-L59
  - https://github.com/apache/cordova-plugin-camera/blob/master/package.json#L54-L60
  - https://github.com/apache/cordova-js/blob/master/package.json#L76-L79
- jQuery:
  - https://github.com/jquery/jquery/blob/master/package.json#L32-L40
  - https://github.com/jquery/jquery-migrate/blob/master/package.json#L37
  - https://github.com/jquery/sizzle/blob/master/package.json#L38-L45
  - https://github.com/jquery/esprima/blob/master/package.json#L38-L42
  - exceptions:
     - jquery-ui: https://github.com/jquery/jquery-ui/blob/master/package.json#L64
     - jquery-mobile: https://github.com/jquery/jquery-mobile/blob/master/package.json#L41 (no commits since July 2019)
- Apache CouchDB:
  - https://github.com/apache/couchdb-fauxton/blob/master/package.json#L55-L57

These entries should be removed (or in case of jQuery updated) to represent the current situation.

**Comment by jugglinmike** [comment]
Wow, you really did the homework on this one! The page you referenced is built from the `README.md` file in this repository. Would you care to write a patch with the corrections (replacing "jQuery" with "jQuery UI")?

**Comment by thetric** [comment]
See #3463

**Comment by mgol** [comment]
A followup for remaining jQuery projects here: #3615
