### ISSUE TITLE
Missing semicolon (React / JSX)

### ISSUE THREAD

**Issue by dwilhel1** [jshint/jshint#3466]
JSHint usage via the Codacy platform is complaining about needing semicolons in my unit tests for shallow mounting a component. Code is as follows:

**Code**
![Screen Shot 2020-04-14 at 10 23 40 AM](https://user-images.githubusercontent.com/14366454/79244781-e39bd680-7e3c-11ea-9b60-a8cf70acfa75.png)

**Further Detail**
![Screen Shot 2020-04-14 at 10 45 01 AM](https://user-images.githubusercontent.com/14366454/79244988-1ba31980-7e3d-11ea-9022-7862927dadc2.png)

**`.jshintrc`**
```
{
  "globals": {
    "React": true
  },
  "esversion": 6
}

```

I haven't read anywhere that JSX is officially unsupported, so maybe I'm missing something and this is just an issue on my end?

**Comment by jugglinmike** [comment]
This is expected behavior; JSHint does not support JSX. Thanks for taking the time to file an issue!
