### ISSUE TITLE
'async functions' is only available in ES8 (use 'esversion: 8'). (W119)jshint(W119)

### ISSUE THREAD

**Issue by vaibhav019** [jshint/jshint#3474]
how to fix  this problem

**Comment by vaibhav019** [comment]
open VS Code then press ctrl+shift+p together >
 command palellet will appear > open user settings>
 search jshint> click on jshint:options > "jshint.options": { "esversion": 6, }
   not work

**Comment by ArturTrainee** [comment]
You can create ".jshintrc" file (see [jshint.com/docs/](https://jshint.com/docs/ )) at project root and simply add to it lines given below:
```
{
  "esversion": 8,
}
```

**Comment by jugglinmike** [comment]
Artur's right: setting the `esversion` option in a configuration file is one way to resolve this. Although given your report, it sounds like your editor may be maintaining the configuration for you. In that case, you'll want to set the value to `8` (or higher) in your editor.
