### ISSUE TITLE
Functions declared within a loop that use outer scoped variables and let keyword

### ISSUE THREAD

**Issue by anubas** [jshint/jshint#3476]
I have noticed that jshint 2.11.0 produces an error if a function is defined inside a loop while using outer scoped variables. For example...

Code (from the loopfunc option page example):

```javascript
var nums = [];

for (var i = 0; i < 10; i++) {
  nums[i] = function (j) {
    return i + j;
  };
}

console.log(nums[0](2)); // Prints 12 instead of 2
```

Code (using let keyword instead of var or nothing):

```javascript
var nums = [];

for (let i = 0; i < 10; i++) {
  nums[i] = function (j) {
    return i + j;
  };
}

console.log(nums[0](2)); // Prints 2 as expected
```

Even though use of the let keyword in the second code snippet allows everything to work as expected, jshint still produces the following error:

```
Functions declared within loops referencing an outer scoped variable may lead to confusing semantics. (i)
```

Why is this message still produced when using the let keyword? Especially when the esversion option is set to 6 (ECMAScript 2015) or later when the keyword was added? I do not want to set the relaxing option loopfunc to true because I still want this error to show up if the let keyword is not used.

**Comment by jugglinmike** [comment]
Thanks for the report! This is a known issue, and we have gh-3100 to track it. I'm going to close this to keep things tidy.
