### ISSUE TITLE
ES6 issue

### ISSUE THREAD

**Issue by TrollFace365** [jshint/jshint#3481]
I tried to update the settings to ES6 by using: 

{"esversion":6}

but it didn't work, the warnings are still there, HELP!

**Comment by jugglinmike** [comment]
Hi there! Your message is missing some important information; [the project's contribution guidelines](https://github.com/jshint/jshint/blob/master/CONTRIBUTING.md) has advice for how to file a great support request.

**Comment by jugglinmike** [comment]
Closing this to keep things organized. We can re-open once we have more information.
