### ISSUE TITLE
Configuration to run for nodejs application

### ISSUE THREAD

**Issue by prakaashkpk** [jshint/jshint#3488]
I am using jshint to lint my nodejs code which doesn't run on the browser. I don't seem to find documentation which says to throw errors specific to node js environment. 

```
line 7, col 1, 'const' is available in ES6 (use 'esversion: 6') or Mozilla JS extensions (use moz).
line 8, col 1, 'const' is available in ES6 (use 'esversion: 6') or Mozilla JS extensions (use moz).
line 9, col 1, 'const' is available in ES6 (use 'esversion: 6') or Mozilla JS extensions (use moz).
```

**Comment by nblasgen** [comment]
It says "use esversion: 6"

https://jshint.com/docs/options/#esversion

And you can use Node.Green to get a guess about what version of ECMA Script you might support: https://node.green/

Note that ES9 is ES2018, ES8 is ES2017, etc.

**Comment by prakaashkpk** [comment]
Thanks @nblasgen

**Comment by prakaashkpk** [comment]
I added following to `.jshintrc` file
```json
{
  "esversion": 8
}
```
