### ISSUE TITLE
More handy way to update browsers default global variables

### ISSUE THREAD

**Issue by shapkarin** [jshint/jshint#3491]
Hello. I was making my [npm package](https://www.npmjs.com/package/global-diff)
Here is [the code](https://github.com/shapkarin/global-diff#readme)
It name is `global-diff`. It outputs the your project global variables.
Next I found package and [that Github repo](https://github.com/sindresorhus/globals) and decide to update the list of variables automatically. So I open a PR https://github.com/sindresorhus/globals/pull/165
~~Maybe this project also need to add it as dev-tools or at least to update the [default browsers variables](https://github.com/shapkarin/jshint/blob/1013d51d8ca8cfe4ed3d8b54835c9c181c5ac7b7/src/vars.js#L74).~~

UPD: Not the package itself, but the [update features](https://github.com/shapkarin/global-diff/tree/combine/update/get-browser-globals)

**Comment by shapkarin** [comment]
Not the package itself, but the [update features](https://github.com/shapkarin/global-diff/tree/combine/update/get-browser-globals)

**Comment by jugglinmike** [comment]
Hi there. What problem does this package solve? How would JSHint use it?

**Comment by shapkarin** [comment]
@jugglinmike hello! currently can help not this package itself but it's update toolset - https://github.com/shapkarin/global-diff/tree/combine/update/get-browser-globals
When I start to create that package and use jshint as a dependency I realised that sometimes we need to update the [default browser variables](https://github.com/shapkarin/jshint/blob/1013d51d8ca8cfe4ed3d8b54835c9c181c5ac7b7/src/vars.js#L74) so [this toolset](https://github.com/shapkarin/global-diff/tree/combine/update/get-browser-globals) can help that with that. This toolset is not completely ready but soon it will be and I can provide a PR with that as a dev utils to update the browser variables.

**Comment by shapkarin** [comment]
BTW this package itself write the list of custom global variables. Next I plan to create an extension on top of it.

**Comment by shapkarin** [comment]
@jugglinmike can you please provide more info how that list https://github.com/shapkarin/jshint/blob/1013d51d8ca8cfe4ed3d8b54835c9c181c5ac7b7/src/vars.js#L74 was created and update? Maybe I can add some improve in that and combine the approaches.

**Comment by shapkarin** [comment]
@jugglinmike currently now update almost done in that way – [readme.md](https://github.com/shapkarin/global-diff/blob/combine/update/get-browser-globals/readme.md) and it's not a big deal to implement the rest. 
But maybe I can create something even more handy for that purpose and provide a PR.

**Comment by jugglinmike** [comment]
I think I understand. JSHint's global variable list is not a public API, and it's not something I'd like to support as such. The good news is that the file you are using is licensed under the terms of the MIT "Expat" license, so you can feel free to include it in your project and use it however you like!

**Comment by shapkarin** [comment]
@jugglinmike what do you think about some dev tools to update that list? I mentioned about that before.

**Comment by jugglinmike** [comment]
Thanks, but we're in good shape with our current process

**Comment by shapkarin** [comment]
Can you describe it? I just think that it's can be useful to have some tools for that propose and don't know how you update it.

**Comment by jugglinmike** [comment]
Sure: we update the file directly whenever someone needs a new global API
