### ISSUE TITLE
Add support for private class fields (#name) [low-priority]

### ISSUE THREAD

**Issue by fbarda** [jshint/jshint#3499]
This allows classes have private variables and methods like the ones you can have in a *constructor function*.

[ ] JSHint should be able to detect variable & method definitions via their # prefix.
[ ] Also, JSHint should give an error for using # in front of `get` and `set`. Getters and setters can be defined with `get #name`.
[ ] Also, according to a editor note below the `Note 2` [in the proposal for private fields](https://tc39.es/proposal-class-fields/#sec-static-semantics-early-errors), JSHint should give an error for trying to delete any private static or instance definition.
[ ] Also, according to the same proposal, having `#constructor` should give an error.

^This thing is pretty new, [*even firefox doesn't support it now*](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_class_fields#Browser_compatibility), so it would be the best to leave this as a low-priority.

**Comment by jugglinmike** [comment]
Hi there! We're using gh-3139 to track this feature request, so I'm going to close this in the interest of keeping things organized.
