### ISSUE TITLE
change line/col logging to allow for editor hyperlinking

### ISSUE THREAD

**Issue by nektro** [jshint/jshint#3500]
Present behavior:
```
www/chat/js/script.js: line 261, col 15, Missing semicolon.
```

Wanted behavior:
```
www/chat/js/script.js:261:15, Missing semicolon.
```

This will allow clicking on the link and the editor bringing you to the exact line/column of the error.

**Comment by jugglinmike** [comment]
I'd be supportive of a change like this if we had some concrete examples of widely-used editors which recognized the pattern.

Alternatively, you can build your own solution without forking JSHint itself. Check out [the documentation on writing a custom reporter](https://jshint.com/docs/reporters/).

**Comment by nektro** [comment]
Thanks a ton! Yeah this works great for me. I'll post the code I used but otherwise I'm personally okay if the issue is closed. If it's kept open for the research you mentioned, that's up to the team.

```js
module.exports = {
    reporter: function (res) {
        for (const item of res) {
            const file = item.file;
            const err = item.error;
            console.log(file + ":" + err.line + ":" + err.character + ", " + err.reason);
        }
    }
};
```
