### ISSUE TITLE
Documentation: Options typo for esversion 10

### ISSUE THREAD

**Issue by jp-larose** [jshint/jshint#3505]
In the page https://jshint.com/docs/options/, there's a typo in the link in the description for esversion bullet point for 10.  It's causing the URL to include the trailing ')'.  I think it's missing the '[' in front of "ECMAScript 10]".

**Comment by matt-nelson1** [comment]
I noticed that too—@jugglinmike @caitp. Also FYI, there are many pages on JSHint.com that aren't synched with the GitHub repo. Probably needs a fresh sync.
