### ISSUE TITLE
Various Pages Out of Date on JSHint.com

### ISSUE THREAD

**Issue by matt-nelson1** [jshint/jshint#3506]
Just a heads up that the domain (JSHint.com) needs a current sync from the Github repo for September/October. Docs, About, Install pages, etc. are missing some updates vs. the source code on the repo.

**Comment by jugglinmike** [comment]
This is controlled in the website repository. [Should be good, now.](https://github.com/jshint/jshint.github.io/commit/71e7292339393e6440b3fa51e8f80e1418d9f085)
