### ISSUE TITLE
Docs page: Example code wrong?

### ISSUE THREAD

**Issue by svArtist** [jshint/jshint#3512]
The example in the [JSHint.com docs](url=https://jshint.com/docs/) for relaxing and enforcing rules proposes:

> Take the following code as an example:
```
function main(a, b) {
   return a == null;
 }
```
> This code will produce the following warning when run with default JSHint options:
> > line 2, col 14, Use '===' to compare with 'null'.
> 
> Let's say that you know what you're doing and want to disable the produced warning but, in the same time, you're curious whether you have any variables that were defined but never used. What you need to do, in this case, is to enable two options: one relaxing that will suppress the `=== null` warning and one enforcing that will enable checks for unused variables. In your case these options are `unused` and `eqnull`.
```
/*jshint unused:true, eqnull:true */ // <-- Don't you mean "eqnull:FALSE"?
 function main(a, b) {
   return a == null;
 }
```
> After that, JSHint will produce the following warning while linting this example code:
> 
> > demo.js: line 2, col 14, 'main' is defined but never used.
> > demo.js: line 2, col 19, 'b' is defined but never used.

at XPath "/html/body/div/div/div[1]/pre[12]/code" (I wish I could insert a simple link; the doc could use some IDs; at least for every heading)
If it is about enabling `unused` and DISABLING `eqnull`, shouldn't it be
`/*jshint unused:true, eqnull:false */`
instead of
`/*jshint unused:true, eqnull:true */`
?

**Comment by jugglinmike** [comment]
Thanks for the report! That example is incorrect in more ways than one. As of [gh-3109](https://github.com/jshint/jshint/issues/3109), JSHint no longer reports the referenced warning, ever. To resolve this, we'll need to demonstrate "relaxing" options with a different example.

Want to try fixing this, @svArtist?

[Note that the documentation in question currently resides in the project website repository.](https://github.com/jshint/jshint.github.io/blob/dev/pages/docs.md)

**Comment by svArtist** [comment]
> Want to try fixing this, @svArtist?

I'm having a hard time understanding what exactly happened with `eqeqeq` vs `eqnull`, so I steered clear of that and replaced the example entirely, while trying to highlight how the two different options work in conjunction with current default settings
https://github.com/jshint/jshint.github.io/pull/58

Is that okay?

**Comment by svArtist** [comment]
...but as a side note: I think I my original issue is invalid, because I found `eqnull` under the *relaxing* options.
I may have misunderstood that before; now I've had a closer look
