### ISSUE TITLE
Add support for optional chaining

### ISSUE THREAD

**Issue by ghost** [jshint/jshint#3514]
Hello. With Node 14, `?.` added to use but JSHint shows as error. I can avoid it by manually doing `// jshint ignore:line`, but I think it might be more appropriate if support comes in. Thank you

**Comment by jugglinmike** [comment]
The feature you're looking for is called "optional chaining," and we have it on the roadmap for the next major release:

https://github.com/jshint/jshint/pull/3486

I'll rename this issue to help others find it.

**Comment by jugglinmike** [comment]
JSHint version 2.13.0, [released today](https://jshint.com/blog/2021-05-30/release-2-13-0/), includes support for optional chaining. Be sure to update your configuration to opt in to the new language feature via `esversion: 11` or later.
