### ISSUE TITLE
Recognise Binary Operation

### ISSUE THREAD

**Issue by erosman** [jshint/jshint#3517]
I noticed warnings on binary logical operations such as:

```js
a && console.log('OK');
b || someFunc();
```

> Expected an assignment or function call and instead saw an expression.

**Note:**
Following is a genuine error
```js
const a = true;
let b;
a && b = 5;
```

JSHint
> Bad assignment.

Firefox
> Uncaught SyntaxError: invalid assignment left-hand side

Correct syntax:
```js
const a = true;
let b;
a && (b = 5);
```

JSHint
> Expected an assignment or function call and instead saw an expression.

**Comment by fbarda** [comment]
The expected 'assignment' is just saving the result to somewhere.
If you use it in a function and `return` said expression, it shouldn't complain about it.

I'm using jshint on vscode with the fix I said:

```js
const a = true;
let b;

function getB() {
    return a && (b = 5);
}
```

![Code above with no complaints from IDE](https://user-images.githubusercontent.com/30421526/103035553-a0bc0200-4578-11eb-8bb2-2ec803ac9ff3.png)

**Comment by jugglinmike** [comment]
@fbarda has it (thanks, Arda!). By default, JSHint prefers that control flow be expressed with statements rather than expressions. So you could satisfy it by rewriting the code as follows:

```diff
-a && console.log('OK');
+if (a) {
+  console.log('OK');
+}
-b || someFunc();
+if (!b) {
+  someFunc();
+}
```

The motivation is that the verbosity is meaningful because it helps human readers better identify and understand the code paths.

But JSHint is configurable, so you can also resolve this by keeping your code just as it is and configuring JSHint to tolerate that shorthand. Here's how you'd do that with an in-line directive:

```diff
+// jshint expr: true
 a && console.log('OK');
 b || someFunc();
```

**Comment by erosman** [comment]
@jugglinmike The JS code that is being parsed is not my own code therefore, rewriting the code is not an option, neither is adding `// jshint expr: true`.

I use JSHint with Codemirror in a Firefox extension and the code that is being parsed is user's code (userscript) so I have no control over it.

The issue was that `a && console.log('OK');` is valid JavaScript code but it is reported as an error by JSHint.

**Comment by jugglinmike** [comment]
JSHint issues a warning for that code, but it should correctly recognize it as valid JavaScript. (JSHint reserves the term "error" for invalid syntax; error messages have identifiers which start with the letter "E", while identifiers for warning messages start with the letter "W". If it JSHint is reporting an error for syntactically valid code, then that is a bug.)

The `expr` option exists for exactly cases like yours, where the person running JSHint does not agree with the warning and wishes to tolerate the programming pattern it disallows.

I hear that you can't edit the code directly, but maybe you can change the linting options when you invoke JSHint. It sounds like you're using [the JavaScript API](https://jshint.com/docs/api/). If so, you can write something like `JSHint(theUserscriptCode, {expr: true})`.

**Comment by erosman** [comment]
Thank you for the reply.

> If it JSHint is reporting an error for syntactically valid code, then that is a bug.

I see... JSHint indeed reports as warning (not error).

> I hear that you can't edit the code directly, but maybe you can change the linting options when you invoke JSHint. It sounds like you're using the JavaScript API. If so, you can write something like JSHint(theUserscriptCode, {expr: true}).

I do control the JSHint options and can set `expr: true`. Reading from [JSHint Options](https://jshint.com/docs/options/), I was concerns that `expr: true` may miss other valid warnings. :thinking:
