### ISSUE TITLE
Using the "--exclude" flag does not work in ignoring the "node_modules" folder

### ISSUE THREAD

**Issue by Jacob-Mahoney** [jshint/jshint#3518]
I run the command `jshint --exclude ./node_modules .` within my project folder and it gives me back 4467 errors... most which are within packages in the "node_modules" directory.

**Comment by fbarda** [comment]
Have you tried using `--exclude-files`? Read more about CLI arguments in [JSDoc Docs](https://jshint.com/docs/cli/#ignoring-files).

**Comment by jugglinmike** [comment]
You can also use the CLI's `--help` flag to learn about the available command-line options and how to use them (as in `jshint --help`). Here's the output which is relevant to your question:

```
--exclude STRING   Exclude files matching the given filename pattern 
                   (same as .jshintignore) 
--exclude-path STRINGPass in a custom jshintignore file path
```
