### ISSUE TITLE
How to exclude an object property

### ISSUE THREAD

**Issue by erosman** [jshint/jshint#3520]
Considering the following:

```js
const OBJ = {
  a: [],
  b: [],
  c: [],
  d: []
}

// JSHint options
globals: {
  OBJ: false
}
```

How can a property (e.g. `OBJ.c`) be **excluded** so that is would generate an undefined error?

**Comment by fbarda** [comment]
If you want to create an `OBJ` object with an unaccessible `c` property, you need to define a [Proxy](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) or something like that. It's **not** tied to JSDoc.

However, if you would like to exclude it from just JSDoc, you can just use
```js
/**@type {{a:*[], b:*[], d:*[]}} */
const OBJ= { a:[], b:[], c:[], d:[]};
```
The `globals` option is used for **outer** globals, such as defining a script loader in a browser enviroment.
`"globals":{"goog":false}`
Check [JSDoc Docs](https://jshint.com/docs/options/#globals) for more details.

**Comment by jugglinmike** [comment]
JSHint isn't well-situated to track the runtime type of the bindings in your code. If you'd like to enforce restrictions like this, you might consider using [Flow](https://flow.org/) or [TypeScript](https://www.typescriptlang.org/).
