### ISSUE TITLE
Incorrect location for `use strict` without semicolon

### ISSUE THREAD

**Issue by ybiquitous** [jshint/jshint#3528]
## Summary

On the [`strict`](https://jshint.com/docs/options/#strict) rule, I found that the output location (line and column) is different depending on whether a semicolon is present or not.

```diff
-"use strict"
+"use strict";
```

If a semicolon is not present with `"use strict"`, JSHint reports `line 0, col 0` instead of `line 1, col 1`. I think that JSHint should report `line 1, col 1` in both cases.

## Reproduction

Here are the reproduction steps on a terminal:

```console
$ cat semi.js
"use strict";

$ cat no-semi.js
"use strict"

$ jshint semi.js no-semi.js
semi.js: line 1, col 1, Use the function form of "use strict".

no-semi.js: line 1, col 13, Missing semicolon.
no-semi.js: line 0, col 0, Use the function form of "use strict".

3 errors
```

(Note: `.jshintrc` is not specified)

## Environment

- JSHint 2.12.0
- Node.js 14.15.4

**Comment by jugglinmike** [comment]
Thanks for the report! The problem extends beyond just ASI--it relates to a faulty assumption about the contents of a directive block. For instance, JSHint currently reports the wrong location if the `"use strict"` directive is not the final directive:

    $ echo '"use strict";"use foobar";' | ./bin/jshint --verbose -
    stdin: line 1, col 14, Use the function form of "use strict". (W097)

I submitted a fix for review: gh-3530

**Comment by jugglinmike** [comment]
We merged that patch, so the fix will be available in the next release of JSHint. Thanks again for letting us know

**Comment by ybiquitous** [comment]
Thank you so much! 😊
