### ISSUE TITLE
options esversion:10  conflicts with incompatibe with esnext

### ISSUE THREAD

**Issue by cloudbender** [jshint/jshint#3555]
Maybe not a bug, could not suppress warning
Incompatible values for the 'esversion' and 'esnext' linting

**Comment by jugglinmike** [comment]
There isn't enough information here for anyone to help you. [The project's contribution guidelines have some suggestions for filing an actionable support request](https://github.com/jshint/jshint/blob/master/CONTRIBUTING.md); we can re-open this issue once there's more information.
