### ISSUE TITLE
Logical nullish assignment (??=) throwing error

### ISSUE THREAD

**Issue by sothix** [jshint/jshint#3560]
This code seems to be breaking latest NPM version: 2.13.1 with the following error:

```
let a = [1,2];
a[0] ??= 0;
```

`Uncaught TypeError: Cannot read property 'paren' of undefined`

**Comment by youngbob** [comment]
I'm seeing this on just a regular bullish expression on both 2.13.0 and 2.13.1. The source line of the error is https://github.com/jshint/jshint/blob/11dc0a677a8190487c197681d51e7076a4ee0565/src/jshint.js#L2453

**Comment by jugglinmike** [comment]
A fix is under review here: gh-3563

JSHint does not currently support "logical assignment" operator nor will it following the acceptance of that patch. The bug in this case is the crash; JSHint is expected to report a syntax error for the provided input. Please refer to gh-3544 to follow the implementation of logical assignment.

**Comment by youngbob** [comment]
I was seeing this in the codemirror editor, using the jshint integration, while typing a nullish coalescing expression. So it's probably the same issue - I was in the middle of typing an (incomplete) expression and jshint crashed instead of returning a syntax error for the incomplete line.
