### ISSUE TITLE
URL should be a global when `node: true`

### ISSUE THREAD

**Issue by coolaj86** [jshint/jshint#3567]
```js
var url = new URL("https://example.com?" + resp.toJSON().body);
```

```txt
[jshint] URL is not defined
```

Node has `URL`, the same as browsers.

**Comment by jugglinmike** [comment]
Sounds good to me! Care to send a patch our way?

**Comment by coolaj86** [comment]
sent

**Comment by jugglinmike** [comment]
Great! Now that your patch is merged, the next release of JSHint will recognize URL for Node.js environments.
