### ISSUE TITLE
Cannot read properties of undefined at Object.e.nud

### ISSUE THREAD

**Issue by guille-botmaker** [jshint/jshint#3571]
JSHint Version: 2.13.1

**Comment by guille-botmaker** [comment]
Sorry ...
JSHint Version: 2.13.1
Input source code: `const a = {do}`
Configuration values : `default`
Description of expected behavior: `Do not throw an exception`
Description of actual behavior:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'value')
    at Object.e.nud (jshint.js:8)
    at j (jshint.js:7)
    at Te (jshint.js:7)
    at Object.fud (jshint.js:8)
    at j (jshint.js:7)
    at le (jshint.js:7)
    at fe (jshint.js:7)
    at yt (jshint.js:8)
    at self.onmessage (worker.js:7)
```

**Comment by guille-botmaker** [comment]
![Screenshot from 2021-09-15 18-11-25](https://user-images.githubusercontent.com/70526472/133510168-ac5e37bc-ae86-46a6-9a3e-21cb2bec5565.png)

**Comment by jugglinmike** [comment]
Confirmed. Thanks for the report! I'll have a fix up for review lickety split.

**Comment by jugglinmike** [comment]
Patch under review at gh-3572

**Comment by jugglinmike** [comment]
Resolved (over a year ago!) by gh-3572.
