### ISSUE TITLE
Feature: require await (particularly return await) whereever promises are used

### ISSUE THREAD

**Issue by coolaj86** [jshint/jshint#3576]
There's an entire class of error that can be categorically eliminated by _always_ using `await` whenever there is a promise.

Consider this simple refactor:

```js
async function doStuff() {
  return theOnlyFunctionIThoughtIWouldEverNeed();
}
```

```js
async function doStuff() {
  let x = theOnlyFunctionIThoughtIWouldEverNeed();
  let y = doMoreThings(x); // error, expected 'x' to be a value, not a promise
  return y;
}
```

or this one, following the "return something, or return nothing" philosophy:

```js
async function doStuff() {
  theOnlyFunctionIThoughtIWouldEverNeed();
}
```

which should instead be

```js
async function doStuff() {
  await theOnlyFunctionIThoughtIWouldEverNeed();
}
```

Also, `await` lends clarity to the reader when it's non-obvious that the function being called is a promise / async function.

Hence the original should be:

```js
async function doStuff() {
  return await theOnlyFunctionIThoughtIWouldEverNeed();
}
```

I would put this in the same category as `curly: true` in terms of its usefulness and the kinds of problems that it solves.

**Comment by kaizhu256** [comment]
do you mean to change the title to:

```diff
-Feature: require await (particularly return await) whereever promises are used
+Feature: require await (particularly return await) for async functions
```

detecting whether objects are thenable is probably out-of-scope for linters.
