### ISSUE TITLE
`l({var});` gives TypeError

### ISSUE THREAD

**Issue by nabati** [jshint/jshint#3577]
Paste: `l({var});` in the demo and you get a TypeError. 

![image](https://user-images.githubusercontent.com/1499050/138113256-5a58ea22-05ac-436a-9b41-a90d75816ec9.png)

**Comment by jugglinmike** [comment]
Thanks for taking the time to report this bug! Even though gh-3571 may look distinct, it actually describes the same bug. In the interest of keeping things organized, I'm going to close this report as a duplicate.

(Good news: that bug has been fixed on the project's main branch, so the next release of JSHint will definitely tolerate that syntax error.)
