### ISSUE TITLE
Help please with underlined errors

### ISSUE THREAD

**Issue by Sane-4ka** [jshint/jshint#3585]
When an error occurs, only the first character is underlined, but in fact it need to underline whole word
How i may change them?
Help please

**Comment by jugglinmike** [comment]
JSHint does not itself underline text; it analyzes code and generates a report about possible problems. This sounds like a problem with a text editor or an IDE which integrates with JSHint, though it's also possible that there is a bug in the report generated by JSHint.

Before we can help, though, we'll need to know more about your environment. Can you share more information about how you are using JSHint (e.g. how you installed it, whether it is running in an editor, and the versions of the relevant software)?

**Comment by Sane-4ka** [comment]
I am working in vscode. Installed JsHint via npm globally

The latest version of vscode is installed.

Errors are displayed in the console and underlined, but when the entire word needs to be underlined, only the first character is underlined, which makes it very difficult to see an error when hovering over
