### ISSUE TITLE
BigInt is still not recognized

### ISSUE THREAD

**Issue by acarstoiu** [jshint/jshint#3595]
In spite of the recent addition in the list of known globals for ECMAScript 11, `BigInt` is still reported as not defined.

And yes, I have `"esversion": 11` in my _.jshintrc_ file.

**Comment by jugglinmike** [comment]
Thanks for the report! Looks like we missed `globalThis`, as well. gh-3597 addresses both problems.

**Comment by acarstoiu** [comment]
Can I dare to ask for a new release?

**Comment by jugglinmike** [comment]
Resolved in [version 2.13.3](https://jshint.com/blog/2022-01-05/release-2-13-3/)
