### ISSUE TITLE
Wrong "unused variable" hint

### ISSUE THREAD

**Issue by NilsHoyer** [jshint/jshint#3598]
I have the following code:

```
var
  foo = 'Hello, World!';

function main() {
  return window.foo;
}

main();
```

I get the hint `One unused variable`, even the variable is used.

**Comment by jugglinmike** [comment]
Hi there, thanks for taking the time to file a report!

In the sample code, JSHint doesn't recognize that `window.foo` and the `foo` binding reference the same value. You can resolve it by referencing the value consistently, and you have two options for doing that.

```diff
-var
-  foo = 'Hello, World!';
+window.foo = 'Hello, World!';
 
 function main() {
   return window.foo;
 }
 
 main();
```

Or:

```diff
 var
   foo = 'Hello, World!';
 
 function main() {
-  return window.foo;
+  return foo;
 }
 
 main();
```

**Comment by jugglinmike** [comment]
It's been a few weeks, so I'm going to assume this solved your problem.
