### ISSUE TITLE
esversion 11 causes esversion 6 arrow function complaints

### ISSUE THREAD

**Issue by stumash** [jshint/jshint#3605]
getting output like this
![image](https://user-images.githubusercontent.com/13181078/153631283-d75d0d9a-ba4f-4009-a3bd-714395f9eaa5.png)
from code that looks like this
![image](https://user-images.githubusercontent.com/13181078/153631984-3a226eb4-30cb-472f-8cfb-67815ee6cffb.png)

gulp config like this (using `gulp-load-plugins`)
![image](https://user-images.githubusercontent.com/13181078/153631515-3a7fa636-0686-46f5-bb1b-0bf2660e7bfe.png)
and all this in the `package.json`
```
    "gulp": "^3.9.0",
    "gulp-angular-templatecache": "^1.7.0",
    "gulp-autoprefixer": "^2.3.1",
    "gulp-bower-files": "^0.2.7",
    "gulp-cache": "^0.2.10",
    "gulp-clean": "^0.3.2",
    "gulp-csso": "^1.0.0",
    "gulp-filter": "^3.0.1",
    "gulp-flatten": "^0.2.0",
    "gulp-imagemin": "^2.3.0",
    "gulp-jshint": "^2.1.0",
    "gulp-less": "^3.0.3",
    "gulp-livereload": "^3.8.0",
    "gulp-load-plugins": "^1.0.0-rc.1",
    "gulp-newer": "^0.5.1",
    "gulp-ng-config": "^1.2.1",
    "gulp-rev-all": "^0.8.21",
    "gulp-size": "^2.0.0",
    "gulp-uglify": "^1.4.0",
    "gulp-useref": "^1.3.0",
    "gulp-util": "^3.0.6",
    "jshint": "2.9.x",
    "jshint-stylish": "^2.0.1",
```

setting `esversion: 6` gets rid of these new errors but obviously brings back the ones I was trying to get rid of by bumping to 11 in the first place

**Comment by jugglinmike** [comment]
Hi there! Your Node.js dependency list specifies the pattern `2.9.x` for JSHint. The latest release which matches that patter in 2.9.7, and [that was published over three years ago](https://jshint.com/blog/2018-12-07/release-2-9-7/). Could you update JSHint to the latest release and try again?

If the problem persists, it would also help to see a little more context of the source code. [The project's contributing guidelines](https://github.com/jshint/jshint/blob/main/CONTRIBUTING.md) have suggestions.

**Comment by stumash** [comment]
bumping versions seems to have done the trick. closing.

thank you!

**Comment by jugglinmike** [comment]
Sure thing; I'm glad we got that sorted!
