### ISSUE TITLE
Missing semicolon after await

### ISSUE THREAD

**Issue by mini-programmer** [jshint/jshint#3614]
jshint says 'Missing semicolon after await', is there an way i can disable it? or what i can do to remove the error?
i've already added  "esversion": 9  to my .jshintrc file but it still gives the error, what can i do?

**Comment by jugglinmike** [comment]
Hi there! It will help us if you share a small example program. [This project's contribution guidelines have some suggestions for filing an actionable support request](https://github.com/jshint/jshint/blob/master/CONTRIBUTING.md).

**Comment by mini-programmer** [comment]
Im trying to create a little api, just to help me in some code and, in an specific command, the error appears(code down there)
```js
commands.fetchReturnText = function(url) {
let response = await fetch(url);
let data = await response.text();
return data;
};
```

**Comment by jugglinmike** [comment]
This appears to be expected behavior.

The `await` operator is only available within asynchronous functions. In synchronous functions, it is interpreted as a keyword. JSHint is issuing an error because as written, that code will not run.

Try making this change--it should get JSHint to pass *and* allow the code to run in your target environment.

```diff
-commands.fetchReturnText = function(url) {
+commands.fetchReturnText = async function(url) {
 let response = await fetch(url);
 let data = await response.text();
 return data;
 };
```

**Comment by mini-programmer** [comment]
Thanks! it worked

**Comment by jugglinmike** [comment]
Sure thing

**Comment by JYone3A** [comment]
Hi,

my problem is that I'm writing code that will be wrapped in an async scope later, without jshint knowing about it.

So I'd like to specifically tell jshint that this code will run in an async context. Is this possible?

**Comment by JYone3A** [comment]
Just found #3447 - that's what I'd need.
