### ISSUE TITLE
vsc is giving me this error cant run js

### ISSUE THREAD

**Issue by juliochinchilla** [jshint/jshint#3617]
[Error - 9:44:10 PM] Failed to load jshint library
c:\Users\chinc\.vscode\extensions\dbaeumer.jshint-0.11.0\jshint-server\out\server.js:336
                throw new Error('Failed to load jshint library. Please install jshint in your workspace folder using \'npm install jshint\' or globally using \'npm install -g jshint\' and then reload.');
                      ^

Error: Failed to load jshint library. Please install jshint in your workspace folder using 'npm install jshint' or globally using 'npm install -g jshint' and then reload.
    at Linter.<anonymous> (c:\Users\chinc\.vscode\extensions\dbaeumer.jshint-0.11.0\jshint-server\out\server.js:336:23)
    at Generator.throw (<anonymous>)
    at rejected (c:\Users\chinc\.vscode\extensions\dbaeumer.jshint-0.11.0\jshint-server\out\server.js:9:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[Info  - 9:44:10 PM] Connection to server got closed. Server will restart.
[Error - 9:44:11 PM] Failed to load jshint library
c:\Users\chinc\.vscode\extensions\dbaeumer.jshint-0.11.0\jshint-server\out\server.js:336
                throw new Error('Failed to load jshint library. Please install jshint in your workspace folder using \'npm install jshint\' or globally using \'npm install -g jshint\' and then reload.');
                      ^

**Comment by jugglinmike** [comment]
Hi there! The JSHint project does not maintain any editor integrations, so we won't be able to help you with this.

Judging from your error message, the relevant project appears to be [this VS Code extension](https://marketplace.visualstudio.com/items?itemName=dbaeumer.jshint), so you might try bringing your question to those maintainers. (If you do, consider surrounding your console output in three "backtick" characters (```) so that it renders with a fixed-width font. [GitHub offers some more help on using Markdown on this site.](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax))
