### ISSUE TITLE
'fetch' is not defined. (W117) - Although it is a base feature of Node 18 (although experimental)

### ISSUE THREAD

**Issue by MrGcGamer** [jshint/jshint#3628]
so there should probably be some flag or something for Node18 / experimental features

**Comment by Flashwalker** [comment]
I got:
```
jshint: warning
W117 - 'fetch' is not defined.
```
warning

What does it mean? Should i update Nodejs? I have v.18 installed

I also have:
```
jshint: warning
W117 - 'setTimeout' is not defined.
```

I tried `"esversion": 6,` and `"esversion": 2021,`

How to fix it?

**Comment by MrGcGamer** [comment]
@Flashwalker I use this kinda `.jshintrc`:
```json
{
	"esversion": 11,
	"bitwise": false,
	"node": true,
	"eqeqeq": true,
	"globals": {
		"fetch": true
	}
}
```

**Comment by Flashwalker** [comment]
> @Flashwalker I use this kinda `.jshintrc`:
> 
> ```json
> {
> 	"esversion": 11,
> 	"bitwise": false,
> 	"node": true,
> 	"eqeqeq": true,
> 	"globals": {
> 		"fetch": true
> 	}
> }
> ```

Thanks, it works
