### ISSUE TITLE
False error on static property

### ISSUE THREAD

**Issue by erosman** [jshint/jshint#3631]
JSHint 2.13.5
esversion: 11

JSHint appears to report a false error on [static properties](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes#static_methods_and_properties).

> Class properties must be methods. Expected '(' but instead saw '='.

Code Example: [YouTubePatchCollection.user.js](https://github.com/aubymori/YouTubePatchCollection/blob/main/YouTubePatchCollection.user.js)
Code snippet
```js
class YTP {
  static observer = new MutationObserver(this.onNewScript);

  static _config = {};

  static isObject(item) {
      return (item && typeof item === "object" && !Array.isArray(item));
  }
...
```

**Comment by jugglinmike** [comment]
Thanks for taking the time to write a report! The JavaScript language feature you are looking for is called "class fields," and it has not yet been implemented in JSHint. We already have an issue to track that feature at gh-3139, so I'm going to keep the discussion focused there and close this issue.
