### ISSUE TITLE
W080 incorrect message for initializing const with undefined

### ISSUE THREAD

**Issue by qdirks** [jshint/jshint#3632]
```
const UNKNOWN = undefined; // W080 on this line
```
jshint advises that it's not necessary to initialize const variables with undefined. Taking the initializer away causes a syntax error. Thanks! :)

**Comment by jugglinmike** [comment]
Thanks for the report! That's definitely a bug. I've submitted a patch in gh-3633.

(This also highlighted a kind of wonky error message, so I've suggested an improvement in gh-3634.)

**Comment by jugglinmike** [comment]
We released the fix today in [version 2.13.6](https://jshint.com/blog/2022-11-11/release-2-13-6/)!
