### ISSUE TITLE
JShint in VScode

### ISSUE THREAD

**Issue by Leraline** [jshint/jshint#3642]
Hello. Could you explain me please, why jshint is deprecated in vscode and it's recommended me migration to ESlint
![image](https://user-images.githubusercontent.com/39736564/214933979-4d1d8bde-2684-44f8-b260-66f7f4b3db16.png)

**Comment by jugglinmike** [comment]
Hi there! The maintainers of JSHint focus on the linter itself; helpful folks from around the world build and manage [the many ways it integrates with other tools](https://jshint.com/install/). If JSHint is reporting something strange about your code, then we can help, but for for questions about the way JSHint integrates with VSCode, you should contact the people who maintain the VSCode plugin.
