### ISSUE TITLE
jshint 2.13.6 is not warning me about mixing tabs and spaces

### ISSUE THREAD

**Issue by dvhx** [jshint/jshint#3647]
Here I mix spaces and tabs but JSHINT does not produce any errors:

```
JSHINT('var a = 1;\n    var b = 2;\n\tvar c = 3;', {});
console.log(JSHINT.errors);
```

**Comment by jugglinmike** [comment]
Hi there, thanks for taking the time to file a report! [JSHint hasn't warned about mixed tabs and spaces for a very long time](https://github.com/jshint/jshint/commit/4035fef1af4ef426e9dc99918ca3aac0ce44b784), so I'm going to close this. If there's any documentation which incorrectly suggests that this is a feature of JSHint (I can't find any, for whatever that's worth), would you mind filing an issue to let us know about it?
