### ISSUE TITLE
VSCode

### ISSUE THREAD

**Issue by FreeTime42** [jshint/jshint#3649]
VSCode ask me do not use JShint.

Why it happened ? 

![img-2023-08-14-15-25-26](https://github.com/jshint/jshint/assets/103095148/19992bd5-2313-4656-bc5b-e0ee0db2744c)

**Comment by jugglinmike** [comment]
This project is limited to the JSHint JavaScript linter itself. All text editor extensions and IDE extensions are maintained by others in external projects. Please direct questions about those extensions to those maintainers.
