### ISSUE TITLE
Jshint doest trigger hint when access non exist property of an object

### ISSUE THREAD

**Issue by zl7261** [jshint/jshint#3651]
``` javascript 
const { JSHINT } = require('jshint');
const source = [
  `var SlotEntity = {`,
  `getSlot:function(slotName){return;},`,
  `getSlots:function() {return;},`,
  `setSlot:function(Slots){return;}`,
  `};`,
  `SlotEntity.ac23(123);`,
];

JSHINT(source, {
  undef: true,
  strict: 'implied',
});
console.log(JSHINT.data().errors);
```

get no errror , error message should be 'ac23 doest not exist on SlotEntity'.

**Comment by jugglinmike** [comment]
Thanks for taking the time to file an issue! This is expected  behavior because JSHint does not track property definitions. If you find documentation suggesting otherwise, please file a new issue, and we'll reword it!
