### ISSUE TITLE
Identify & ignore side-effect short-circuit expressions?

### ISSUE THREAD

**Issue by jamietre** [jshint/jshint#411]
I am not sure how much this construct comes up (see below), and I am sure it strikes fear and terror into purists. But I see it from time to time in code and it would be nice if this could be allowed to pass conditionally. I don't think any option currently would cause jshint to ignore this kind of statement  -- presently it fails with "Expected an assignment or function call and instead saw an expression."

```
var x=true, y;
function doit() {
     y=true;   
}
function doit2() {
    y=false;
}
// here's the sketchy construct
x && doit(); 

// equivalent to
if (x) {
   doit();
}

// another version
x ? doit() : doit2();

// equivalent to
if (x) {
    doit();
} else {
    doit2();
}
```

I think that the merits of such a construct are debatable, but it's legal, it's also terse and shortens up some commonly used constructs, enough so that I've thought about adding it to my own lexicon. But more importantly, its presence in code that I've forked from others means I have to either rewrite it all, or not lint the entire file.

Thoughts?

**Comment by jcrben** [comment]
Did something like this ever get figured out and merged in?
