### ISSUE TITLE
Opt-out of `Confusing use of '!'.`

### ISSUE THREAD

**Issue by 3rd-Eden** [jshint/jshint#455]
This check was added for issue #211 but there is no way to opt-out of this detection. As the original poster of that issue suggested, it should be enabled by default, but with an override.

**Comment by anurag1490** [comment]
Then what would be one liner code for !(Condition > -1)

**Comment by iki** [comment]
+1 for optout, `!!x` is a **valid use case** and common idiom for converting to bool as @mgoldWork and @jakub-g pointed out

**Comment by kosich** [comment]
+1  for `!!a  === !!b`

**Comment by iki** [comment]
actually `!!x` can be used anywhere for converting to bool...

could it be marked as valid construct in jshint (with no optout needed), @valueof?

**Comment by mjhm** [comment]
+1 for opt out

**Comment by cjc343** [comment]
It's great when the first Google result for a problem is a closed issue with no solution.

Per #780, this option can be enabled/disabled with the not-at-all-cryptic `/*jshint -W018 */` and `/*jshint +W018 */`

+1 for a more cryptic opt-out.

**Comment by callumlocke** [comment]
@cjc343 thanks.

there should be a way to opt out from `.jshintrc` too.

whenever someone asks for a way to opt out of something, people always come back with "but why would you ever want to write that, that's bad bad code". this is never a valid response to someone asking for an opt-out. if they're asking for an opt-out, they disagree with you that it's 100% always bad, and that's that. jshint is supposed to help us, not get in the way. everything should be opt-out-able. absolutely everything.

**Comment by bucaran** [comment]
What is the `.jshintrc` field to allow confusing use of `!`?

For example, the following is giving me the warning:

```js
function even(n) {
  return !(n % 2)
}
```

**Comment by sigod** [comment]
+1 for opt out

**Comment by sigod** [comment]
> Could you give us a valid usage example, please?

```js
console.assert(!!prototype === !!object, 'invalid state', prototype, object);
```

**Comment by bitdivine** [comment]
+1.  Here is one of my common use cases:

    // Note: points is an array, each having latitude and longitude
    var dataset = {};
    points.forEach(function(point){
        if (!(dataset.latMin<point.lat)) dataset.latMin = point.lat;
    });

Note that `!(dataset.latMin<point.lat)` is not the same as `dataset.latMin>=point.lat` when the LHS is undefined.

**Comment by lukeapage** [comment]
> Note that !(dataset.latMin<point.lat) is not the same as dataset.latMin>=point.lat when the LHS is undefined.

Isn't that confusing for the poor person reading the code?

Anyway, this has been merged into #780 where it is noted you can use `W018` to disable this warning.

**Comment by qm3ster** [comment]
```javascript
if (data === undefined || (!(data.length > 0))) 
```
is considered confusing. so is
```javascript
if (data === undefined || !(data.length > 0)) 
```
Wat do?

**Comment by jugglinmike** [comment]
Have you tried

```diff
-if (data === undefined || !(data.length > 0)) 
+if (data === undefined || data.length <= 0) 
```

...although a property name like `length` makes me suspect that `data.length === 0` may suffice.

**Comment by qm3ster** [comment]
It's not equivalent, because for a non-array object with no length property your examples give false.
Now I realize there are also strings with the default "length" property so I may have to check for type first, as well -.-

**Comment by bitdivine** [comment]
Whether or not ** is ugly or not, there should be an opt-out, right?

Yes.  I'm not sure why this is being discussed.

**Comment by MythicAngel** [comment]
!! is the easiest way to convert "anything" into "bool". +1 for opt-out

**Comment by JohnCoker** [comment]
The case I keep running into is wanting to test if something is not a positive number:
`if (!(n > 0)) return;`
Otherwise, one needs to write something like:
`if (typeof n != 'number' || isNaN(n) || n <= 0)`

**Comment by rogercoder** [comment]
> The case I keep running into is wanting to test if something is not a positive number:
if (!(n > 0))
Otherwise, one needs to write something like:
if (typeof n != 'number' || isNaN(n) || n <= 0)

This is exactly why I came here wondering why jshint was keeping me from writing code the way I want.

**Comment by nicolo-ribaudo** [comment]
`!(n > 0)` and `typeof n != 'number' || isNaN(n) || n <= 0` aren't the same thing:

```js
var n = "1";
console.log(!(n > 0)); // false
console.log(typeof n != 'number' || isNaN(n) || n <= 0) // true
```

Anyway, you can just use -W018 to disable the warning
