### ISSUE TITLE
allow non-curly when same line

### ISSUE THREAD

**Issue by Phoscur** [jshint/jshint#474]
I know the purpose of the curly attribute, but shouldn't it be clearer (and therefore allowed) to write a single command without newline behind the condition?

``` javascript
while (day) shuffle(); // allowed
```

``` javascript
while (day)
    shuffle(); // not allowed
    // because this line could be confused to be inside the loop/conditional
```

``` javascript
while (day) {
    shuffle(); // allowed
}
```

How can I create a relaxing option for this/modify curly?

**Comment by ljcp** [comment]
+1
