### ISSUE TITLE
jshint should support some line breaks without laxbreak

### ISSUE THREAD

**Issue by pluma** [jshint/jshint#557]
The following code is marked as an error without laxbreak:

```
foo = bar
    ? 'yes'
    : 'no';
```

As does this:

```
foo = (bar
    ? 'yes'
    : 'no');
```

I can understand why the first one might be considered dodgy. It's safe, but easy to misread by an idiot in a hurry. The second one, however, is perfectly fine. The open parenthesis makes it clear that the line break cannot possibly be the end of the statement.

Note that neither of these is marked as an error by jslint. As jshint pretends to be more lenient than jslint, I fail to see how this could require `laxbreak: true` to pass.

Even more inane: the error given is "illegal line break before '?'", which is plain wrong. This is doubly so if you consider that the permitted alternative is

```
foo = (bar ?
    'yes' :
    'no');
```

Which is no less or more safe than operator-first ternaries.

**Comment by barneycarroll** [comment]
For posterity: you can allow `laxbreak` while disallowing `laxcomma` (although JSHint will soon wash its hands of code style issues).
