### ISSUE TITLE
create flag to omit "Confusing use of..." messages

### ISSUE THREAD

**Issue by HopingCoding** [jshint/jshint#578]
Could you introduce a flag that omits messages like this:

```
 Confusing use of '!'. (../src/js/bla.js:595:9)
  > if (!(somevariable > 0)) {
```

i have very good reasons to leave the code like it is. (somevariable can be null or undefined)

thanks!

**Comment by absynce** [comment]
Use `/*jshint -W018 */`.

**Comment by zachborboa** [comment]
Suppress warnings using a configuration file.

```bash
$ jshint myscript.js
myscript.js: line 109, col 10, Confusing use of '!'.

1 error
```

```bash
$ cat jshint-config.json
{
  "-W018": false
}
```

```bash
$ jshint --config=jshint-config.json myscript.js
$ echo $?
0
```

Warning codes
https://github.com/jshint/jshint/blob/HEAD/src/messages.js#L82

#2551

**Comment by axkibe** [comment]
@zachborboa. Finally!

Since when is this possible?

I was fed up since years of people telling to put inline comments to "fix" this and other similar stupid warnings.

**Comment by zachborboa** [comment]
@axkibe At least since July 2015.

> and there is a reason why I've seen it before.. This syntax works..! It is just undocumented.

https://github.com/jshint/jshint/issues/2551#issuecomment-121148888

**Comment by axkibe** [comment]
Okay nice. So how about documenting it then?

**Comment by iSkore** [comment]
@zachborboa's solution worked. Add `"-W018": false` to the `.jshintrc` file.
