### ISSUE TITLE
Usage of 'undefined' as identifier must not be reported as error

### ISSUE THREAD

**Issue by alexeykuzmin** [jshint/jshint#584]
jshint v0.7.1

> src/filename.js: line 130, col 15, Expected an identifier and instead saw 'undefined' (a reserved word).

'undefined' is not a reserved word in ES [262-3](http://www.ecma-international.org/publications/files/ECMA-ST-ARCH/ECMA-262,%203rd%20edition,%20December%201999.pdf) nor [262-5](http://www.ecma-international.org/publications/files/ECMA-ST/Ecma-262.pdf).

**Comment by trotyl** [comment]
Although it is really **BAD** to name a variable as `undefined` , it's **NOT** a reserved word at all, the error message itself is wrong about what the error is.
