### ISSUE TITLE
Allow line breaking before && or ||

### ISSUE THREAD

**Issue by arian** [jshint/jshint#60]
For multiple line conditions it might be more readable if the && and || are at the beginning of the line. JSHint however does not allow this, resulting in the error "Bad line breaking before '&&'."

```
if (a
    && b
    && c
    && (
        d
        || e
    )
){
    /* yay! */
}
```

Example: http://jsfiddle.net/AkeF3/1/

**Comment by ava-dylang** [comment]
:+1:

**Comment by Rob--W** [comment]
This error is still in 2.7.0.

I added `"-W014": true` to `.jshintrc` to get rid of this error (https://github.com/jshint/jshint/blob/e47168f5aa9576819830554f1b37dc0d49b76d31/src/messages.js#L90).

**Comment by janaspage** [comment]
@Raynos : Can you recommend a resource for which JS parsers might meet this failure? 

> This may cause problems like semi colon insertion and old javascript parsers breaking. Please check a large range of browsers.

**Comment by jcrben** [comment]
Why was this closed? Is it considered a duplicate of https://github.com/jshint/jshint/issues/735?

**Comment by janaspage** [comment]
+1 Why was this closed? Is it still a problem in any current-less-two-versions browser to break before logic operators or concatenation? Can this warning be silenced? Thank you.
