### ISSUE TITLE
Shadow variable in 'catch' should be an Error

### ISSUE THREAD

**Issue by alexkopy** [jshint/jshint#618]
Consider the following code:

``` javascript
    var x = 3;
    try{ throw "boom"; }
    catch (x) { }
    console.log(x);
```

According to JS spec catch should have its own scope. This behaviour can be observed in almost every browser, since they will all print `3` at the end. The exception is naturally IE which will print "boom" (tested up to IE9, would be interesting to see how 10 does with this, considering its high test262 score).

Right now as you can see, you can get your nice numeric vars turned into strings, or anything else for that matter. It doesn't matter whether `x` is in a function or global scope. This is extremely hard to notice and debug, you just wouldn't think about this.

**Comment by Gerst20051** [comment]
:+1:
