### ISSUE TITLE
jshint “Possible strict violation.” when using `bind`

### ISSUE THREAD

**Issue by ralt** [jshint/jshint#621]
Consider this simple code:

```
"use strict";

var obj = {
    f: function() {
        this.prop = 'value';
        g.bind( this )();
    }
};

function g() {
    console.log( this.prop );
}
```

If I try to validate this code, jshint gives me the error `Possible strict violation.` where I call `console.log( this.prop );`. This is because `this` is undefined in strict mode in a function.

But I'm binding this function before calling it, so `this` is the correct object.

I'm using this "design pattern" to avoid cluttering the main object. Passing the properties in the parameters will also clutter the function, so I refuse to do this. Besides, this is exactly what `bind` is for.

Is there a way for jshint to let me do this?

<sub>PS: I cross posted this on [StackOverflow](http://stackoverflow.com/questions/12057427/jshint-possible-strict-violation-when-using-bind) if you'd rather answer over there. Also, the comments are worth reading.</sub>

**Comment by realityking** [comment]
Has anything ever come from this?

**Comment by bugs181** [comment]
Also getting this warning when binding a function in a class constructor.

**Comment by rwaldron** [comment]
It's just a warning, suppress with: `/*jshint validthis: true */ `

**Comment by bugs181** [comment]
Perhaps we'd rather not suppress warnings just because it's convenient. A linter should look for such edge cases. I've switched to ESLint and no longer receive this warning. Much happier with the ability to customize and extend it as well.

**Comment by jugglinmike** [comment]
@bugs181 The original report concerned a warning issued from within a function
declaration. The method in the object initializer was a bit of a red herring.
Your comment about class constructor makes me wonder if your are experiencing a
separate bug. Was the warning you experienced issued from the class constructor
function?

**Comment by bugs181** [comment]
@jugglinmike Yes it was in a class constructor function. I don't have the code nor remember the exact implementation but was giving me issues when using .bind with duck typing.

Here's some pseudo-code that I believe should give you the expected result. I've since switched to eslint so can no longer verify.

    'use strict'

    class someClass {
        constructor() {
            this.fn = fn.bind(this)
        }
    }

    function fn() { }
