### ISSUE TITLE
var statement in nested ifs

### ISSUE THREAD

**Issue by kkapsner** [jshint/jshint#640]
I would realy like a feature that is able to detect if two nested ifs use the same variable.

Example:
```js
for (var i = 0; i < 2; i++){
	for (var i = 0; i < 3; i++){
		doSomething();
	}
}
```
should give an error but
```js

for (var i = 0; i < 2; i++){
	doSomething();
}
for (var i = 0; i < 3; i++){
	doSomething();
}
```
NOT.

Hope you get what I mean...

Until now I can just use shadow which will give me an error in both cases or none.

**Comment by rwaldron** [comment]
This doesn't appear to be a widely desirable feature. Closing until a more compelling case is made.
