### ISSUE TITLE
Introduce label for "Don't use extra leading zeros"

### ISSUE THREAD

**Issue by barneycarroll** [jshint/jshint#663]
This rule is such a subjective stylistic issue, I'm incredibly surprised there's no option to turn it off. 

For example, when I'm describing a set of co-ordinates, I like to be able to make use of spaces to allow quick recognition of pairs, and use zeros to make alignment within numbers. Example:

```
var shape1 = [79,85, 62,88, 48,95, 35,88, 18,85, 07,77, 02,65, 02,58, 09,38, 02,23];
var shape2 = [23,02, 35,07, 48,02, 60,07, 73,02, 96,23, 88,38, 95,58, 96,65, 90,77];
```

I'm almost reticent of posting an example because I can't find any documentation of reasons against leading zeros… But there's a pro, and I don't see any cons.

**Comment by popomore** [comment]
@lepture want fix this code style, then saw your comment

**Comment by lepture** [comment]
@popomore haha
