### ISSUE TITLE
Input via stdin

### ISSUE THREAD

**Issue by valueof** [jshint/jshint#687]
(OP: @hallettj)

It would be super useful to me to have an option for jshint to accept input from stdin instead of from a file input. The use case that I have in mind is taking a text buffer from an editor, piping it to jshint, and parsing jshint output to highlight errors in the editor.

My suggestion is to follow the Unix convention where if a given file path is a dash (-) then the program reads from stdin.

**Comment by iahu** [comment]
+1

**Comment by nicolo-ribaudo** [comment]
@iahu Just run `jshint` with a `-` instead of the file path and it will read the input from stdin

**Comment by iahu** [comment]
Yes, I have got it form http://jshint.com/docs/cli/
Thank you @nicolo-ribaudo

**Comment by mslinn** [comment]
The CLI docs say "If a file path is a dash (-) then JSHint will read from standard input."

Here is how I use that feature to strip out empty Jekyll front matter from `myfile.js` and JSHint the remaining lines:
```shell
sed '/---/d' < myfile.js | jshint -
```
