### ISSUE TITLE
Unexpected 'ŝ'.

### ISSUE THREAD

**Issue by Krinkle** [jshint/jshint#729]
A library I'm working on contains a quick environmental check to see that the file has not be mal-encoded and the engine supports what should be supported according to the spec:

```
var orig, ŝablono;

orig = 'some token';
ŝablono = orig;
```

However JSHint someone keeps invalidating this, no idea how to get rid of it. Is this a bug in JSHint?

**Comment by rwaldron** [comment]
I'm not seeing this issue in 2.5.11

**Comment by nicolo-ribaudo** [comment]
This issue can be closed.

**Comment by lukeapage** [comment]
Saw earlier..  Given @rwaldon didnt close i wanted to wait for feedback on my how can i help issue before closing lots..

**Comment by Krinkle** [comment]
I can't reproduce the issue with jshint@2.8.0. Thanks!
