### ISSUE TITLE
Eval error when eval method exists in a object

### ISSUE THREAD

**Issue by arunoda** [jshint/jshint#738]
Following line cause an error and It is a legitimate and It has no relationship to eval.

~~~js
result =  schemaEvaluator.eval(experimentId, schema);
~~~

Error is shown here: http://arunoda.me/blog/jshint-evil-eval-check.html

**Comment by rwaldron** [comment]
This _should've_ been corrected for ES5

**Comment by mbildner** [comment]
this pr should fix that https://github.com/jshint/jshint/pull/2188
