### ISSUE TITLE
Expose `loadConfig` from CLI for use from external tools

### ISSUE THREAD

**Issue by dpashkevich** [jshint/jshint#741]
Currently only the CLI version of JSHint loads the `.jshintrc` file. 

It would be nice if the config file would still be respected when jshint is used from tools like Grunt.
If  [`loadConfig`](https://github.com/jshint/jshint/blob/master/src/cli/cli.js#L47-82) function was  exposed, that would be possible.

And I can't just use `grunt.file.readJSON()` because .`jshintrc` isn't strictly a JSON file since it may contain comments (which I think is a great idea).

Please see related discussion here: https://github.com/gruntjs/grunt-contrib-jshint/issues/2

**Comment by FagnerMartinsBrack** [comment]
> ... .jshintrc isn't strictly a JSON file since it may contain comments (which I think is a great idea).

Is this publicly documented somewhere? I just want to make sure using comments in my `.jshintrc` files won't have side-effects in the future and it will be mentioned in changelog if something is changed.
