### ISSUE TITLE
Checking mixed tabs/spaces

### ISSUE THREAD

**Issue by ghostwords** [jshint/jshint#829]
Why doesn't checking the following produce a mixed tabs/spaces warning?

``` javascript
function test() {
    var x = 5; // four spaces
    return x; // a single tab
}
test();
```

> $ jshint --version
> 0.9.1

.jshintrc:

``` javascript
{
    "smarttabs": false,
    "indent": 4
}
```

**Comment by billymoon** [comment]
+1 - I want to use JSHint to validate code and fail builds - not an inferior library with this one vital feature included :+1:
