### ISSUE TITLE
High cyclomatic complexity on switch statements

### ISSUE THREAD

**Issue by jncraton** [jshint/jshint#840]
Currently, every case in a switch block increments the cyclomatic complexity regardless of whether or not it falls through.

This has a complexity of 4:

```
function(someVal) {
    switch (someVal) {
        case 1:
        case 2:
        case 3:
            doSomething();
            break;
        default:
            doSomethingElse();
            break;
    }
}
```

This has a complexity of 2 while being logically equivalent:

```
function(someVal) {
    if (someVal === 1 || someVal === 2 || someVal === 3) {
        doSomething();
    } else {
        doSomethingElse();
    }
}
```

I'm not an expert in cyclomatic complexity by any means, so I'm honestly not sure if this is correct or not. Even if this is the expected behavior, it seems like it would be nice to at least have a flag which could make these two function calculate the same cyclomatic complexity.

**Comment by daemon1981** [comment]
Why && doesn't increase cyclomatic complexity count ?

function functionWithCyclomaticComplexityDueToAndOperator_1(a, b) {
  return a && b;
}
// => jshint return complexity 1

function functionWithCyclomaticComplexityDueToOrOperator_2(a, b) {
  return a || b;
}
// => jshint return complexity 2

function functionWithCyclomaticComplexityDueToNegativeAndOperator_1(a, b) {
  return !(!a && !b);
}
// => jshint return complexity 1

Looks strange...

I can increase the complexity of the strange without be warning ?

**Comment by truhlikfredy** [comment]
I don't know how exactly it's working but let me guess it's because the analysis is done on bytecode and not source? So it's after compiling and the last statement got optimized by compiler into the first one.

**Comment by rwaldron** [comment]
The function with && has only one path, as both sides of && are always evaluated. || has two paths: the left side lone evaluation and the left + right evaluation

**Comment by mikesherov** [comment]
@rwaldron, sounds like a bug to me. `&&` short circuits when left is false, just like || short circuits when left is true. No?

**Comment by rwaldron** [comment]
Yes, and for future reference I should avoid commenting or reviewing issues on days that I'm playing video games or otherwise not focusing on the subject at hand.

**Comment by mikesherov** [comment]
Lol. that's like every day for me.

**Comment by truhlikfredy** [comment]
So there two different issues? 

 * The short circuit for && is ignored and gives smaller complexity than it really is
 * The code can get more complex looking and the source can get harder to read and easier to make a bug inside it. But if it's optimized and byte-code is the same then it will not increase the complexity in report.

**Comment by mikesherov** [comment]
> The code can get more complex looking and the source can get harder to read and easier to make a bug inside it. But if it's somewhere optimized then it will not increase the complexity in report.

No, you just made this up!

This is just a bug like any other in the source code. A condition that should be increasing complexity isn't.

**Comment by truhlikfredy** [comment]
Ok never mind.. I said in beginning I don't know how this one exactly works and the whole thread is a bit confusing.

So for **!(!a && !b)** and **a && b** will be given 2.

**Comment by paul-wade** [comment]
is cyclomatic complexity worthy of its own unit test file? Or should it just be a part of core tests... I could be wrong but I'm not seeing any current tests around it.

**Comment by lukeapage** [comment]
@paul-wade 
The tests are in the options file.

https://github.com/jshint/jshint/blob/9d021eede3e5ebffe2c98fce12293703586b491b/tests/unit/options.js#L2089

**Comment by paul-wade** [comment]
Thanks @lukeapage I missed that

**Comment by paul-wade** [comment]
@lukeapage The original issues is in regards to switch statements. Does your pull request handle just && or both?

**Comment by lukeapage** [comment]
if you read through this issue carefully i think the conclusion was that either
a.  case,  & &,  || should not increase complexity
b.  they all should
e. g.  it should be consistent 
also i think people preferred a. because we already increase complexity for ||, case and because with a, if you rewrite code to do the same thing, using different syntax, the complexity won't change.

**Comment by paul-wade** [comment]
I'm not sure logical consistency is the right thinking here. Logically sure || and a few fall through case statements should be the same. In terms of maintaining code would you find it easier to read a switch with a few fall through case statements or an if with a bunch of ||. I'd also argue that visual studio, code maid, reshaper, intellij consistently do not increase complexity for an empty case. 

Isn't consistency with other languages/analyzers also important?

**Comment by lukeapage** [comment]
If you search around about cyclomatic complexity you will see some implement OR/empty switch cases as increasing complexity and some don't. But they are always consistent because they are equivalent code.

It is highly likely those c# tools are showing info from the same source. Are you sure they are increasing complexity for || but *not* for empty case statements?

JavaScript is a different language from c# and I've found code measuring PHP that does count OR - so it may also be a microsoft convention - none of which are reasons for us to go one way or another.

JSHint has included OR and empty switch for a long time, so there isn't really a reason to change that I see.

**Comment by lukeapage** [comment]
interestingly http://jscomplexity.org/ has the exact same behaviour as jshint at the moment (+1 for ||, +1 for empty switch, +0 for &&) though it is an option.

**Comment by jugglinmike** [comment]
Thanks for the heads-up, Gustavo! It would be a shame for that money to go back to Bountysource, especially when [Luke contributed a fix almost *five years ago*](https://github.com/jshint/jshint/pull/2597). I've merged the fix, resolving the conflicts that have been introduced in a half-decade of development.

@lukeapage: [your $25 is waiting](https://www.bountysource.com/issues/100587-high-cyclomatic-complexity-on-switch-statements).
