### ISSUE TITLE
Unsafe Characters error message.

### ISSUE THREAD

**Issue by manngo** [jshint/jshint#901]
JSHint warns me about unsafe characters when I include unicode characters, such as the “smart” quotes. For example:

var a='This is a string with “smart” quotes';
alert(a);    //    string includes “smart” quotes
a=/[“”‘’]/;

The message I get is:

This character may get silently deleted by one or more browsers.

I am using Komodo Edit 7.1.3 on Macintosh OSX 10.8; the version of jshint is 1.1.0 manually installed.

Because the page is encoded in utf-8, these (and many other) characters should be perfectly safe, and no browser, even Internet Exterminator, has a hard time with them.

Thanks,

Mark

**Comment by bigfish** [comment]
/*jshint -W100*/

works to supress this error, in 2.5.8, whereas 'unsafechars' is flagged as a 'bad option'

**Comment by bigfish** [comment]
that should have read

        /*jshint -W100*/
