### ISSUE TITLE
window namespaced vars not recognized as global variables

### ISSUE THREAD

**Issue by cmcculloh** [jshint/jshint#91]
```
window.namespace = window.namespace || {};

namespace.blah = "something";
```

Attaching a variable to the window object and then using it later without specifying window. results in JSHint failing the code stating that the variable is not defined.

Letting JSHint know it is a global var fixes this:

```
/*global namespace: true */

window.namespace = window.namespace || {};

namespace.blah = "something";
```

However, it seems like JSHint ought to be able to detect the global variable when I attach it to the window object...

**Comment by Densaugeo** [comment]
For anyone else Googling this...I have found the following works as a workaround:

`var namespace = window.namespace = {}`

Which, incidentally, is also recognized as a variable declaration by my syntax highlighter.
