### ISSUE TITLE
Incorrectly switches to JSON mode

### ISSUE THREAD

**Issue by spadgos** [jshint/jshint#911]
When some code starts with a `[` (or I guess `{` too), JSHint assumes it is JSON and then reports that all strings should be double-quoted.

Example:

```javascript
['foo', 'bar'].forEach(function () { /* some code here */ });
```

This should not produce any warnings, however it reports: "Strings must use doublequote"

**Comment by lukeapage** [comment]
Fixed in 2.5.2
