### ISSUE TITLE
Why the return codes are different?

### ISSUE THREAD

**Issue by camilonova** [jshint/jshint#916]
I just realize version 0.9.1 returns code 1 when a file has errors, and version 1.1.0 returns code 2

it happens on any file, even non javascript files.

**Comment by BlackVegetable** [comment]
Forgive the intrusion.  Github did something unexpected when I referenced a pull request from a private repo. I've removed the reference, but I cannot seem to reverse the backward link (although I doubt anyone has access to it here.)

**Comment by jugglinmike** [comment]
@BlackVegetable Don't worry--those links are only visible to users with access to the private repository in question (if you look carefully, the UI has some text to this effect).

**Comment by BlackVegetable** [comment]
Hah! you are correct. It was in the hover-text. Thank you; I was horribly worried I was misbehaving for a moment.
