### ISSUE TITLE
Feature request: Check that every file ends with exactly n new lines

### ISSUE THREAD

**Issue by JustinDrake** [jshint/jshint#926]
Some people like having no extra new lines at the end of files. Some like having exactly one new line.

A JSHint flag to check that the correct number of new lines appear at the end of every JavaScript file would be helpful. The number of lines, n, would be customisable.

**Comment by mgireesh05** [comment]
I was looking for this but found another way to do this on Sublime. 
From https://robots.thoughtbot.com/no-newline-at-end-of-file
>> For Sublime users, set the ensure_newline_at_eof_on_save option to true.
