### ISSUE TITLE
jshint incorrectly asserts functions declared in loop initializer as being inside of loop

### ISSUE THREAD

**Issue by Xunnamius** [jshint/jshint#982]
Take the following code for example:

``` javascript
~function()
{
    for(var noop=function noop(){}, len=10; len--;)
        noop(len);
}();
```

Of course the above code is useless (and not as "anonymous" as it otherwise should be, wink wink), but it demonstrates the issue. JSHint will incorrectly throw the "don't make functions within a loop" error, although the function is not, technically, created _inside_ of the loop in the manner that JSHint is attempting to ward against.

**Comment by nicolo-ribaudo** [comment]
This issue has been fixed by 08eb4e2
