### ISSUE TITLE
JSHint reports error for failing to recognize statement labels inside the catch (e) {}

### ISSUE THREAD

**Issue by sterpe** [jshint/jshint#985]
Consider:

````javascript
function labelExample() {
    "use strict";
    var i;
example:
    for (i = 0; i < 10; i += 1) {
        try {
            if (i === 5) {
                break example;
            } else {
                throw new Error();
            }
        } catch (e) {
            continue example;
        }
    }
}
````

JSHint reports:

Line 12: 'example' is not a statement label.

JSLint reports:

Line 12: unexpected continue.
 

Continue may or may not be necessary in this case but no matter what the contents of the catch are definitely within the same scope and have access to the loop label.

**Comment by lukeapage** [comment]
This is fixed in #2435 and I added a test to #2468
